import { 
    Code, 
    Globe, 
    FlaskConical, 
    Zap, 
    BarChart3, 
    Table, 
    Grid, 
    Image, 
    Palette, 
    Cpu, 
    Brain, 
    Flame, 
    Activity,
    Monitor,
    Circle,
    Box,
    Triangle,
    Server,
    Hexagon,
    Send,
    Feather,
    Shuffle,
    Layers,
    Atom,
    Droplet,
    ArrowUpRight,
    Brush,
    Check,
    CheckCircle,
    Cloud,
    Coffee,
    Database,
    Eye,
    Layout,
    Leaf,
    LineChart,
    Link,
    MousePointer,
    Network,
    Package,
    Plug,
    RefreshCw,
    Rocket,
    Smile,
    Soup,
    Square,
    Wind,
    Wrench,
    Waves
  } from 'lucide-react';
  import { CubeIcon } from '@radix-ui/react-icons';
  import { GiPrism } from 'react-icons/gi';

export const programmingLibraries = [
    {
      id: "python",
      label: "Python",
      icon: <Brain />,
      items: [
        {
          id: "webDevelopment",
          label: "Web Development",
          icon: <Globe />,
          items: [
            { id: "django", label: "Django", icon: <Layers /> },
            { id: "flask", label: "Flask", icon: <FlaskConical /> },
            { id: "fastApi", label: "FastAPI", icon: <Zap /> },
            { id: "tornado", label: "Tornado", icon: <Wind /> },
            { id: "bottle", label: "Bottle", icon: <Droplet /> },
          ],
        },
        {
          id: "dataAnalysis",
          label: "Data Analysis & Visualization",
          icon: <BarChart3 />,
          items: [
            { id: "pandas", label: "Pandas", icon: <Table /> },
            { id: "numpy", label: "NumPy", icon: <Grid /> },
            { id: "matplotlib", label: "Matplotlib", icon: <Image /> },
            { id: "seaborn", label: "Seaborn", icon: <Palette /> },
            { id: "plotly", label: "Plotly", icon: <LineChart /> },
            { id: "bokeh", label: "Bokeh", icon: <Eye /> },
          ],
        },
        {
          id: "machineLearning",
          label: "Machine Learning & AI",
          icon: <Cpu />,
          items: [
            { id: "tensorflow", label: "TensorFlow", icon: <Brain /> },
            { id: "pytorch", label: "PyTorch", icon: <Flame /> },
            { id: "scikitLearn", label: "Scikit-Learn", icon: <Code /> },
            { id: "keras", label: "Keras", icon: <Activity /> },
            { id: "lora", label: "LoRA", icon: <Brain /> },
            { id: "xgboost", label: "XGBoost", icon: <Rocket /> },
            { id: "lightgbm", label: "LightGBM", icon: <Leaf /> },
          ],
        },
        {
          id: "databaseTools",
          label: "Database & ORM Tools",
          icon: <Database />,
          items: [
            { id: "sqlalchemy", label: "SQLAlchemy", icon: <Link /> },
            { id: "djangoOrm", label: "Django ORM", icon: <Layers /> },
            { id: "psycopg2", label: "Psycopg2", icon: <Plug /> },
            { id: "pymongo", label: "PyMongo", icon: <Database /> },
          ],
        },
        {
          id: "automation",
          label: "Automation & Scripting",
          icon: <Wrench />,
          items: [
            { id: "selenium", label: "Selenium", icon: <MousePointer /> },
            { id: "beautifulsoup", label: "Beautiful Soup", icon: <Soup /> },
            { id: "requests", label: "Requests", icon: <Send /> },
            { id: "pytest", label: "Pytest", icon: <CheckCircle /> },
          ],
        },
      ],
    },
    {
      id: "javascript",
      label: "JavaScript",
      icon: <Code />,
      items: [
        {
          id: "frontEndFrameworks",
          label: "Front-End Frameworks",
          icon: <Monitor />,
          items: [
            { id: "react", label: "React.js", icon: <Circle /> },
            { id: "angular", label: "Angular", icon: <Box /> },
            { id: "vue", label: "Vue.js", icon: <Triangle /> },
            { id: "svelte", label: "Svelte", icon: <Flame /> },
            { id: "nextjs", label: "Next.js", icon: <ArrowUpRight /> },
            { id: "nuxtjs", label: "Nuxt.js", icon: <Square /> },
          ],
        },
        {
          id: "backEndFrameworks",
          label: "Back-End Frameworks",
          icon: <Server />,
          items: [
            { id: "node", label: "Node.js", icon: <Hexagon /> },
            { id: "express", label: "Express.js", icon: <Send /> },
            { id: "nestjs", label: "NestJS", icon: <Feather /> },
            { id: "koa", label: "Koa", icon: <Waves /> },
            { id: "fastify", label: "Fastify", icon: <Zap /> },
          ],
        },
        {
          id: "stateManagement",
          label: "State Management",
          icon: <Shuffle />,
          items: [
            { id: "redux", label: "Redux", icon: <Layers /> },
            { id: "mobx", label: "MobX", icon: <Atom /> },
            { id: "zustand", label: "Zustand", icon: <CubeIcon /> },
            { id: "recoil", label: "Recoil", icon: <RefreshCw /> },
            { id: "contextApi", label: "Context API", icon: <Network /> },
          ],
        },
        {
          id: "uiLibraries",
          label: "UI Libraries & Tools",
          icon: <Palette />,
          items: [
            { id: "materialUi", label: "Material-UI", icon: <Brush /> },
            { id: "tailwind", label: "Tailwind CSS", icon: <Wind /> },
            { id: "bootstrap", label: "Bootstrap", icon: <Grid /> },
            { id: "chakraUi", label: "Chakra UI", icon: <Box /> },
            { id: "antDesign", label: "Ant Design", icon: <Layout /> },
          ],
        },
        {
          id: "databaseTools",
          label: "Database & Backend Services",
          icon: <Database />,
          items: [
            { id: "mongoose", label: "Mongoose", icon: <Link /> },
            { id: "prisma", label: "Prisma", icon: <GiPrism /> },
            { id: "supabase", label: "Supabase", icon: <Cloud /> },
            { id: "firebase", label: "Firebase", icon: <Flame /> },
          ],
        },
        {
          id: "testing",
          label: "Testing Frameworks",
          icon: <CheckCircle />,
          items: [
            { id: "jest", label: "Jest", icon: <Smile /> },
            { id: "mocha", label: "Mocha", icon: <Coffee /> },
            { id: "cypress", label: "Cypress", icon: <Eye /> },
            { id: "vitest", label: "Vitest", icon: <Zap /> },
          ],
        },
      ],
    },
    {
      id: "crossPlatform",
      label: "Cross-Platform & Utilities",
      icon: <Globe />,
      items: [
        {
          id: "apiTools",
          label: "API & Backend Services",
          icon: <Plug />,
          items: [
            { id: "supabase", label: "Supabase", icon: <Cloud /> },
            { id: "firebase", label: "Firebase", icon: <Flame /> },
            { id: "graphql", label: "GraphQL", icon: <Hexagon /> },
            { id: "axios", label: "Axios", icon: <Send /> },
          ],
        },
        {
          id: "devTools",
          label: "Development Tools",
          icon: <Wrench />,
          items: [
            { id: "typescript", label: "TypeScript", icon: <Code /> },
            { id: "eslint", label: "ESLint", icon: <Check /> },
            { id: "prettier", label: "Prettier", icon: <Brush /> },
            { id: "webpack", label: "Webpack", icon: <Package /> },
            { id: "vite", label: "Vite", icon: <Rocket /> },
          ],
        },
      ],
    },
  ];
