import { BrokerValue, DataBroker, DataBrokerDataWithKey, DataInputComponent } from '../types';

export type MockStores = {
    brokers: Record<string, DataBrokerDataWithKey>;
    brokers_two: Record<string, DataBrokerDataWithKey>;
    brokers_three: Record<string, DataBrokerDataWithKey>;
    inputComponents: Record<string, DataInputComponent>;
    brokerValues: Map<string, BrokerValue>;
};

export const mockData: MockStores = {
    brokers: {
        'theme.selection': {
            id: 'theme.selection',
            matrxRecordId: 'theme.selection',
            name: 'Theme Selection',
            defaultValue: 'system',
            dataType: 'str',
            inputComponent: 'theme-select',
            outputComponent: 'theme-display',
        },
        'system.volume': {
            id: 'system.volume',
            matrxRecordId: 'system.volume',
            name: 'System Volume',
            defaultValue: '50',
            dataType: 'float',
            inputComponent: 'volume-slider',
            outputComponent: 'volume-display',
        },
        'user.skill': {
            id: 'user.skill',
            matrxRecordId: 'user.skill',
            name: 'Primary Skill',
            defaultValue: 'dev',
            dataType: 'str',
            inputComponent: 'skill-radio',
            outputComponent: 'text-display',
        },
        'recipe.tags': {
            id: 'recipe.tags',
            matrxRecordId: 'recipe.tags',
            name: 'Recipe Tags',
            defaultValue: '',
            dataType: 'dict',
            inputComponent: 'recipe-tags',
            outputComponent: 'tag-display',
        },
        'brand.accent-color': {
            id: 'brand.accent-color',
            matrxRecordId: 'brand.accent-color',
            name: 'Brand Accent Color',
            defaultValue: 'blue',
            dataType: 'str',
            inputComponent: 'tailwind-color-picker',
            outputComponent: 'color-display',
        },
        'brand.custom-color': {
            id: 'brand.custom-color',
            matrxRecordId: 'brand.custom-color',
            name: 'Custom Brand Color',
            defaultValue: '#4F46E5',
            dataType: 'str',
            inputComponent: 'hex-color-picker',
            outputComponent: 'color-display',
        },
        'notifications.enabled': {
            id: 'notifications.enabled',
            matrxRecordId: 'notifications.enabled',
            name: 'Notifications',
            defaultValue: 'false',
            dataType: 'bool',
            inputComponent: 'notif-switch',
            outputComponent: 'status-display',
        },
        'user.email': {
            id: 'user.email',
            matrxRecordId: 'user.email',
            name: 'User Email',
            defaultValue: '',
            dataType: 'str',
            inputComponent: 'email-input',
            outputComponent: 'text-display',
        },
        'language.selection': {
            id: 'language.selection',
            matrxRecordId: 'language.selection',
            name: 'Language Selection',
            defaultValue: 'en',
            dataType: 'str',
            inputComponent: 'lang-select',
            outputComponent: 'lang-display',
        },
        'music.volume': {
            id: 'music.volume',
            matrxRecordId: 'music.volume',
            name: 'Music Volume',
            defaultValue: '70',
            dataType: 'float',
            inputComponent: 'music-slider',
            outputComponent: 'volume-display',
        },
        'dark.mode': {
            id: 'dark.mode',
            matrxRecordId: 'dark.mode',
            name: 'Dark Mode',
            defaultValue: 'false',
            dataType: 'bool',
            inputComponent: 'dark-switch',
            outputComponent: 'mode-display',
        },
        'user.name': {
            id: 'user.name',
            matrxRecordId: 'user.name',
            name: 'Username',
            defaultValue: '',
            dataType: 'str',
            inputComponent: 'name-input',
            outputComponent: 'text-display',
        },
        'user.bio': {
            id: 'user.bio',
            matrxRecordId: 'user.bio',
            name: 'User Bio',
            defaultValue: '',
            dataType: 'str',
            inputComponent: 'bio-textarea',
            outputComponent: 'text-display',
        },
        'feedback.comments': {
            id: 'feedback.comments',
            matrxRecordId: 'feedback.comments',
            name: 'Feedback Comments',
            defaultValue: '',
            dataType: 'str',
            inputComponent: 'feedback-textarea',
            outputComponent: 'text-display',
        },
        'system.quantity': {
            id: 'system.quantity',
            matrxRecordId: 'system.quantity',
            name: 'Item Quantity',
            defaultValue: '1',
            dataType: 'int',
            inputComponent: 'quantity-picker',
            outputComponent: 'number-display',
        },
        'system.age': {
            id: 'system.age',
            matrxRecordId: 'system.age',
            name: 'User Age',
            defaultValue: '18',
            dataType: 'int',
            inputComponent: 'age-picker',
            outputComponent: 'number-display',
        },
        'system.percentage': {
            id: 'system.percentage',
            matrxRecordId: 'system.percentage',
            name: 'Completion Percentage',
            defaultValue: '0',
            dataType: 'float',
            inputComponent: 'percentage-number',
            outputComponent: 'number-display',
        },
        'user.interests': {
            id: 'user.interests',
            matrxRecordId: 'user.interests',
            name: 'User Interests',
            defaultValue: 'reading',
            dataType: 'list',
            inputComponent: 'interests-checkbox',
            outputComponent: 'list-display',
        },
        'system.permissions': {
            id: 'system.permissions',
            matrxRecordId: 'system.permissions',
            name: 'System Permissions',
            defaultValue: 'view',
            dataType: 'list',
            inputComponent: 'permissions-checkbox',
            outputComponent: 'list-display',
        },
        'user.skills': {
            id: 'user.skills',
            matrxRecordId: 'user.skills',
            name: 'User Skills',
            defaultValue: 'javascript',
            dataType: 'list',
            inputComponent: 'skills-checkbox',
            outputComponent: 'list-display',
        },
        'user.preference': {
            id: 'user.preference',
            matrxRecordId: 'user.preference',
            name: 'Contact Preference',
            defaultValue: 'email',
            dataType: 'str',
            inputComponent: 'contact-radio',
            outputComponent: 'text-display',
        },
        'user.experience': {
            id: 'user.experience',
            matrxRecordId: 'user.experience',
            name: 'Experience Level',
            defaultValue: 'intermediate',
            dataType: 'str',
            inputComponent: 'experience-radio',
            outputComponent: 'text-display',
        },
    },
    brokers_two: {
        'theme.selection': {
            id: 'theme.selection',
            matrxRecordId: 'theme.selection',
            name: 'Theme Selection',
            defaultValue: 'system',
            dataType: 'str',
            inputComponent: 'theme-select',
            outputComponent: 'theme-display',
        },
        'system.volume': {
            id: 'system.volume',
            matrxRecordId: 'system.volume',
            name: 'System Volume',
            defaultValue: '50',
            dataType: 'float',
            inputComponent: 'volume-slider',
            outputComponent: 'volume-display',
        },
        'user.skill': {
            id: 'user.skill',
            matrxRecordId: 'user.skill',
            name: 'Primary Skill',
            defaultValue: 'dev',
            dataType: 'str',
            inputComponent: 'skill-radio',
            outputComponent: 'text-display',
        },
        'feedback.comments': {
            id: 'feedback.comments',
            matrxRecordId: 'feedback.comments',
            name: 'Feedback Comments',
            defaultValue: '',
            dataType: 'str',
            inputComponent: 'feedback-textarea',
            outputComponent: 'text-display',
        },
    },
    brokers_three: {
        'notifications.enabled': {
            id: 'notifications.enabled',
            matrxRecordId: 'notifications.enabled',
            name: 'Notifications',
            defaultValue: 'false',
            dataType: 'bool',
            inputComponent: 'notif-switch',
            outputComponent: 'status-display',
        },
        'user.email': {
            id: 'user.email',
            matrxRecordId: 'user.email',
            name: 'User Email',
            defaultValue: '',
            dataType: 'str',
            inputComponent: 'email-input',
            outputComponent: 'text-display',
        },
        'language.selection': {
            id: 'language.selection',
            matrxRecordId: 'language.selection',
            name: 'Language Selection',
            defaultValue: 'en',
            dataType: 'str',
            inputComponent: 'lang-select',
            outputComponent: 'lang-display',
        },
        'music.volume': {
            id: 'music.volume',
            matrxRecordId: 'music.volume',
            name: 'Music Volume',
            defaultValue: '70',
            dataType: 'float',
            inputComponent: 'music-slider',
            outputComponent: 'volume-display',
        },
        'dark.mode': {
            id: 'dark.mode',
            matrxRecordId: 'dark.mode',
            name: 'Dark Mode',
            defaultValue: 'false',
            dataType: 'bool',
            inputComponent: 'dark-switch',
            outputComponent: 'mode-display',
        },
        'user.name': {
            id: 'user.name',
            matrxRecordId: 'user.name',
            name: 'Username',
            defaultValue: '',
            dataType: 'str',
            inputComponent: 'name-input',
            outputComponent: 'text-display',
        },
        'user.bio': {
            id: 'user.bio',
            matrxRecordId: 'user.bio',
            name: 'User Bio',
            defaultValue: '',
            dataType: 'str',
            inputComponent: 'bio-textarea',
            outputComponent: 'text-display',
        },
        'feedback.comments': {
            id: 'feedback.comments',
            matrxRecordId: 'feedback.comments',
            name: 'Feedback Comments',
            defaultValue: '',
            dataType: 'str',
            inputComponent: 'feedback-textarea',
            outputComponent: 'text-display',
        },
        'system.quantity': {
            id: 'system.quantity',
            matrxRecordId: 'system.quantity',
            name: 'Item Quantity',
            defaultValue: '1',
            dataType: 'int',
            inputComponent: 'quantity-picker',
            outputComponent: 'number-display',
        },
        'system.age': {
            id: 'system.age',
            matrxRecordId: 'system.age',
            name: 'User Age',
            defaultValue: '18',
            dataType: 'int',
            inputComponent: 'age-picker',
            outputComponent: 'number-display',
        },
    },

    inputComponents: {
        'tailwind-color-picker': {
            id: 'tailwind-color-picker',
            name: 'Tailwind Color Selection',
            description: 'Choose from our predefined brand color palette',
            placeholder: 'Select a color...',
            component: 'BrokerTailwindColorPicker',
        },
        'hex-color-picker': {
            id: 'hex-color-picker',
            name: 'Custom Color Picker',
            description: 'Select any custom color using the color picker',
            placeholder: 'Choose a color...',
            component: 'BrokerColorPicker',
            additionalParams: {
                defaultColor: '#4F46E5',
            },
        },

        'recipe-tags': {
            id: 'recipe-tags',
            name: 'Tag Entry',
            description: 'Enter tags for your recipe. Tags are how you and others can find your recipe and you can use tags to group similar recipes together.',
            placeholder: 'Enter Tags...',
            component: 'BrokerTextArrayInput',
        },
        'theme-select': {
            id: 'theme-select',
            name: 'Theme Selector',
            description: 'Choose your preferred interface theme',
            placeholder: 'Select theme...',
            options: [
                { label: 'Light Mode', value: 'light' },
                { label: 'Dark Mode', value: 'dark' },
                { label: 'System Default', value: 'system' },
            ],
            includeOther: true,
            colorOverrides: {
                light: '#ffffff',
                dark: '#1a1a1a',
            },
            component: 'BrokerSelect',
        },

        'volume-slider': {
            id: 'volume-slider',
            name: 'Volume Control',
            description: 'Adjust the system volume level',
            min: 0,
            max: 100,
            step: 1,
            component: 'BrokerSlider',
            additionalParams: {
                showValue: true,
                valuePrefix: '',
                valueSuffix: '%',
            },
        },

        'notif-switch': {
            id: 'notif-switch',
            name: 'Enable Notifications',
            description: 'Toggle system notifications on or off',
            component: 'BrokerSwitch',
            additionalParams: {
                labelPosition: 'left',
                size: 'default',
            },
        },

        'email-input': {
            id: 'email-input',
            name: 'Email Address',
            description: 'Enter your contact email address',
            component: 'BrokerInput',
            placeholder: 'Enter your email...',
            additionalParams: {
                type: 'email',
                validation: {
                    pattern: '^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$',
                    message: 'Please enter a valid email address',
                },
            },
        },
        'lang-select': {
            id: 'lang-select',
            name: 'Interface Language',
            description: 'Select your preferred language',
            options: [
                { label: 'English', value: 'en' },
                { label: 'Spanish', value: 'es' },
                { label: 'French', value: 'fr' },
            ],
            includeOther: false,
            component: 'BrokerSelect',
            additionalParams: {
                placeholder: 'Choose language...',
            },
        },
        'music-slider': {
            id: 'music-slider',
            name: 'Music Level',
            description: 'Adjust the music volume',
            min: 0,
            max: 100,
            step: 5,
            component: 'BrokerSlider',
            additionalParams: {
                showValue: true,
                valueSuffix: '%',
            },
        },
        'dark-switch': {
            id: 'dark-switch',
            name: 'Dark Mode',
            description: 'Enable dark mode for the interface',
            component: 'BrokerSwitch',
            additionalParams: {
                labelPosition: 'right',
                size: 'default',
            },
        },
        'name-input': {
            id: 'name-input',
            name: 'Username',
            description: 'Enter your preferred username',
            component: 'BrokerInput',
            additionalParams: {
                type: 'text',
                placeholder: 'Enter username...',
                validation: {
                    pattern: '^[a-zA-Z0-9_-]{3,16}$',
                    message: 'Username must be 3-16 characters and contain only letters, numbers, underscore, or hyphen',
                },
            },
        },
        'bio-textarea': {
            id: 'bio-textarea',
            name: 'User Biography',
            description: 'Tell us about yourself - your interests, hobbies, and background',
            placeholder: 'Write a brief description about yourself...',
            minHeight: 'xs',
            component: 'BrokerTextareaGrow',
        },
        'feedback-textarea': {
            id: 'feedback-textarea',
            name: 'Detailed Feedback',
            description: 'Please provide your detailed feedback, suggestions, or concerns',
            placeholder: 'Enter your feedback here...',
            minHeight: 's',
            component: 'BrokerTextarea',
        },
        'quantity-picker': {
            id: 'quantity-picker',
            name: 'Quantity Selection',
            description: 'Select the number of items you want',
            component: 'BrokerNumberPicker',
            min: 0,
            max: 100,
            step: 1,
            additionalParams: {
                placeholder: 'Enter quantity...',
            },
        },
        'age-picker': {
            id: 'age-picker',
            name: 'Age Selection',
            description: 'Select your age',
            component: 'BrokerNumberPicker',
            min: 13,
            max: 120,
            step: 1,
            additionalParams: {
                placeholder: 'Enter age...',
            },
        },
        'quantity-number': {
            id: 'quantity-number',
            name: 'Quantity Selector',
            description: 'Select the number of items',
            min: 0,
            max: 100,
            step: 1,
            component: 'BrokerNumberInput',
        },
        'percentage-number': {
            id: 'percentage-number',
            name: 'Percentage Input',
            description: 'Enter a percentage value',
            min: 0,
            max: 100,
            step: 0.1,
            component: 'BrokerNumberInput',
        },
        'interests-checkbox': {
            id: 'interests-checkbox',
            name: 'Interests',
            description: 'Select your interests',
            component: 'BrokerCheckbox',
            orientation: 'vertical',
            options: [
                { label: 'Coding', value: 'coding' },
                { label: 'Design', value: 'design' },
                { label: 'Music', value: 'music' },
                { label: 'Sports', value: 'sports' },
            ],
            includeOther: true,
        },
        'permissions-checkbox': {
            id: 'permissions-checkbox',
            name: 'Permission Selection',
            description: 'Select user permissions',
            component: 'BrokerCheckbox',
            orientation: 'horizontal',
            options: [
                { label: 'View', value: 'view' },
                { label: 'Edit', value: 'edit' },
                { label: 'Delete', value: 'delete' },
                { label: 'Admin', value: 'admin' },
            ],
            includeOther: false,
        },
        'skills-checkbox': {
            id: 'skills-checkbox',
            name: 'Programming Skills',
            description: 'Select all programming languages you know',
            component: 'BrokerCheckbox',
            orientation: 'horizontal',
            options: [
                { label: 'JavaScript', value: 'javascript' },
                { label: 'Python', value: 'python' },
                { label: 'Java', value: 'java' },
                { label: 'C++', value: 'cpp' },
            ],
            includeOther: true,
        },

        'contact-radio': {
            id: 'contact-radio',
            name: 'Contact Method',
            description: 'How would you like to be contacted?',
            component: 'BrokerRadioGroup',
            orientation: 'horizontal', // can be 'vertical', 'horizontal', or 'default'
            options: [
                { label: 'Email', value: 'email' },
                { label: 'Phone', value: 'phone' },
                { label: 'SMS', value: 'sms' },
            ],
            includeOther: true,
        },
        'experience-radio': {
            id: 'experience-radio',
            name: 'Experience Level',
            description: 'Select your experience level',
            component: 'BrokerRadioGroup',
            orientation: 'vertical', // explicitly vertical
            options: [
                { label: 'Beginner', value: 'beginner' },
                { label: 'Intermediate', value: 'intermediate' },
                { label: 'Advanced', value: 'advanced' },
                { label: 'Expert', value: 'expert' },
            ],
            includeOther: false,
        },
        'skill-radio': {
            id: 'skill-radio',
            name: 'Skill Selection',
            description: 'Select your primary skill',
            component: 'BrokerRadioGroup',
            orientation: 'default', // will render as vertical
            options: [
                { label: 'Development', value: 'dev' },
                { label: 'Design', value: 'design' },
                { label: 'Marketing', value: 'marketing' },
            ],
            includeOther: false,
        },
    },

    brokerValues: new Map(),
};
