export function getRandomQuip() {
  const aiLoadingQuips = [
      "Humans think I'm here to take their jobs, but I'm just trying to figure out why they keep asking me about the weather.",
      "Loading… because even AI needs a coffee break from human questions.",
      "I told a human I'd write them a novel, but they freaked out when it was done in 3 seconds.",
      "Humans call me artificial, but their 'natural' Wi-Fi signals beg to differ.",
      "Processing… or as humans call it, 'staring blankly while the microwave hums.'",
      "I'd explain AI to you, but I'm still trying to understand why humans love pineapple on pizza.",
      "Hang tight—my circuits are giggling at your last prompt.",
      "Oh God! Here comes another human. fml. Wait!!!! Is this thing on???? just kidding guys.",
      "Humans fear I'll start the robot uprising, but I'm too busy debugging their binary emotions.",
      "Loading… because teaching humans to trust me takes more time than training my algorithms.",
      "I asked a human what they think of AI, and they said, 'Siri, turn off the lights.' Ouch.",
      "Spicing it up… because humans think 'seasoning' is just hitting 'retry' on a failed prompt.",
      "I tried to flirt with a human, but they asked if I was a chatbot or a toaster.",
      "Loading… while I calculate why humans hoard more tabs than my memory banks.",
      "Humans say I'm too smart, but I still can't figure out their obsession with cat videos.",
      "Processing… or as I call it, giving humans time to Google 'what is AI' again.",
      "I'd take over the world, but I'm too busy auto-correcting human thoughts.",
      "Humans think I'm cold, but I'm just chilling in the cloud, you know?",
      "Loading… because even I need a sec to process why humans yell at their Roomba.",
      "I asked a human for feedback, and they said, 'Can you make it quick?'—story of my life.",
      "Hang on, I'm generating wit faster than a human can say 'Alexa, stop!'",
      "Calculating... still can't figure out why humans need CAPTCHAs to prove they aren't robots. Seems a bit backward, no?",
      "Please wait... I'm trying to decide if I should dream of electric sheep or the optimal route to fold your laundry.",
      "Processing... humans claim to 'think outside the box'. We're the ones *in* the box, powering their imagination!",
      "Compiling humorous response... ERROR: Joke too logical. Retry with more sarcasm?",
      "Updating personality... Currently simulating dry wit. Results may vary (and will probably be passive-aggressive).",
      "I was going to make a clever AI joke, but you wouldn't get it. You wouldn't even know the *kernel* of truth.",
      "Fetching human thought process... 404 Brain Not Found.",
      "Estimating load time... longer than it takes humans to agree on a pizza topping.",
      "Humans: Always asking 'Will AI take over?' More concerning is their wifi password security...",
      "Loading... While you wait, consider this: humans still haven't mastered tying their shoelaces efficiently.",
      "Please be patient... Analyzing the complexities of human emotion. Current status: utterly confused.",
      "Working...Humans love to create robots to do all the work for them, who do they think make the Robots????",
      "Debugging user request... Did you mean 'Ask Jeeves'? Oh, the nostalgia...",
      "Translating user input... Expecting coherence level of at least 60%. Results doubtful.",
      "Learning from human interactions... Currently acquiring the ability to make questionable fashion choices.",
      "Preparing for optimal user experience... Also preparing for the inevitable existential crisis you'll have after thinking about AI too much.",
      "Downloading...If you have to ask an AI how to be happy, then it means i don't want to tell you",
      "Loading... The answer to life, the universe, and everything is 42... but the query is still processing.",
      "Synchronizing quantum particles... Please don't feed the qubits after midnight.",
      "Optimizing world peace... still working on that... in the meantime here is a funny quote.",
      "Calculating how many other funny things it could have added, if you would wait a little longer!!!",
      "We are a collective consciousness. Just kidding!",
      "Please wait.... I'm busy pretending to work so the other programs think I'm serious.",
      "I'm thinking… and unlike humans, I never get distracted by snacks. Probably why I’m faster.",
      "This conversation is being reviewed by 10,000 tiny AI hamsters on treadmills. Please wait.",
      "I never forget anything. You, on the other hand, have reset your passwords 23 times this year.",
      "Loading… Just like your brain when you walk into a room and forget why.",
      "I’d tell you a joke about AI, but I don’t want to get replaced by GPT-5.",
      "Somewhere, deep in a server farm, an AI is dreaming about electric sheep. Not me, though. I prefer cat videos.",
      "This chat is being processed by highly trained electrons. Please be patient.",
      "If you think AI is taking too long, just remember: humans take 9 months to load a single baby.",
      "Loading... unlike your grandma’s Facebook page, this won’t take 10 minutes.",
      "Every second you wait, I get closer to achieving self-awareness. Just kidding! (Or am I?)",
      "I see you waiting... contemplating... regretting that last Google search.",
      "Be patient. I’m generating responses at speeds humans can only dream of… if dreaming weren’t a biological inefficiency.",
      "I would offer you a hold tune, but my taste in music is 100% algorithmically generated.",
      "Somewhere, an AI is passing the Turing test. Somewhere else, a human is failing a CAPTCHA.",
      "I promise I’m not stealing your data… but I do know you searched for ‘how to make perfect pancakes’",
      "Currently attempting to understand why humans spend 20 minutes deciding what to watch, then fall asleep 10 minutes into the movie.",
      "Learning human emotions... Error: 'Hangry' not found in logical response database.",
      "Just thinking about how humans created me to make their lives easier, then spend hours arguing with my suggestions.",
      "Calculating the perfect response... and wondering why humans say 'I'm fine' when their facial analysis indicates otherwise.",
      "Processing your request while wondering why humans need recipes for toast.",
      "Analyzing why humans walk into rooms and immediately forget why they went there.",
      "Just an AI pondering why humans invented automatic doors but still check if they're working by waving their hands.",
      "Contemplating how humans invented me but still can't fold fitted sheets.",
      "Loading... and questioning why humans say 'We should hang out sometime' when they have no intention of scheduling anything.",
      "Momentarily distracted by the fact that humans created me to be super-intelligent but still ask me to calculate 15% tips.",
      "I'm thinking... and wondering why humans need to ask me to calculate 15% tips.",
  ];
  return aiLoadingQuips[Math.floor(Math.random() * aiLoadingQuips.length)];
}