/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed Health Check */
        get: operations["detailed_health_check_health_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/agent/warm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Warm Agent */
        post: operations["warm_agent_ai_agent_warm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/agent/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Agent */
        post: operations["execute_agent_ai_agent_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chat/unified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unified Chat */
        post: operations["unified_chat_ai_chat_unified_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/cancel/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Request */
        post: operations["cancel_request_ai_cancel__request_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/utilities/pdf/extract-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Text From Pdf */
        post: operations["extract_text_from_pdf_utilities_pdf_extract_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scraper/quick-scrape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quick Scrape */
        post: operations["quick_scrape_scraper_quick_scrape_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scraper/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Keywords */
        post: operations["search_keywords_scraper_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scraper/search-and-scrape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search And Scrape */
        post: operations["search_and_scrape_scraper_search_and_scrape_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scraper/search-and-scrape-limited": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search And Scrape Limited */
        post: operations["search_and_scrape_limited_scraper_search_and_scrape_limited_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scraper/mic-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mic Check */
        post: operations["mic_check_scraper_mic_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/test/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_tools_test_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/test/{tool_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tool Detail */
        get: operations["get_tool_detail_tools_test__tool_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/test/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Or Create Test Session */
        post: operations["get_or_create_test_session_tools_test_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/test/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Tool Test */
        post: operations["execute_tool_test_tools_test_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Examples */
        get: operations["list_examples_tests_examples_get"];
        put?: never;
        /** Create Example */
        post: operations["create_example_tests_examples_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/examples/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Example */
        get: operations["get_example_tests_examples__item_id__get"];
        /** Update Example */
        put: operations["update_example_tests_examples__item_id__put"];
        post?: never;
        /** Delete Example */
        delete: operations["delete_example_tests_examples__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/examples/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Examples */
        get: operations["search_examples_tests_examples_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/stream/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Text */
        get: operations["stream_text_tests_stream_text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentExecuteRequest */
        AgentExecuteRequest: {
            /** Prompt Id */
            prompt_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Is New Conversation
             * @default true
             */
            is_new_conversation: boolean;
            /** User Input */
            user_input?: string | {
                [key: string]: unknown;
            }[] | null;
            /** Variables */
            variables?: {
                [key: string]: unknown;
            } | null;
            /** Config Overrides */
            config_overrides?: {
                [key: string]: unknown;
            } | null;
            /**
             * Is Builtin
             * @default false
             */
            is_builtin: boolean;
            /**
             * Stream
             * @default true
             */
            stream: boolean;
            /**
             * Debug
             * @default true
             */
            debug: boolean;
        };
        /** AgentWarmRequest */
        AgentWarmRequest: {
            /** Prompt Id */
            prompt_id: string;
            /**
             * Is Builtin
             * @default false
             */
            is_builtin: boolean;
        };
        /** Body_extract_text_from_pdf_utilities_pdf_extract_text_post */
        Body_extract_text_from_pdf_utilities_pdf_extract_text_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Item */
        Item: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Price */
            price: number;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** ItemResponse */
        ItemResponse: {
            /** Id */
            id: number;
            item: components["schemas"]["Item"];
            /**
             * Created
             * @default true
             */
            created: boolean;
        };
        /** QuickScrapeRequest */
        QuickScrapeRequest: {
            /**
             * Get Organized Data
             * @default false
             */
            get_organized_data: boolean;
            /**
             * Get Structured Data
             * @default false
             */
            get_structured_data: boolean;
            /**
             * Get Overview
             * @default false
             */
            get_overview: boolean;
            /**
             * Get Text Data
             * @default true
             */
            get_text_data: boolean;
            /**
             * Get Main Image
             * @default false
             */
            get_main_image: boolean;
            /**
             * Get Links
             * @default false
             */
            get_links: boolean;
            /**
             * Get Content Filter Removal Details
             * @default false
             */
            get_content_filter_removal_details: boolean;
            /**
             * Include Highlighting Markers
             * @default true
             */
            include_highlighting_markers: boolean;
            /**
             * Include Media
             * @default true
             */
            include_media: boolean;
            /**
             * Include Media Links
             * @default true
             */
            include_media_links: boolean;
            /**
             * Include Media Description
             * @default true
             */
            include_media_description: boolean;
            /**
             * Include Anchors
             * @default true
             */
            include_anchors: boolean;
            /**
             * Anchor Size
             * @default 100
             */
            anchor_size: number;
            /** Urls */
            urls: string[];
            /**
             * Use Cache
             * @default true
             */
            use_cache: boolean;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
        };
        /** SearchAndScrapeLimitedRequest */
        SearchAndScrapeLimitedRequest: {
            /**
             * Get Organized Data
             * @default false
             */
            get_organized_data: boolean;
            /**
             * Get Structured Data
             * @default false
             */
            get_structured_data: boolean;
            /**
             * Get Overview
             * @default false
             */
            get_overview: boolean;
            /**
             * Get Text Data
             * @default true
             */
            get_text_data: boolean;
            /**
             * Get Main Image
             * @default false
             */
            get_main_image: boolean;
            /**
             * Get Links
             * @default false
             */
            get_links: boolean;
            /**
             * Get Content Filter Removal Details
             * @default false
             */
            get_content_filter_removal_details: boolean;
            /**
             * Include Highlighting Markers
             * @default true
             */
            include_highlighting_markers: boolean;
            /**
             * Include Media
             * @default true
             */
            include_media: boolean;
            /**
             * Include Media Links
             * @default true
             */
            include_media_links: boolean;
            /**
             * Include Media Description
             * @default true
             */
            include_media_description: boolean;
            /**
             * Include Anchors
             * @default true
             */
            include_anchors: boolean;
            /**
             * Anchor Size
             * @default 100
             */
            anchor_size: number;
            /** Keyword */
            keyword: string;
            /**
             * Country Code
             * @default all
             */
            country_code: string;
            /**
             * Max Page Read
             * @default 10
             */
            max_page_read: number;
            /**
             * Search Type
             * @default all
             */
            search_type: string;
        };
        /** SearchAndScrapeRequest */
        SearchAndScrapeRequest: {
            /**
             * Get Organized Data
             * @default false
             */
            get_organized_data: boolean;
            /**
             * Get Structured Data
             * @default false
             */
            get_structured_data: boolean;
            /**
             * Get Overview
             * @default false
             */
            get_overview: boolean;
            /**
             * Get Text Data
             * @default true
             */
            get_text_data: boolean;
            /**
             * Get Main Image
             * @default false
             */
            get_main_image: boolean;
            /**
             * Get Links
             * @default false
             */
            get_links: boolean;
            /**
             * Get Content Filter Removal Details
             * @default false
             */
            get_content_filter_removal_details: boolean;
            /**
             * Include Highlighting Markers
             * @default true
             */
            include_highlighting_markers: boolean;
            /**
             * Include Media
             * @default true
             */
            include_media: boolean;
            /**
             * Include Media Links
             * @default true
             */
            include_media_links: boolean;
            /**
             * Include Media Description
             * @default true
             */
            include_media_description: boolean;
            /**
             * Include Anchors
             * @default true
             */
            include_anchors: boolean;
            /**
             * Anchor Size
             * @default 100
             */
            anchor_size: number;
            /** Keywords */
            keywords: string[];
            /**
             * Country Code
             * @default all
             */
            country_code: string;
            /**
             * Total Results Per Keyword
             * @default 10
             */
            total_results_per_keyword: number;
            /**
             * Search Type
             * @default all
             */
            search_type: string;
        };
        /** SearchKeywordsRequest */
        SearchKeywordsRequest: {
            /** Keywords */
            keywords: string[];
            /**
             * Country Code
             * @default all
             */
            country_code: string;
            /**
             * Total Results Per Keyword
             * @default 5
             */
            total_results_per_keyword: number;
            /**
             * Search Type
             * @default all
             */
            search_type: string;
        };
        /** ToolTestExecuteRequest */
        ToolTestExecuteRequest: {
            /** Tool Name */
            tool_name: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** UnifiedChatRequest */
        UnifiedChatRequest: {
            /** Ai Model Id */
            ai_model_id: string;
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
            /**
             * Max Iterations
             * @default 20
             */
            max_iterations: number;
            /**
             * Max Retries Per Iteration
             * @default 2
             */
            max_retries_per_iteration: number;
            /**
             * Stream
             * @default true
             */
            stream: boolean;
            /**
             * Debug
             * @default false
             */
            debug: boolean;
            /** System Instruction */
            system_instruction?: string | null;
            /** Max Output Tokens */
            max_output_tokens?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Top P */
            top_p?: number | null;
            /** Top K */
            top_k?: number | null;
            /** Tools */
            tools?: string[] | null;
            /** Tool Choice */
            tool_choice?: unknown | null;
            /**
             * Parallel Tool Calls
             * @default true
             */
            parallel_tool_calls: boolean;
            /** Reasoning Effort */
            reasoning_effort?: string | null;
            /** Reasoning Summary */
            reasoning_summary?: string | null;
            /** Thinking Level */
            thinking_level?: string | null;
            /** Include Thoughts */
            include_thoughts?: boolean | null;
            /** Thinking Budget */
            thinking_budget?: number | null;
            /** Response Format */
            response_format?: {
                [key: string]: unknown;
            } | null;
            /** Stop Sequences */
            stop_sequences?: string[] | null;
            /** Internal Web Search */
            internal_web_search?: boolean | null;
            /** Internal Url Context */
            internal_url_context?: boolean | null;
            /** Size */
            size?: string | null;
            /** Quality */
            quality?: string | null;
            /**
             * Count
             * @default 1
             */
            count: number;
            /** Audio Voice */
            audio_voice?: string | null;
            /** Audio Format */
            audio_format?: string | null;
            /** Seconds */
            seconds?: string | null;
            /** Fps */
            fps?: number | null;
            /** Steps */
            steps?: number | null;
            /** Seed */
            seed?: number | null;
            /** Guidance Scale */
            guidance_scale?: number | null;
            /** Output Quality */
            output_quality?: number | null;
            /** Negative Prompt */
            negative_prompt?: string | null;
            /** Output Format */
            output_format?: string | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Frame Images */
            frame_images?: unknown[] | null;
            /** Reference Images */
            reference_images?: unknown[] | null;
            /** Disable Safety Checker */
            disable_safety_checker?: boolean | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Is New Conversation
             * @default true
             */
            is_new_conversation: boolean;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Store
             * @default true
             */
            store: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    detailed_health_check_health_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    warm_agent_ai_agent_warm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentWarmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_agent_ai_agent_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unified_chat_ai_chat_unified_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnifiedChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_request_ai_cancel__request_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_text_from_pdf_utilities_pdf_extract_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_text_from_pdf_utilities_pdf_extract_text_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quick_scrape_scraper_quick_scrape_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickScrapeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_keywords_scraper_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchKeywordsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_and_scrape_scraper_search_and_scrape_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchAndScrapeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_and_scrape_limited_scraper_search_and_scrape_limited_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchAndScrapeLimitedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mic_check_scraper_mic_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_tools_tools_test_list_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tool_detail_tools_test__tool_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_or_create_test_session_tools_test_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    execute_tool_test_tools_test_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolTestExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_examples_tests_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_example_tests_examples_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Item"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_example_tests_examples__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_example_tests_examples__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Item"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_example_tests_examples__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_examples_tests_examples_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_text_tests_stream_text_get: {
        parameters: {
            query?: {
                message?: string;
                chunks?: number;
                delay?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
