"use client";

/**
 * Auto-label a studio session from its raw transcript content.
 *
 * Pattern stolen wholesale from features/notes/hooks/useAutoLabel.ts —
 * `generateLabelFromContent` is the same generic title-from-prose function
 * that powers iPhone-Notes-style auto-titling there. We only auto-overwrite
 * when the title is the default placeholder; once the user edits manually,
 * the heuristic stops firing for the rest of the session.
 *
 * Threshold mirrors notes: fires when the joined raw text reaches ~minChars
 * OR contains a sentence break / newline. After a successful auto-title,
 * the local guard `hasAutoGenerated` prevents it from firing again — the
 * user is free to edit the title manually after that.
 */

import { useEffect, useRef } from "react";
import { generateLabelFromContent } from "@/features/notes/hooks/useAutoLabel";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import { selectRawSegments } from "../redux/selectors";
import { updateSessionThunk } from "../redux/thunks";
import { NEW_SESSION_DEFAULT_TITLE } from "../constants";

const TITLE_MIN_CHARS = 20;
const TITLE_MAX_LEN = 50;
const PLACEHOLDER_TITLES = new Set([
  NEW_SESSION_DEFAULT_TITLE.toLowerCase(),
  "new studio session",
  "untitled",
  "",
]);

interface UseStudioAutoLabelOptions {
  sessionId: string;
  currentTitle: string;
}

export function useStudioAutoLabel({
  sessionId,
  currentTitle,
}: UseStudioAutoLabelOptions) {
  const dispatch = useAppDispatch();
  const rawSegments = useAppSelector(selectRawSegments(sessionId));
  const hasAutoGenerated = useRef(false);
  const lastSeenSessionId = useRef<string | null>(null);

  useEffect(() => {
    // Reset the guard whenever the active session changes — different
    // sessions get their own one-shot auto-title chance.
    if (lastSeenSessionId.current !== sessionId) {
      lastSeenSessionId.current = sessionId;
      hasAutoGenerated.current = false;
    }

    if (hasAutoGenerated.current) return;

    const titleNorm = currentTitle.trim().toLowerCase();
    const isPlaceholder = PLACEHOLDER_TITLES.has(titleNorm);
    if (!isPlaceholder) {
      // User picked their own title — don't touch it again this session.
      hasAutoGenerated.current = true;
      return;
    }

    // Build the candidate text from the first ~3 raw segments. We don't
    // need the whole transcript — the first sentence or two is enough.
    const head = rawSegments
      .slice(0, 3)
      .map((s) => s.text)
      .join(" ")
      .trim();

    if (head.length < TITLE_MIN_CHARS && !head.includes("\n")) return;

    const generated = generateLabelFromContent(head, TITLE_MAX_LEN);
    if (!generated || generated.toLowerCase() === titleNorm) return;

    hasAutoGenerated.current = true;
    void dispatch(
      updateSessionThunk({ id: sessionId, patch: { title: generated } }),
    );
  }, [sessionId, currentTitle, rawSegments, dispatch]);
}
