/**
 * features/files/utils/folder-conventions.ts
 *
 * Canonical folder paths for every feature that uploads on behalf of the
 * user. The rule is simple: **organize files the way a user would expect to
 * find them.** When a user opens `/files`, they should be able to
 * point at a folder and say "that's where X goes" without us explaining it.
 *
 * Two buckets:
 *
 *  1. Visible folders — real, user-facing. Files go here when the user
 *     produced them, uploaded them, or attached them to something. Names are
 *     human-readable (Title Case) because they're shown in the tree.
 *
 *  2. Hidden folders (leading `.`) — ephemeral / infrastructure files the
 *     user doesn't need to see or manage. Auto-collapsed in the UI. These
 *     should be rare; only use them for true transients (short-lived URL
 *     staging, drafts) and prefer deletion on completion.
 *
 * Every consumer migration should pick its folder from this file or add a
 * new constant here — do NOT hand-roll folder paths at call sites.
 */

// ---------------------------------------------------------------------------
// Static (feature-level) folders
// ---------------------------------------------------------------------------

export const CloudFolders = {
  // ── Visible / user-managed ────────────────────────────────────────────

  /** Top-level "Images" drawer. */
  IMAGES: "Images",
  /** Images pasted/attached inside a chat. */
  IMAGES_CHAT: "Images/Chat",
  /** Screenshots dragged or pasted into the app. */
  IMAGES_SCREENSHOTS: "Images/Screenshots",
  /** User avatars / profile images. */
  IMAGES_AVATARS: "Images/Avatars",
  /** Images generated by AI tools. */
  IMAGES_GENERATED: "Images/Generated",

  /** Top-level "Audio" drawer. */
  AUDIO: "Audio",
  /** User-initiated audio recordings (voice-to-text, voice pad, etc.). */
  AUDIO_RECORDINGS: "Audio/Recordings",
  /** Podcast asset uploads. */
  AUDIO_PODCASTS: "Audio/Podcasts",

  /** Top-level documents (PDF, DOCX, etc.). */
  DOCUMENTS: "Documents",
  /** PDF-specific drawer. */
  DOCUMENTS_PDFS: "Documents/PDFs",

  /** Top-level code files (scripts, snippets). */
  CODE: "Code",
  /** Code saved via the code-editor window. */
  CODE_EDITOR: "Code/Editor",

  /** Generic AI-generated outputs. */
  GENERATED: "Generated",

  /** Files attached to agent apps, keyed by app id at runtime. */
  AGENT_APPS: "Agent Apps",

  /** Files attached to tasks, keyed by task id at runtime. */
  TASK_ATTACHMENTS: "Task Attachments",

  /** Files dropped into a chat composer (pre-send or history). */
  CHAT_ATTACHMENTS: "Chat Attachments",

  /** Slack-imported files. */
  SLACK_IMPORTS: "Slack Imports",

  /** Web-scrape captures (HTML snapshots, exported markdown). */
  SCRAPED_CONTENT: "Scraped Content",

  // ── Hidden / ephemeral ─────────────────────────────────────────────────
  // All hidden roots live under ".matrx-tmp/" so the tree has a single
  // ignorable folder rather than many. Callers that use these MUST delete
  // the file when done.

  /** Root for all ephemeral cloud-files work. Hidden in the tree. */
  TMP: ".matrx-tmp",
  /** Short-lived audio files staged for URL-based transcription. */
  TMP_TRANSCRIPTS: ".matrx-tmp/transcripts",
  /** Upload-in-progress staging (future use). */
  TMP_UPLOADS: ".matrx-tmp/uploads",
} as const;

// ---------------------------------------------------------------------------
// Dynamic folder builders — for entity-scoped subfolders.
// ---------------------------------------------------------------------------

/**
 * Files attached to a specific task.
 *   folderForTask("abc-123") → "Task Attachments/abc-123"
 */
export function folderForTask(taskId: string): string {
  return `${CloudFolders.TASK_ATTACHMENTS}/${taskId}`;
}

/**
 * Files attached to a specific chat / conversation.
 *   folderForConversation("xyz") → "Chat Attachments/xyz"
 */
export function folderForConversation(conversationId: string): string {
  return `${CloudFolders.CHAT_ATTACHMENTS}/${conversationId}`;
}

/**
 * Assets for a specific agent app (favicon, icons, etc.).
 *   folderForAgentApp("abc") → "Agent Apps/abc"
 */
export function folderForAgentApp(appId: string): string {
  return `${CloudFolders.AGENT_APPS}/${appId}`;
}

/**
 * Per-podcast episode assets.
 */
export function folderForPodcast(podcastId: string): string {
  return `${CloudFolders.AUDIO_PODCASTS}/${podcastId}`;
}

// ---------------------------------------------------------------------------
// Predicates
// ---------------------------------------------------------------------------

/** True if the folder is under `.matrx-tmp/` (user-hidden). */
export function isHiddenFolder(folderPath: string): boolean {
  return (
    folderPath === CloudFolders.TMP || folderPath.startsWith(".matrx-tmp/")
  );
}

/**
 * True if the folder path matches one of our canonical conventions (either
 * visible or hidden). Useful for UI that wants to show a pretty icon next
 * to known folders.
 */
export function isConventionalFolder(folderPath: string): boolean {
  const all = Object.values(CloudFolders) as string[];
  return all.includes(folderPath);
}

// ---------------------------------------------------------------------------
// Reverse-lookup helpers — used by e.g. FileIcon to render a special badge
// for well-known folders.
// ---------------------------------------------------------------------------

/**
 * Maps a CloudFolders constant → human-friendly description for tooltips /
 * empty states. Extend as needed.
 */
export const CloudFolderDescriptions: Record<string, string> = {
  [CloudFolders.IMAGES]: "All your images, organized.",
  [CloudFolders.IMAGES_CHAT]: "Images shared in chat.",
  [CloudFolders.IMAGES_SCREENSHOTS]: "Screenshots you pasted or dragged in.",
  [CloudFolders.IMAGES_AVATARS]: "Profile pictures and avatars.",
  [CloudFolders.IMAGES_GENERATED]: "AI-generated images.",
  [CloudFolders.AUDIO]: "Audio files.",
  [CloudFolders.AUDIO_RECORDINGS]: "Voice recordings.",
  [CloudFolders.AUDIO_PODCASTS]: "Podcast assets.",
  [CloudFolders.DOCUMENTS]: "Documents and reports.",
  [CloudFolders.DOCUMENTS_PDFS]: "PDFs.",
  [CloudFolders.CODE]: "Code files.",
  [CloudFolders.GENERATED]: "Files produced by AI tools.",
  [CloudFolders.AGENT_APPS]: "Assets attached to your agent apps.",
  [CloudFolders.TASK_ATTACHMENTS]: "Files attached to tasks.",
  [CloudFolders.CHAT_ATTACHMENTS]: "Files shared in conversations.",
  [CloudFolders.SLACK_IMPORTS]: "Files imported from Slack.",
  [CloudFolders.SCRAPED_CONTENT]: "Captures from the web scraper.",
  [CloudFolders.TMP]: "Internal temporary workspace (hidden).",
};
