import { createClient } from "@/utils/supabase/server";
import { NextRequest, NextResponse } from "next/server";

/**
 * POST /api/agent-shortcut-categories/[id]/duplicate
 *
 * Duplicates a shortcut category while preserving the source row's ownership
 * (`user_id`, `organization_id`, `project_id`, `task_id`). The caller may
 * override `label`, `placementType`, and `parentCategoryId`; all other fields
 * (description, iconName, color, sortOrder, isActive, enabledFeatures,
 * metadata) are copied from the source. `id`, `createdAt`, and `updatedAt` are
 * always regenerated by the database.
 *
 * Scope preservation matters for the admin surfaces: duplicating a global
 * category must produce another global category, not one owned by the
 * admin's user account. The row-level FKs travel with the copy as-is, and
 * RLS on INSERT is expected to allow the caller based on the resulting row
 * shape (same rules that govern `POST /api/agent-shortcut-categories`).
 */
export async function POST(
  request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await context.params;
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    let overrides: {
      label?: unknown;
      placement_type?: unknown;
      parent_category_id?: unknown;
      sort_order?: unknown;
    } = {};
    try {
      const raw = await request.json();
      if (raw && typeof raw === "object") {
        overrides = raw as typeof overrides;
      }
    } catch {
      // empty body is fine — fall through with defaults
    }

    const { data: source, error: sourceError } = await supabase
      .from("shortcut_categories")
      .select("*")
      .eq("id", id)
      .maybeSingle();

    if (sourceError) {
      console.error("Error loading source category:", sourceError);
      return NextResponse.json(
        {
          error: "Failed to load source category",
          details: sourceError.message,
        },
        { status: 500 },
      );
    }

    if (!source) {
      return NextResponse.json(
        { error: "Source category not found or access denied" },
        { status: 404 },
      );
    }

    const nextLabel =
      typeof overrides.label === "string" && overrides.label.trim().length > 0
        ? overrides.label.trim()
        : `${source.label} (Copy)`;

    const nextPlacementType =
      typeof overrides.placement_type === "string" &&
      overrides.placement_type.trim().length > 0
        ? overrides.placement_type.trim()
        : source.placement_type;

    // `parent_category_id` is only carried over when the placement matches the
    // source; otherwise the old parent no longer makes sense.
    let nextParentCategoryId: string | null = null;
    if (nextPlacementType === source.placement_type) {
      nextParentCategoryId = source.parent_category_id;
    }
    if (overrides.parent_category_id === null) {
      nextParentCategoryId = null;
    } else if (typeof overrides.parent_category_id === "string") {
      nextParentCategoryId = overrides.parent_category_id;
    }

    const nextSortOrder =
      typeof overrides.sort_order === "number"
        ? overrides.sort_order
        : source.sort_order;

    const insertPayload = {
      label: nextLabel,
      description: source.description,
      icon_name: source.icon_name,
      color: source.color,
      placement_type: nextPlacementType,
      parent_category_id: nextParentCategoryId,
      sort_order: nextSortOrder,
      is_active: source.is_active,
      metadata: source.metadata,
      enabled_features: source.enabled_features,
      // Preserve ownership exactly — admins keep global, users keep user,
      // orgs keep org, etc.
      user_id: source.user_id,
      organization_id: source.organization_id,
      project_id: source.project_id,
      task_id: source.task_id,
    };

    const { data, error } = await supabase
      .from("shortcut_categories")
      .insert(insertPayload as never)
      .select()
      .single();

    if (error) {
      console.error("Error duplicating shortcut category:", error);
      const status =
        error.code === "42501" || error.code === "PGRST301" ? 403 : 500;
      return NextResponse.json(
        {
          error: "Failed to duplicate shortcut category",
          details: error.message,
        },
        { status },
      );
    }

    return NextResponse.json({ data }, { status: 201 });
  } catch (error) {
    console.error(
      "Error in POST /api/agent-shortcut-categories/[id]/duplicate:",
      error,
    );
    return NextResponse.json(
      {
        error: "Internal server error",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
