export const tableNameLookup: Record<string, string> = {
    Action: "action",
    p_action: "action",
    action: "action",
    "ai-endpoint": "ai_endpoint",
    "Ai Endpoint": "ai_endpoint",
    aiEndpoint: "ai_endpoint",
    p_ai_endpoint: "ai_endpoint",
    ai_endpoint: "ai_endpoint",
    AiEndpoint: "ai_endpoint",
    "ai-model": "ai_model",
    AiModel: "ai_model",
    p_ai_model: "ai_model",
    aiModel: "ai_model",
    "Ai Model": "ai_model",
    ai_model: "ai_model",
    Arg: "arg",
    p_arg: "arg",
    arg: "arg",
    p_automation_boundary_broker: "automation_boundary_broker",
    "Automation Boundary Broker": "automation_boundary_broker",
    AutomationBoundaryBroker: "automation_boundary_broker",
    "automation-boundary-broker": "automation_boundary_broker",
    automationBoundaryBroker: "automation_boundary_broker",
    automation_boundary_broker: "automation_boundary_broker",
    p_automation_matrix: "automation_matrix",
    "automation-matrix": "automation_matrix",
    AutomationMatrix: "automation_matrix",
    "Automation Matrix": "automation_matrix",
    automation_matrix: "automation_matrix",
    automationMatrix: "automation_matrix",
    broker: "broker",
    p_broker: "broker",
    Broker: "broker",
    dataInputComponent: "data_input_component",
    "Data Input Component": "data_input_component",
    data_input_component: "data_input_component",
    p_data_input_component: "data_input_component",
    "data-input-component": "data_input_component",
    DataInputComponent: "data_input_component",
    "Data Output Component": "data_output_component",
    data_output_component: "data_output_component",
    DataOutputComponent: "data_output_component",
    p_data_output_component: "data_output_component",
    "data-output-component": "data_output_component",
    dataOutputComponent: "data_output_component",
    DisplayOption: "display_option",
    "Display Option": "display_option",
    displayOption: "display_option",
    "display-option": "display_option",
    p_display_option: "display_option",
    display_option: "display_option",
    emails: "emails",
    Emails: "emails",
    p_emails: "emails",
    extractor: "extractor",
    p_extractor: "extractor",
    Extractor: "extractor",
    flashcard_data: "flashcard_data",
    flashcardData: "flashcard_data",
    "Flashcard Data": "flashcard_data",
    "flashcard-data": "flashcard_data",
    p_flashcard_data: "flashcard_data",
    FlashcardData: "flashcard_data",
    FlashcardHistory: "flashcard_history",
    p_flashcard_history: "flashcard_history",
    flashcardHistory: "flashcard_history",
    "Flashcard History": "flashcard_history",
    flashcard_history: "flashcard_history",
    "flashcard-history": "flashcard_history",
    FlashcardImages: "flashcard_images",
    "Flashcard Images": "flashcard_images",
    flashcard_images: "flashcard_images",
    flashcardImages: "flashcard_images",
    "flashcard-images": "flashcard_images",
    p_flashcard_images: "flashcard_images",
    FlashcardSetRelations: "flashcard_set_relations",
    "flashcard-set-relations": "flashcard_set_relations",
    flashcard_set_relations: "flashcard_set_relations",
    "Flashcard Set Relations": "flashcard_set_relations",
    p_flashcard_set_relations: "flashcard_set_relations",
    flashcardSetRelations: "flashcard_set_relations",
    flashcard_sets: "flashcard_sets",
    FlashcardSets: "flashcard_sets",
    "Flashcard Sets": "flashcard_sets",
    p_flashcard_sets: "flashcard_sets",
    "flashcard-sets": "flashcard_sets",
    flashcardSets: "flashcard_sets",
    Processor: "processor",
    processor: "processor",
    p_processor: "processor",
    recipe: "recipe",
    p_recipe: "recipe",
    Recipe: "recipe",
    recipe_broker: "recipe_broker",
    "Recipe Broker": "recipe_broker",
    p_recipe_broker: "recipe_broker",
    RecipeBroker: "recipe_broker",
    recipeBroker: "recipe_broker",
    "recipe-broker": "recipe_broker",
    recipeDisplay: "recipe_display",
    recipe_display: "recipe_display",
    RecipeDisplay: "recipe_display",
    p_recipe_display: "recipe_display",
    "Recipe Display": "recipe_display",
    "recipe-display": "recipe_display",
    p_recipe_function: "recipe_function",
    "Recipe Function": "recipe_function",
    RecipeFunction: "recipe_function",
    recipeFunction: "recipe_function",
    recipe_function: "recipe_function",
    "recipe-function": "recipe_function",
    recipe_model: "recipe_model",
    RecipeModel: "recipe_model",
    recipeModel: "recipe_model",
    p_recipe_model: "recipe_model",
    "recipe-model": "recipe_model",
    "Recipe Model": "recipe_model",
    "recipe-processor": "recipe_processor",
    p_recipe_processor: "recipe_processor",
    "Recipe Processor": "recipe_processor",
    recipeProcessor: "recipe_processor",
    recipe_processor: "recipe_processor",
    RecipeProcessor: "recipe_processor",
    "Recipe Tool": "recipe_tool",
    p_recipe_tool: "recipe_tool",
    "recipe-tool": "recipe_tool",
    RecipeTool: "recipe_tool",
    recipeTool: "recipe_tool",
    recipe_tool: "recipe_tool",
    RegisteredFunction: "registered_function",
    registered_function: "registered_function",
    "registered-function": "registered_function",
    "Registered Function": "registered_function",
    p_registered_function: "registered_function",
    registeredFunction: "registered_function",
    SystemFunction: "system_function",
    "System Function": "system_function",
    "system-function": "system_function",
    p_system_function: "system_function",
    system_function: "system_function",
    systemFunction: "system_function",
    p_tool: "tool",
    tool: "tool",
    Tool: "tool",
    transformer: "transformer",
    p_transformer: "transformer",
    Transformer: "transformer",
    UserPreferences: "user_preferences",
    "user-preferences": "user_preferences",
    p_user_preferences: "user_preferences",
    user_preferences: "user_preferences",
    "User Preferences": "user_preferences",
    userPreferences: "user_preferences",
};

export const viewNameLookup: Record<string, string> = {
    ViewRegisteredFunction: "view_registered_function",
    "View Registered Function": "view_registered_function",
    "view-registered-function": "view_registered_function",
    viewRegisteredFunction: "view_registered_function",
    p_view_registered_function: "view_registered_function",
    view_registered_function: "view_registered_function",
    ViewRegisteredFunctionAllRels: "view_registered_function_all_rels",
    p_view_registered_function_all_rels: "view_registered_function_all_rels",
    viewRegisteredFunctionAllRels: "view_registered_function_all_rels",
    view_registered_function_all_rels: "view_registered_function_all_rels",
    "view-registered-function-all-rels": "view_registered_function_all_rels",
    "View Registered Function All Rels": "view_registered_function_all_rels",
};

export const fieldNameLookup: Record<string, Record<string, string>> = {
    action: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        Matrix: "matrix",
        p_matrix: "matrix",
        matrix: "matrix",
        transformer: "transformer",
        p_transformer: "transformer",
        Transformer: "transformer",
        "Node Type": "node_type",
        NodeType: "node_type",
        "node-type": "node_type",
        p_node_type: "node_type",
        node_type: "node_type",
        nodeType: "node_type",
        p_reference_id: "reference_id",
        "reference-id": "reference_id",
        ReferenceId: "reference_id",
        referenceId: "reference_id",
        "Reference Id": "reference_id",
        reference_id: "reference_id"
    },
    aiEndpoint: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        p_provider: "provider",
        Provider: "provider",
        provider: "provider",
        description: "description",
        p_description: "description",
        Description: "description",
        additional_cost: "additional_cost",
        "additional-cost": "additional_cost",
        AdditionalCost: "additional_cost",
        "Additional Cost": "additional_cost",
        p_additional_cost: "additional_cost",
        additionalCost: "additional_cost",
        "cost-details": "cost_details",
        cost_details: "cost_details",
        "Cost Details": "cost_details",
        costDetails: "cost_details",
        CostDetails: "cost_details",
        p_cost_details: "cost_details",
        p_params: "params",
        Params: "params",
        params: "params"
    },
    aiModel: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        "common-name": "common_name",
        CommonName: "common_name",
        commonName: "common_name",
        p_common_name: "common_name",
        "Common Name": "common_name",
        common_name: "common_name",
        "Model Class": "model_class",
        modelClass: "model_class",
        "model-class": "model_class",
        model_class: "model_class",
        p_model_class: "model_class",
        ModelClass: "model_class",
        p_provider: "provider",
        Provider: "provider",
        provider: "provider",
        Endpoints: "endpoints",
        p_endpoints: "endpoints",
        endpoints: "endpoints",
        contextWindow: "context_window",
        "Context Window": "context_window",
        p_context_window: "context_window",
        ContextWindow: "context_window",
        "context-window": "context_window",
        context_window: "context_window",
        p_max_tokens: "max_tokens",
        maxTokens: "max_tokens",
        max_tokens: "max_tokens",
        MaxTokens: "max_tokens",
        "max-tokens": "max_tokens",
        "Max Tokens": "max_tokens",
        Capabilities: "capabilities",
        p_capabilities: "capabilities",
        capabilities: "capabilities",
        p_controls: "controls",
        Controls: "controls",
        controls: "controls"
    },
    arg: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        p_required: "required",
        required: "required",
        Required: "required",
        p_default: "default",
        default: "default",
        Default: "default",
        data_type: "data_type",
        DataType: "data_type",
        p_data_type: "data_type",
        "Data Type": "data_type",
        dataType: "data_type",
        "data-type": "data_type",
        p_ready: "ready",
        ready: "ready",
        Ready: "ready",
        RegisteredFunction: "registered_function",
        registered_function: "registered_function",
        "registered-function": "registered_function",
        "Registered Function": "registered_function",
        p_registered_function: "registered_function",
        registeredFunction: "registered_function"
    },
    automationBoundaryBroker: {
        p_id: "id",
        id: "id",
        Id: "id",
        Matrix: "matrix",
        p_matrix: "matrix",
        matrix: "matrix",
        broker: "broker",
        p_broker: "broker",
        Broker: "broker",
        "spark-source": "spark_source",
        "Spark Source": "spark_source",
        spark_source: "spark_source",
        sparkSource: "spark_source",
        p_spark_source: "spark_source",
        SparkSource: "spark_source",
        "beacon-destination": "beacon_destination",
        p_beacon_destination: "beacon_destination",
        BeaconDestination: "beacon_destination",
        beacon_destination: "beacon_destination",
        "Beacon Destination": "beacon_destination",
        beaconDestination: "beacon_destination"
    },
    automationMatrix: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        description: "description",
        p_description: "description",
        Description: "description",
        averageSeconds: "average_seconds",
        "Average Seconds": "average_seconds",
        average_seconds: "average_seconds",
        p_average_seconds: "average_seconds",
        AverageSeconds: "average_seconds",
        "average-seconds": "average_seconds",
        "Is Automated": "is_automated",
        p_is_automated: "is_automated",
        IsAutomated: "is_automated",
        isAutomated: "is_automated",
        is_automated: "is_automated",
        "is-automated": "is_automated",
        cognitionMatrices: "cognition_matrices",
        "Cognition Matrices": "cognition_matrices",
        p_cognition_matrices: "cognition_matrices",
        cognition_matrices: "cognition_matrices",
        CognitionMatrices: "cognition_matrices",
        "cognition-matrices": "cognition_matrices"
    },
    broker: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        value: "value",
        Value: "value",
        p_value: "value",
        data_type: "data_type",
        DataType: "data_type",
        p_data_type: "data_type",
        "Data Type": "data_type",
        dataType: "data_type",
        "data-type": "data_type",
        p_ready: "ready",
        ready: "ready",
        Ready: "ready",
        "default-source": "default_source",
        defaultSource: "default_source",
        DefaultSource: "default_source",
        p_default_source: "default_source",
        default_source: "default_source",
        "Default Source": "default_source",
        "display-name": "display_name",
        display_name: "display_name",
        p_display_name: "display_name",
        displayName: "display_name",
        "Display Name": "display_name",
        DisplayName: "display_name",
        description: "description",
        p_description: "description",
        Description: "description",
        tooltip: "tooltip",
        Tooltip: "tooltip",
        p_tooltip: "tooltip",
        p_validation_rules: "validation_rules",
        validation_rules: "validation_rules",
        "validation-rules": "validation_rules",
        "Validation Rules": "validation_rules",
        validationRules: "validation_rules",
        ValidationRules: "validation_rules",
        sampleEntries: "sample_entries",
        "Sample Entries": "sample_entries",
        p_sample_entries: "sample_entries",
        sample_entries: "sample_entries",
        "sample-entries": "sample_entries",
        SampleEntries: "sample_entries",
        "custom-source-component": "custom_source_component",
        custom_source_component: "custom_source_component",
        customSourceComponent: "custom_source_component",
        CustomSourceComponent: "custom_source_component",
        p_custom_source_component: "custom_source_component",
        "Custom Source Component": "custom_source_component",
        additionalParams: "additional_params",
        additional_params: "additional_params",
        p_additional_params: "additional_params",
        "Additional Params": "additional_params",
        AdditionalParams: "additional_params",
        "additional-params": "additional_params",
        OtherSourceParams: "other_source_params",
        p_other_source_params: "other_source_params",
        "other-source-params": "other_source_params",
        otherSourceParams: "other_source_params",
        other_source_params: "other_source_params",
        "Other Source Params": "other_source_params",
        default_destination: "default_destination",
        "Default Destination": "default_destination",
        p_default_destination: "default_destination",
        DefaultDestination: "default_destination",
        defaultDestination: "default_destination",
        "default-destination": "default_destination",
        p_output_component: "output_component",
        "output-component": "output_component",
        outputComponent: "output_component",
        "Output Component": "output_component",
        output_component: "output_component",
        OutputComponent: "output_component",
        p_tags: "tags",
        Tags: "tags",
        tags: "tags"
    },
    dataInputComponent: {
        p_id: "id",
        id: "id",
        Id: "id",
        options: "options",
        p_options: "options",
        Options: "options",
        "include-other": "include_other",
        includeOther: "include_other",
        IncludeOther: "include_other",
        p_include_other: "include_other",
        "Include Other": "include_other",
        include_other: "include_other",
        p_min: "min",
        min: "min",
        Min: "min",
        max: "max",
        Max: "max",
        p_max: "max",
        p_step: "step",
        step: "step",
        Step: "step",
        MinRows: "min_rows",
        min_rows: "min_rows",
        "Min Rows": "min_rows",
        "min-rows": "min_rows",
        minRows: "min_rows",
        p_min_rows: "min_rows",
        p_max_rows: "max_rows",
        MaxRows: "max_rows",
        "max-rows": "max_rows",
        max_rows: "max_rows",
        "Max Rows": "max_rows",
        maxRows: "max_rows",
        "acceptable-filetypes": "acceptable_filetypes",
        AcceptableFiletypes: "acceptable_filetypes",
        p_acceptable_filetypes: "acceptable_filetypes",
        "Acceptable Filetypes": "acceptable_filetypes",
        acceptableFiletypes: "acceptable_filetypes",
        acceptable_filetypes: "acceptable_filetypes",
        p_src: "src",
        src: "src",
        Src: "src",
        Classes: "classes",
        classes: "classes",
        p_classes: "classes",
        "Color Overrides": "color_overrides",
        p_color_overrides: "color_overrides",
        ColorOverrides: "color_overrides",
        colorOverrides: "color_overrides",
        color_overrides: "color_overrides",
        "color-overrides": "color_overrides",
        additionalParams: "additional_params",
        additional_params: "additional_params",
        p_additional_params: "additional_params",
        "Additional Params": "additional_params",
        AdditionalParams: "additional_params",
        "additional-params": "additional_params"
    },
    dataOutputComponent: {
        p_id: "id",
        id: "id",
        Id: "id",
        "Component Type": "component_type",
        component_type: "component_type",
        "component-type": "component_type",
        p_component_type: "component_type",
        componentType: "component_type",
        ComponentType: "component_type",
        "Ui Component": "ui_component",
        p_ui_component: "ui_component",
        UiComponent: "ui_component",
        "ui-component": "ui_component",
        uiComponent: "ui_component",
        ui_component: "ui_component",
        props: "props",
        Props: "props",
        p_props: "props",
        additionalParams: "additional_params",
        additional_params: "additional_params",
        p_additional_params: "additional_params",
        "Additional Params": "additional_params",
        AdditionalParams: "additional_params",
        "additional-params": "additional_params"
    },
    displayOption: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        defaultParams: "default_params",
        p_default_params: "default_params",
        default_params: "default_params",
        DefaultParams: "default_params",
        "Default Params": "default_params",
        "default-params": "default_params",
        "Customizable Params": "customizable_params",
        customizable_params: "customizable_params",
        customizableParams: "customizable_params",
        p_customizable_params: "customizable_params",
        "customizable-params": "customizable_params",
        CustomizableParams: "customizable_params",
        additionalParams: "additional_params",
        additional_params: "additional_params",
        p_additional_params: "additional_params",
        "Additional Params": "additional_params",
        AdditionalParams: "additional_params",
        "additional-params": "additional_params"
    },
    emails: {
        p_id: "id",
        id: "id",
        Id: "id",
        Sender: "sender",
        p_sender: "sender",
        sender: "sender",
        Recipient: "recipient",
        p_recipient: "recipient",
        recipient: "recipient",
        Subject: "subject",
        subject: "subject",
        p_subject: "subject",
        body: "body",
        Body: "body",
        p_body: "body",
        timestamp: "timestamp",
        Timestamp: "timestamp",
        p_timestamp: "timestamp",
        p_is_read: "is_read",
        IsRead: "is_read",
        is_read: "is_read",
        "is-read": "is_read",
        isRead: "is_read",
        "Is Read": "is_read"
    },
    extractor: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        p_output_type: "output_type",
        output_type: "output_type",
        "output-type": "output_type",
        OutputType: "output_type",
        outputType: "output_type",
        "Output Type": "output_type",
        default_identifier: "default_identifier",
        DefaultIdentifier: "default_identifier",
        p_default_identifier: "default_identifier",
        defaultIdentifier: "default_identifier",
        "Default Identifier": "default_identifier",
        "default-identifier": "default_identifier",
        DefaultIndex: "default_index",
        p_default_index: "default_index",
        default_index: "default_index",
        "default-index": "default_index",
        "Default Index": "default_index",
        defaultIndex: "default_index"
    },
    flashcardData: {
        p_id: "id",
        id: "id",
        Id: "id",
        "User Id": "user_id",
        userId: "user_id",
        user_id: "user_id",
        p_user_id: "user_id",
        "user-id": "user_id",
        UserId: "user_id",
        topic: "topic",
        Topic: "topic",
        p_topic: "topic",
        lesson: "lesson",
        Lesson: "lesson",
        p_lesson: "lesson",
        Difficulty: "difficulty",
        p_difficulty: "difficulty",
        difficulty: "difficulty",
        p_front: "front",
        Front: "front",
        front: "front",
        Back: "back",
        p_back: "back",
        back: "back",
        example: "example",
        Example: "example",
        p_example: "example",
        detailed_explanation: "detailed_explanation",
        DetailedExplanation: "detailed_explanation",
        detailedExplanation: "detailed_explanation",
        "detailed-explanation": "detailed_explanation",
        p_detailed_explanation: "detailed_explanation",
        "Detailed Explanation": "detailed_explanation",
        "audio-explanation": "audio_explanation",
        audioExplanation: "audio_explanation",
        "Audio Explanation": "audio_explanation",
        AudioExplanation: "audio_explanation",
        p_audio_explanation: "audio_explanation",
        audio_explanation: "audio_explanation",
        "personal-notes": "personal_notes",
        PersonalNotes: "personal_notes",
        p_personal_notes: "personal_notes",
        personal_notes: "personal_notes",
        "Personal Notes": "personal_notes",
        personalNotes: "personal_notes",
        "Is Deleted": "is_deleted",
        "is-deleted": "is_deleted",
        is_deleted: "is_deleted",
        isDeleted: "is_deleted",
        IsDeleted: "is_deleted",
        p_is_deleted: "is_deleted",
        public: "public",
        Public: "public",
        p_public: "public",
        p_shared_with: "shared_with",
        "Shared With": "shared_with",
        "shared-with": "shared_with",
        shared_with: "shared_with",
        sharedWith: "shared_with",
        SharedWith: "shared_with",
        created_at: "created_at",
        createdAt: "created_at",
        CreatedAt: "created_at",
        "created-at": "created_at",
        p_created_at: "created_at",
        "Created At": "created_at",
        updated_at: "updated_at",
        "updated-at": "updated_at",
        "Updated At": "updated_at",
        p_updated_at: "updated_at",
        updatedAt: "updated_at",
        UpdatedAt: "updated_at"
    },
    flashcardHistory: {
        p_id: "id",
        id: "id",
        Id: "id",
        "Flashcard Id": "flashcard_id",
        p_flashcard_id: "flashcard_id",
        FlashcardId: "flashcard_id",
        flashcard_id: "flashcard_id",
        "flashcard-id": "flashcard_id",
        flashcardId: "flashcard_id",
        "User Id": "user_id",
        userId: "user_id",
        user_id: "user_id",
        p_user_id: "user_id",
        "user-id": "user_id",
        UserId: "user_id",
        "Review Count": "review_count",
        "review-count": "review_count",
        ReviewCount: "review_count",
        p_review_count: "review_count",
        reviewCount: "review_count",
        review_count: "review_count",
        correct_count: "correct_count",
        p_correct_count: "correct_count",
        correctCount: "correct_count",
        CorrectCount: "correct_count",
        "Correct Count": "correct_count",
        "correct-count": "correct_count",
        p_incorrect_count: "incorrect_count",
        incorrectCount: "incorrect_count",
        incorrect_count: "incorrect_count",
        "Incorrect Count": "incorrect_count",
        IncorrectCount: "incorrect_count",
        "incorrect-count": "incorrect_count",
        created_at: "created_at",
        createdAt: "created_at",
        CreatedAt: "created_at",
        "created-at": "created_at",
        p_created_at: "created_at",
        "Created At": "created_at",
        updated_at: "updated_at",
        "updated-at": "updated_at",
        "Updated At": "updated_at",
        p_updated_at: "updated_at",
        updatedAt: "updated_at",
        UpdatedAt: "updated_at"
    },
    flashcardImages: {
        p_id: "id",
        id: "id",
        Id: "id",
        "Flashcard Id": "flashcard_id",
        p_flashcard_id: "flashcard_id",
        FlashcardId: "flashcard_id",
        flashcard_id: "flashcard_id",
        "flashcard-id": "flashcard_id",
        flashcardId: "flashcard_id",
        file_path: "file_path",
        "file-path": "file_path",
        filePath: "file_path",
        "File Path": "file_path",
        p_file_path: "file_path",
        FilePath: "file_path",
        file_name: "file_name",
        p_file_name: "file_name",
        fileName: "file_name",
        FileName: "file_name",
        "File Name": "file_name",
        "file-name": "file_name",
        "mime-type": "mime_type",
        "Mime Type": "mime_type",
        mimeType: "mime_type",
        MimeType: "mime_type",
        mime_type: "mime_type",
        p_mime_type: "mime_type",
        size: "size",
        Size: "size",
        p_size: "size",
        created_at: "created_at",
        createdAt: "created_at",
        CreatedAt: "created_at",
        "created-at": "created_at",
        p_created_at: "created_at",
        "Created At": "created_at"
    },
    flashcardSetRelations: {
        "Flashcard Id": "flashcard_id",
        p_flashcard_id: "flashcard_id",
        FlashcardId: "flashcard_id",
        flashcard_id: "flashcard_id",
        "flashcard-id": "flashcard_id",
        flashcardId: "flashcard_id",
        setId: "set_id",
        "set-id": "set_id",
        SetId: "set_id",
        set_id: "set_id",
        "Set Id": "set_id",
        p_set_id: "set_id",
        order: "order",
        p_order: "order",
        Order: "order"
    },
    flashcardSets: {
        setId: "set_id",
        "set-id": "set_id",
        SetId: "set_id",
        set_id: "set_id",
        "Set Id": "set_id",
        p_set_id: "set_id",
        "User Id": "user_id",
        userId: "user_id",
        user_id: "user_id",
        p_user_id: "user_id",
        "user-id": "user_id",
        UserId: "user_id",
        name: "name",
        p_name: "name",
        Name: "name",
        created_at: "created_at",
        createdAt: "created_at",
        CreatedAt: "created_at",
        "created-at": "created_at",
        p_created_at: "created_at",
        "Created At": "created_at",
        updated_at: "updated_at",
        "updated-at": "updated_at",
        "Updated At": "updated_at",
        p_updated_at: "updated_at",
        updatedAt: "updated_at",
        UpdatedAt: "updated_at",
        p_shared_with: "shared_with",
        "Shared With": "shared_with",
        "shared-with": "shared_with",
        shared_with: "shared_with",
        sharedWith: "shared_with",
        SharedWith: "shared_with",
        public: "public",
        Public: "public",
        p_public: "public",
        topic: "topic",
        Topic: "topic",
        p_topic: "topic",
        lesson: "lesson",
        Lesson: "lesson",
        p_lesson: "lesson",
        Difficulty: "difficulty",
        p_difficulty: "difficulty",
        difficulty: "difficulty",
        "audio-overview": "audio_overview",
        AudioOverview: "audio_overview",
        p_audio_overview: "audio_overview",
        "Audio Overview": "audio_overview",
        audio_overview: "audio_overview",
        audioOverview: "audio_overview"
    },
    processor: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        "Depends Default": "depends_default",
        dependsDefault: "depends_default",
        DependsDefault: "depends_default",
        depends_default: "depends_default",
        "depends-default": "depends_default",
        p_depends_default: "depends_default",
        default_extractors: "default_extractors",
        "default-extractors": "default_extractors",
        "Default Extractors": "default_extractors",
        defaultExtractors: "default_extractors",
        DefaultExtractors: "default_extractors",
        p_default_extractors: "default_extractors",
        p_params: "params",
        Params: "params",
        params: "params"
    },
    recipe: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        description: "description",
        p_description: "description",
        Description: "description",
        p_tags: "tags",
        Tags: "tags",
        tags: "tags",
        "sample-output": "sample_output",
        "Sample Output": "sample_output",
        p_sample_output: "sample_output",
        sample_output: "sample_output",
        SampleOutput: "sample_output",
        sampleOutput: "sample_output",
        isPublic: "is_public",
        IsPublic: "is_public",
        "is-public": "is_public",
        p_is_public: "is_public",
        "Is Public": "is_public",
        is_public: "is_public",
        p_status: "status",
        status: "status",
        Status: "status",
        version: "version",
        Version: "version",
        p_version: "version",
        messages: "messages",
        Messages: "messages",
        p_messages: "messages",
        postResultOptions: "post_result_options",
        p_post_result_options: "post_result_options",
        post_result_options: "post_result_options",
        PostResultOptions: "post_result_options",
        "post-result-options": "post_result_options",
        "Post Result Options": "post_result_options"
    },
    recipeBroker: {
        p_id: "id",
        id: "id",
        Id: "id",
        recipe: "recipe",
        p_recipe: "recipe",
        Recipe: "recipe",
        broker: "broker",
        p_broker: "broker",
        Broker: "broker",
        "broker-role": "broker_role",
        BrokerRole: "broker_role",
        p_broker_role: "broker_role",
        broker_role: "broker_role",
        "Broker Role": "broker_role",
        brokerRole: "broker_role",
        p_required: "required",
        required: "required",
        Required: "required"
    },
    recipeDisplay: {
        p_id: "id",
        id: "id",
        Id: "id",
        recipe: "recipe",
        p_recipe: "recipe",
        Recipe: "recipe",
        Display: "display",
        p_display: "display",
        display: "display",
        priority: "priority",
        p_priority: "priority",
        Priority: "priority",
        display_settings: "display_settings",
        p_display_settings: "display_settings",
        "display-settings": "display_settings",
        displaySettings: "display_settings",
        DisplaySettings: "display_settings",
        "Display Settings": "display_settings"
    },
    recipeFunction: {
        p_id: "id",
        id: "id",
        Id: "id",
        recipe: "recipe",
        p_recipe: "recipe",
        Recipe: "recipe",
        Function: "function",
        p_function: "function",
        function: "function",
        role: "role",
        p_role: "role",
        Role: "role",
        p_params: "params",
        Params: "params",
        params: "params"
    },
    recipeModel: {
        p_id: "id",
        id: "id",
        Id: "id",
        recipe: "recipe",
        p_recipe: "recipe",
        Recipe: "recipe",
        "ai-model": "ai_model",
        AiModel: "ai_model",
        p_ai_model: "ai_model",
        aiModel: "ai_model",
        "Ai Model": "ai_model",
        ai_model: "ai_model",
        role: "role",
        p_role: "role",
        Role: "role",
        priority: "priority",
        p_priority: "priority",
        Priority: "priority"
    },
    recipeProcessor: {
        p_id: "id",
        id: "id",
        Id: "id",
        recipe: "recipe",
        p_recipe: "recipe",
        Recipe: "recipe",
        Processor: "processor",
        processor: "processor",
        p_processor: "processor",
        p_params: "params",
        Params: "params",
        params: "params"
    },
    recipeTool: {
        p_id: "id",
        id: "id",
        Id: "id",
        recipe: "recipe",
        p_recipe: "recipe",
        Recipe: "recipe",
        p_tool: "tool",
        tool: "tool",
        Tool: "tool",
        p_params: "params",
        Params: "params",
        params: "params"
    },
    registeredFunction: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        "module-path": "module_path",
        ModulePath: "module_path",
        "Module Path": "module_path",
        p_module_path: "module_path",
        modulePath: "module_path",
        module_path: "module_path",
        p_class_name: "class_name",
        "class-name": "class_name",
        ClassName: "class_name",
        class_name: "class_name",
        className: "class_name",
        "Class Name": "class_name",
        description: "description",
        p_description: "description",
        Description: "description",
        return_broker: "return_broker",
        p_return_broker: "return_broker",
        "Return Broker": "return_broker",
        returnBroker: "return_broker",
        "return-broker": "return_broker",
        ReturnBroker: "return_broker"
    },
    systemFunction: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        description: "description",
        p_description: "description",
        Description: "description",
        p_sample: "sample",
        sample: "sample",
        Sample: "sample",
        InputParams: "input_params",
        "input-params": "input_params",
        inputParams: "input_params",
        input_params: "input_params",
        p_input_params: "input_params",
        "Input Params": "input_params",
        output_options: "output_options",
        OutputOptions: "output_options",
        "Output Options": "output_options",
        p_output_options: "output_options",
        "output-options": "output_options",
        outputOptions: "output_options",
        rfId: "rf_id",
        p_rf_id: "rf_id",
        RfId: "rf_id",
        "rf-id": "rf_id",
        "Rf Id": "rf_id",
        rf_id: "rf_id"
    },
    tool: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        p_source: "source",
        source: "source",
        Source: "source",
        description: "description",
        p_description: "description",
        Description: "description",
        Parameters: "parameters",
        p_parameters: "parameters",
        parameters: "parameters",
        "required-args": "required_args",
        p_required_args: "required_args",
        "Required Args": "required_args",
        RequiredArgs: "required_args",
        required_args: "required_args",
        requiredArgs: "required_args",
        SystemFunction: "system_function",
        "System Function": "system_function",
        "system-function": "system_function",
        p_system_function: "system_function",
        system_function: "system_function",
        systemFunction: "system_function",
        additionalParams: "additional_params",
        additional_params: "additional_params",
        p_additional_params: "additional_params",
        "Additional Params": "additional_params",
        AdditionalParams: "additional_params",
        "additional-params": "additional_params"
    },
    transformer: {
        p_id: "id",
        id: "id",
        Id: "id",
        name: "name",
        p_name: "name",
        Name: "name",
        InputParams: "input_params",
        "input-params": "input_params",
        inputParams: "input_params",
        input_params: "input_params",
        p_input_params: "input_params",
        "Input Params": "input_params",
        "Output Params": "output_params",
        outputParams: "output_params",
        p_output_params: "output_params",
        output_params: "output_params",
        OutputParams: "output_params",
        "output-params": "output_params"
    },
    userPreferences: {
        "User Id": "user_id",
        userId: "user_id",
        user_id: "user_id",
        p_user_id: "user_id",
        "user-id": "user_id",
        UserId: "user_id",
        Preferences: "preferences",
        p_preferences: "preferences",
        preferences: "preferences",
        created_at: "created_at",
        createdAt: "created_at",
        CreatedAt: "created_at",
        "created-at": "created_at",
        p_created_at: "created_at",
        "Created At": "created_at",
        updated_at: "updated_at",
        "updated-at": "updated_at",
        "Updated At": "updated_at",
        p_updated_at: "updated_at",
        updatedAt: "updated_at",
        UpdatedAt: "updated_at"
    },
};
