export const tableNameLookup: Record<string, string> = {
    p_action: "action",
    Action: "action",
    action: "action",
    "Ai Endpoint": "aiEndpoint",
    ai_endpoint: "aiEndpoint",
    p_ai_endpoint: "aiEndpoint",
    aiEndpoint: "aiEndpoint",
    "ai-endpoint": "aiEndpoint",
    AiEndpoint: "aiEndpoint",
    ai_model: "aiModel",
    "Ai Model": "aiModel",
    "ai-model": "aiModel",
    AiModel: "aiModel",
    aiModel: "aiModel",
    p_ai_model: "aiModel",
    Arg: "arg",
    p_arg: "arg",
    arg: "arg",
    "Automation Boundary Broker": "automationBoundaryBroker",
    automationBoundaryBroker: "automationBoundaryBroker",
    AutomationBoundaryBroker: "automationBoundaryBroker",
    p_automation_boundary_broker: "automationBoundaryBroker",
    automation_boundary_broker: "automationBoundaryBroker",
    "automation-boundary-broker": "automationBoundaryBroker",
    "Automation Matrix": "automationMatrix",
    AutomationMatrix: "automationMatrix",
    p_automation_matrix: "automationMatrix",
    "automation-matrix": "automationMatrix",
    automation_matrix: "automationMatrix",
    automationMatrix: "automationMatrix",
    broker: "broker",
    Broker: "broker",
    p_broker: "broker",
    DataInputComponent: "dataInputComponent",
    data_input_component: "dataInputComponent",
    p_data_input_component: "dataInputComponent",
    "Data Input Component": "dataInputComponent",
    dataInputComponent: "dataInputComponent",
    "data-input-component": "dataInputComponent",
    p_data_output_component: "dataOutputComponent",
    dataOutputComponent: "dataOutputComponent",
    data_output_component: "dataOutputComponent",
    DataOutputComponent: "dataOutputComponent",
    "data-output-component": "dataOutputComponent",
    "Data Output Component": "dataOutputComponent",
    "Display Option": "displayOption",
    displayOption: "displayOption",
    display_option: "displayOption",
    "display-option": "displayOption",
    DisplayOption: "displayOption",
    p_display_option: "displayOption",
    p_emails: "emails",
    emails: "emails",
    Emails: "emails",
    Extractor: "extractor",
    extractor: "extractor",
    p_extractor: "extractor",
    "flashcard-data": "flashcardData",
    "Flashcard Data": "flashcardData",
    FlashcardData: "flashcardData",
    flashcardData: "flashcardData",
    flashcard_data: "flashcardData",
    p_flashcard_data: "flashcardData",
    "flashcard-history": "flashcardHistory",
    FlashcardHistory: "flashcardHistory",
    p_flashcard_history: "flashcardHistory",
    flashcardHistory: "flashcardHistory",
    flashcard_history: "flashcardHistory",
    "Flashcard History": "flashcardHistory",
    p_flashcard_images: "flashcardImages",
    "flashcard-images": "flashcardImages",
    FlashcardImages: "flashcardImages",
    flashcardImages: "flashcardImages",
    "Flashcard Images": "flashcardImages",
    flashcard_images: "flashcardImages",
    "Flashcard Set Relations": "flashcardSetRelations",
    flashcardSetRelations: "flashcardSetRelations",
    FlashcardSetRelations: "flashcardSetRelations",
    p_flashcard_set_relations: "flashcardSetRelations",
    flashcard_set_relations: "flashcardSetRelations",
    "flashcard-set-relations": "flashcardSetRelations",
    flashcardSets: "flashcardSets",
    FlashcardSets: "flashcardSets",
    p_flashcard_sets: "flashcardSets",
    flashcard_sets: "flashcardSets",
    "flashcard-sets": "flashcardSets",
    "Flashcard Sets": "flashcardSets",
    processor: "processor",
    Processor: "processor",
    p_processor: "processor",
    Recipe: "recipe",
    recipe: "recipe",
    p_recipe: "recipe",
    p_recipe_broker: "recipeBroker",
    recipeBroker: "recipeBroker",
    recipe_broker: "recipeBroker",
    "Recipe Broker": "recipeBroker",
    "recipe-broker": "recipeBroker",
    RecipeBroker: "recipeBroker",
    p_recipe_display: "recipeDisplay",
    "recipe-display": "recipeDisplay",
    recipeDisplay: "recipeDisplay",
    recipe_display: "recipeDisplay",
    RecipeDisplay: "recipeDisplay",
    "Recipe Display": "recipeDisplay",
    RecipeFunction: "recipeFunction",
    "recipe-function": "recipeFunction",
    recipeFunction: "recipeFunction",
    "Recipe Function": "recipeFunction",
    recipe_function: "recipeFunction",
    p_recipe_function: "recipeFunction",
    RecipeModel: "recipeModel",
    "recipe-model": "recipeModel",
    recipe_model: "recipeModel",
    p_recipe_model: "recipeModel",
    recipeModel: "recipeModel",
    "Recipe Model": "recipeModel",
    "recipe-processor": "recipeProcessor",
    recipe_processor: "recipeProcessor",
    p_recipe_processor: "recipeProcessor",
    recipeProcessor: "recipeProcessor",
    RecipeProcessor: "recipeProcessor",
    "Recipe Processor": "recipeProcessor",
    recipeTool: "recipeTool",
    "Recipe Tool": "recipeTool",
    "recipe-tool": "recipeTool",
    recipe_tool: "recipeTool",
    p_recipe_tool: "recipeTool",
    RecipeTool: "recipeTool",
    RegisteredFunction: "registeredFunction",
    registered_function: "registeredFunction",
    p_registered_function: "registeredFunction",
    "Registered Function": "registeredFunction",
    registeredFunction: "registeredFunction",
    "registered-function": "registeredFunction",
    SystemFunction: "systemFunction",
    "System Function": "systemFunction",
    "system-function": "systemFunction",
    system_function: "systemFunction",
    p_system_function: "systemFunction",
    systemFunction: "systemFunction",
    Tool: "tool",
    p_tool: "tool",
    tool: "tool",
    p_transformer: "transformer",
    transformer: "transformer",
    Transformer: "transformer",
    user_preferences: "userPreferences",
    "User Preferences": "userPreferences",
    UserPreferences: "userPreferences",
    "user-preferences": "userPreferences",
    p_user_preferences: "userPreferences",
    userPreferences: "userPreferences",
};

export const viewNameLookup: Record<string, string> = {
    view_registered_function: "viewRegisteredFunction",
    viewRegisteredFunction: "viewRegisteredFunction",
    "view-registered-function": "viewRegisteredFunction",
    "View Registered Function": "viewRegisteredFunction",
    p_view_registered_function: "viewRegisteredFunction",
    ViewRegisteredFunction: "viewRegisteredFunction",
    "view-registered-function-all-rels": "viewRegisteredFunctionAllRels",
    view_registered_function_all_rels: "viewRegisteredFunctionAllRels",
    "View Registered Function All Rels": "viewRegisteredFunctionAllRels",
    p_view_registered_function_all_rels: "viewRegisteredFunctionAllRels",
    viewRegisteredFunctionAllRels: "viewRegisteredFunctionAllRels",
    ViewRegisteredFunctionAllRels: "viewRegisteredFunctionAllRels",
};

export const fieldNameLookup: Record<string, Record<string, string>> = {
    action: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        p_matrix: "matrix",
        matrix: "matrix",
        Matrix: "matrix",
        p_transformer: "transformer",
        transformer: "transformer",
        Transformer: "transformer",
        nodeType: "nodeType",
        "Node Type": "nodeType",
        "node-type": "nodeType",
        node_type: "nodeType",
        p_node_type: "nodeType",
        NodeType: "nodeType",
        p_reference_id: "referenceId",
        referenceId: "referenceId",
        "Reference Id": "referenceId",
        ReferenceId: "referenceId",
        "reference-id": "referenceId",
        reference_id: "referenceId"
    },
    aiEndpoint: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        p_provider: "provider",
        Provider: "provider",
        provider: "provider",
        Description: "description",
        p_description: "description",
        description: "description",
        additional_cost: "additionalCost",
        AdditionalCost: "additionalCost",
        p_additional_cost: "additionalCost",
        additionalCost: "additionalCost",
        "Additional Cost": "additionalCost",
        "additional-cost": "additionalCost",
        CostDetails: "costDetails",
        costDetails: "costDetails",
        "Cost Details": "costDetails",
        p_cost_details: "costDetails",
        "cost-details": "costDetails",
        cost_details: "costDetails",
        params: "params",
        Params: "params",
        p_params: "params"
    },
    aiModel: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        commonName: "commonName",
        common_name: "commonName",
        CommonName: "commonName",
        "Common Name": "commonName",
        p_common_name: "commonName",
        "common-name": "commonName",
        ModelClass: "modelClass",
        p_model_class: "modelClass",
        modelClass: "modelClass",
        "model-class": "modelClass",
        "Model Class": "modelClass",
        model_class: "modelClass",
        p_provider: "provider",
        Provider: "provider",
        provider: "provider",
        Endpoints: "endpoints",
        endpoints: "endpoints",
        p_endpoints: "endpoints",
        context_window: "contextWindow",
        "context-window": "contextWindow",
        "Context Window": "contextWindow",
        ContextWindow: "contextWindow",
        contextWindow: "contextWindow",
        p_context_window: "contextWindow",
        "Max Tokens": "maxTokens",
        p_max_tokens: "maxTokens",
        MaxTokens: "maxTokens",
        max_tokens: "maxTokens",
        "max-tokens": "maxTokens",
        maxTokens: "maxTokens",
        capabilities: "capabilities",
        p_capabilities: "capabilities",
        Capabilities: "capabilities",
        Controls: "controls",
        controls: "controls",
        p_controls: "controls"
    },
    arg: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        Required: "required",
        p_required: "required",
        required: "required",
        Default: "default",
        p_default: "default",
        default: "default",
        p_data_type: "dataType",
        data_type: "dataType",
        DataType: "dataType",
        "data-type": "dataType",
        "Data Type": "dataType",
        dataType: "dataType",
        Ready: "ready",
        ready: "ready",
        p_ready: "ready",
        RegisteredFunction: "registeredFunction",
        registered_function: "registeredFunction",
        p_registered_function: "registeredFunction",
        "Registered Function": "registeredFunction",
        registeredFunction: "registeredFunction",
        "registered-function": "registeredFunction"
    },
    automationBoundaryBroker: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_matrix: "matrix",
        matrix: "matrix",
        Matrix: "matrix",
        broker: "broker",
        Broker: "broker",
        p_broker: "broker",
        "spark-source": "sparkSource",
        spark_source: "sparkSource",
        SparkSource: "sparkSource",
        "Spark Source": "sparkSource",
        p_spark_source: "sparkSource",
        sparkSource: "sparkSource",
        beaconDestination: "beaconDestination",
        BeaconDestination: "beaconDestination",
        beacon_destination: "beaconDestination",
        "beacon-destination": "beaconDestination",
        "Beacon Destination": "beaconDestination",
        p_beacon_destination: "beaconDestination"
    },
    automationMatrix: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        Description: "description",
        p_description: "description",
        description: "description",
        p_average_seconds: "averageSeconds",
        AverageSeconds: "averageSeconds",
        average_seconds: "averageSeconds",
        "Average Seconds": "averageSeconds",
        averageSeconds: "averageSeconds",
        "average-seconds": "averageSeconds",
        p_is_automated: "isAutomated",
        "Is Automated": "isAutomated",
        isAutomated: "isAutomated",
        is_automated: "isAutomated",
        IsAutomated: "isAutomated",
        "is-automated": "isAutomated",
        cognitionMatrices: "cognitionMatrices",
        cognition_matrices: "cognitionMatrices",
        CognitionMatrices: "cognitionMatrices",
        p_cognition_matrices: "cognitionMatrices",
        "Cognition Matrices": "cognitionMatrices",
        "cognition-matrices": "cognitionMatrices"
    },
    broker: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        Value: "value",
        value: "value",
        p_value: "value",
        p_data_type: "dataType",
        data_type: "dataType",
        DataType: "dataType",
        "data-type": "dataType",
        "Data Type": "dataType",
        dataType: "dataType",
        Ready: "ready",
        ready: "ready",
        p_ready: "ready",
        defaultSource: "defaultSource",
        default_source: "defaultSource",
        "default-source": "defaultSource",
        p_default_source: "defaultSource",
        "Default Source": "defaultSource",
        DefaultSource: "defaultSource",
        DisplayName: "displayName",
        p_display_name: "displayName",
        "display-name": "displayName",
        "Display Name": "displayName",
        displayName: "displayName",
        display_name: "displayName",
        Description: "description",
        p_description: "description",
        description: "description",
        Tooltip: "tooltip",
        tooltip: "tooltip",
        p_tooltip: "tooltip",
        validation_rules: "validationRules",
        "Validation Rules": "validationRules",
        validationRules: "validationRules",
        "validation-rules": "validationRules",
        p_validation_rules: "validationRules",
        ValidationRules: "validationRules",
        "sample-entries": "sampleEntries",
        p_sample_entries: "sampleEntries",
        SampleEntries: "sampleEntries",
        "Sample Entries": "sampleEntries",
        sampleEntries: "sampleEntries",
        sample_entries: "sampleEntries",
        customSourceComponent: "customSourceComponent",
        CustomSourceComponent: "customSourceComponent",
        custom_source_component: "customSourceComponent",
        "custom-source-component": "customSourceComponent",
        "Custom Source Component": "customSourceComponent",
        p_custom_source_component: "customSourceComponent",
        additional_params: "additionalParams",
        additionalParams: "additionalParams",
        "Additional Params": "additionalParams",
        "additional-params": "additionalParams",
        p_additional_params: "additionalParams",
        AdditionalParams: "additionalParams",
        "Other Source Params": "otherSourceParams",
        otherSourceParams: "otherSourceParams",
        other_source_params: "otherSourceParams",
        "other-source-params": "otherSourceParams",
        p_other_source_params: "otherSourceParams",
        OtherSourceParams: "otherSourceParams",
        defaultDestination: "defaultDestination",
        default_destination: "defaultDestination",
        "Default Destination": "defaultDestination",
        "default-destination": "defaultDestination",
        p_default_destination: "defaultDestination",
        DefaultDestination: "defaultDestination",
        p_output_component: "outputComponent",
        outputComponent: "outputComponent",
        output_component: "outputComponent",
        "Output Component": "outputComponent",
        OutputComponent: "outputComponent",
        "output-component": "outputComponent",
        tags: "tags",
        p_tags: "tags",
        Tags: "tags"
    },
    dataInputComponent: {
        Id: "id",
        id: "id",
        p_id: "id",
        options: "options",
        Options: "options",
        p_options: "options",
        IncludeOther: "includeOther",
        "include-other": "includeOther",
        "Include Other": "includeOther",
        p_include_other: "includeOther",
        include_other: "includeOther",
        includeOther: "includeOther",
        Min: "min",
        min: "min",
        p_min: "min",
        Max: "max",
        p_max: "max",
        max: "max",
        step: "step",
        p_step: "step",
        Step: "step",
        minRows: "minRows",
        "Min Rows": "minRows",
        p_min_rows: "minRows",
        min_rows: "minRows",
        MinRows: "minRows",
        "min-rows": "minRows",
        maxRows: "maxRows",
        p_max_rows: "maxRows",
        max_rows: "maxRows",
        "max-rows": "maxRows",
        MaxRows: "maxRows",
        "Max Rows": "maxRows",
        "Acceptable Filetypes": "acceptableFiletypes",
        AcceptableFiletypes: "acceptableFiletypes",
        "acceptable-filetypes": "acceptableFiletypes",
        p_acceptable_filetypes: "acceptableFiletypes",
        acceptable_filetypes: "acceptableFiletypes",
        acceptableFiletypes: "acceptableFiletypes",
        Src: "src",
        src: "src",
        p_src: "src",
        Classes: "classes",
        p_classes: "classes",
        classes: "classes",
        p_color_overrides: "colorOverrides",
        ColorOverrides: "colorOverrides",
        colorOverrides: "colorOverrides",
        color_overrides: "colorOverrides",
        "color-overrides": "colorOverrides",
        "Color Overrides": "colorOverrides",
        additional_params: "additionalParams",
        additionalParams: "additionalParams",
        "Additional Params": "additionalParams",
        "additional-params": "additionalParams",
        p_additional_params: "additionalParams",
        AdditionalParams: "additionalParams"
    },
    dataOutputComponent: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_component_type: "componentType",
        ComponentType: "componentType",
        "component-type": "componentType",
        component_type: "componentType",
        componentType: "componentType",
        "Component Type": "componentType",
        UiComponent: "uiComponent",
        ui_component: "uiComponent",
        uiComponent: "uiComponent",
        p_ui_component: "uiComponent",
        "Ui Component": "uiComponent",
        "ui-component": "uiComponent",
        Props: "props",
        p_props: "props",
        props: "props",
        additional_params: "additionalParams",
        additionalParams: "additionalParams",
        "Additional Params": "additionalParams",
        "additional-params": "additionalParams",
        p_additional_params: "additionalParams",
        AdditionalParams: "additionalParams"
    },
    displayOption: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        DefaultParams: "defaultParams",
        "Default Params": "defaultParams",
        defaultParams: "defaultParams",
        default_params: "defaultParams",
        p_default_params: "defaultParams",
        "default-params": "defaultParams",
        customizableParams: "customizableParams",
        "customizable-params": "customizableParams",
        p_customizable_params: "customizableParams",
        "Customizable Params": "customizableParams",
        customizable_params: "customizableParams",
        CustomizableParams: "customizableParams",
        additional_params: "additionalParams",
        additionalParams: "additionalParams",
        "Additional Params": "additionalParams",
        "additional-params": "additionalParams",
        p_additional_params: "additionalParams",
        AdditionalParams: "additionalParams"
    },
    emails: {
        Id: "id",
        id: "id",
        p_id: "id",
        sender: "sender",
        p_sender: "sender",
        Sender: "sender",
        recipient: "recipient",
        Recipient: "recipient",
        p_recipient: "recipient",
        Subject: "subject",
        p_subject: "subject",
        subject: "subject",
        Body: "body",
        p_body: "body",
        body: "body",
        timestamp: "timestamp",
        p_timestamp: "timestamp",
        Timestamp: "timestamp",
        IsRead: "isRead",
        isRead: "isRead",
        p_is_read: "isRead",
        "is-read": "isRead",
        "Is Read": "isRead",
        is_read: "isRead"
    },
    extractor: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        output_type: "outputType",
        "Output Type": "outputType",
        "output-type": "outputType",
        OutputType: "outputType",
        p_output_type: "outputType",
        outputType: "outputType",
        defaultIdentifier: "defaultIdentifier",
        "Default Identifier": "defaultIdentifier",
        p_default_identifier: "defaultIdentifier",
        default_identifier: "defaultIdentifier",
        DefaultIdentifier: "defaultIdentifier",
        "default-identifier": "defaultIdentifier",
        default_index: "defaultIndex",
        DefaultIndex: "defaultIndex",
        p_default_index: "defaultIndex",
        defaultIndex: "defaultIndex",
        "Default Index": "defaultIndex",
        "default-index": "defaultIndex"
    },
    flashcardData: {
        Id: "id",
        id: "id",
        p_id: "id",
        user_id: "userId",
        "user-id": "userId",
        UserId: "userId",
        p_user_id: "userId",
        "User Id": "userId",
        userId: "userId",
        Topic: "topic",
        topic: "topic",
        p_topic: "topic",
        Lesson: "lesson",
        p_lesson: "lesson",
        lesson: "lesson",
        Difficulty: "difficulty",
        difficulty: "difficulty",
        p_difficulty: "difficulty",
        p_front: "front",
        front: "front",
        Front: "front",
        Back: "back",
        p_back: "back",
        back: "back",
        example: "example",
        Example: "example",
        p_example: "example",
        detailed_explanation: "detailedExplanation",
        "detailed-explanation": "detailedExplanation",
        "Detailed Explanation": "detailedExplanation",
        DetailedExplanation: "detailedExplanation",
        detailedExplanation: "detailedExplanation",
        p_detailed_explanation: "detailedExplanation",
        "audio-explanation": "audioExplanation",
        p_audio_explanation: "audioExplanation",
        audioExplanation: "audioExplanation",
        AudioExplanation: "audioExplanation",
        audio_explanation: "audioExplanation",
        "Audio Explanation": "audioExplanation",
        "Personal Notes": "personalNotes",
        "personal-notes": "personalNotes",
        personal_notes: "personalNotes",
        personalNotes: "personalNotes",
        PersonalNotes: "personalNotes",
        p_personal_notes: "personalNotes",
        IsDeleted: "isDeleted",
        is_deleted: "isDeleted",
        "Is Deleted": "isDeleted",
        p_is_deleted: "isDeleted",
        isDeleted: "isDeleted",
        "is-deleted": "isDeleted",
        public: "public",
        Public: "public",
        p_public: "public",
        "shared-with": "sharedWith",
        SharedWith: "sharedWith",
        p_shared_with: "sharedWith",
        shared_with: "sharedWith",
        "Shared With": "sharedWith",
        sharedWith: "sharedWith",
        created_at: "createdAt",
        CreatedAt: "createdAt",
        p_created_at: "createdAt",
        "created-at": "createdAt",
        "Created At": "createdAt",
        createdAt: "createdAt",
        UpdatedAt: "updatedAt",
        "updated-at": "updatedAt",
        updated_at: "updatedAt",
        updatedAt: "updatedAt",
        "Updated At": "updatedAt",
        p_updated_at: "updatedAt"
    },
    flashcardHistory: {
        Id: "id",
        id: "id",
        p_id: "id",
        "Flashcard Id": "flashcardId",
        p_flashcard_id: "flashcardId",
        "flashcard-id": "flashcardId",
        flashcard_id: "flashcardId",
        FlashcardId: "flashcardId",
        flashcardId: "flashcardId",
        user_id: "userId",
        "user-id": "userId",
        UserId: "userId",
        p_user_id: "userId",
        "User Id": "userId",
        userId: "userId",
        p_review_count: "reviewCount",
        review_count: "reviewCount",
        ReviewCount: "reviewCount",
        "Review Count": "reviewCount",
        reviewCount: "reviewCount",
        "review-count": "reviewCount",
        CorrectCount: "correctCount",
        "Correct Count": "correctCount",
        correctCount: "correctCount",
        correct_count: "correctCount",
        "correct-count": "correctCount",
        p_correct_count: "correctCount",
        IncorrectCount: "incorrectCount",
        "Incorrect Count": "incorrectCount",
        "incorrect-count": "incorrectCount",
        p_incorrect_count: "incorrectCount",
        incorrect_count: "incorrectCount",
        incorrectCount: "incorrectCount",
        created_at: "createdAt",
        CreatedAt: "createdAt",
        p_created_at: "createdAt",
        "created-at": "createdAt",
        "Created At": "createdAt",
        createdAt: "createdAt",
        UpdatedAt: "updatedAt",
        "updated-at": "updatedAt",
        updated_at: "updatedAt",
        updatedAt: "updatedAt",
        "Updated At": "updatedAt",
        p_updated_at: "updatedAt"
    },
    flashcardImages: {
        Id: "id",
        id: "id",
        p_id: "id",
        "Flashcard Id": "flashcardId",
        p_flashcard_id: "flashcardId",
        "flashcard-id": "flashcardId",
        flashcard_id: "flashcardId",
        FlashcardId: "flashcardId",
        flashcardId: "flashcardId",
        "File Path": "filePath",
        p_file_path: "filePath",
        file_path: "filePath",
        FilePath: "filePath",
        "file-path": "filePath",
        filePath: "filePath",
        "file-name": "fileName",
        FileName: "fileName",
        p_file_name: "fileName",
        "File Name": "fileName",
        fileName: "fileName",
        file_name: "fileName",
        "Mime Type": "mimeType",
        mimeType: "mimeType",
        "mime-type": "mimeType",
        MimeType: "mimeType",
        p_mime_type: "mimeType",
        mime_type: "mimeType",
        p_size: "size",
        Size: "size",
        size: "size",
        created_at: "createdAt",
        CreatedAt: "createdAt",
        p_created_at: "createdAt",
        "created-at": "createdAt",
        "Created At": "createdAt",
        createdAt: "createdAt"
    },
    flashcardSetRelations: {
        "Flashcard Id": "flashcardId",
        p_flashcard_id: "flashcardId",
        "flashcard-id": "flashcardId",
        flashcard_id: "flashcardId",
        FlashcardId: "flashcardId",
        flashcardId: "flashcardId",
        set_id: "setId",
        p_set_id: "setId",
        "Set Id": "setId",
        setId: "setId",
        SetId: "setId",
        "set-id": "setId",
        Order: "order",
        order: "order",
        p_order: "order"
    },
    flashcardSets: {
        set_id: "setId",
        p_set_id: "setId",
        "Set Id": "setId",
        setId: "setId",
        SetId: "setId",
        "set-id": "setId",
        user_id: "userId",
        "user-id": "userId",
        UserId: "userId",
        p_user_id: "userId",
        "User Id": "userId",
        userId: "userId",
        p_name: "name",
        name: "name",
        Name: "name",
        created_at: "createdAt",
        CreatedAt: "createdAt",
        p_created_at: "createdAt",
        "created-at": "createdAt",
        "Created At": "createdAt",
        createdAt: "createdAt",
        UpdatedAt: "updatedAt",
        "updated-at": "updatedAt",
        updated_at: "updatedAt",
        updatedAt: "updatedAt",
        "Updated At": "updatedAt",
        p_updated_at: "updatedAt",
        "shared-with": "sharedWith",
        SharedWith: "sharedWith",
        p_shared_with: "sharedWith",
        shared_with: "sharedWith",
        "Shared With": "sharedWith",
        sharedWith: "sharedWith",
        public: "public",
        Public: "public",
        p_public: "public",
        Topic: "topic",
        topic: "topic",
        p_topic: "topic",
        Lesson: "lesson",
        p_lesson: "lesson",
        lesson: "lesson",
        Difficulty: "difficulty",
        difficulty: "difficulty",
        p_difficulty: "difficulty",
        "audio-overview": "audioOverview",
        "Audio Overview": "audioOverview",
        AudioOverview: "audioOverview",
        audio_overview: "audioOverview",
        p_audio_overview: "audioOverview",
        audioOverview: "audioOverview"
    },
    processor: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        "depends-default": "dependsDefault",
        depends_default: "dependsDefault",
        DependsDefault: "dependsDefault",
        "Depends Default": "dependsDefault",
        dependsDefault: "dependsDefault",
        p_depends_default: "dependsDefault",
        default_extractors: "defaultExtractors",
        "Default Extractors": "defaultExtractors",
        "default-extractors": "defaultExtractors",
        defaultExtractors: "defaultExtractors",
        DefaultExtractors: "defaultExtractors",
        p_default_extractors: "defaultExtractors",
        params: "params",
        Params: "params",
        p_params: "params"
    },
    recipe: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        Description: "description",
        p_description: "description",
        description: "description",
        tags: "tags",
        p_tags: "tags",
        Tags: "tags",
        "sample-output": "sampleOutput",
        "Sample Output": "sampleOutput",
        SampleOutput: "sampleOutput",
        sample_output: "sampleOutput",
        sampleOutput: "sampleOutput",
        p_sample_output: "sampleOutput",
        isPublic: "isPublic",
        IsPublic: "isPublic",
        "Is Public": "isPublic",
        is_public: "isPublic",
        p_is_public: "isPublic",
        "is-public": "isPublic",
        p_status: "status",
        status: "status",
        Status: "status",
        Version: "version",
        p_version: "version",
        version: "version",
        messages: "messages",
        p_messages: "messages",
        Messages: "messages",
        post_result_options: "postResultOptions",
        "Post Result Options": "postResultOptions",
        PostResultOptions: "postResultOptions",
        "post-result-options": "postResultOptions",
        postResultOptions: "postResultOptions",
        p_post_result_options: "postResultOptions"
    },
    recipeBroker: {
        Id: "id",
        id: "id",
        p_id: "id",
        Recipe: "recipe",
        recipe: "recipe",
        p_recipe: "recipe",
        broker: "broker",
        Broker: "broker",
        p_broker: "broker",
        "Broker Role": "brokerRole",
        BrokerRole: "brokerRole",
        "broker-role": "brokerRole",
        broker_role: "brokerRole",
        p_broker_role: "brokerRole",
        brokerRole: "brokerRole",
        Required: "required",
        p_required: "required",
        required: "required"
    },
    recipeDisplay: {
        Id: "id",
        id: "id",
        p_id: "id",
        Recipe: "recipe",
        recipe: "recipe",
        p_recipe: "recipe",
        display: "display",
        Display: "display",
        p_display: "display",
        priority: "priority",
        Priority: "priority",
        p_priority: "priority",
        DisplaySettings: "displaySettings",
        "display-settings": "displaySettings",
        display_settings: "displaySettings",
        displaySettings: "displaySettings",
        "Display Settings": "displaySettings",
        p_display_settings: "displaySettings"
    },
    recipeFunction: {
        Id: "id",
        id: "id",
        p_id: "id",
        Recipe: "recipe",
        recipe: "recipe",
        p_recipe: "recipe",
        function: "function",
        p_function: "function",
        Function: "function",
        Role: "role",
        p_role: "role",
        role: "role",
        params: "params",
        Params: "params",
        p_params: "params"
    },
    recipeModel: {
        Id: "id",
        id: "id",
        p_id: "id",
        Recipe: "recipe",
        recipe: "recipe",
        p_recipe: "recipe",
        ai_model: "aiModel",
        "Ai Model": "aiModel",
        "ai-model": "aiModel",
        AiModel: "aiModel",
        aiModel: "aiModel",
        p_ai_model: "aiModel",
        Role: "role",
        p_role: "role",
        role: "role",
        priority: "priority",
        Priority: "priority",
        p_priority: "priority"
    },
    recipeProcessor: {
        Id: "id",
        id: "id",
        p_id: "id",
        Recipe: "recipe",
        recipe: "recipe",
        p_recipe: "recipe",
        processor: "processor",
        Processor: "processor",
        p_processor: "processor",
        params: "params",
        Params: "params",
        p_params: "params"
    },
    recipeTool: {
        Id: "id",
        id: "id",
        p_id: "id",
        Recipe: "recipe",
        recipe: "recipe",
        p_recipe: "recipe",
        Tool: "tool",
        p_tool: "tool",
        tool: "tool",
        params: "params",
        Params: "params",
        p_params: "params"
    },
    registeredFunction: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        "module-path": "modulePath",
        module_path: "modulePath",
        p_module_path: "modulePath",
        modulePath: "modulePath",
        "Module Path": "modulePath",
        ModulePath: "modulePath",
        className: "className",
        p_class_name: "className",
        class_name: "className",
        "class-name": "className",
        ClassName: "className",
        "Class Name": "className",
        Description: "description",
        p_description: "description",
        description: "description",
        p_return_broker: "returnBroker",
        "return-broker": "returnBroker",
        returnBroker: "returnBroker",
        ReturnBroker: "returnBroker",
        return_broker: "returnBroker",
        "Return Broker": "returnBroker"
    },
    systemFunction: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        Description: "description",
        p_description: "description",
        description: "description",
        sample: "sample",
        p_sample: "sample",
        Sample: "sample",
        p_input_params: "inputParams",
        input_params: "inputParams",
        inputParams: "inputParams",
        InputParams: "inputParams",
        "input-params": "inputParams",
        "Input Params": "inputParams",
        outputOptions: "outputOptions",
        OutputOptions: "outputOptions",
        p_output_options: "outputOptions",
        "output-options": "outputOptions",
        "Output Options": "outputOptions",
        output_options: "outputOptions",
        p_rf_id: "rfId",
        rf_id: "rfId",
        "rf-id": "rfId",
        "Rf Id": "rfId",
        RfId: "rfId",
        rfId: "rfId"
    },
    tool: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        source: "source",
        p_source: "source",
        Source: "source",
        Description: "description",
        p_description: "description",
        description: "description",
        p_parameters: "parameters",
        parameters: "parameters",
        Parameters: "parameters",
        "required-args": "requiredArgs",
        RequiredArgs: "requiredArgs",
        "Required Args": "requiredArgs",
        requiredArgs: "requiredArgs",
        p_required_args: "requiredArgs",
        required_args: "requiredArgs",
        SystemFunction: "systemFunction",
        "System Function": "systemFunction",
        "system-function": "systemFunction",
        system_function: "systemFunction",
        p_system_function: "systemFunction",
        systemFunction: "systemFunction",
        additional_params: "additionalParams",
        additionalParams: "additionalParams",
        "Additional Params": "additionalParams",
        "additional-params": "additionalParams",
        p_additional_params: "additionalParams",
        AdditionalParams: "additionalParams"
    },
    transformer: {
        Id: "id",
        id: "id",
        p_id: "id",
        p_name: "name",
        name: "name",
        Name: "name",
        p_input_params: "inputParams",
        input_params: "inputParams",
        inputParams: "inputParams",
        InputParams: "inputParams",
        "input-params": "inputParams",
        "Input Params": "inputParams",
        "output-params": "outputParams",
        output_params: "outputParams",
        p_output_params: "outputParams",
        outputParams: "outputParams",
        OutputParams: "outputParams",
        "Output Params": "outputParams"
    },
    userPreferences: {
        user_id: "userId",
        "user-id": "userId",
        UserId: "userId",
        p_user_id: "userId",
        "User Id": "userId",
        userId: "userId",
        Preferences: "preferences",
        preferences: "preferences",
        p_preferences: "preferences",
        created_at: "createdAt",
        CreatedAt: "createdAt",
        p_created_at: "createdAt",
        "created-at": "createdAt",
        "Created At": "createdAt",
        createdAt: "createdAt",
        UpdatedAt: "updatedAt",
        "updated-at": "updatedAt",
        updated_at: "updatedAt",
        updatedAt: "updatedAt",
        "Updated At": "updatedAt",
        p_updated_at: "updatedAt"
    },
};

