export const requestEventOptions = [
    'simple_recipe',
    'full_recipe',
    'scrape',
    'transcription',
    'text_processing',
    'google_cloud',
    'workflow',
    'functions',
    'ai_prog',
    'video_processing',
    'dynamic_event_completed',
];

export const requestTaskOptions = [
    'run_recipe',
    'validate_recipe',
    'get_recipe_brokers',
    'edit_recipe',
    'add_recipe',
    'scrape_one',
    'scrape_many',
    'scrape_keyword',
    'scrape_site',
    'transcribe',
    'audio_to_task',
    'audio_to_presentation',
    'online_video_to_text',
    'video_to_blog',
    'video_to_presentation',
    'pdf_to_text',
    'validate_workflow',
    'run_workflow',
    'validate_function',
    'run_function',
    'compile_workflow',
    'compile_recipe',
];
