// features/notes/redux/autoSaveMiddleware.ts
// Watches for note content/label changes and auto-saves after a debounce.
// Debounce is adaptive: smaller content = faster save, larger = slower.
// For auto-generated notes, materializes them (first DB insert) on first edit.

import type { Middleware } from "@reduxjs/toolkit";
import type { RootState } from "@/lib/redux/store";
import { supabase } from "@/utils/supabase/client";
import {
  markNoteSaving,
  markNoteSaved,
  markNoteSaveError,
  materializeNote,
  updateNoteLabel,
  addPendingDispatchId,
  removePendingDispatchId,
} from "./slice";
import { getAutoSaveDelay } from "./notes.types";
import type { NoteRecord } from "./notes.types";
import { generateLabelFromContent } from "../hooks/useAutoLabel";

// Timer map — one debounce timer per note
const saveTimers = new Map<string, ReturnType<typeof setTimeout>>();

// Pending dispatch cleanup timers
const echoCleanupTimers = new Map<string, ReturnType<typeof setTimeout>>();

/**
 * Auto-save middleware.
 * Listens for updateNoteContent and updateNoteLabel actions.
 * Schedules a debounced save to Supabase.
 * For auto-generated notes, performs INSERT instead of UPDATE on first save.
 */
export const autoSaveMiddleware: Middleware = (storeApi) => (next) => (action) => {
  const result = next(action);

  // Only act on note content/label changes
  const actionType = (action as { type?: string }).type;
  if (
    actionType !== "notes/updateNoteContent" &&
    actionType !== "notes/updateNoteLabel" &&
    actionType !== "notes/updateNoteFolder" &&
    actionType !== "notes/updateNoteTags" &&
    actionType !== "notes/setNoteField" &&
    actionType !== "notes/setNoteFields"
  ) {
    return result;
  }

  // Extract noteId from action payload
  const payload = (action as { payload?: { id?: string } }).payload;
  const noteId = payload?.id;
  if (!noteId) return result;

  // Read current note from state
  const state = storeApi.getState() as RootState;
  const record = state.notes?.notes?.[noteId] as NoteRecord | undefined;
  if (!record || !record._dirty) return result;

  // Clear existing timer for this note
  const existing = saveTimers.get(noteId);
  if (existing) clearTimeout(existing);

  // Calculate debounce based on content size
  const delay = getAutoSaveDelay(record.content?.length ?? 0);

  // Schedule save
  const timer = setTimeout(async () => {
    saveTimers.delete(noteId);

    const currentState = storeApi.getState() as RootState;
    const currentRecord = currentState.notes?.notes?.[noteId] as NoteRecord | undefined;
    if (!currentRecord || !currentRecord._dirty) return;

    // ── Auto-label: generate label from content if still "New Note" ──
    const shouldAutoLabel =
      !currentRecord.label ||
      currentRecord.label.trim() === "" ||
      currentRecord.label.toLowerCase() === "new note";

    if (shouldAutoLabel && currentRecord.content && currentRecord.content.trim().length >= 12) {
      const generated = generateLabelFromContent(currentRecord.content);
      if (generated) {
        storeApi.dispatch(updateNoteLabel({ id: noteId, label: generated }));
      }
    }

    // Re-read state after potential label update
    const stateAfterLabel = storeApi.getState() as RootState;
    const recordAfterLabel = stateAfterLabel.notes?.notes?.[noteId] as NoteRecord | undefined;
    if (!recordAfterLabel || !recordAfterLabel._dirty) return;

    storeApi.dispatch(markNoteSaving(noteId));

    // Echo suppression: register this as our own write
    storeApi.dispatch(addPendingDispatchId(noteId));

    // Safety net: clear the pending dispatch ID after 10s
    const existingCleanup = echoCleanupTimers.get(noteId);
    if (existingCleanup) clearTimeout(existingCleanup);
    echoCleanupTimers.set(
      noteId,
      setTimeout(() => {
        storeApi.dispatch(removePendingDispatchId(noteId));
        echoCleanupTimers.delete(noteId);
      }, 10_000),
    );

    try {
      if (recordAfterLabel._isAutogenerated) {
        // ── First save: INSERT (materialize) ─────────────────────
        const userId = recordAfterLabel.user_id || (currentState as any).user?.id;
        if (!userId) {
          storeApi.dispatch(markNoteSaveError({ id: noteId, error: "No user ID" }));
          return;
        }

        const { data, error } = await supabase
          .from("notes")
          .insert({
            id: noteId,
            user_id: userId,
            label: recordAfterLabel.label,
            content: recordAfterLabel.content,
            folder_name: recordAfterLabel.folder_name,
            tags: recordAfterLabel.tags,
            metadata: recordAfterLabel.metadata,
            position: recordAfterLabel.position ?? 0,
          })
          .select("updated_at")
          .single();

        if (error) {
          console.error("[AutoSave] INSERT failed:", error.message);
          storeApi.dispatch(markNoteSaveError({ id: noteId, error: error.message }));
          return;
        }

        // Mark as materialized (no longer auto-generated)
        storeApi.dispatch(materializeNote(noteId));
        storeApi.dispatch(markNoteSaved({ id: noteId, updatedAt: data?.updated_at }));
      } else {
        // ── Subsequent saves: UPDATE ──────────────────────────────
        // Only send dirty fields
        const updates: Record<string, unknown> = {};
        for (const field of recordAfterLabel._dirtyFields) {
          updates[field] = recordAfterLabel[field];
        }

        if (Object.keys(updates).length === 0) {
          storeApi.dispatch(markNoteSaved({ id: noteId }));
          return;
        }

        const { data, error } = await supabase
          .from("notes")
          .update(updates)
          .eq("id", noteId)
          .select("updated_at")
          .single();

        if (error) {
          console.error("[AutoSave] UPDATE failed:", error.message);
          storeApi.dispatch(markNoteSaveError({ id: noteId, error: error.message }));
          return;
        }

        storeApi.dispatch(markNoteSaved({ id: noteId, updatedAt: data?.updated_at }));
      }

      // Notify sidebar of label changes
      if (recordAfterLabel._dirtyFields.has("label")) {
        window.dispatchEvent(
          new CustomEvent("notes:labelChange", {
            detail: { noteId, label: recordAfterLabel.label },
          }),
        );
      }
    } catch (err) {
      storeApi.dispatch(
        markNoteSaveError({
          id: noteId,
          error: err instanceof Error ? err.message : "Save failed",
        }),
      );
    }
  }, delay);

  saveTimers.set(noteId, timer);

  return result;
};
