/**
 * PDF Extractor — frontend type surface.
 *
 * Re-exports the OpenAPI-generated schemas the backend team ships at
 * `types/python-generated/api-types.ts`. Always import PDF request/response
 * shapes from this file rather than reaching directly into the generated
 * file — that keeps the import path stable when the generated layout changes.
 *
 * The generated file is regenerated by:
 *   `pnpm update-api-types` (against the staging backend)
 *   `pnpm update-api-types:local` (against http://localhost:8000)
 *
 * Do not edit `types/python-generated/api-types.ts` by hand.
 */

import type { components } from "@/types/python-generated/api-types";

type Schemas = components["schemas"];

// ── Source contract (pick one of: media | file | url | local_path) ─────────

/**
 * Reference to a media file. The preferred source — `cld_id` carries a
 * Cloud Files row id so the backend can look up the canonical record
 * without re-uploading bytes.
 */
export type MediaRef = Schemas["MediaRef"];

// ── Page selection ─────────────────────────────────────────────────────────

/** 1-based page range. */
export type PdfPageRange = Schemas["PdfPageRange"];

/** Crop box used by `/crop-pages`. */
export type PdfCropBox = Schemas["PdfCropBox"];

// ── Manipulation requests (all return PDF blob) ────────────────────────────

export type ExtractPagesRequest = Schemas["ExtractPagesRequest"];
export type CropPagesRequest = Schemas["CropPagesRequest"];
export type RotatePagesRequest = Schemas["RotatePagesRequest"];
export type DeletePagesRequest = Schemas["DeletePagesRequest"];
export type MergePdfsRequest = Schemas["MergePdfsRequest"];
export type SplitPdfRequest = Schemas["SplitPdfRequest"];

// ── Pipeline / extraction results ──────────────────────────────────────────

/** Options for `process-with-ai` and `full-pipeline` (streaming JSONL). */
export type PdfPipelineOptions = Schemas["PdfPipelineOptions"];

/**
 * Canonical result for `extract-text-remote` and `extract-tables`.
 * Carries the raw text plus optional per-page / per-block / per-word
 * metadata when the corresponding `include_*_metadata` flags are set.
 */
export type PdfResult = Schemas["PdfResult"];

/** Per-page text + bounding-box metadata. */
export type PdfPageText = Schemas["PdfPageText"];

/** Block-level (paragraph / heading) bounding box on a page. */
export type PdfTextBlock = Schemas["PdfTextBlock"];

/** Word-level bounding box on a page. */
export type PdfTextWord = Schemas["PdfTextWord"];

/** A chunk produced by the pipeline (text + page span). */
export type PdfTextChunk = Schemas["PdfTextChunk"];

/** Page span attached to a chunk so the UI can resolve back to source pages. */
export type PdfPageSpan = Schemas["PdfPageSpan"];
