import { useConversationWithFetch, useMessageWithFetch } from "@/lib/redux/entity/hooks/entity-main-hooks";

export function useConversationMessages() {
    const {
        conversationSelectors,
        conversationActions,
        conversationRecords,
        conversationUnsavedRecords,
        conversationSelectedRecordIds,
        conversationIsLoading,
        conversationIsError,
        conversationQuickRefRecords,
        addConversationMatrxId,
        addConversationMatrxIds,
        removeConversationMatrxId,
        removeConversationMatrxIds,
        addConversationPkValue,
        addConversationPkValues,
        removeConversationPkValue,
        removeConversationPkValues,
        isConversationMissingRecords,
        setConversationShouldFetch,
        setConversationFetchMode,
        fetchConversationQuickRefs,
        fetchConversationOne,
        fetchConversationOneWithFkIfk,
        fetchConversationAll,
        fetchConversationPaginated,
    } = useConversationWithFetch();

    const {
        messageSelectors,
        messageActions,
        messageRecords,
        messageUnsavedRecords,
        messageSelectedRecordIds,
        messageIsLoading,
        messageIsError,
        messageQuickRefRecords,
        addMessageMatrxId,
        addMessageMatrxIds,
        removeMessageMatrxId,
        removeMessageMatrxIds,
        addMessagePkValue,
        addMessagePkValues,
        removeMessagePkValue,
        removeMessagePkValues,
        isMessageMissingRecords,
        setMessageShouldFetch,
        setMessageFetchMode,
        fetchMessageQuickRefs,
        fetchMessageOne,
        fetchMessageOneWithFkIfk,
        fetchMessageAll,
        fetchMessagePaginated,
    } = useMessageWithFetch();
}
