import { ReactFlowUIMetadata } from "@/features/workflows/types";
import { Node } from "reactflow";


// Represents a dependency between two broker ids.
export interface WorkflowDependency {
    source_broker_id: string; // Required field for the the broker id
    source_broker_name?: string; // Optional field for the broker name
    target_broker_id?: string; // Optional target broker id
    target_broker_name?: string; // Optional target broker name
}

// Represents an override for a function argument
export interface ArgumentOverride {
    name: string; // Official argument name for this specific Registered Function.
    default_value?: any; // Overrides the default value which is pre-defined in the Registered Function.
    ready: boolean; // Indicates if the argument is ready (Should always default to false, until overriden by the user)
    required: boolean; // Indicates if the argument is required (Should always default to false, until overriden by the user)
}

// Represents a mapping of arguments to broker IDs
export interface ArgumentMapping {
    source_broker_id: string; // ID of the broker
    source_broker_name?: string; // Optional source broker name
    target_arg_name: string; // Official argument name for this specific Registered Function.
}

export interface DbFunctionNode {
    id: string;
    created_at?: string;
    updated_at?: string;
    user_id: string | null;
    workflow_id: string;
    function_id: string;
    function_type: string;
    step_name: string;
    node_type: string;
    execution_required: boolean;
    additional_dependencies: WorkflowDependency[];
    arg_mapping: ArgumentMapping[];
    return_broker_overrides: string[];
    arg_overrides: ArgumentOverride[];
    status: string;
    is_public?: boolean;
    authenticated_read?: boolean;
    public_read?: boolean;
    metadata: Record<string, any>;
    ui_node_data?: ReactFlowUIMetadata;
}

interface BaseWorkflowNode {
    id: string; // Auto-generated by the database (Never set in React.)
    function_id?: string; // UUID, Foreign Key to the Registered Function.
    function_type?: string; // Nearly always set to "registered_function"
    step_name?: string; // Varchar, nullable (Human readable name for the step.)
    execution_required?: boolean; // Boolean, nullable (If true, the only thing that changes is that the workflow will 'fail' if it doesn't execute.)
    additional_dependencies?: WorkflowDependency[]; // JSONB, Ensures the function does not execute until the source_broker_id is updated and 'ready'=True. If a target is provided, the value of this broker is also passed to the target.
    arg_mapping?: ArgumentMapping[]; // JSONB, This is where args get their values during a workflow run or if there is a user input.
    return_broker_overrides?: string[]; // JSONB, nullable, array of strings (When the function executes, in addition to it's default broker id, these will also get the same value.)
    arg_overrides?: ArgumentOverride[]; // JSONB, nullable, Overides the default settings for a registered function's arguments. (default_value and ready state.)
    workflow_id?: string; // UUID, nullable (Foreign Key to the Workflow.)
    status?: string; // The status of the node. Can be: pending, initialized, ready_to_execute, executing, execution_complete, execution_failed.
    node_type?: string; // The type of node. Can be: workflowNode, userInputNode, brokerRelayNode.
    metadata?: Record<string, any>;
    ui_node_data?: ReactFlowUIMetadata;
    [key: string]: any;
}

export interface FunctionNodeData {
    id: string;
    created_at?: string;
    updated_at?: string;
    workflow_id?: string;
    user_id?: string;
    function_id: string | null;
    function_type: string | null;
    step_name: string | null;
    node_type: string;
    execution_required: boolean;
    additional_dependencies: WorkflowDependency[];
    arg_mapping: ArgumentMapping[];
    return_broker_overrides: string[];
    arg_overrides: ArgumentOverride[];
    status: string;
    metadata?: Record<string, any>;
    ui_node_data?: ReactFlowUIMetadata;
}

export type FunctionNode = Node<FunctionNodeData>;
