import {
    IconSort09, IconSort90, IconSortAZ, IconSortAscending,
    IconSortAscending2, IconSortAscending2Filled, IconSortAscendingLetters, IconSortAscendingNumbers,
    IconSortAscendingShapes, IconSortAscendingShapesFilled, IconSortAscendingSmallBig,
    IconSortDeacendingSmallBig, IconSortDescending, IconSortDescending2, IconSortDescending2Filled,
    IconSortDescendingLetters, IconSortDescendingNumbers, IconSortDescendingShapes, IconSortDescendingShapesFilled,
    IconSortDescendingSmallBig, IconSortZA, IconSos, IconSoup, IconSoupFilled, IconSoupOff, IconSourceCode,
    IconSpace, IconSpaceOff, IconSpaces, IconSpacingHorizontal, IconSpacingVertical, IconSpade, IconSpadeFilled,
    IconSparkles, IconSpeakerphone, IconSpeedboat, IconSphere, IconSphereOff, IconSpherePlus, IconSpider, IconSpiral,
    IconSpiralOff, IconSportBillard, IconSpray, IconSpy, IconSpyOff, IconSql, IconSquare, IconSquare0, IconSquare1,
    IconSquare2, IconSquare3, IconSquare4, IconSquare5, IconSquare6, IconSquare7, IconSquare8, IconSquare9,
    IconSquareArrowDown, IconSquareArrowDownFilled, IconSquareArrowLeft, IconSquareArrowLeftFilled,
    IconSquareArrowRight, IconSquareArrowRightFilled, IconSquareArrowUp, IconSquareArrowUpFilled,
    IconSquareAsterisk, IconSquareAsteriskFilled, IconSquareCheck, IconSquareCheckFilled, IconSquareChevronDown,
    IconSquareChevronDownFilled, IconSquareChevronLeft, IconSquareChevronLeftFilled, IconSquareChevronRight,
    IconSquareChevronRightFilled, IconSquareChevronUp, IconSquareChevronUpFilled, IconSquareChevronsDown,
    IconSquareChevronsDownFilled, IconSquareChevronsLeft, IconSquareChevronsLeftFilled, IconSquareChevronsRight,
    IconSquareChevronsRightFilled, IconSquareChevronsUp, IconSquareChevronsUpFilled, IconSquareDashed,
    IconSquareDot, IconSquareDotFilled, IconSquareF0, IconSquareF0Filled, IconSquareF1, IconSquareF1Filled,
    IconSquareF2, IconSquareF2Filled, IconSquareF3, IconSquareF3Filled, IconSquareF4, IconSquareF4Filled,
    IconSquareF5, IconSquareF5Filled, IconSquareF6, IconSquareF6Filled, IconSquareF7, IconSquareF7Filled,
    IconSquareF8, IconSquareF8Filled, IconSquareF9, IconSquareF9Filled, IconSquareFilled, IconSquareForbid,
    IconSquareForbid2, IconSquareHalf, IconSquareKey, IconSquareLetterA, IconSquareLetterAFilled, IconSquareLetterB,
    IconSquareLetterBFilled, IconSquareLetterC, IconSquareLetterCFilled, IconSquareLetterD, IconSquareLetterDFilled,
    IconSquareLetterE, IconSquareLetterEFilled, IconSquareLetterF, IconSquareLetterFFilled, IconSquareLetterG,
    IconSquareLetterGFilled, IconSquareLetterH, IconSquareLetterHFilled, IconSquareLetterI,
    IconSquareLetterIFilled, IconSquareLetterJ, IconSquareLetterJFilled, IconSquareLetterK, IconSquareLetterKFilled,
    IconSquareLetterL, IconSquareLetterLFilled, IconSquareLetterM, IconSquareLetterMFilled, IconSquareLetterN,
    IconSquareLetterNFilled, IconSquareLetterO, IconSquareLetterOFilled, IconSquareLetterP, IconSquareLetterPFilled,
    IconSquareLetterQ, IconSquareLetterQFilled, IconSquareLetterR, IconSquareLetterRFilled, IconSquareLetterS,
    IconSquareLetterSFilled, IconSquareLetterT, IconSquareLetterTFilled, IconSquareLetterU, IconSquareLetterUFilled,
    IconSquareLetterV, IconSquareLetterVFilled, IconSquareLetterW, IconSquareLetterWFilled, IconSquareLetterX,
    IconSquareLetterXFilled, IconSquareLetterY, IconSquareLetterYFilled, IconSquareLetterZ, IconSquareLetterZFilled,
    IconSquareMinus, IconSquareMinusFilled, IconSquareNumber0, IconSquareNumber0Filled, IconSquareNumber1,
    IconSquareNumber1Filled, IconSquareNumber2, IconSquareNumber2Filled, IconSquareNumber3, IconSquareNumber3Filled,
    IconSquareNumber4, IconSquareNumber4Filled, IconSquareNumber5, IconSquareNumber5Filled, IconSquareNumber6,
    IconSquareNumber6Filled, IconSquareNumber7, IconSquareNumber7Filled, IconSquareNumber8, IconSquareNumber8Filled,
    IconSquareNumber9, IconSquareNumber9Filled, IconSquareOff, IconSquarePercentage, IconSquarePlus, IconSquarePlus2,
    IconSquareRoot, IconSquareRoot2, IconSquareRotated, IconSquareRotatedFilled, IconSquareRotatedForbid,
    IconSquareRotatedForbid2, IconSquareRotatedOff, IconSquareRounded, IconSquareRoundedArrowDown,
    IconSquareRoundedArrowDownFilled, IconSquareRoundedArrowLeft, IconSquareRoundedArrowLeftFilled,
    IconSquareRoundedArrowRight, IconSquareRoundedArrowRightFilled, IconSquareRoundedArrowUp,
    IconSquareRoundedArrowUpFilled, IconSquareRoundedCheck, IconSquareRoundedCheckFilled, IconSquareRoundedChevronDown,
    IconSquareRoundedChevronDownFilled, IconSquareRoundedChevronLeft, IconSquareRoundedChevronLeftFilled,
    IconSquareRoundedChevronRight, IconSquareRoundedChevronRightFilled, IconSquareRoundedChevronUp,
    IconSquareRoundedChevronUpFilled, IconSquareRoundedChevronsDown, IconSquareRoundedChevronsDownFilled,
    IconSquareRoundedChevronsLeft, IconSquareRoundedChevronsLeftFilled, IconSquareRoundedChevronsRight,
    IconSquareRoundedChevronsRightFilled, IconSquareRoundedChevronsUp, IconSquareRoundedChevronsUpFilled,
    IconSquareRoundedFilled, IconSquareRoundedLetterA, IconSquareRoundedLetterAFilled, IconSquareRoundedLetterB,
    IconSquareRoundedLetterBFilled, IconSquareRoundedLetterC, IconSquareRoundedLetterCFilled,
    IconSquareRoundedLetterD, IconSquareRoundedLetterDFilled, IconSquareRoundedLetterE, IconSquareRoundedLetterEFilled,
    IconSquareRoundedLetterF, IconSquareRoundedLetterFFilled, IconSquareRoundedLetterG, IconSquareRoundedLetterGFilled,
    IconSquareRoundedLetterH, IconSquareRoundedLetterHFilled, IconSquareRoundedLetterI, IconSquareRoundedLetterIFilled,
    IconSquareRoundedLetterJ, IconSquareRoundedLetterJFilled, IconSquareRoundedLetterK, IconSquareRoundedLetterKFilled,
    IconSquareRoundedLetterL, IconSquareRoundedLetterLFilled, IconSquareRoundedLetterM, IconSquareRoundedLetterMFilled,
    IconSquareRoundedLetterN, IconSquareRoundedLetterNFilled, IconSquareRoundedLetterO, IconSquareRoundedLetterOFilled,
    IconSquareRoundedLetterP, IconSquareRoundedLetterPFilled, IconSquareRoundedLetterQ, IconSquareRoundedLetterQFilled,
    IconSquareRoundedLetterR, IconSquareRoundedLetterRFilled, IconSquareRoundedLetterS, IconSquareRoundedLetterSFilled,
    IconSquareRoundedLetterT, IconSquareRoundedLetterTFilled, IconSquareRoundedLetterU, IconSquareRoundedLetterUFilled,
    IconSquareRoundedLetterV, IconSquareRoundedLetterVFilled, IconSquareRoundedLetterW, IconSquareRoundedLetterWFilled,
    IconSquareRoundedLetterX, IconSquareRoundedLetterXFilled, IconSquareRoundedLetterY, IconSquareRoundedLetterYFilled,
    IconSquareRoundedLetterZ, IconSquareRoundedLetterZFilled, IconSquareRoundedMinus, IconSquareRoundedMinus2,
    IconSquareRoundedMinusFilled, IconSquareRoundedNumber0, IconSquareRoundedNumber0Filled, IconSquareRoundedNumber1,
    IconSquareRoundedNumber1Filled, IconSquareRoundedNumber2, IconSquareRoundedNumber2Filled, IconSquareRoundedNumber3,
    IconSquareRoundedNumber3Filled, IconSquareRoundedNumber4, IconSquareRoundedNumber4Filled, IconSquareRoundedNumber5,
    IconSquareRoundedNumber5Filled, IconSquareRoundedNumber6, IconSquareRoundedNumber6Filled, IconSquareRoundedNumber7,
    IconSquareRoundedNumber7Filled, IconSquareRoundedNumber8, IconSquareRoundedNumber8Filled, IconSquareRoundedNumber9,
    IconSquareRoundedNumber9Filled, IconSquareRoundedPercentage, IconSquareRoundedPlus, IconSquareRoundedPlus2,
    IconSquareRoundedPlusFilled, IconSquareRoundedX, IconSquareRoundedXFilled, IconSquareToggle, IconSquareToggleHorizontal,
} from "@tabler/icons-react";


export const availableIcons4 = {
    IconSort09, IconSort90, IconSortAZ, IconSortAscending,
    IconSortAscending2, IconSortAscending2Filled, IconSortAscendingLetters, IconSortAscendingNumbers,
    IconSortAscendingShapes, IconSortAscendingShapesFilled, IconSortAscendingSmallBig,
    IconSortDeacendingSmallBig, IconSortDescending, IconSortDescending2, IconSortDescending2Filled,
    IconSortDescendingLetters, IconSortDescendingNumbers, IconSortDescendingShapes, IconSortDescendingShapesFilled,
    IconSortDescendingSmallBig, IconSortZA, IconSos, IconSoup, IconSoupFilled, IconSoupOff, IconSourceCode,
    IconSpace, IconSpaceOff, IconSpaces, IconSpacingHorizontal, IconSpacingVertical, IconSpade, IconSpadeFilled,
    IconSparkles, IconSpeakerphone, IconSpeedboat, IconSphere, IconSphereOff, IconSpherePlus, IconSpider, IconSpiral,
    IconSpiralOff, IconSportBillard, IconSpray, IconSpy, IconSpyOff, IconSql, IconSquare, IconSquare0, IconSquare1,
    IconSquare2, IconSquare3, IconSquare4, IconSquare5, IconSquare6, IconSquare7, IconSquare8, IconSquare9,
    IconSquareArrowDown, IconSquareArrowDownFilled, IconSquareArrowLeft, IconSquareArrowLeftFilled,
    IconSquareArrowRight, IconSquareArrowRightFilled, IconSquareArrowUp, IconSquareArrowUpFilled,
    IconSquareAsterisk, IconSquareAsteriskFilled, IconSquareCheck, IconSquareCheckFilled, IconSquareChevronDown,
    IconSquareChevronDownFilled, IconSquareChevronLeft, IconSquareChevronLeftFilled, IconSquareChevronRight,
    IconSquareChevronRightFilled, IconSquareChevronUp, IconSquareChevronUpFilled, IconSquareChevronsDown,
    IconSquareChevronsDownFilled, IconSquareChevronsLeft, IconSquareChevronsLeftFilled, IconSquareChevronsRight,
    IconSquareChevronsRightFilled, IconSquareChevronsUp, IconSquareChevronsUpFilled, IconSquareDashed,
    IconSquareDot, IconSquareDotFilled, IconSquareF0, IconSquareF0Filled, IconSquareF1, IconSquareF1Filled,
    IconSquareF2, IconSquareF2Filled, IconSquareF3, IconSquareF3Filled, IconSquareF4, IconSquareF4Filled,
    IconSquareF5, IconSquareF5Filled, IconSquareF6, IconSquareF6Filled, IconSquareF7, IconSquareF7Filled,
    IconSquareF8, IconSquareF8Filled, IconSquareF9, IconSquareF9Filled, IconSquareFilled, IconSquareForbid,
    IconSquareForbid2, IconSquareHalf, IconSquareKey, IconSquareLetterA, IconSquareLetterAFilled, IconSquareLetterB,
    IconSquareLetterBFilled, IconSquareLetterC, IconSquareLetterCFilled, IconSquareLetterD, IconSquareLetterDFilled,
    IconSquareLetterE, IconSquareLetterEFilled, IconSquareLetterF, IconSquareLetterFFilled, IconSquareLetterG,
    IconSquareLetterGFilled, IconSquareLetterH, IconSquareLetterHFilled, IconSquareLetterI,
    IconSquareLetterIFilled, IconSquareLetterJ, IconSquareLetterJFilled, IconSquareLetterK, IconSquareLetterKFilled,
    IconSquareLetterL, IconSquareLetterLFilled, IconSquareLetterM, IconSquareLetterMFilled, IconSquareLetterN,
    IconSquareLetterNFilled, IconSquareLetterO, IconSquareLetterOFilled, IconSquareLetterP, IconSquareLetterPFilled,
    IconSquareLetterQ, IconSquareLetterQFilled, IconSquareLetterR, IconSquareLetterRFilled, IconSquareLetterS,
    IconSquareLetterSFilled, IconSquareLetterT, IconSquareLetterTFilled, IconSquareLetterU, IconSquareLetterUFilled,
    IconSquareLetterV, IconSquareLetterVFilled, IconSquareLetterW, IconSquareLetterWFilled, IconSquareLetterX,
    IconSquareLetterXFilled, IconSquareLetterY, IconSquareLetterYFilled, IconSquareLetterZ, IconSquareLetterZFilled,
    IconSquareMinus, IconSquareMinusFilled, IconSquareNumber0, IconSquareNumber0Filled, IconSquareNumber1,
    IconSquareNumber1Filled, IconSquareNumber2, IconSquareNumber2Filled, IconSquareNumber3, IconSquareNumber3Filled,
    IconSquareNumber4, IconSquareNumber4Filled, IconSquareNumber5, IconSquareNumber5Filled, IconSquareNumber6,
    IconSquareNumber6Filled, IconSquareNumber7, IconSquareNumber7Filled, IconSquareNumber8, IconSquareNumber8Filled,
    IconSquareNumber9, IconSquareNumber9Filled, IconSquareOff, IconSquarePercentage, IconSquarePlus, IconSquarePlus2,
    IconSquareRoot, IconSquareRoot2, IconSquareRotated, IconSquareRotatedFilled, IconSquareRotatedForbid,
    IconSquareRotatedForbid2, IconSquareRotatedOff, IconSquareRounded, IconSquareRoundedArrowDown,
    IconSquareRoundedArrowDownFilled, IconSquareRoundedArrowLeft, IconSquareRoundedArrowLeftFilled,
    IconSquareRoundedArrowRight, IconSquareRoundedArrowRightFilled, IconSquareRoundedArrowUp,
    IconSquareRoundedArrowUpFilled, IconSquareRoundedCheck, IconSquareRoundedCheckFilled, IconSquareRoundedChevronDown,
    IconSquareRoundedChevronDownFilled, IconSquareRoundedChevronLeft, IconSquareRoundedChevronLeftFilled,
    IconSquareRoundedChevronRight, IconSquareRoundedChevronRightFilled, IconSquareRoundedChevronUp,
    IconSquareRoundedChevronUpFilled, IconSquareRoundedChevronsDown, IconSquareRoundedChevronsDownFilled,
    IconSquareRoundedChevronsLeft, IconSquareRoundedChevronsLeftFilled, IconSquareRoundedChevronsRight,
    IconSquareRoundedChevronsRightFilled, IconSquareRoundedChevronsUp, IconSquareRoundedChevronsUpFilled,
    IconSquareRoundedFilled, IconSquareRoundedLetterA, IconSquareRoundedLetterAFilled, IconSquareRoundedLetterB,
    IconSquareRoundedLetterBFilled, IconSquareRoundedLetterC, IconSquareRoundedLetterCFilled,
    IconSquareRoundedLetterD, IconSquareRoundedLetterDFilled, IconSquareRoundedLetterE, IconSquareRoundedLetterEFilled,
    IconSquareRoundedLetterF, IconSquareRoundedLetterFFilled, IconSquareRoundedLetterG, IconSquareRoundedLetterGFilled,
    IconSquareRoundedLetterH, IconSquareRoundedLetterHFilled, IconSquareRoundedLetterI, IconSquareRoundedLetterIFilled,
    IconSquareRoundedLetterJ, IconSquareRoundedLetterJFilled, IconSquareRoundedLetterK, IconSquareRoundedLetterKFilled,
    IconSquareRoundedLetterL, IconSquareRoundedLetterLFilled, IconSquareRoundedLetterM, IconSquareRoundedLetterMFilled,
    IconSquareRoundedLetterN, IconSquareRoundedLetterNFilled, IconSquareRoundedLetterO, IconSquareRoundedLetterOFilled,
    IconSquareRoundedLetterP, IconSquareRoundedLetterPFilled, IconSquareRoundedLetterQ, IconSquareRoundedLetterQFilled,
    IconSquareRoundedLetterR, IconSquareRoundedLetterRFilled, IconSquareRoundedLetterS, IconSquareRoundedLetterSFilled,
    IconSquareRoundedLetterT, IconSquareRoundedLetterTFilled, IconSquareRoundedLetterU, IconSquareRoundedLetterUFilled,
    IconSquareRoundedLetterV, IconSquareRoundedLetterVFilled, IconSquareRoundedLetterW, IconSquareRoundedLetterWFilled,
    IconSquareRoundedLetterX, IconSquareRoundedLetterXFilled, IconSquareRoundedLetterY, IconSquareRoundedLetterYFilled,
    IconSquareRoundedLetterZ, IconSquareRoundedLetterZFilled, IconSquareRoundedMinus, IconSquareRoundedMinus2,
    IconSquareRoundedMinusFilled, IconSquareRoundedNumber0, IconSquareRoundedNumber0Filled, IconSquareRoundedNumber1,
    IconSquareRoundedNumber1Filled, IconSquareRoundedNumber2, IconSquareRoundedNumber2Filled, IconSquareRoundedNumber3,
    IconSquareRoundedNumber3Filled, IconSquareRoundedNumber4, IconSquareRoundedNumber4Filled, IconSquareRoundedNumber5,
    IconSquareRoundedNumber5Filled, IconSquareRoundedNumber6, IconSquareRoundedNumber6Filled, IconSquareRoundedNumber7,
    IconSquareRoundedNumber7Filled, IconSquareRoundedNumber8, IconSquareRoundedNumber8Filled, IconSquareRoundedNumber9,
    IconSquareRoundedNumber9Filled, IconSquareRoundedPercentage, IconSquareRoundedPlus, IconSquareRoundedPlus2,
    IconSquareRoundedPlusFilled, IconSquareRoundedX, IconSquareRoundedXFilled, IconSquareToggle, IconSquareToggleHorizontal,
};
