// iconRegistry.ts
export const ICON_REGISTRY = {
    lucide: {
        // Files and documents
        FileJson: { type: 'lucide', import: 'FileJson', searchTerms: ['json', 'file', 'data', 'code'] },
        FileText: { type: 'lucide', import: 'FileText', searchTerms: ['text', 'document', 'file', 'note'] },
        FileCode: { type: 'lucide', import: 'FileCode', searchTerms: ['code', 'programming', 'developer', 'file'] },
        FileImage: { type: 'lucide', import: 'FileImage', searchTerms: ['image', 'picture', 'photo', 'file'] },
        FileInput: { type: 'lucide', import: 'FileInput', searchTerms: ['input', 'file', 'upload', 'data'] },
        FileVideo: { type: 'lucide', import: 'FileVideo', searchTerms: ['video', 'file', 'movie', 'media'] },
        FileSpreadsheet: { type: 'lucide', import: 'FileSpreadsheet', searchTerms: ['spreadsheet', 'excel', 'data', 'file'] },
        FileAudio: { type: 'lucide', import: 'FileAudio', searchTerms: ['audio', 'file', 'music', 'sound'] },
        FileArchive: { type: 'lucide', import: 'FileArchive', searchTerms: ['archive', 'compressed', 'zip', 'file'] },

        // Basic shapes and symbols
        Book: { type: 'lucide', import: 'Book', searchTerms: ['book', 'reading', 'library', 'education'] },
        Circle: { type: 'lucide', import: 'Circle', searchTerms: ['circle', 'shape', 'round', 'geometry'] },
        Square: { type: 'lucide', import: 'Square', searchTerms: ['square', 'shape', 'box', 'geometry'] },
        Triangle: { type: 'lucide', import: 'Triangle', searchTerms: ['triangle', 'shape', 'geometry'] },
        Heart: { type: 'lucide', import: 'Heart', searchTerms: ['love', 'like', 'favorite', 'emotion'] },
        Star: { type: 'lucide', import: 'Star', searchTerms: ['star', 'favorite', 'award', 'rating'] },

        // Arrows and navigation
        ArrowUp: { type: 'lucide', import: 'ArrowUp', searchTerms: ['arrow', 'up', 'direction', 'move up'] },
        ArrowDown: { type: 'lucide', import: 'ArrowDown', searchTerms: ['arrow', 'down', 'direction', 'move down'] },
        ArrowLeft: { type: 'lucide', import: 'ArrowLeft', searchTerms: ['arrow', 'left', 'direction', 'move left'] },
        ArrowRight: { type: 'lucide', import: 'ArrowRight', searchTerms: ['arrow', 'right', 'direction', 'move right'] },
        ChevronUp: { type: 'lucide', import: 'ChevronUp', searchTerms: ['chevron', 'up', 'arrow', 'direction'] },
        ChevronDown: { type: 'lucide', import: 'ChevronDown', searchTerms: ['chevron', 'down', 'arrow', 'direction'] },
        ChevronLeft: { type: 'lucide', import: 'ChevronLeft', searchTerms: ['chevron', 'left', 'arrow', 'direction'] },
        ChevronRight: { type: 'lucide', import: 'ChevronRight', searchTerms: ['chevron', 'right', 'arrow', 'direction'] },

        // User interface
        Search: { type: 'lucide', import: 'Search', searchTerms: ['magnifying glass', 'find', 'look up'] },
        Settings: { type: 'lucide', import: 'Settings', searchTerms: ['settings', 'preferences', 'gear', 'configuration'] },
        Home: { type: 'lucide', import: 'Home', searchTerms: ['home', 'house', 'start', 'main page'] },
        Menu: { type: 'lucide', import: 'Menu', searchTerms: ['menu', 'hamburger', 'navigation', 'options'] },
        X: { type: 'lucide', import: 'X', searchTerms: ['close', 'cross', 'cancel', 'exit'] },
        Check: { type: 'lucide', import: 'Check', searchTerms: ['check', 'tick', 'done', 'confirm'] },
        Plus: { type: 'lucide', import: 'Plus', searchTerms: ['plus', 'add', 'increase', 'expand'] },
        Minus: { type: 'lucide', import: 'Minus', searchTerms: ['minus', 'subtract', 'decrease', 'reduce'] },

        // Media and files
        Image: { type: 'lucide', import: 'Image', searchTerms: ['image', 'picture', 'photo', 'media'] },
        Video: { type: 'lucide', import: 'Video', searchTerms: ['video', 'film', 'movie', 'media'] },
        Music: { type: 'lucide', import: 'Music', searchTerms: ['music', 'sound', 'audio', 'note'] },
        File: { type: 'lucide', import: 'File', searchTerms: ['file', 'document', 'data', 'paper'] },
        Folder: { type: 'lucide', import: 'Folder', searchTerms: ['folder', 'directory', 'file', 'organize'] },
        Camera: { type: 'lucide', import: 'Camera', searchTerms: ['camera', 'photo', 'picture', 'snapshot'] },

        // Communication
        Mail: { type: 'lucide', import: 'Mail', searchTerms: ['mail', 'email', 'letter', 'message'] },
        Phone: { type: 'lucide', import: 'Phone', searchTerms: ['phone', 'call', 'communication', 'contact'] },
        MessageCircle: { type: 'lucide', import: 'MessageCircle', searchTerms: ['message', 'chat', 'communication', 'bubble'] },
        Bell: { type: 'lucide', import: 'Bell', searchTerms: ['bell', 'notification', 'alert', 'ring'] },

        // Users and accounts
        User: { type: 'lucide', import: 'User', searchTerms: ['person', 'profile', 'account', 'identity'] },
        Users: { type: 'lucide', import: 'Users', searchTerms: ['users', 'people', 'group', 'accounts'] },
        UserPlus: { type: 'lucide', import: 'UserPlus', searchTerms: ['add user', 'user', 'account', 'plus'] },
        UserMinus: { type: 'lucide', import: 'UserMinus', searchTerms: ['remove user', 'user', 'minus', 'account'] },

        // Devices and tech
        Smartphone: { type: 'lucide', import: 'Smartphone', searchTerms: ['smartphone', 'phone', 'mobile', 'device'] },
        Tablet: { type: 'lucide', import: 'Tablet', searchTerms: ['tablet', 'device', 'mobile', 'screen'] },
        Laptop: { type: 'lucide', import: 'Laptop', searchTerms: ['laptop', 'computer', 'device', 'portable'] },
        Monitor: { type: 'lucide', import: 'Monitor', searchTerms: ['monitor', 'screen', 'display', 'computer'] },

        // Weather and nature
        Sun: { type: 'lucide', import: 'Sun', searchTerms: ['sun', 'day', 'weather', 'sunny'] },
        Moon: { type: 'lucide', import: 'Moon', searchTerms: ['moon', 'night', 'weather', 'lunar'] },
        Cloud: { type: 'lucide', import: 'Cloud', searchTerms: ['cloud', 'weather', 'sky', 'overcast'] },
        CloudRain: { type: 'lucide', import: 'CloudRain', searchTerms: ['rain', 'cloud', 'weather', 'storm'] },

        // Business and commerce
        DollarSign: { type: 'lucide', import: 'DollarSign', searchTerms: ['dollar', 'money', 'currency', 'finance'] },
        ShoppingCart: { type: 'lucide', import: 'ShoppingCart', searchTerms: ['shopping', 'cart', 'purchase', 'buy'] },
        CreditCard: { type: 'lucide', import: 'CreditCard', searchTerms: ['credit card', 'payment', 'buy', 'finance'] },

        // Social and sharing
        Share: { type: 'lucide', import: 'Share', searchTerms: ['share', 'social', 'send', 'forward'] },
        Link: { type: 'lucide', import: 'Link', searchTerms: ['link', 'url', 'web', 'connect'] },
        Upload: { type: 'lucide', import: 'Upload', searchTerms: ['upload', 'cloud', 'transfer', 'file'] },
        Download: { type: 'lucide', import: 'Download', searchTerms: ['download', 'file', 'save', 'transfer'] },

        // Editor tools
        Bold: { type: 'lucide', import: 'Bold', searchTerms: ['bold', 'text', 'font', 'style'] },
        Italic: { type: 'lucide', import: 'Italic', searchTerms: ['italic', 'text', 'font', 'style'] },
        Underline: { type: 'lucide', import: 'Underline', searchTerms: ['underline', 'text', 'font', 'style'] },
        List: { type: 'lucide', import: 'List', searchTerms: ['list', 'bullets', 'items', 'text'] },

        // Others
        Calendar: { type: 'lucide', import: 'Calendar', searchTerms: ['calendar', 'schedule', 'event', 'date'] },
        Clock: { type: 'lucide', import: 'Clock', searchTerms: ['clock', 'time', 'watch', 'hour'] },
        Map: { type: 'lucide', import: 'Map', searchTerms: ['map', 'location', 'geography', 'navigation'] },
        Bookmark: { type: 'lucide', import: 'Bookmark', searchTerms: ['bookmark', 'save', 'link', 'favorite'] },

        Save: { type: 'lucide', import: 'Save', searchTerms: ['save', 'disk', 'file', 'document'] },
        Trash: { type: 'lucide', import: 'Trash', searchTerms: ['trash', 'delete', 'remove', 'bin'] },
        Edit: { type: 'lucide', import: 'Edit', searchTerms: ['edit', 'pencil', 'modify', 'change'] },
        Eye: { type: 'lucide', import: 'Eye', searchTerms: ['eye', 'view', 'see', 'visibility'] },
        EyeOff: { type: 'lucide', import: 'EyeOff', searchTerms: ['eye off', 'invisible', 'hide', 'visibility'] },

        Lock: { type: 'lucide', import: 'Lock', searchTerms: ['lock', 'security', 'private', 'protect'] },
        Unlock: { type: 'lucide', import: 'Unlock', searchTerms: ['unlock', 'open', 'security', 'access'] },
        Key: { type: 'lucide', import: 'Key', searchTerms: ['key', 'lock', 'access', 'security'] },
        Flag: { type: 'lucide', import: 'Flag', searchTerms: ['flag', 'mark', 'country', 'signal'] },

        ClipboardCopy: { type: 'lucide', import: 'ClipboardCopy', searchTerms: ['clipboard', 'copy', 'paste', 'text'] },
        Clipboard: { type: 'lucide', import: 'Clipboard', searchTerms: ['clipboard', 'paste', 'copy', 'text'] },
        Database: { type: 'lucide', import: 'Database', searchTerms: ['database', 'data', 'server', 'storage'] },
        Server: { type: 'lucide', import: 'Server', searchTerms: ['server', 'network', 'hosting', 'cloud'] },
        Code: { type: 'lucide', import: 'Code', searchTerms: ['code', 'programming', 'developer', 'script'] },

        StopCircleIcon: { type: 'lucide', import: 'StopCircleIcon', searchTerms: ['stop', 'circle', 'pause', 'halt'] },
        PlayCircleIcon: { type: 'lucide', import: 'PlayCircleIcon', searchTerms: ['play', 'circle', 'start', 'media'] },
        PauseCircleIcon: { type: 'lucide', import: 'PauseCircleIcon', searchTerms: ['pause', 'circle', 'media', 'stop'] },
    },
    tabler: {
        IconGif: { type: 'tabler', import: 'IconGif', searchTerms: ['gif', 'file', 'image', 'type'] },
        IconFile3d: { type: 'tabler', import: 'IconFile3d', searchTerms: ['3d', 'file', 'model', 'document'] },
        IconFileAi: { type: 'tabler', import: 'IconFileAi', searchTerms: ['ai', 'file', 'artificial intelligence', 'design'] },
        IconFileAlert: { type: 'tabler', import: 'IconFileAlert', searchTerms: ['alert', 'file', 'warning', 'notification'] },
        IconFileAnalytics: { type: 'tabler', import: 'IconFileAnalytics', searchTerms: ['analytics', 'file', 'data', 'statistics'] },
        IconFileArrowLeft: { type: 'tabler', import: 'IconFileArrowLeft', searchTerms: ['file', 'arrow', 'left', 'direction'] },
        IconFileArrowRight: { type: 'tabler', import: 'IconFileArrowRight', searchTerms: ['file', 'arrow', 'right', 'direction'] },
        IconFileBarcode: { type: 'tabler', import: 'IconFileBarcode', searchTerms: ['barcode', 'file', 'scan', 'product'] },
        IconFileBitcoin: { type: 'tabler', import: 'IconFileBitcoin', searchTerms: ['bitcoin', 'file', 'crypto', 'currency'] },
        IconFileBroken: { type: 'tabler', import: 'IconFileBroken', searchTerms: ['broken', 'file', 'error', 'damage'] },
        IconFileCertificate: { type: 'tabler', import: 'IconFileCertificate', searchTerms: ['certificate', 'file', 'document', 'award'] },
        IconFileChart: { type: 'tabler', import: 'IconFileChart', searchTerms: ['chart', 'file', 'statistics', 'data'] },
        IconFileCheck: { type: 'tabler', import: 'IconFileCheck', searchTerms: ['check', 'file', 'tick', 'done'] },
        IconFileCode: { type: 'tabler', import: 'IconFileCode', searchTerms: ['file', 'code', 'programming', 'developer'] },
        IconFileCode2: { type: 'tabler', import: 'IconFileCode2', searchTerms: ['file', 'code', 'developer', 'script'] },
        IconFileCv: { type: 'tabler', import: 'IconFileCv', searchTerms: ['cv', 'resume', 'file', 'document'] },
        IconFileDatabase: { type: 'tabler', import: 'IconFileDatabase', searchTerms: ['file', 'database', 'data', 'storage'] },
        IconFileDelta: { type: 'tabler', import: 'IconFileDelta', searchTerms: ['delta', 'file', 'change', 'difference'] },
        IconFileDescription: { type: 'tabler', import: 'IconFileDescription', searchTerms: ['file', 'description', 'document', 'info'] },
        IconFileDiff: { type: 'tabler', import: 'IconFileDiff', searchTerms: ['diff', 'file', 'comparison', 'change'] },
        IconFileDigit: { type: 'tabler', import: 'IconFileDigit', searchTerms: ['file', 'digit', 'number', 'data'] },
        IconFileDislike: { type: 'tabler', import: 'IconFileDislike', searchTerms: ['file', 'dislike', 'thumbs down', 'negative'] },
        IconFileDollar: { type: 'tabler', import: 'IconFileDollar', searchTerms: ['file', 'dollar', 'money', 'currency'] },
        IconFileDots: { type: 'tabler', import: 'IconFileDots', searchTerms: ['file', 'dots', 'menu', 'options'] },
        IconFileDownload: { type: 'tabler', import: 'IconFileDownload', searchTerms: ['file', 'download', 'cloud', 'transfer'] },
        IconFileEuro: { type: 'tabler', import: 'IconFileEuro', searchTerms: ['file', 'euro', 'currency', 'money'] },
        IconFileExcel: { type: 'tabler', import: 'IconFileExcel', searchTerms: ['file', 'excel', 'spreadsheet', 'data'] },
        IconFileExport: { type: 'tabler', import: 'IconFileExport', searchTerms: ['file', 'export', 'transfer', 'data'] },
        IconFileFilled: { type: 'tabler', import: 'IconFileFilled', searchTerms: ['file', 'filled', 'document', 'solid'] },
        IconFileFunction: { type: 'tabler', import: 'IconFileFunction', searchTerms: ['file', 'function', 'programming', 'code'] },
        IconFileHorizontal: { type: 'tabler', import: 'IconFileHorizontal', searchTerms: ['file', 'horizontal', 'document', 'layout'] },
        IconFileImport: { type: 'tabler', import: 'IconFileImport', searchTerms: ['file', 'import', 'upload', 'data'] },
        IconFileInfinity: { type: 'tabler', import: 'IconFileInfinity', searchTerms: ['file', 'infinity', 'loop', 'endless'] },
        IconFileInfo: { type: 'tabler', import: 'IconFileInfo', searchTerms: ['file', 'info', 'information', 'data'] },
        IconFileInvoice: { type: 'tabler', import: 'IconFileInvoice', searchTerms: ['file', 'invoice', 'document', 'billing'] },
        IconFileIsr: { type: 'tabler', import: 'IconFileIsr', searchTerms: ['file', 'isr', 'document', 'security'] },
        IconFileLambda: { type: 'tabler', import: 'IconFileLambda', searchTerms: ['file', 'lambda', 'programming', 'function'] },
        IconFileLike: { type: 'tabler', import: 'IconFileLike', searchTerms: ['file', 'like', 'thumbs up', 'positive'] },
        IconFileMinus: { type: 'tabler', import: 'IconFileMinus', searchTerms: ['file', 'minus', 'remove', 'subtract'] },
        IconFileMusic: { type: 'tabler', import: 'IconFileMusic', searchTerms: ['file', 'music', 'audio', 'sound'] },
        IconFileNeutral: { type: 'tabler', import: 'IconFileNeutral', searchTerms: ['file', 'neutral', 'document', 'balance'] },
        IconFileOff: { type: 'tabler', import: 'IconFileOff', searchTerms: ['file', 'off', 'disabled', 'inactive'] },
        IconFileOrientation: { type: 'tabler', import: 'IconFileOrientation', searchTerms: ['file', 'orientation', 'landscape', 'portrait'] },
        IconFilePencil: { type: 'tabler', import: 'IconFilePencil', searchTerms: ['file', 'edit', 'pencil', 'modify'] },
        IconFilePercent: { type: 'tabler', import: 'IconFilePercent', searchTerms: ['file', 'percent', 'percentage', 'data'] },
        IconFilePhone: { type: 'tabler', import: 'IconFilePhone', searchTerms: ['file', 'phone', 'communication', 'contact'] },
        IconFilePlus: { type: 'tabler', import: 'IconFilePlus', searchTerms: ['file', 'plus', 'add', 'create'] },
        IconFilePower: { type: 'tabler', import: 'IconFilePower', searchTerms: ['file', 'power', 'on', 'energy'] },
        IconFileReport: { type: 'tabler', import: 'IconFileReport', searchTerms: ['file', 'report', 'document', 'analysis'] },
        IconFileRss: { type: 'tabler', import: 'IconFileRss', searchTerms: ['file', 'rss', 'feed', 'news'] },
        IconFileSad: { type: 'tabler', import: 'IconFileSad', searchTerms: ['file', 'sad', 'emotion', 'negative'] },
        IconFileScissors: { type: 'tabler', import: 'IconFileScissors', searchTerms: ['file', 'scissors', 'cut', 'edit'] },
        IconFileSearch: { type: 'tabler', import: 'IconFileSearch', searchTerms: ['file', 'search', 'find', 'document'] },
        IconFileSettings: { type: 'tabler', import: 'IconFileSettings', searchTerms: ['file', 'settings', 'config', 'preferences'] },
        IconFileShredder: { type: 'tabler', import: 'IconFileShredder', searchTerms: ['file', 'shredder', 'delete', 'confidential'] },
        IconFileSignal: { type: 'tabler', import: 'IconFileSignal', searchTerms: ['file', 'signal', 'strength', 'connection'] },
        IconFileSmile: { type: 'tabler', import: 'IconFileSmile', searchTerms: ['file', 'smile', 'happy', 'emotion'] },
        IconFileSpark: { type: 'tabler', import: 'IconFileSpark', searchTerms: ['file', 'spark', 'flame', 'idea'] },
        IconFileSpreadsheet: { type: 'tabler', import: 'IconFileSpreadsheet', searchTerms: ['file', 'spreadsheet', 'excel', 'data'] },
        IconFileStack: { type: 'tabler', import: 'IconFileStack', searchTerms: ['file', 'stack', 'document', 'layers'] },
        IconFileStar: { type: 'tabler', import: 'IconFileStar', searchTerms: ['file', 'star', 'favorite', 'rating'] },
        IconFileSymlink: { type: 'tabler', import: 'IconFileSymlink', searchTerms: ['file', 'symlink', 'link', 'shortcut'] },
        IconFileText: { type: 'tabler', import: 'IconFileText', searchTerms: ['file', 'text', 'document', 'note'] },
        IconFileTextAi: { type: 'tabler', import: 'IconFileTextAi', searchTerms: ['file', 'text', 'ai', 'artificial intelligence'] },
        IconFileTextSpark: { type: 'tabler', import: 'IconFileTextSpark', searchTerms: ['file', 'text', 'spark', 'idea'] },
        IconFileTime: { type: 'tabler', import: 'IconFileTime', searchTerms: ['file', 'time', 'document', 'clock'] },
        IconFileTypeBmp: { type: 'tabler', import: 'IconFileTypeBmp', searchTerms: ['bmp', 'file', 'image', 'type'] },
        IconFileTypeCss: { type: 'tabler', import: 'IconFileTypeCss', searchTerms: ['css', 'file', 'style', 'stylesheet'] },
        IconFileTypeCsv: { type: 'tabler', import: 'IconFileTypeCsv', searchTerms: ['csv', 'file', 'data', 'spreadsheet'] },
        IconFileTypeDoc: { type: 'tabler', import: 'IconFileTypeDoc', searchTerms: ['doc', 'file', 'document', 'word'] },
        IconFileTypeDocx: { type: 'tabler', import: 'IconFileTypeDocx', searchTerms: ['docx', 'file', 'document', 'word'] },
        IconFileTypeHtml: { type: 'tabler', import: 'IconFileTypeHtml', searchTerms: ['html', 'file', 'web', 'code'] },
        IconFileTypeJpg: { type: 'tabler', import: 'IconFileTypeJpg', searchTerms: ['jpg', 'file', 'image', 'photo'] },
        IconFileTypeJs: { type: 'tabler', import: 'IconFileTypeJs', searchTerms: ['js', 'file', 'javascript', 'code'] },
        IconFileTypeJsx: { type: 'tabler', import: 'IconFileTypeJsx', searchTerms: ['jsx', 'file', 'react', 'code'] },
        IconFileTypePdf: { type: 'tabler', import: 'IconFileTypePdf', searchTerms: ['pdf', 'file', 'document', 'read'] },
        IconFileTypePhp: { type: 'tabler', import: 'IconFileTypePhp', searchTerms: ['php', 'file', 'code', 'web'] },
        IconFileTypePng: { type: 'tabler', import: 'IconFileTypePng', searchTerms: ['png', 'file', 'image', 'photo'] },
        IconFileTypePpt: { type: 'tabler', import: 'IconFileTypePpt', searchTerms: ['ppt', 'file', 'presentation', 'slide'] },
        IconFileTypePptx: { type: 'tabler', import: 'IconFileTypePptx', searchTerms: ['pptx', 'file', 'presentation', 'slide'] },
        IconFileTypeRar: { type: 'tabler', import: 'IconFileTypeRar', searchTerms: ['rar', 'file', 'archive', 'compressed'] },
        IconFileTypeRtf: { type: 'tabler', import: 'IconFileTypeRtf', searchTerms: ['rtf', 'file', 'document', 'text'] },
        IconFileTypeSql: { type: 'tabler', import: 'IconFileTypeSql', searchTerms: ['sql', 'file', 'database', 'query'] },
        IconFileTypeSvg: { type: 'tabler', import: 'IconFileTypeSvg', searchTerms: ['svg', 'file', 'image', 'vector'] },
        IconFileTypeTxt: { type: 'tabler', import: 'IconFileTypeTxt', searchTerms: ['txt', 'file', 'text', 'document'] },
        IconFileTypeXls: { type: 'tabler', import: 'IconFileTypeXls', searchTerms: ['xls', 'file', 'spreadsheet', 'excel'] },
        IconFileTypeXlsx: { type: 'tabler', import: 'IconFileTypeXlsx', searchTerms: ['xlsx', 'file', 'spreadsheet', 'excel'] },
        IconFileTypeXml: { type: 'tabler', import: 'IconFileTypeXml', searchTerms: ['xml', 'file', 'data', 'document'] },
        IconFileTypeZip: { type: 'tabler', import: 'IconFileTypeZip', searchTerms: ['zip', 'file', 'archive', 'compressed'] },
        IconFileUpload: { type: 'tabler', import: 'IconFileUpload', searchTerms: ['file', 'upload', 'cloud', 'transfer'] },
        IconFileUser: { type: 'tabler', import: 'IconFileUser', searchTerms: ['file', 'user', 'person', 'profile'] },
        IconFileUsers: { type: 'tabler', import: 'IconFileUsers', searchTerms: ['file', 'users', 'people', 'group'] },
        IconFileVideo: { type: 'tabler', import: 'IconFileVideo', searchTerms: ['file', 'video', 'movie', 'media'] },
        IconFileWord: { type: 'tabler', import: 'IconFileWord', searchTerms: ['file', 'word', 'document', 'text'] },
        IconHeadphonesOff: { type: 'tabler', import: 'IconHeadphonesOff', searchTerms: ['headphones', 'off', 'audio', 'music', 'sound'] },
        IconHeadset: { type: 'tabler', import: 'IconHeadset', searchTerms: ['headset', 'audio', 'music', 'sound'] },
        IconHeadsetOff: { type: 'tabler', import: 'IconHeadsetOff', searchTerms: ['headset', 'off', 'audio', 'music', 'sound'] },
        IconHealthRecognition: { type: 'tabler', import: 'IconHealthRecognition', searchTerms: ['health', 'recognition', 'medical', 'monitoring'] },
        IconHeart: { type: 'tabler', import: 'IconHeart', searchTerms: ['heart', 'love', 'like', 'emotion'] },
        IconHeartBitcoin: { type: 'tabler', import: 'IconHeartBitcoin', searchTerms: ['heart', 'bitcoin', 'cryptocurrency', 'love'] },
        IconHeartBolt: { type: 'tabler', import: 'IconHeartBolt', searchTerms: ['heart', 'bolt', 'energy', 'lightning'] },
        IconHeartBroken: { type: 'tabler', import: 'IconHeartBroken', searchTerms: ['heart', 'broken', 'love', 'emotion'] },
        IconHeartCancel: { type: 'tabler', import: 'IconHeartCancel', searchTerms: ['heart', 'cancel', 'love', 'emotion'] },
        IconHeartCheck: { type: 'tabler', import: 'IconHeartCheck', searchTerms: ['heart', 'check', 'love', 'confirmation'] },
        IconHeartCode: { type: 'tabler', import: 'IconHeartCode', searchTerms: ['heart', 'code', 'programming', 'love'] },
        IconHeartCog: { type: 'tabler', import: 'IconHeartCog', searchTerms: ['heart', 'cog', 'settings', 'gear'] },
        IconHeartDiscount: { type: 'tabler', import: 'IconHeartDiscount', searchTerms: ['heart', 'discount', 'love', 'sale'] },
        IconHeartDollar: { type: 'tabler', import: 'IconHeartDollar', searchTerms: ['heart', 'dollar', 'money', 'finance'] },
        IconHeartDown: { type: 'tabler', import: 'IconHeartDown', searchTerms: ['heart', 'down', 'emotion', 'sad'] },
        IconHeartExclamation: { type: 'tabler', import: 'IconHeartExclamation', searchTerms: ['heart', 'exclamation', 'warning', 'alert'] },
        IconHeartFilled: { type: 'tabler', import: 'IconHeartFilled', searchTerms: ['heart', 'filled', 'love', 'emotion'] },
        IconHeartHandshake: { type: 'tabler', import: 'IconHeartHandshake', searchTerms: ['heart', 'handshake', 'love', 'agreement'] },
        IconHeartMinus: { type: 'tabler', import: 'IconHeartMinus', searchTerms: ['heart', 'minus', 'love', 'decrease'] },
        IconHeartOff: { type: 'tabler', import: 'IconHeartOff', searchTerms: ['heart', 'off', 'love', 'stop'] },
        IconHeartPause: { type: 'tabler', import: 'IconHeartPause', searchTerms: ['heart', 'pause', 'love', 'stop'] },
        IconHeartPin: { type: 'tabler', import: 'IconHeartPin', searchTerms: ['heart', 'pin', 'love', 'location'] },
        IconHeartPlus: { type: 'tabler', import: 'IconHeartPlus', searchTerms: ['heart', 'plus', 'love', 'add'] },
        IconHeartQuestion: { type: 'tabler', import: 'IconHeartQuestion', searchTerms: ['heart', 'question', 'love', 'uncertain'] },
        IconHeartRateMonitor: { type: 'tabler', import: 'IconHeartRateMonitor', searchTerms: ['heart', 'rate', 'monitor', 'health'] },
        IconHeartSearch: { type: 'tabler', import: 'IconHeartSearch', searchTerms: ['heart', 'search', 'love', 'look up'] },
        IconHeartShare: { type: 'tabler', import: 'IconHeartShare', searchTerms: ['heart', 'share', 'love', 'send'] },
        IconHeartSpark: { type: 'tabler', import: 'IconHeartSpark', searchTerms: ['heart', 'spark', 'love', 'energy'] },
        IconHeartStar: { type: 'tabler', import: 'IconHeartStar', searchTerms: ['heart', 'star', 'love', 'emotion'] },
        IconHeartUp: { type: 'tabler', import: 'IconHeartUp', searchTerms: ['heart', 'up', 'love', 'emotion'] },
        IconHeartX: { type: 'tabler', import: 'IconHeartX', searchTerms: ['heart', 'x', 'cross', 'love', 'cancel'] },
        IconHeartbeat: { type: 'tabler', import: 'IconHeartbeat', searchTerms: ['heartbeat', 'heart', 'pulse', 'health'] },
        IconHearts: { type: 'tabler', import: 'IconHearts', searchTerms: ['hearts', 'love', 'group', 'emotion'] },
        IconHeartsOff: { type: 'tabler', import: 'IconHeartsOff', searchTerms: ['hearts', 'off', 'love', 'stop'] },
        IconHelicopter: { type: 'tabler', import: 'IconHelicopter', searchTerms: ['helicopter', 'aircraft', 'transport', 'chopper'] },
        IconHelicopterLanding: { type: 'tabler', import: 'IconHelicopterLanding', searchTerms: ['helicopter', 'landing', 'aircraft', 'transport'] },
        IconHelicopterLandingFilled: { type: 'tabler', import: 'IconHelicopterLandingFilled', searchTerms: ['helicopter', 'landing', 'aircraft', 'filled'] },
        IconHelmet: { type: 'tabler', import: 'IconHelmet', searchTerms: ['helmet', 'safety', 'protection', 'gear'] },
        IconHelmetOff: { type: 'tabler', import: 'IconHelmetOff', searchTerms: ['helmet', 'off', 'safety', 'protection'] },
        IconHelp: { type: 'tabler', import: 'IconHelp', searchTerms: ['help', 'question', 'support', 'assistance'] },
        IconHelpCircle: { type: 'tabler', import: 'IconHelpCircle', searchTerms: ['help', 'circle', 'support', 'question'] },
        IconHelpCircleFilled: { type: 'tabler', import: 'IconHelpCircleFilled', searchTerms: ['help', 'circle', 'filled', 'support'] },
        IconHelpHexagon: { type: 'tabler', import: 'IconHelpHexagon', searchTerms: ['help', 'hexagon', 'question', 'support'] },
        IconHelpHexagonFilled: { type: 'tabler', import: 'IconHelpHexagonFilled', searchTerms: ['help', 'hexagon', 'question', 'support', 'filled'] },
        IconHelpOctagon: { type: 'tabler', import: 'IconHelpOctagon', searchTerms: ['help', 'octagon', 'question', 'support'] },
        IconHelpOctagonFilled: { type: 'tabler', import: 'IconHelpOctagonFilled', searchTerms: ['help', 'octagon', 'question', 'support', 'filled'] },
        IconHelpOff: { type: 'tabler', import: 'IconHelpOff', searchTerms: ['help', 'off', 'question', 'support'] },
        IconHelpSmall: { type: 'tabler', import: 'IconHelpSmall', searchTerms: ['help', 'small', 'question', 'support'] },
        IconHelpSquare: { type: 'tabler', import: 'IconHelpSquare', searchTerms: ['help', 'square', 'question', 'support'] },
        IconHelpSquareFilled: { type: 'tabler', import: 'IconHelpSquareFilled', searchTerms: ['help', 'square', 'question', 'support', 'filled'] },
        IconHelpSquareRounded: { type: 'tabler', import: 'IconHelpSquareRounded', searchTerms: ['help', 'square', 'rounded', 'question', 'support'] },
        IconHelpSquareRoundedFilled: { type: 'tabler', import: 'IconHelpSquareRoundedFilled', searchTerms: ['help', 'square', 'rounded', 'question', 'support', 'filled'] },
        IconHelpTriangle: { type: 'tabler', import: 'IconHelpTriangle', searchTerms: ['help', 'triangle', 'question', 'support'] },
        IconHelpTriangleFilled: { type: 'tabler', import: 'IconHelpTriangleFilled', searchTerms: ['help', 'triangle', 'question', 'support', 'filled'] },
        IconInputAi: { type: 'tabler', import: 'IconInputAi', searchTerms: ['input', 'AI', 'artificial intelligence', 'data'] },
        IconInputCheck: { type: 'tabler', import: 'IconInputCheck', searchTerms: ['input', 'check', 'form', 'confirm'] },
        IconInputSearch: { type: 'tabler', import: 'IconInputSearch', searchTerms: ['input', 'search', 'form', 'query'] },
        IconInputSpark: { type: 'tabler', import: 'IconInputSpark', searchTerms: ['input', 'spark', 'form', 'data'] },
        IconInputX: { type: 'tabler', import: 'IconInputX', searchTerms: ['input', 'x', 'cross', 'form'] },
        IconInvoice: { type: 'tabler', import: 'IconInvoice', searchTerms: ['invoice', 'bill', 'payment', 'receipt'] },
        IconIroning: { type: 'tabler', import: 'IconIroning', searchTerms: ['ironing', 'clothes', 'press', 'steam'] },
        IconIroning1: { type: 'tabler', import: 'IconIroning1', searchTerms: ['ironing', 'clothes', 'press', 'steam'] },
        IconIroning1Filled: { type: 'tabler', import: 'IconIroning1Filled', searchTerms: ['ironing', 'clothes', 'press', 'steam', 'filled'] },
        IconIroning2: { type: 'tabler', import: 'IconIroning2', searchTerms: ['ironing', 'clothes', 'press', 'steam'] },
        IconIroning2Filled: { type: 'tabler', import: 'IconIroning2Filled', searchTerms: ['ironing', 'clothes', 'press', 'steam', 'filled'] },
        IconIroning3: { type: 'tabler', import: 'IconIroning3', searchTerms: ['ironing', 'clothes', 'press', 'steam'] },
        IconIroning3Filled: { type: 'tabler', import: 'IconIroning3Filled', searchTerms: ['ironing', 'clothes', 'press', 'steam', 'filled'] },
        IconIroningFilled: { type: 'tabler', import: 'IconIroningFilled', searchTerms: ['ironing', 'clothes', 'press', 'steam', 'filled'] },
        IconIroningOff: { type: 'tabler', import: 'IconIroningOff', searchTerms: ['ironing', 'off', 'clothes', 'press'] },
        IconIroningSteam: { type: 'tabler', import: 'IconIroningSteam', searchTerms: ['ironing', 'steam', 'clothes', 'press'] },
        IconIroningSteamFilled: { type: 'tabler', import: 'IconIroningSteamFilled', searchTerms: ['ironing', 'steam', 'clothes', 'press', 'filled'] },
        IconIroningSteamOff: { type: 'tabler', import: 'IconIroningSteamOff', searchTerms: ['ironing', 'steam', 'off', 'clothes', 'press'] },
        IconIrregularPolyhedron: { type: 'tabler', import: 'IconIrregularPolyhedron', searchTerms: ['polyhedron', 'geometry', 'irregular', 'shape'] },
        IconIrregularPolyhedronOff: { type: 'tabler', import: 'IconIrregularPolyhedronOff', searchTerms: ['polyhedron', 'geometry', 'irregular', 'off'] },
        IconIrregularPolyhedronPlus: { type: 'tabler', import: 'IconIrregularPolyhedronPlus', searchTerms: ['polyhedron', 'plus', 'geometry', 'irregular'] },
        IconItalic: { type: 'tabler', import: 'IconItalic', searchTerms: ['italic', 'text', 'style', 'font'] },
        IconJacket: { type: 'tabler', import: 'IconJacket', searchTerms: ['jacket', 'clothing', 'wear', 'outerwear'] },
        IconJetpack: { type: 'tabler', import: 'IconJetpack', searchTerms: ['jetpack', 'flight', 'technology', 'backpack'] },
        IconJetpackFilled: { type: 'tabler', import: 'IconJetpackFilled', searchTerms: ['jetpack', 'flight', 'technology', 'filled'] },
        IconJewishStar: { type: 'tabler', import: 'IconJewishStar', searchTerms: ['star', 'jewish', 'symbol', 'religion'] },
        IconJewishStarFilled: { type: 'tabler', import: 'IconJewishStarFilled', searchTerms: ['star', 'jewish', 'symbol', 'religion', 'filled'] },
        IconJoinBevel: { type: 'tabler', import: 'IconJoinBevel', searchTerms: ['join', 'bevel', 'angle', 'geometry'] },
        IconJoinRound: { type: 'tabler', import: 'IconJoinRound', searchTerms: ['join', 'round', 'angle', 'geometry'] },
        IconJoinStraight: { type: 'tabler', import: 'IconJoinStraight', searchTerms: ['join', 'straight', 'angle', 'geometry'] },
        IconJoker: { type: 'tabler', import: 'IconJoker', searchTerms: ['joker', 'card', 'fun', 'game'] },
        IconJpg: { type: 'tabler', import: 'IconJpg', searchTerms: ['jpg', 'image', 'photo', 'file'] },
        IconJson: { type: 'tabler', import: 'IconJson', searchTerms: ['json', 'data', 'file', 'format'] },
        IconJumpRope: { type: 'tabler', import: 'IconJumpRope', searchTerms: ['jump rope', 'exercise', 'fitness', 'workout'] },
        IconKarate: { type: 'tabler', import: 'IconKarate', searchTerms: ['karate', 'martial arts', 'sport', 'fight'] },
        IconKayak: { type: 'tabler', import: 'IconKayak', searchTerms: ['kayak', 'boat', 'water', 'sport'] },
        IconKering: { type: 'tabler', import: 'IconKering', searchTerms: ['kering', 'fashion', 'brand', 'luxury'] },
        IconKerning: { type: 'tabler', import: 'IconKerning', searchTerms: ['kerning', 'typography', 'letter spacing', 'font'] },
        IconKey: { type: 'tabler', import: 'IconKey', searchTerms: ['key', 'lock', 'access', 'security'] },
        IconKeyFilled: { type: 'tabler', import: 'IconKeyFilled', searchTerms: ['key', 'lock', 'access', 'security', 'filled'] },
        IconKeyOff: { type: 'tabler', import: 'IconKeyOff', searchTerms: ['key', 'off', 'lock', 'security'] },
        IconKeyboard: { type: 'tabler', import: 'IconKeyboard', searchTerms: ['keyboard', 'type', 'input', 'device'] },
        IconKeyboardFilled: { type: 'tabler', import: 'IconKeyboardFilled', searchTerms: ['keyboard', 'type', 'input', 'device', 'filled'] },
        IconKeyboardHide: { type: 'tabler', import: 'IconKeyboardHide', searchTerms: ['keyboard', 'hide', 'input', 'device'] },
        IconKeyboardOff: { type: 'tabler', import: 'IconKeyboardOff', searchTerms: ['keyboard', 'off', 'input', 'device'] },
        IconKeyboardShow: { type: 'tabler', import: 'IconKeyboardShow', searchTerms: ['keyboard', 'show', 'input', 'device'] },
        IconKeyframe: { type: 'tabler', import: 'IconKeyframe', searchTerms: ['keyframe', 'animation', 'timeline', 'motion'] },
        IconKeyframeAlignCenter: { type: 'tabler', import: 'IconKeyframeAlignCenter', searchTerms: ['keyframe', 'align', 'center', 'animation'] },
        IconKeyframeAlignCenterFilled: { type: 'tabler', import: 'IconKeyframeAlignCenterFilled', searchTerms: ['keyframe', 'align', 'center', 'animation', 'filled'] }

    }
};