export const thinkingFragments = [
    // Step 0: Analyzing input
    [
      "Analyzing your input...",
      "Decoding your message...",
      "Understanding your request...",
      "Interpreting what you've said...",
      "Breaking down your query...",
      "Let me see what you're asking...",
      "Taking a closer look at your words...",
      "Processing your input data...",
      "Evaluating your statement...",
      "Getting to the heart of your question...",
      "Deciphering your cryptic message... just kidding!",
      "Input received. Commencing analysis.",
      "Let me put on my thinking cap for this one.",
      "Analyzing... please don't tell me it's another 'why is the sky blue?'",
      "Initiating deep analysis mode."
    ],
    // Step 1: Considering context
    [
      "Considering the context...",
      "Looking at the bigger picture...",
      "Taking into account previous interactions...",
      "Weighing the surrounding information...",
      "Factoring in the background...",
      "Context is key, so let's see...",
      "Putting your input in perspective...",
      "Considering all angles...",
      "Contextualizing your query...",
      "Seeing how this fits into the conversation...",
      "Context is everything, right?",
      "Taking a step back to see the whole picture.",
      "Considering the context... it's like detective work.",
      "Contextual analysis in progress.",
      "Looking at the conversation history... interesting."
    ],
    // Step 2: Generating draft
    [
      "Generating a draft response...",
      "Sketching out some ideas...",
      "Putting together a preliminary answer...",
      "Crafting an initial reply...",
      "Formulating a rough draft...",
      "Brainstorming possible solutions...",
      "Assembling the first version...",
      "Creating a starting point...",
      "Generating initial thoughts...",
      "Laying the groundwork for an answer...",
      "Drafting a response... hope it's not too drafty!",
      "Generating ideas faster than a caffeinated squirrel.",
      "Putting pen to paper... metaphorically speaking.",
      "Creating a draft that's rough around the edges.",
      "Draft in progress... stay tuned."
    ],
    // Step 3: Refining steps
    [
      "Refining the steps...",
      "Polishing the process...",
      "Fine-tuning the approach...",
      "Improving the method...",
      "Sharpening the strategy...",
      "Enhancing the plan...",
      "Optimizing the workflow...",
      "Smoothing out the details...",
      "Perfecting the sequence...",
      "Making the steps more efficient...",
      "Refining like a fine wine... or a fine AI.",
      "Polishing the steps until they shine.",
      "Making sure the process is smoother than a jazz solo.",
      "Refinement in action.",
      "Tweaking and tuning for perfection."
    ],
    // Step 4: Checking constraints
    [
      "Checking constraints...",
      "Ensuring all rules are followed...",
      "Verifying limitations...",
      "Making sure we're within bounds...",
      "Confirming compliance with guidelines...",
      "Double-checking restrictions...",
      "Assessing the boundaries...",
      "Validating against constraints...",
      "Ensuring feasibility...",
      "Checking for any roadblocks...",
      "Constraints? More like guidelines, am I right? Just kidding, checking them now.",
      "Ensuring we're playing by the rules.",
      "Checking the fine print.",
      "Making sure we don't break any AI laws.",
      "Constraint verification underway."
    ],
    // Step 5: Structuring thoughts
    [
      "Structuring thoughts...",
      "Organizing ideas...",
      "Arranging the response...",
      "Putting thoughts in order...",
      "Building a coherent structure...",
      "Shaping the answer...",
      "Forming a logical flow...",
      "Constructing the narrative...",
      "Assembling the pieces...",
      "Creating a clear framework...",
      "Organizing thoughts like a librarian on a mission.",
      "Structuring the response for maximum clarity.",
      "Putting ideas in their proper places.",
      "Creating a thought architecture.",
      "Arranging the answer like a puzzle."
    ],
    // Step 6: Cross-referencing
    [
      "Cross-referencing information...",
      "Checking against known data...",
      "Comparing with existing knowledge...",
      "Verifying with sources...",
      "Looking for corroboration...",
      "Ensuring consistency...",
      "Matching with relevant facts...",
      "Consulting the knowledge base...",
      "Cross-checking details...",
      "Seeking supporting evidence...",
      "Cross-referencing like a boss.",
      "Checking the facts, because accuracy matters.",
      "Diving into the data pool.",
      "Cross-referencing with the speed of light.",
      "Ensuring everything adds up."
    ],
    // Step 7: Finalizing chain
    [
      "Finalizing the chain of thought...",
      "Putting the finishing touches...",
      "Wrapping up the response...",
      "Completing the answer...",
      "Polishing the final draft...",
      "Ensuring everything ties together...",
      "Making sure it's ready for you...",
      "Double-checking for accuracy...",
      "Preparing to present the solution...",
      "Almost there, just a moment...",
      "Finalizing... almost as satisfying as hitting 'send' on an email.",
      "Putting the final touches, like an artist signing their work.",
      "Wrapping it up with a bow.",
      "Making sure it's perfect before it reaches you.",
      "Final checks complete. Ready to roll."
    ]
  ];