/**
 * lib/sync/messages.ts
 *
 * Channel message schema — versioned discriminated union with Zod validation
 * in development and a cheap discriminant check in production (I5).
 *
 * The Zod schemas are the single source of truth. The production fast-path
 * check is generated by hand from them and unit-tested to accept every shape
 * Zod accepts.
 */

import { z } from "zod";

/** Bumped when the wire format changes incompatibly. Readers drop mismatched versions. */
export const SYNC_PROTOCOL_VERSION = 1;

// ---- Zod schemas (single source of truth) --------------------------------

const ActionMessageSchema = z.object({
    type: z.literal("ACTION"),
    protocolVersion: z.literal(SYNC_PROTOCOL_VERSION),
    identityKey: z.string().min(1),
    sliceName: z.string().min(1),
    version: z.number().int().nonnegative(),
    action: z.object({
        type: z.string().min(1),
        payload: z.unknown().optional(),
    }),
});

const HydrateRequestMessageSchema = z.object({
    type: z.literal("HYDRATE_REQUEST"),
    protocolVersion: z.literal(SYNC_PROTOCOL_VERSION),
    identityKey: z.string().min(1),
    nonce: z.string().min(1),
    slices: z
        .array(
            z.object({
                sliceName: z.string().min(1),
                version: z.number().int().nonnegative(),
            }),
        )
        .min(1),
});

const HydrateResponseMessageSchema = z.object({
    type: z.literal("HYDRATE_RESPONSE"),
    protocolVersion: z.literal(SYNC_PROTOCOL_VERSION),
    identityKey: z.string().min(1),
    nonce: z.string().min(1),
    slices: z.record(z.string(), z.unknown()),
});

export const SyncMessageSchema = z.discriminatedUnion("type", [
    ActionMessageSchema,
    HydrateRequestMessageSchema,
    HydrateResponseMessageSchema,
]);

// ---- Inferred types ------------------------------------------------------

export type ActionMessage = z.infer<typeof ActionMessageSchema>;
export type HydrateRequestMessage = z.infer<typeof HydrateRequestMessageSchema>;
export type HydrateResponseMessage = z.infer<typeof HydrateResponseMessageSchema>;
export type SyncMessage = z.infer<typeof SyncMessageSchema>;

// ---- Production fast-path check -----------------------------------------

const VALID_TYPES = new Set<SyncMessage["type"]>(["ACTION", "HYDRATE_REQUEST", "HYDRATE_RESPONSE"]);

/**
 * Cheap prod-time discriminant + shape check. Must accept every message the
 * Zod schema accepts; must reject messages the Zod schema rejects.
 *
 * Verified by `messages.test.ts` which fuzzes with valid/invalid samples
 * against both paths and asserts their verdicts agree.
 */
export function isProbablyValidSyncMessage(raw: unknown): raw is SyncMessage {
    if (raw === null || typeof raw !== "object") return false;
    const m = raw as Record<string, unknown>;
    if (typeof m.type !== "string" || !VALID_TYPES.has(m.type as SyncMessage["type"])) return false;
    if (m.protocolVersion !== SYNC_PROTOCOL_VERSION) return false;
    if (typeof m.identityKey !== "string" || m.identityKey.length === 0) return false;

    switch (m.type) {
        case "ACTION": {
            if (typeof m.sliceName !== "string" || m.sliceName.length === 0) return false;
            if (typeof m.version !== "number" || !Number.isInteger(m.version) || m.version < 0) return false;
            if (m.action === null || typeof m.action !== "object") return false;
            const action = m.action as Record<string, unknown>;
            return typeof action.type === "string" && action.type.length > 0;
        }
        case "HYDRATE_REQUEST": {
            if (typeof m.nonce !== "string" || m.nonce.length === 0) return false;
            if (!Array.isArray(m.slices) || m.slices.length === 0) return false;
            for (const s of m.slices) {
                if (s === null || typeof s !== "object") return false;
                const slice = s as Record<string, unknown>;
                if (typeof slice.sliceName !== "string" || slice.sliceName.length === 0) return false;
                if (typeof slice.version !== "number" || !Number.isInteger(slice.version) || slice.version < 0) {
                    return false;
                }
            }
            return true;
        }
        case "HYDRATE_RESPONSE": {
            if (typeof m.nonce !== "string" || m.nonce.length === 0) return false;
            return m.slices !== null && typeof m.slices === "object" && !Array.isArray(m.slices);
        }
        default:
            return false;
    }
}

/**
 * Parse an inbound channel payload. In dev, runs the full Zod parser for
 * detailed error reporting. In prod, runs the cheap check.
 *
 * Returns `{ ok: true, message }` or `{ ok: false, reason }`.
 */
export type ParseResult =
    | { ok: true; message: SyncMessage }
    | { ok: false; reason: string; issues?: z.ZodIssue[] };

export function parseSyncMessage(raw: unknown): ParseResult {
    if (process.env.NODE_ENV !== "production") {
        const result = SyncMessageSchema.safeParse(raw);
        if (result.success) return { ok: true, message: result.data };
        return { ok: false, reason: "zod", issues: result.error.issues };
    }
    if (isProbablyValidSyncMessage(raw)) return { ok: true, message: raw };
    return { ok: false, reason: "shape" };
}

// ---- Constructors (used by engine; tested in messages.test.ts) ----------

export function buildActionMessage(
    identityKey: string,
    sliceName: string,
    version: number,
    action: { type: string; payload?: unknown },
): ActionMessage {
    return {
        type: "ACTION",
        protocolVersion: SYNC_PROTOCOL_VERSION,
        identityKey,
        sliceName,
        version,
        action,
    };
}

export function buildHydrateRequest(
    identityKey: string,
    nonce: string,
    slices: readonly { sliceName: string; version: number }[],
): HydrateRequestMessage {
    return {
        type: "HYDRATE_REQUEST",
        protocolVersion: SYNC_PROTOCOL_VERSION,
        identityKey,
        nonce,
        slices: [...slices],
    };
}

export function buildHydrateResponse(
    identityKey: string,
    nonce: string,
    slices: Record<string, unknown>,
): HydrateResponseMessage {
    return {
        type: "HYDRATE_RESPONSE",
        protocolVersion: SYNC_PROTOCOL_VERSION,
        identityKey,
        nonce,
        slices,
    };
}
