import {
    ClipboardCheck,
    Users,
    FlaskConical,
    CalendarRange,
    UserSquare2,
    Files,
    PieChart,
    UserCog,
    Settings2,
    Workflow,
    BarChart,
    Database,
    FileSpreadsheet,
    ServerCog,
    LayoutDashboard,
    Brain,
    GitCompare,
    LineChart,
    TrendingUp,
    Store,
    Target,
    Mail,
    Share2,
    Search,
    Activity,
    UserPlus,
    Megaphone,
    Network,
    MessageSquare,
    Shield,
    Calendar,
    Upload,
    FileText,
    Play,
    Radio,
    Music,
    Video,
    Image,
    Gamepad2,
    Tv,
    Code,
    TestTube,
    Bug,
    Webhook,
    FileCode,
    Zap,
    Gauge,
    Container,
    Heart,
    Flower2,
    Hospital,
    ClipboardList,
    GraduationCap,
    Utensils,
    PenTool,
    MonitorPlay,
    BookOpen,
    Languages,
    CheckSquare,
    Clock,
    FolderKanban,
    ListTodo,
    Wallet,
    Compass,
    MessageCircle,
    Share,
    CalendarCheck,
    UsersRound,
    Laptop,
    StickyNote,
    GitBranch,
    Plane,
    MapPin,
    Sparkles,
    Hotel,
    Shapes,
    Puzzle,
    Lightbulb,
    AppleIcon,
    Wrench,
    MapIcon,
    LucideIcon,
} from "lucide-react";

export interface AppletSubcategory {
    key: string;
    title: string;
    description: string;
    category: string;
    icon: LucideIcon;
    link: string;
    features: string[];
    badges?: string[];
}

export const appletSubcategories: AppletSubcategory[] = [
    // Business & Enterprise Subcategories
    {
        key: "project-management",
        title: "Project Management",
        description: "Comprehensive tools for project planning, tracking, and delivery",
        category: "business-enterprise",
        icon: ClipboardCheck,
        link: "/applets/business-enterprise/project-management",
        features: ["Task management", "Timeline planning", "Resource allocation", "Project tracking", "Team collaboration"],
    },
    {
        key: "team-management",
        title: "Team Management",
        description: "Solutions for team coordination, performance tracking, and collaboration",
        category: "business-enterprise",
        icon: Users,
        link: "/applets/business-enterprise/team-management",
        features: ["Team coordination", "Performance tracking", "Work scheduling", "Team communications", "Role management"],
    },
    {
        key: "resource-planning",
        title: "Resource Planning",
        description: "Tools for managing and optimizing organizational resources",
        category: "business-enterprise",
        icon: CalendarRange,
        link: "/applets/business-enterprise/resource-planning",
        features: ["Resource allocation", "Capacity planning", "Budget management", "Asset tracking", "Resource optimization"],
    },
    {
        key: "crm",
        title: "CRM",
        description: "Customer relationship management solutions for business growth",
        category: "business-enterprise",
        icon: UserSquare2,
        link: "/applets/business-enterprise/crm",
        features: ["Contact management", "Lead tracking", "Sales pipeline", "Customer support", "Relationship analytics"],
    },
    {
        key: "document-management",
        title: "Document Management",
        description: "Systems for organizing, storing, and managing business documents",
        category: "business-enterprise",
        icon: Files,
        link: "/applets/business-enterprise/document-management",
        features: ["File organization", "Version control", "Document sharing", "Access control", "Document workflow"],
    },
    {
        key: "business-intelligence",
        title: "Business Intelligence",
        description: "Tools for data-driven business insights and decision making",
        category: "business-enterprise",
        icon: PieChart,
        link: "/applets/business-enterprise/business-intelligence",
        features: ["Data analysis", "Performance metrics", "Business reporting", "Trend analysis", "Decision support"],
    },
    {
        key: "hr-recruitment",
        title: "HR & Recruitment",
        description: "Solutions for human resources management and talent acquisition",
        category: "business-enterprise",
        icon: UserCog,
        link: "/applets/business-enterprise/hr-recruitment",
        features: ["Recruitment tracking", "Employee management", "Performance review", "Training management", "HR analytics"],
    },
    {
        key: "operations-management",
        title: "Operations Management",
        description: "Tools for managing and optimizing business operations",
        category: "business-enterprise",
        icon: Settings2,
        link: "/applets/business-enterprise/operations-management",
        features: ["Process optimization", "Operations tracking", "Quality management", "Supply chain", "Inventory control"],
    },
    {
        key: "business-process-automation",
        title: "Business Process Automation",
        description: "Solutions for automating repetitive business tasks and workflows",
        category: "business-enterprise",
        icon: Workflow,
        link: "/applets/business-enterprise/business-process-automation",
        features: ["Workflow automation", "Process mapping", "Task automation", "Integration tools", "Performance monitoring"],
    },

    // Data & Analytics Subcategories
    {
        key: "data-visualization",
        title: "Data Visualization",
        description: "Tools for creating visual representations of data and insights",
        category: "data-analytics",
        icon: BarChart,
        link: "/applets/data-analytics/data-visualization",
        features: ["Chart creation", "Interactive dashboards", "Data plotting", "Visual analytics", "Custom visualizations"],
    },
    {
        key: "data-analytics-bi",
        title: "Business Intelligence",
        description: "Advanced analytics tools for business insight and decision making",
        category: "data-analytics",
        icon: PieChart,
        link: "/applets/data-analytics/business-intelligence",
        features: ["Data analysis", "Report generation", "KPI tracking", "Trend analysis", "Predictive modeling"],
    },
    {
        key: "reporting-tools",
        title: "Reporting Tools",
        description: "Solutions for creating and managing data reports and analytics",
        category: "data-analytics",
        icon: FileSpreadsheet,
        link: "/applets/data-analytics/reporting-tools",
        features: ["Report generation", "Data export", "Custom reporting", "Automated reports", "Report scheduling"],
    },
    {
        key: "data-processing",
        title: "Data Processing",
        description: "Tools for processing, cleaning, and transforming data",
        category: "data-analytics",
        icon: ServerCog,
        link: "/applets/data-analytics/data-processing",
        features: ["Data cleaning", "Data transformation", "ETL processes", "Data validation", "Batch processing"],
    },
    {
        key: "analytics-dashboards",
        title: "Analytics Dashboards",
        description: "Interactive dashboards for data visualization and analysis",
        category: "data-analytics",
        icon: LayoutDashboard,
        link: "/applets/data-analytics/analytics-dashboards",
        features: ["Real-time analytics", "Custom dashboards", "Data monitoring", "Performance metrics", "Interactive filters"],
    },
    {
        key: "machine-learning-tools",
        title: "Machine Learning Tools",
        description: "Solutions for implementing and managing machine learning models",
        category: "data-analytics",
        icon: Brain,
        link: "/applets/data-analytics/machine-learning-tools",
        features: ["Model training", "Prediction tools", "Algorithm selection", "Model deployment", "Performance monitoring"],
    },
    {
        key: "data-integration",
        title: "Data Integration",
        description: "Tools for combining and managing data from multiple sources",
        category: "data-analytics",
        icon: GitCompare,
        link: "/applets/data-analytics/data-integration",
        features: ["Data connectors", "Integration pipelines", "Data mapping", "Source management", "Data synchronization"],
    },
    {
        key: "statistical-analysis",
        title: "Statistical Analysis",
        description: "Tools for performing statistical analysis on data sets",
        category: "data-analytics",
        icon: LineChart,
        link: "/applets/data-analytics/statistical-analysis",
        features: ["Statistical testing", "Data correlation", "Regression analysis", "Descriptive statistics", "Statistical modeling"],
    },
    {
        key: "predictive-analytics",
        title: "Predictive Analytics",
        description: "Solutions for forecasting and predictive modeling",
        category: "data-analytics",
        icon: TrendingUp,
        link: "/applets/data-analytics/predictive-analytics",
        features: ["Forecasting", "Trend analysis", "Predictive modeling", "Risk assessment", "Pattern recognition"],
    },
    // Commerce & Marketing Subcategories
    {
        key: "ecommerce-platforms",
        title: "E-commerce Platforms",
        description: "Complete solutions for online store management and e-commerce operations",
        category: "commerce-marketing",
        icon: Store,
        link: "/applets/commerce-marketing/ecommerce-platforms",
        features: ["Product management", "Shopping cart", "Payment processing", "Inventory management", "Order fulfillment"],
    },
    {
        key: "digital-marketing",
        title: "Digital Marketing",
        description: "Tools for planning and executing digital marketing campaigns",
        category: "commerce-marketing",
        icon: Target,
        link: "/applets/commerce-marketing/digital-marketing",
        features: ["Campaign management", "Marketing automation", "Lead generation", "Content marketing", "Performance tracking"],
    },
    {
        key: "email-marketing",
        title: "Email Marketing",
        description: "Solutions for email campaign management and automation",
        category: "commerce-marketing",
        icon: Mail,
        link: "/applets/commerce-marketing/email-marketing",
        features: ["Email campaigns", "Newsletter management", "Template design", "Audience segmentation", "Analytics tracking"],
    },
    {
        key: "social-media-marketing",
        title: "Social Media Marketing",
        description: "Tools for managing and optimizing social media marketing efforts",
        category: "commerce-marketing",
        icon: Share2,
        link: "/applets/commerce-marketing/social-media-marketing",
        features: ["Content scheduling", "Social analytics", "Engagement tracking", "Campaign management", "Cross-platform posting"],
    },
    {
        key: "seo-tools",
        title: "SEO Tools",
        description: "Tools for improving search engine visibility and ranking",
        category: "commerce-marketing",
        icon: Search,
        link: "/applets/commerce-marketing/seo-tools",
        features: ["Keyword research", "SEO analysis", "Rank tracking", "Content optimization", "Backlink management"],
    },
    {
        key: "marketing-analytics",
        title: "Marketing Analytics",
        description: "Solutions for analyzing and optimizing marketing performance",
        category: "commerce-marketing",
        icon: Activity,
        link: "/applets/commerce-marketing/marketing-analytics",
        features: ["Performance metrics", "ROI tracking", "Campaign analytics", "Conversion tracking", "Customer insights"],
    },
    {
        key: "customer-engagement",
        title: "Customer Engagement",
        description: "Tools for managing and improving customer interactions",
        category: "commerce-marketing",
        icon: UserPlus,
        link: "/applets/commerce-marketing/customer-engagement",
        features: ["Customer feedback", "Loyalty programs", "Engagement tracking", "Customer support", "Personalization"],
    },
    {
        key: "marketplace-management",
        title: "Marketplace Management",
        description: "Solutions for managing online marketplace operations",
        category: "commerce-marketing",
        icon: Store,
        link: "/applets/commerce-marketing/marketplace-management",
        features: ["Vendor management", "Product listings", "Order processing", "Marketplace analytics", "Commission tracking"],
    },
    {
        key: "advertising-tools",
        title: "Advertising Tools",
        description: "Tools for managing and optimizing advertising campaigns",
        category: "commerce-marketing",
        icon: Megaphone,
        link: "/applets/commerce-marketing/advertising-tools",
        features: ["Ad campaign management", "Budget optimization", "Ad performance tracking", "Audience targeting", "A/B testing"],
    },
    {
        key: "sales-management",
        title: "Sales Management",
        description: "Solutions for managing and optimizing sales processes",
        category: "commerce-marketing",
        icon: TrendingUp,
        link: "/applets/commerce-marketing/sales-management",
        features: ["Sales pipeline", "Lead management", "Sales analytics", "Quote management", "Sales forecasting"],
    },

    // Social & Community Subcategories
    {
        key: "community-management",
        title: "Community Management",
        description: "Tools for managing online communities and user engagement",
        category: "social-community",
        icon: Users,
        link: "/applets/social-community/community-management",
        features: ["Member management", "Community engagement", "Content moderation", "Analytics tracking", "Community insights"],
    },
    {
        key: "social-networks",
        title: "Social Networks",
        description: "Platforms for building and managing social networking communities",
        category: "social-community",
        icon: Network,
        link: "/applets/social-community/social-networks",
        features: ["User profiles", "Social connections", "Activity feeds", "Privacy controls", "Content sharing"],
    },
    {
        key: "forums-discussion",
        title: "Forums & Discussion",
        description: "Solutions for hosting and managing online discussion forums",
        category: "social-community",
        icon: MessageSquare,
        link: "/applets/social-community/forums-discussion",
        features: ["Thread management", "User discussions", "Category organization", "Moderation tools", "Search functionality"],
    },
    {
        key: "member-management",
        title: "Member Management",
        description: "Tools for managing community members and user accounts",
        category: "social-community",
        icon: UserCog,
        link: "/applets/social-community/member-management",
        features: ["User profiles", "Access control", "Member directory", "Role management", "Member analytics"],
    },
    {
        key: "content-moderation",
        title: "Content Moderation",
        description: "Solutions for moderating and managing community content",
        category: "social-community",
        icon: Shield,
        link: "/applets/social-community/content-moderation",
        features: ["Content filtering", "Automated moderation", "Report handling", "Policy enforcement", "Moderation queue"],
    },
    {
        key: "event-management",
        title: "Event Management",
        description: "Tools for organizing and managing community events",
        category: "social-community",
        icon: Calendar,
        link: "/applets/social-community/event-management",
        features: ["Event scheduling", "Registration management", "Attendee tracking", "Event analytics", "Virtual events"],
    },
    {
        key: "social-media-integration",
        title: "Social Media Integration",
        description: "Solutions for integrating with social media platforms",
        category: "social-community",
        icon: Share2,
        link: "/applets/social-community/social-media-integration",
        features: ["Platform connections", "Content sharing", "Social login", "Cross-posting", "Social analytics"],
    },
    {
        key: "user-generated-content",
        title: "User Generated Content",
        description: "Tools for managing and leveraging user-created content",
        category: "social-community",
        icon: Upload,
        link: "/applets/social-community/user-generated-content",
        features: ["Content submission", "Curation tools", "Rights management", "Content analytics", "Community engagement"],
    },

    // Media & Entertainment Subcategories
    {
        key: "content-management",
        title: "Content Management",
        description: "Solutions for managing digital content and media assets",
        category: "media-entertainment",
        icon: FileText,
        link: "/applets/media-entertainment/content-management",
        features: ["Content organization", "Workflow management", "Version control", "Content scheduling", "Distribution tools"],
    },
    {
        key: "media-players",
        title: "Media Players",
        description: "Tools for playing and managing media content",
        category: "media-entertainment",
        icon: Play,
        link: "/applets/media-entertainment/media-players",
        features: ["Playback controls", "Format support", "Playlist management", "Streaming capability", "Media library"],
    },
    {
        key: "streaming-tools",
        title: "Streaming Tools",
        description: "Solutions for live streaming and content delivery",
        category: "media-entertainment",
        icon: Radio,
        link: "/applets/media-entertainment/streaming-tools",
        features: ["Live streaming", "Stream management", "Chat integration", "Broadcasting tools", "Analytics tracking"],
    },
    {
        key: "audio-processing",
        title: "Audio Processing",
        description: "Tools for audio editing and processing",
        category: "media-entertainment",
        icon: Music,
        link: "/applets/media-entertainment/audio-processing",
        features: ["Audio editing", "Sound effects", "Audio mixing", "Format conversion", "Quality enhancement"],
    },
    {
        key: "video-processing",
        title: "Video Processing",
        description: "Solutions for video editing and processing",
        category: "media-entertainment",
        icon: Video,
        link: "/applets/media-entertainment/video-processing",
        features: ["Video editing", "Effects processing", "Format conversion", "Video compression", "Color correction"],
    },
    {
        key: "image-editing",
        title: "Image Editing",
        description: "Tools for image editing and manipulation",
        category: "media-entertainment",
        icon: Image,
        link: "/applets/media-entertainment/image-editing",
        features: ["Photo editing", "Image effects", "Batch processing", "Format conversion", "Asset management"],
    },
    {
        key: "digital-asset-management",
        title: "Digital Asset Management",
        description: "Solutions for managing digital media assets",
        category: "media-entertainment",
        icon: Database,
        link: "/applets/media-entertainment/digital-asset-management",
        features: ["Asset organization", "Metadata management", "Asset distribution", "Version control", "Rights management"],
    },
    {
        key: "gaming-interactive",
        title: "Gaming & Interactive",
        description: "Tools for gaming and interactive media experiences",
        category: "media-entertainment",
        icon: Gamepad2,
        link: "/applets/media-entertainment/gaming-interactive",
        features: ["Game development", "Interactive content", "User engagement", "Performance tracking", "Multiplayer support"],
    },
    {
        key: "entertainment-platforms",
        title: "Entertainment Platforms",
        description: "Platforms for delivering entertainment content",
        category: "media-entertainment",
        icon: Tv,
        link: "/applets/media-entertainment/entertainment-platforms",
        features: ["Content delivery", "User management", "Content discovery", "Recommendation engine", "Analytics tracking"],
    },
    // Developer Tools & Utilities Subcategories
    {
        key: "code-editors",
        title: "Code Editors",
        description: "Advanced text editors and IDEs for software development",
        category: "developer-tools-utilities",
        icon: Code,
        link: "/applets/developer-tools-utilities/code-editors",
        features: ["Syntax highlighting", "Code completion", "File management", "Extension support", "Version control integration"],
    },
    {
        key: "testing-tools",
        title: "Testing Tools",
        description: "Tools for software testing and quality assurance",
        category: "developer-tools-utilities",
        icon: TestTube,
        link: "/applets/developer-tools-utilities/testing-tools",
        features: ["Unit testing", "Integration testing", "Test automation", "Coverage reporting", "Performance testing"],
    },
    {
        key: "debugging-tools",
        title: "Debugging Tools",
        description: "Solutions for identifying and fixing software issues",
        category: "developer-tools-utilities",
        icon: Bug,
        link: "/applets/developer-tools-utilities/debugging-tools",
        features: ["Error tracking", "Log analysis", "Breakpoint management", "Variable inspection", "Memory profiling"],
    },
    {
        key: "api-development",
        title: "API Development",
        description: "Tools for building and testing APIs",
        category: "developer-tools-utilities",
        icon: Webhook,
        link: "/applets/developer-tools-utilities/api-development",
        features: ["API design", "Documentation generation", "Request testing", "Authentication handling", "Performance monitoring"],
    },
    {
        key: "development-workflows",
        title: "Development Workflows",
        description: "Solutions for managing development processes and workflows",
        category: "developer-tools-utilities",
        icon: Workflow,
        link: "/applets/developer-tools-utilities/development-workflows",
        features: ["CI/CD pipelines", "Build automation", "Deployment management", "Environment configuration", "Task automation"],
    },
    {
        key: "version-control",
        title: "Version Control",
        description: "Tools for managing code versions and collaboration",
        category: "developer-tools-utilities",
        icon: GitBranch,
        link: "/applets/developer-tools-utilities/version-control",
        features: ["Code versioning", "Branch management", "Merge handling", "Collaboration tools", "History tracking"],
    },
    {
        key: "documentation-tools",
        title: "Documentation Tools",
        description: "Solutions for creating and managing technical documentation",
        category: "developer-tools-utilities",
        icon: FileCode,
        link: "/applets/developer-tools-utilities/documentation-tools",
        features: ["Documentation generation", "API documentation", "Version control", "Search functionality", "Collaboration tools"],
    },
    {
        key: "code-generation",
        title: "Code Generation",
        description: "Tools for automated code generation and scaffolding",
        category: "developer-tools-utilities",
        icon: Zap,
        link: "/applets/developer-tools-utilities/code-generation",
        features: [
            "Template generation",
            "Boilerplate creation",
            "Code scaffolding",
            "API client generation",
            "Database schema generation",
        ],
    },
    {
        key: "performance-monitoring",
        title: "Performance Monitoring",
        description: "Solutions for monitoring application performance",
        category: "developer-tools-utilities",
        icon: Gauge,
        link: "/applets/developer-tools-utilities/performance-monitoring",
        features: ["Resource monitoring", "Performance metrics", "Error tracking", "Real-time analytics", "Alert management"],
    },
    {
        key: "devops-tools",
        title: "DevOps Tools",
        description: "Tools for DevOps practices and infrastructure management",
        category: "developer-tools-utilities",
        icon: Container,
        link: "/applets/developer-tools-utilities/devops-tools",
        features: [
            "Infrastructure as code",
            "Container management",
            "Configuration management",
            "Monitoring and logging",
            "Deployment automation",
        ],
    },

    // Health & Wellness Subcategories
    {
        key: "fitness-tracking",
        title: "Fitness Tracking",
        description: "Tools for tracking physical activity and fitness progress",
        category: "health-wellness",
        icon: Activity,
        link: "/applets/health-wellness/fitness-tracking",
        features: ["Activity monitoring", "Workout planning", "Progress tracking", "Goal setting", "Performance analytics"],
    },
    {
        key: "health-monitoring",
        title: "Health Monitoring",
        description: "Solutions for monitoring health metrics and vital signs",
        category: "health-wellness",
        icon: Heart,
        link: "/applets/health-wellness/health-monitoring",
        features: ["Vital sign tracking", "Health metrics", "Sleep monitoring", "Symptom tracking", "Health analytics"],
    },
    {
        key: "mental-health",
        title: "Mental Health",
        description: "Tools for mental health support and management",
        category: "health-wellness",
        icon: Brain,
        link: "/applets/health-wellness/mental-health",
        features: ["Mood tracking", "Therapy support", "Stress management", "Progress monitoring", "Resource library"],
    },
    {
        key: "meditation-mindfulness",
        title: "Meditation & Mindfulness",
        description: "Solutions for meditation and mindfulness practices",
        category: "health-wellness",
        icon: Flower2,
        link: "/applets/health-wellness/meditation-mindfulness",
        features: ["Guided meditation", "Breathing exercises", "Progress tracking", "Session planning", "Mindfulness exercises"],
    },
    {
        key: "nutrition-planning",
        title: "Nutrition Planning",
        description: "Tools for meal planning and nutrition tracking",
        category: "health-wellness",
        icon: Utensils,
        link: "/applets/health-wellness/nutrition-planning",
        features: ["Meal planning", "Nutritional tracking", "Recipe management", "Diet analysis", "Goal setting"],
    },
    {
        key: "healthcare-management",
        title: "Healthcare Management",
        description: "Solutions for managing healthcare and medical needs",
        category: "health-wellness",
        icon: Hospital,
        link: "/applets/health-wellness/healthcare-management",
        features: ["Appointment scheduling", "Medication tracking", "Provider management", "Health records", "Treatment planning"],
    },
    {
        key: "medical-records",
        title: "Medical Records",
        description: "Tools for managing personal medical records and history",
        category: "health-wellness",
        icon: ClipboardList,
        link: "/applets/health-wellness/medical-records",
        features: ["Record management", "Document storage", "History tracking", "Provider sharing", "Security controls"],
    },
    {
        key: "wellness-education",
        title: "Wellness Education",
        description: "Educational resources for health and wellness",
        category: "health-wellness",
        icon: GraduationCap,
        link: "/applets/health-wellness/wellness-education",
        features: ["Health information", "Educational content", "Resource library", "Learning tools", "Progress tracking"],
    },
    {
        key: "telemedicine",
        title: "Telemedicine",
        description: "Solutions for remote healthcare and medical consultations",
        category: "health-wellness",
        icon: Video,
        link: "/applets/health-wellness/telemedicine",
        features: ["Virtual consultations", "Appointment scheduling", "Medical chat", "Prescription management", "Health records access"],
    },
    // Education & Learning Subcategories
    {
        key: "learning-management",
        title: "Learning Management",
        description: "Comprehensive systems for managing educational programs and courses",
        category: "education-learning",
        icon: BookOpen,
        link: "/applets/education-learning/learning-management",
        features: ["Course management", "Student tracking", "Progress monitoring", "Resource management", "Learning analytics"],
    },
    {
        key: "course-creation",
        title: "Course Creation",
        description: "Tools for developing and structuring educational content",
        category: "education-learning",
        icon: PenTool,
        link: "/applets/education-learning/course-creation",
        features: ["Content authoring", "Curriculum design", "Assessment creation", "Media integration", "Course templates"],
    },
    {
        key: "assessment-tools",
        title: "Assessment Tools",
        description: "Solutions for creating and managing educational assessments",
        category: "education-learning",
        icon: ClipboardCheck,
        link: "/applets/education-learning/assessment-tools",
        features: ["Quiz creation", "Grading tools", "Performance tracking", "Results analysis", "Feedback management"],
    },
    {
        key: "student-management",
        title: "Student Management",
        description: "Tools for managing student information and progress",
        category: "education-learning",
        icon: Users,
        link: "/applets/education-learning/student-management",
        features: ["Student profiles", "Attendance tracking", "Progress monitoring", "Communication tools", "Performance analytics"],
    },
    {
        key: "virtual-classrooms",
        title: "Virtual Classrooms",
        description: "Platforms for online teaching and learning environments",
        category: "education-learning",
        icon: MonitorPlay,
        link: "/applets/education-learning/virtual-classrooms",
        features: ["Live sessions", "Interactive tools", "Resource sharing", "Student engagement", "Recording capabilities"],
    },
    {
        key: "educational-content",
        title: "Educational Content",
        description: "Resources and tools for educational content management",
        category: "education-learning",
        icon: BookOpen,
        link: "/applets/education-learning/educational-content",
        features: ["Content library", "Resource management", "Media integration", "Content organization", "Access control"],
    },
    {
        key: "training-development",
        title: "Training & Development",
        description: "Solutions for professional training and skill development",
        category: "education-learning",
        icon: GraduationCap,
        link: "/applets/education-learning/training-development",
        features: ["Training programs", "Skill assessment", "Progress tracking", "Certification management", "Learning paths"],
    },
    {
        key: "knowledge-management",
        title: "Knowledge Management",
        description: "Tools for organizing and sharing organizational knowledge",
        category: "education-learning",
        icon: Database,
        link: "/applets/education-learning/knowledge-management",
        features: ["Knowledge base", "Document management", "Search functionality", "Collaboration tools", "Version control"],
    },
    {
        key: "language-learning",
        title: "Language Learning",
        description: "Platforms for language education and practice",
        category: "education-learning",
        icon: Languages,
        link: "/applets/education-learning/language-learning",
        features: ["Language courses", "Practice exercises", "Progress tracking", "Pronunciation tools", "Vocabulary building"],
    },

    // Personal Tools & Productivity Subcategories
    {
        key: "task-management",
        title: "Task Management",
        description: "Tools for organizing and tracking personal tasks",
        category: "personal-tools-productivity",
        icon: CheckSquare,
        link: "/applets/personal-tools-productivity/task-management",
        features: ["Task organization", "Priority setting", "Progress tracking", "Deadline management", "Task collaboration"],
    },
    {
        key: "time-tracking",
        title: "Time Tracking",
        description: "Solutions for monitoring and managing time usage",
        category: "personal-tools-productivity",
        icon: Clock,
        link: "/applets/personal-tools-productivity/time-tracking",
        features: ["Time logging", "Activity tracking", "Productivity analysis", "Report generation", "Project timing"],
    },
    {
        key: "note-taking",
        title: "Note Taking",
        description: "Tools for capturing and organizing personal notes",
        category: "personal-tools-productivity",
        icon: StickyNote,
        link: "/applets/personal-tools-productivity/note-taking",
        features: ["Note organization", "Rich text editing", "Media integration", "Search functionality", "Collaboration options"],
    },
    {
        key: "personal-organization",
        title: "Personal Organization",
        description: "Solutions for personal information management",
        category: "personal-tools-productivity",
        icon: FolderKanban,
        link: "/applets/personal-tools-productivity/personal-organization",
        features: ["Information organization", "File management", "Category system", "Tag management", "Search capabilities"],
    },
    {
        key: "goal-setting",
        title: "Goal Setting",
        description: "Tools for setting and tracking personal goals",
        category: "personal-tools-productivity",
        icon: Target,
        link: "/applets/personal-tools-productivity/goal-setting",
        features: ["Goal definition", "Progress tracking", "Milestone setting", "Achievement monitoring", "Goal analytics"],
    },
    {
        key: "habit-tracking",
        title: "Habit Tracking",
        description: "Solutions for developing and monitoring personal habits",
        category: "personal-tools-productivity",
        icon: ListTodo,
        link: "/applets/personal-tools-productivity/habit-tracking",
        features: ["Habit monitoring", "Streak tracking", "Progress analysis", "Reminder system", "Performance insights"],
    },
    {
        key: "calendar-management",
        title: "Calendar Management",
        description: "Tools for managing personal schedules and events",
        category: "personal-tools-productivity",
        icon: Calendar,
        link: "/applets/personal-tools-productivity/calendar-management",
        features: ["Event scheduling", "Calendar sharing", "Reminder system", "Time blocking", "Integration options"],
    },
    {
        key: "personal-finance",
        title: "Personal Finance",
        description: "Solutions for managing personal finances and budgets",
        category: "personal-tools-productivity",
        icon: Wallet,
        link: "/applets/personal-tools-productivity/personal-finance",
        features: ["Budget tracking", "Expense management", "Financial planning", "Investment tracking", "Report generation"],
    },
    {
        key: "life-planning",
        title: "Life Planning",
        description: "Tools for long-term personal planning and development",
        category: "personal-tools-productivity",
        icon: Compass,
        link: "/applets/personal-tools-productivity/life-planning",
        features: ["Life goals", "Career planning", "Personal development", "Progress tracking", "Action planning"],
    },

    // Communication & Collaboration Subcategories
    {
        key: "team-chat",
        title: "Team Chat",
        description: "Platforms for team communication and messaging",
        category: "communication-collaboration",
        icon: MessageCircle,
        link: "/applets/communication-collaboration/team-chat",
        features: ["Real-time messaging", "Channel management", "File sharing", "Integration options", "Search functionality"],
    },
    {
        key: "video-conferencing",
        title: "Video Conferencing",
        description: "Solutions for virtual meetings and video calls",
        category: "communication-collaboration",
        icon: Video,
        link: "/applets/communication-collaboration/video-conferencing",
        features: ["Video calls", "Screen sharing", "Meeting recording", "Chat features", "Virtual backgrounds"],
    },
    {
        key: "file-sharing",
        title: "File Sharing",
        description: "Tools for sharing and managing team files",
        category: "communication-collaboration",
        icon: Share,
        link: "/applets/communication-collaboration/file-sharing",
        features: ["File upload", "Access control", "Version control", "Collaboration tools", "Storage management"],
    },
    {
        key: "project-collaboration",
        title: "Project Collaboration",
        description: "Platforms for team project coordination",
        category: "communication-collaboration",
        icon: Users,
        link: "/applets/communication-collaboration/project-collaboration",
        features: ["Task management", "Team coordination", "Resource sharing", "Progress tracking", "Timeline management"],
    },
    {
        key: "document-collaboration",
        title: "Document Collaboration",
        description: "Solutions for collaborative document editing",
        category: "communication-collaboration",
        icon: FileText,
        link: "/applets/communication-collaboration/document-collaboration",
        features: ["Real-time editing", "Version control", "Comment system", "Access management", "Change tracking"],
    },
    {
        key: "meeting-management",
        title: "Meeting Management",
        description: "Tools for organizing and managing team meetings",
        category: "communication-collaboration",
        icon: CalendarCheck,
        link: "/applets/communication-collaboration/meeting-management",
        features: ["Meeting scheduling", "Agenda management", "Note taking", "Action items", "Follow-up tracking"],
    },
    {
        key: "email-messaging",
        title: "Email & Messaging",
        description: "Platforms for email and message management",
        category: "communication-collaboration",
        icon: Mail,
        link: "/applets/communication-collaboration/email-messaging",
        features: ["Email management", "Message organization", "Contact management", "Template system", "Integration options"],
    },
    {
        key: "remote-work-tools",
        title: "Remote Work Tools",
        description: "Solutions for facilitating remote work",
        category: "communication-collaboration",
        icon: Laptop,
        link: "/applets/communication-collaboration/remote-work-tools",
        features: ["Virtual workspace", "Remote access", "Collaboration tools", "Time zone management", "Team coordination"],
    },
    {
        key: "team-coordination",
        title: "Team Coordination",
        description: "Tools for coordinating team activities and workflows",
        category: "communication-collaboration",
        icon: UsersRound,
        link: "/applets/communication-collaboration/team-coordination",
        features: ["Task assignment", "Schedule management", "Resource allocation", "Progress tracking", "Team communication"],
    },

    // Travel & Lifestyle Subcategories
    {
        key: "travel-planning",
        title: "Travel Planning",
        description: "Tools for planning and organizing travel itineraries",
        category: "travel-lifestyle",
        icon: Plane,
        link: "/applets/travel-lifestyle/travel-planning",
        features: ["Itinerary planning", "Travel scheduling", "Budget management", "Destination research", "Trip optimization"],
    },
    {
        key: "booking-systems",
        title: "Booking Systems",
        description: "Solutions for travel and accommodation bookings",
        category: "travel-lifestyle",
        icon: CalendarRange,
        link: "/applets/travel-lifestyle/booking-systems",
        features: [
            "Reservation management",
            "Availability checking",
            "Payment processing",
            "Booking confirmation",
            "Cancellation handling",
        ],
    },
    {
        key: "trip-organization",
        title: "Trip Organization",
        description: "Tools for organizing and managing travel details",
        category: "travel-lifestyle",
        icon: FolderKanban,
        link: "/applets/travel-lifestyle/trip-organization",
        features: ["Document management", "Travel checklist", "Expense tracking", "Activity planning", "Travel timeline"],
    },
    {
        key: "location-services",
        title: "Location Services",
        description: "Solutions for location-based information and navigation",
        category: "travel-lifestyle",
        icon: MapPin,
        link: "/applets/travel-lifestyle/location-services",
        features: ["Location tracking", "Navigation tools", "Point of interest", "Local information", "Map integration"],
    },
    {
        key: "lifestyle-management",
        title: "Lifestyle Management",
        description: "Tools for managing personal lifestyle and activities",
        category: "travel-lifestyle",
        icon: Sparkles,
        link: "/applets/travel-lifestyle/lifestyle-management",
        features: ["Activity planning", "Lifestyle tracking", "Preference management", "Experience curation", "Personal scheduling"],
    },
    {
        key: "experience-planning",
        title: "Experience Planning",
        description: "Solutions for planning and organizing experiences",
        category: "travel-lifestyle",
        icon: Target,
        link: "/applets/travel-lifestyle/experience-planning",
        features: ["Activity booking", "Experience curation", "Itinerary planning", "Review management", "Recommendation engine"],
    },
    {
        key: "travel-guides",
        title: "Travel Guides",
        description: "Digital guides and resources for travelers",
        category: "travel-lifestyle",
        icon: MapIcon,
        link: "/applets/travel-lifestyle/travel-guides",
        features: ["Destination guides", "Local information", "Travel tips", "Cultural insights", "Recommendation system"],
    },
    {
        key: "accommodation-management",
        title: "Accommodation Management",
        description: "Tools for managing accommodation bookings and stays",
        category: "travel-lifestyle",
        icon: Hotel,
        link: "/applets/travel-lifestyle/accommodation-management",
        features: ["Booking management", "Property information", "Stay organization", "Review system", "Payment handling"],
    },
    {
        key: "local-discovery",
        title: "Local Discovery",
        description: "Solutions for discovering local attractions and activities",
        category: "travel-lifestyle",
        icon: Compass,
        link: "/applets/travel-lifestyle/local-discovery",
        features: ["Local exploration", "Activity discovery", "Event finding", "Local recommendations", "Cultural experiences"],
    },

    // Other & Miscellaneous Subcategories
    {
        key: "experimental",
        title: "Experimental",
        description: "Innovative and experimental applications",
        category: "other-miscellaneous",
        icon: FlaskConical,
        link: "/applets/other-miscellaneous/experimental",
        features: ["Innovation testing", "New technologies", "Prototype features", "Experimental UI", "Beta testing"],
    },
    {
        key: "multi-purpose",
        title: "Multi-purpose",
        description: "Versatile tools serving multiple functions",
        category: "other-miscellaneous",
        icon: Shapes,
        link: "/applets/other-miscellaneous/multi-purpose",
        features: ["Multiple functions", "Flexible usage", "Customization options", "Integration capabilities", "Adaptable features"],
    },
    {
        key: "unique-solutions",
        title: "Unique Solutions",
        description: "Specialized tools for unique use cases",
        category: "other-miscellaneous",
        icon: Puzzle,
        link: "/applets/other-miscellaneous/unique-solutions",
        features: ["Custom solutions", "Specialized features", "Unique workflows", "Niche applications", "Custom integration"],
    },
    {
        key: "emerging-technologies",
        title: "Emerging Technologies",
        description: "Applications leveraging cutting-edge technologies",
        category: "other-miscellaneous",
        icon: Lightbulb,
        link: "/applets/other-miscellaneous/emerging-technologies",
        features: ["New technologies", "Innovation focus", "Modern solutions", "Technology testing", "Future-ready"],
    },
    {
        key: "specialized-tools",
        title: "Specialized Tools",
        description: "Tools designed for specific specialized needs",
        category: "other-miscellaneous",
        icon: Wrench,
        link: "/applets/other-miscellaneous/specialized-tools",
        features: ["Specialized functions", "Focused solutions", "Expert tools", "Professional features", "Industry-specific"],
    },
    {
        key: "cross-category-applications",
        title: "Cross-category Applications",
        description: "Applications spanning multiple categories",
        category: "other-miscellaneous",
        icon: AppleIcon,
        link: "/applets/other-miscellaneous/cross-category-applications",
        features: ["Multi-category use", "Cross-functional", "Versatile applications", "Integrated solutions", "Broad compatibility"],
    },
];

export const getSubcategoriesByCategory = (categoryKey: string): AppletSubcategory[] => {
    return appletSubcategories.filter((subcategory) => subcategory.category === categoryKey);
};

export const getSubcategoryByKey = (key: string): AppletSubcategory | undefined => {
    return appletSubcategories.find((subcategory) => subcategory.key === key);
};

export const getSubcategoryList = (categoryKey: string): Array<{ title: string; link: string }> => {
    return appletSubcategories.filter((subcategory) => subcategory.category === categoryKey).map(({ title, link }) => ({ title, link }));
};
