
import { UserPreferences } from './userPreferencesSlice';

export const defaultUserPreferences: UserPreferences = {
    display: {
        darkMode: true,
        theme: 'default',
        dashboardLayout: 'default',
        sidebarLayout: 'default',
        headerLayout: 'default',
        windowMode: 'default',
    },
    prompts: {
        showSettingsOnMainPage: false,
        defaultModel: '548126f2-714a-4562-9001-0c31cbeea375', // GPT-4.1 Mini
        defaultTemperature: 1.0,
        alwaysIncludeInternalWebSearch: true,
        includeThinkingInAutoPrompts: 'none',
        submitOnEnter: true,
        autoClearResponsesInEditMode: true,
    },
    voice: {
        voice: '',
        language: 'en',
        speed: 1,
        emotion: '',
        microphone: false,
        speaker: false,
        wakeWord: 'Hey Matrix',
    },
    textToSpeech: {
        preferredVoice: 'Cheyenne-PlayAI',
        autoPlay: false,
        processMarkdown: true,
    },
    assistant: {
        alwaysActive: false,
        alwaysWatching: false,
        useAudio: false,
        name: 'Assistant',
        isPersonal: false,
        memoryLevel: 0,
        preferredProvider: 'default',
        preferredModel: 'default',
    },
    email: {
        primaryEmail: '',
        notificationsEnabled: true,
        autoReply: false,
        signature: '',
        preferredEmailClient: 'default',
    },
    videoConference: {
        background: 'default',
        filter: 'default',
        defaultCamera: 'default',
        defaultMicrophone: 'default',
        defaultSpeaker: 'default',
        defaultMeetingType: 'default',
        defaultLayout: 'default',
        defaultNotesType: 'default',
        AiActivityLevel: 'default',
    },
    photoEditing: {
        defaultFilter: 'none',
        autoEnhance: false,
        resolution: '1080p',
        defaultAspectRatio: '16:9',
        watermarkEnabled: false,
    },
    imageGeneration: {
        defaultModel: 'standard',
        resolution: '1080p',
        style: 'realistic',
        useAiEnhancements: true,
        colorPalette: 'vibrant',
    },
    textGeneration: {
        defaultModel: 'GPT-4o',
        tone: 'neutral',
        creativityLevel: 'medium',
        language: 'en',
        plagiarismCheckEnabled: true,
    },
    coding: {
        preferredLanguage: 'javascript',
        preferredTheme: 'dark',
        gitIntegration: true,
        instancePreference: 'local',
        codeCompletion: true,
        codeAnalysis: true,
        codeFormatting: true,
        aiActivityLevel: 'medium',
        voiceAssistance: false,
    },
    flashcard: {
        fontSize: 16,
        educationLevel: 'highSchool',
        flashcardDifficultyAdjustment: 5,
        aiDifficultyAdjustment: 5,
        language: 'en',
        defaultFlashcardMode: 'selfStudy',
        targetScore: 80,
        primaryAudioVoice: 'default',
        primaryTutorPersona: 'default',
    },
    playground: {
        lastRecipeId: '',
        preferredProvider: '',
        preferredModel: '',
        preferredEndpoint: '',
    },
    aiModels: {
        defaultModel: '548126f2-714a-4562-9001-0c31cbeea375', // GPT-4.1 Mini
        activeModels: [],
        inactiveModels: [],
        newModels: [],
    },
    system: {
        viewedAnnouncements: [],
        feedbackFeatureViewCount: 0,
    },
    messaging: {
        notificationSoundEnabled: true,
        notificationVolume: 50,
        showDesktopNotifications: false,
    },
}; 