/**
 * Agent definition and conversation message types — AI Matrx API
 *
 * This file answers: "what is the full structure of a message at every
 * point in an agent's lifecycle?"
 *
 * There are two distinct contexts where messages appear:
 *
 *   1. AGENT DEFINITION  — the messages[] array authored by the agent creator.
 *      These are the "priming" turns baked into the agent's stored definition.
 *      Only user and assistant roles are valid here. No tool calls, no thinking.
 *
 *   2. RUNTIME CONVERSATION — the live messages accumulated during an actual
 *      conversation. Includes all roles and all block types, including
 *      tool calls, tool results, and thinking (extended reasoning).
 *
 * For the user_input field on the request body (what the React app sends),
 * see message-types.ts which covers that surface area exclusively.
 *
 * ---
 * RELATIONSHIP TO message-types.ts
 * ─────────────────────────────────
 * ContentBlock (from message-types.ts) is the set of blocks a user can send.
 * ConversationBlock (this file) is the full superset that can appear in any
 * message in the database or in a streaming response. Every ContentBlock is
 * also a valid ConversationBlock, but not vice versa.
 *
 *   ContentBlock  ⊂  ConversationBlock
 */

// Re-export everything from message-types so callers only need one import.
export type {
  TextBlock,
  ImageBlock,
  AudioBlock,
  VideoBlock,
  YouTubeVideoBlock,
  DocumentBlock,
  WebpageInputBlock,
  NotesInputBlock,
  TaskInputBlock,
  TableInputBlock,
  ListInputBlock,
  DataInputBlock,
  TableBookmark,
  FullTableBookmark,
  TableColumnBookmark,
  TableRowBookmark,
  TableCellBookmark,
  ListBookmark,
  FullListBookmark,
  ListGroupBookmark,
  ListItemBookmark,
  DataRef,
  DbRecordRef,
  DbQueryRef,
  DbFieldRef,
  DataRefTable,
  ContentBlock,
  UserInput,
} from "./message-types";

import type {
  TextBlock,
  ImageBlock,
  AudioBlock,
  VideoBlock,
  YouTubeVideoBlock,
  DocumentBlock,
  WebpageInputBlock,
  NotesInputBlock,
  TaskInputBlock,
  TableInputBlock,
  ListInputBlock,
  DataInputBlock,
  ContentBlock,
} from "./message-types";

// =============================================================================
// SECTION 1 — Roles
// =============================================================================

/**
 * All possible message roles in the system.
 *
 *   user       — A turn authored by the human (or the client app on their behalf).
 *   assistant  — A turn generated by the AI model.
 *   tool       — A turn containing the results of tool executions (fed back to
 *                the model as context). Carries ToolResultBlock content.
 *   system     — System-level instructions. NEVER stored in messages[].
 *                Lives in the separate system_instruction field of the config.
 *                Included here for completeness, but you will never see it in
 *                a stored message.
 *   developer  — Like system, but for developer-level instructions on OpenAI.
 *                Same rule: never in messages[], only in system_instruction.
 *   output     — Internal role for OpenAI Responses API output objects.
 *                Unlikely to appear in the React layer.
 */
export type Role =
  | "user"
  | "assistant"
  | "tool"
  | "system"
  | "developer"
  | "output";

/**
 * Roles that are valid in a stored/transmitted message.
 * system and developer only appear in the system_instruction field.
 */
export type StoredRole = "user" | "assistant" | "tool";

// =============================================================================
// SECTION 2 — Additional block types (assistant / tool role only)
// =============================================================================
// These never appear in user messages. They are produced server-side and
// stored as part of the conversation history.

/**
 * Extended thinking / reasoning produced by the model.
 *
 * All three providers that support thinking (OpenAI, Anthropic, Google) use
 * this single normalized type. The provider field tells you where it came from,
 * and the signature field holds the provider-specific encrypted payload that
 * must be echoed back verbatim on the next turn for reasoning continuity.
 *
 * You will see this in:
 *   - assistant messages from o-series (OpenAI), Claude 3.x (Anthropic),
 *     Gemini 2.x Flash/Pro with think mode (Google).
 *
 * The React layer should treat this as a collapsible "thinking" section.
 * Never modify or omit the signature when re-sending history.
 */
export interface ThinkingBlock {
  type: "thinking";
  /**
   * The model's reasoning text. May be empty for OpenAI (which only provides
   * a summary). Render this as the expanded thinking content.
   */
  text: string;
  /**
   * Which provider generated this block. Required to correctly echo the
   * signature back on the next turn.
   */
  provider: "openai" | "anthropic" | "google" | "cerebras" | null;
  /**
   * Provider-specific encrypted/opaque payload.
   * - OpenAI: "encrypted_content" — a string.
   * - Anthropic: "signature" — a string.
   * - Google: "thoughtSignature" — base64-encoded bytes (stored as string).
   * Must be echoed back verbatim when continuing the conversation.
   */
  signature?: string | null;
  /**
   * OpenAI only: a condensed summary of the reasoning steps.
   * Each item is { type: "summary_text", text: "..." }.
   */
  summary?: Array<{ type: string; text: string }>;
  /** Provider-assigned ID for this thinking block. */
  id?: string;
}

/**
 * A tool call requested by the model.
 *
 * When the model decides to call a tool it emits a ToolCallBlock.
 * The server (or the client, for client-delegated tools) executes the tool
 * and returns a ToolResultBlock that references this call via call_id.
 *
 * These appear in assistant messages.
 */
export interface ToolCallBlock {
  type: "tool_call";
  /**
   * Join key — matches ToolResultBlock.call_id.
   * This is the identifier you use to correlate a call with its result.
   */
  id: string;
  /** Name of the tool being called. */
  name: string;
  /** Arguments passed to the tool, keyed by parameter name. */
  arguments: Record<string, unknown>;
}

/**
 * The result of a tool execution, fed back to the model.
 *
 * These appear in "tool" role messages. The call_id links back to the
 * ToolCallBlock that triggered this execution.
 */
export interface ToolResultBlock {
  type: "tool_result";
  /**
   * Links back to ToolCallBlock.id.
   * Primary correlation key used by the server.
   */
  call_id: string;
  /**
   * Anthropic-specific correlation ID (tool_use_id in their API).
   * Same semantic as call_id — present when the conversation involved
   * an Anthropic model. Omit or leave empty for other providers.
   */
  tool_use_id?: string;
  /** The name of the tool that was executed. */
  name?: string;
  /**
   * The result returned by the tool.
   * Typically a string (JSON or plain text), but may be a structured object
   * depending on the tool.
   */
  content: string | Record<string, unknown> | unknown[];
  /**
   * True if the tool execution raised an error.
   * When true, content contains the error message/details.
   */
  is_error?: boolean;
}

/**
 * Google Gemini code execution request.
 * Appears in assistant messages when Gemini decides to run code.
 * Google only — OpenAI and Anthropic do not support this block type.
 */
export interface CodeExecutionBlock {
  type: "code_execution";
  /** The code to execute. */
  code: string;
  /** Programming language. Default "python". */
  language?: string;
}

/**
 * Result of a Google Gemini code execution.
 * Appears in the model's response alongside or after CodeExecutionBlock.
 * Google only.
 */
export interface CodeExecutionResultBlock {
  type: "code_execution_result";
  /** Execution outcome: "success" | "error" | "timeout" | etc. */
  outcome: string;
  /** Stdout / stderr from the execution. */
  output: string;
}

/**
 * A web search call made by the model (OpenAI built-in web search tool).
 * Appears in the conversation history when OpenAI's web search tool was used.
 * Not produced by Anthropic or Google.
 */
export interface WebSearchCallBlock {
  type: "web_search_call";
  /** Provider-assigned ID for this search action. */
  id?: string;
  /** Execution status: "completed" | "failed" | etc. */
  status?: string;
  /**
   * The search action descriptor as returned by the OpenAI Responses API.
   * Shape: { type: "search", query: "..." } or similar.
   */
  action?: Record<string, unknown>;
}

// =============================================================================
// SECTION 3 — ConversationBlock: the full superset
// =============================================================================

/**
 * Every block type that can appear in any position in a stored conversation.
 *
 * This is a superset of ContentBlock (message-types.ts).
 * All ContentBlock types are included here because prior user messages
 * (with their structured inputs, images, etc.) are part of the history.
 *
 * Role restrictions:
 *   "user"      → any ContentBlock (TextBlock, ImageBlock, structured inputs, …)
 *   "assistant" → TextBlock | ThinkingBlock | ToolCallBlock |
 *                 CodeExecutionBlock | CodeExecutionResultBlock |
 *                 WebSearchCallBlock
 *   "tool"      → ToolResultBlock (one block per tool call result)
 */
export type ConversationBlock =
  // ── User-sendable blocks (ContentBlock) ──
  | TextBlock
  | ImageBlock
  | AudioBlock
  | VideoBlock
  | YouTubeVideoBlock
  | DocumentBlock
  | WebpageInputBlock
  | NotesInputBlock
  | TaskInputBlock
  | TableInputBlock
  | ListInputBlock
  | DataInputBlock
  // ── Assistant-only blocks ──
  | ThinkingBlock
  | ToolCallBlock
  | CodeExecutionBlock
  | CodeExecutionResultBlock
  | WebSearchCallBlock
  // ── Tool-role blocks ──
  | ToolResultBlock;

// =============================================================================
// SECTION 4 — ConversationMessage: a full message with role + content
// =============================================================================

/**
 * A single message in a conversation — exactly as stored in the database
 * and returned by the API.
 *
 * The content array is typed per-role (see RoleMessageUnion below) but in
 * practice the server always enforces correct content types per role.
 * The React layer can use the role discriminant to narrow the content type.
 */
export interface ConversationMessage {
  /** Message role. See Role above. */
  role: StoredRole;
  /** Ordered list of content blocks for this turn. */
  content: ConversationBlock[];
  /**
   * Server-assigned message ID (UUID). Present on persisted messages.
   * Absent for optimistically-rendered messages before the server confirms.
   */
  id?: string;
  /**
   * Display name override for the sender.
   * Rarely used — only when the agent or user has a custom display name.
   */
  name?: string;
  /** ISO-8601 creation timestamp. Present on persisted messages. */
  timestamp?: string;
  /** Message lifecycle status. Default "active". */
  status?: "active" | "archived" | "deleted";
}

// Narrowed per-role message types for exhaustive type narrowing

/** A user turn. Content is any ContentBlock. */
export interface UserMessage extends ConversationMessage {
  role: "user";
  content: ContentBlock[];
}

/** An assistant turn. Content is text, thinking, tool calls, or code execution. */
export interface AssistantMessage extends ConversationMessage {
  role: "assistant";
  content: Array<
    | TextBlock
    | ThinkingBlock
    | ToolCallBlock
    | CodeExecutionBlock
    | CodeExecutionResultBlock
    | WebSearchCallBlock
  >;
}

/** A tool-results turn. Content is one ToolResultBlock per executed call. */
export interface ToolMessage extends ConversationMessage {
  role: "tool";
  content: ToolResultBlock[];
}

/** Discriminated union — narrow on .role for exhaustive handling. */
export type RoleMessage = UserMessage | AssistantMessage | ToolMessage;

// =============================================================================
// SECTION 5 — Agent definition messages
// =============================================================================
//
// Agents are stored as prompts. Each prompt has a messages[] array that
// defines the initial "priming" conversation shown to the model before any
// real user interaction begins.
//
// IMPORTANT RULES for agent definition messages:
//   - Only "user" and "assistant" roles are valid here.
//   - No tool calls, no thinking, no tool results.
//   - System instructions go in the separate system_instruction field.
//   - Content is almost always plain TextBlock — but ImageBlock and other
//     media blocks are technically valid for seeding a visual context.
//   - {{variable_name}} placeholders in TextBlock.text are substituted at
//     runtime using the variables supplied in the AgentStartRequest.

/**
 * A priming message in an agent's definition.
 *
 * Used in the messages[] array that is part of the agent/prompt stored
 * in the database. These messages are prepended to the live conversation
 * before the first user turn.
 *
 * Only "user" and "assistant" roles are valid.
 * Content is restricted to media blocks — no structured inputs
 * (input_notes, input_task, etc.), no tool calls, no thinking.
 * Structured inputs are only valid in live user messages, not priming messages.
 *
 * TextBlock.text may contain {{variable_name}} placeholders that are
 * replaced at runtime from AgentStartRequest.variables.
 */
export interface AgentDefinitionMessage {
  role: "user" | "assistant" | "system" | "developer" | "output";
  /**
   * Content blocks for this priming turn.
   * TextBlock is by far the most common. ImageBlock and DocumentBlock are
   * valid for visually-grounded agents.
   */
  content: Array<
    | TextBlock
    | ImageBlock
    | AudioBlock
    | VideoBlock
    | YouTubeVideoBlock
    | DocumentBlock
  >;
}

/**
 * The messages[] array in an agent/prompt definition.
 * Always a user/assistant alternating sequence. Conventionally starts
 * with a user turn and ends with a user turn (the live user message is
 * appended after these).
 */
export type AgentDefinitionMessages = AgentDefinitionMessage[];

// =============================================================================
// SECTION 6 — Quick reference cheat-sheet
// =============================================================================
//
// ┌─────────────────────────────────────────────────────────────────────────┐
// │  CONTEXT                   │ TYPE TO USE                                │
// ├────────────────────────────┼───────────────────────────────────────────┤
// │ user_input in request body │ UserInput (message-types.ts)               │
// │ Agent definition messages  │ AgentDefinitionMessage[]                   │
// │ Stored conversation turn   │ ConversationMessage (or RoleMessage)       │
// │ Any block anywhere         │ ConversationBlock                          │
// │ User-sendable blocks only  │ ContentBlock (message-types.ts)            │
// │ Single text+image user msg │ UserMessage                                │
// │ Model response with tools  │ AssistantMessage                           │
// │ Tool execution results     │ ToolMessage                                │
// └────────────────────────────┴───────────────────────────────────────────┘
//
// ROLE RULES (enforced server-side)
// ──────────────────────────────────
//   system / developer  → NEVER in messages[]. Always in system_instruction.
//   user                → ContentBlock[] (all media + structured inputs)
//   assistant           → TextBlock | ThinkingBlock | ToolCallBlock |
//                         CodeExecutionBlock | CodeExecutionResultBlock |
//                         WebSearchCallBlock
//   tool                → ToolResultBlock[] (one per executed call)
//
// THINKING SIGNATURE RULE
// ────────────────────────
//   If a ThinkingBlock with a non-null signature is in the history,
//   it MUST be echoed back exactly as received when continuing the
//   conversation. Never strip or modify signatures. The server handles
//   this automatically — only relevant if you manually construct history.
//
// TOOL CALL / RESULT PAIRING
// ───────────────────────────
//   ToolCallBlock.id  ←→  ToolResultBlock.call_id
//   Every ToolCallBlock in an assistant message must be followed (eventually)
//   by a ToolResultBlock with a matching call_id in a "tool" role message.
