"use client";

// Layer 5: NoteSidebar
// Takes ONLY instanceId. Shows folder tree, search, note list.
// Highlights active tab and open tabs from the instance.
// All state from Redux selectors. All mutations via dispatch.
// ZERO PROP DRILLING.

import React, { useState, useCallback, useMemo } from "react";
import {
  FileText,
  FolderOpen,
  Folder,
  ChevronDown,
  ChevronRight,
  Search,
  Plus,
  Edit3,
  User,
  Briefcase,
  Lightbulb,
} from "lucide-react";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import { selectUser } from "@/lib/redux/slices/userSlice";
import {
  setInstanceActiveTab,
  addInstanceTab,
  createAutogeneratedNote,
  setNoteField,
} from "../redux/slice";
import { fetchNoteContent } from "../redux/thunks";
import {
  selectAllNotesList,
  selectInstanceActiveTab,
  selectInstanceTabs,
} from "../redux/selectors";
import { cn } from "@/lib/utils";
import type { NoteRecord } from "../redux/notes.types";

// ── Folder icon map ─────────────────────────────────────────────────────────

const FOLDER_ICONS: Record<string, typeof FileText> = {
  Draft: Edit3,
  Personal: User,
  Business: Briefcase,
  Prompts: Lightbulb,
  Scratch: FileText,
};

const DEFAULT_FOLDERS = ["Draft", "Personal", "Business", "Prompts", "Scratch"];

interface NoteSidebarProps {
  instanceId: string;
}

export function NoteSidebar({ instanceId }: NoteSidebarProps) {
  const dispatch = useAppDispatch();
  const { id: userId } = useAppSelector(selectUser);

  // ── Redux state (memoized selectors — no new references) ──────────
  const allNotes = useAppSelector(selectAllNotesList);
  const activeTabId = useAppSelector(selectInstanceActiveTab(instanceId));
  const openTabIds = useAppSelector(selectInstanceTabs(instanceId));

  // ── Local UI state ─────────────────────────────────────────────────
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(
    () => new Set(DEFAULT_FOLDERS),
  );

  // ── Derived data ───────────────────────────────────────────────────
  const folders = useMemo(() => {
    const set = new Set<string>(DEFAULT_FOLDERS);
    for (const n of allNotes) {
      if (n.folder_name) set.add(n.folder_name);
    }
    const arr = Array.from(set);
    // Defaults first, then alphabetical
    return arr.sort((a, b) => {
      const ai = DEFAULT_FOLDERS.indexOf(a);
      const bi = DEFAULT_FOLDERS.indexOf(b);
      if (ai !== -1 && bi !== -1) return ai - bi;
      if (ai !== -1) return -1;
      if (bi !== -1) return 1;
      return a.localeCompare(b);
    });
  }, [allNotes]);

  const notesByFolder = useMemo(() => {
    const map = new Map<string, NoteRecord[]>();
    const q = searchQuery.toLowerCase();
    for (const n of allNotes) {
      if (
        q &&
        !n.label.toLowerCase().includes(q) &&
        !n.content?.toLowerCase().includes(q)
      ) {
        continue;
      }
      const folder = n.folder_name || "Draft";
      if (!map.has(folder)) map.set(folder, []);
      map.get(folder)!.push(n);
    }
    // Sort each folder by updated_at desc
    for (const notes of map.values()) {
      notes.sort((a, b) =>
        (b.updated_at ?? "").localeCompare(a.updated_at ?? ""),
      );
    }
    return map;
  }, [allNotes, searchQuery]);

  // ── Handlers ───────────────────────────────────────────────────────
  const toggleFolder = useCallback((folder: string) => {
    setExpandedFolders((prev) => {
      const next = new Set(prev);
      if (next.has(folder)) next.delete(folder);
      else next.add(folder);
      return next;
    });
  }, []);

  const selectNote = useCallback(
    (noteId: string) => {
      dispatch(addInstanceTab({ instanceId, noteId }));
      dispatch(setInstanceActiveTab({ instanceId, noteId }));
      dispatch(fetchNoteContent(noteId));
    },
    [dispatch, instanceId],
  );

  const handleNewNote = useCallback(
    (folder: string) => {
      if (!userId) return;
      // Check for existing auto-generated empty note in this folder
      const existing = allNotes.find(
        (n) =>
          n._isAutogenerated && !n.content?.trim() && n.folder_name === folder,
      );
      if (existing) {
        selectNote(existing.id);
        return;
      }
      // Create new auto-generated note (client-only, no DB)
      const id = crypto.randomUUID();
      dispatch(createAutogeneratedNote({ id, userId, folder, instanceId }));
    },
    [dispatch, instanceId, userId, allNotes, selectNote],
  );

  // ── Format time ────────────────────────────────────────────────────
  const formatTime = (dateStr: string) => {
    if (!dateStr) return "";
    const d = new Date(dateStr);
    const mins = Math.floor((Date.now() - d.getTime()) / 60000);
    if (mins < 1) return "now";
    if (mins < 60) return `${mins}m`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `${hrs}h`;
    const days = Math.floor(hrs / 24);
    if (days < 7) return `${days}d`;
    return d.toLocaleDateString(undefined, { month: "short", day: "numeric" });
  };

  // ── Render ─────────────────────────────────────────────────────────
  return (
    <div className="flex flex-col h-full min-h-0">
      {/* Search */}
      <div className="shrink-0 px-2 py-1.5 border-b border-border/30">
        <div className="flex items-center gap-1.5 px-2 py-1 bg-muted/50 rounded-md">
          <Search className="w-3 h-3 text-muted-foreground shrink-0" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search notes..."
            className="flex-1 min-w-0 bg-transparent text-xs outline-none placeholder:text-muted-foreground/50"
            style={{ fontSize: "16px" }}
          />
        </div>
      </div>

      {/* Folder tree */}
      <div className="flex-1 overflow-y-auto">
        {folders.map((folder) => {
          const folderNotes = notesByFolder.get(folder) ?? [];
          const isExpanded = expandedFolders.has(folder);
          const Icon = FOLDER_ICONS[folder] ?? Folder;
          const count = folderNotes.length;

          if (searchQuery && count === 0) return null;

          return (
            <div key={folder}>
              <button
                className="group flex items-center gap-1 w-full px-2 py-1 text-[0.6875rem] font-semibold uppercase tracking-wider text-muted-foreground cursor-pointer transition-colors hover:text-foreground hover:bg-accent/50 [&_svg]:w-3 [&_svg]:h-3"
                onClick={() => toggleFolder(folder)}
              >
                {isExpanded ? (
                  <ChevronDown className="opacity-60" />
                ) : (
                  <ChevronRight className="opacity-60" />
                )}
                {isExpanded ? (
                  <FolderOpen className="opacity-70" />
                ) : (
                  <Icon className="opacity-70" />
                )}
                <span className="flex-1 text-left truncate">{folder}</span>
                <span className="text-[0.625rem] font-normal opacity-50 tabular-nums">
                  {count}
                </span>
              </button>

              {isExpanded && (
                <div className="ml-2">
                  {folderNotes.length === 0 ? (
                    <div className="px-5 py-2 text-[0.625rem] text-muted-foreground/50 italic">
                      Empty
                    </div>
                  ) : (
                    folderNotes.map((note) => {
                      const isActive = activeTabId === note.id;
                      const isOpenTab = openTabIds?.includes(note.id) ?? false;
                      return (
                        <button
                          key={note.id}
                          className={cn(
                            "flex items-center gap-1.5 w-full text-left px-2 py-[3px] rounded-sm cursor-pointer transition-colors group/item",
                            isActive
                              ? "bg-accent text-foreground"
                              : isOpenTab
                                ? "bg-accent/30 text-foreground/80"
                                : "text-muted-foreground hover:bg-accent/50 hover:text-foreground",
                          )}
                          onClick={() => selectNote(note.id)}
                        >
                          <FileText className="w-3.5 h-3.5 shrink-0 opacity-50" />
                          <span className="flex-1 text-xs truncate leading-tight">
                            {note.label}
                          </span>
                          <span className="text-[0.625rem] opacity-40 tabular-nums shrink-0">
                            {formatTime(note.updated_at)}
                          </span>
                        </button>
                      );
                    })
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* New note button */}
      <div className="shrink-0 px-2 py-1.5 border-t border-border/30">
        <button
          className="flex items-center gap-1.5 w-full px-2 py-1 text-[0.6875rem] text-muted-foreground cursor-pointer transition-colors hover:text-foreground hover:bg-accent/50 rounded-md [&_svg]:w-3 [&_svg]:h-3"
          onClick={() => handleNewNote("Draft")}
        >
          <Plus /> New Note
        </button>
      </div>
    </div>
  );
}
