"use client";

// Layer 6: NotesView — Instance wrapper.
// Registers a unique notes instance on mount, cleans up on unmount.
// Renders sidebar + tab bar + active note editor.
// Can be used as full page, floating window, or single-note embed.
// ZERO PROP DRILLING — each child receives only an instanceId or noteId.

import React, { useEffect, useRef, useCallback } from "react";
import {
  FileText,
  SplitSquareHorizontal,
  PilcrowRight,
  Columns,
  Eye,
} from "lucide-react";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import { selectUser } from "@/lib/redux/slices/userSlice";
import {
  registerInstance,
  unregisterInstance,
  setInstanceActiveTab,
  addInstanceTab,
  createAutogeneratedNote,
  setNoteEditorMode,
} from "../redux/slice";
import { fetchNotesList, fetchNoteContent } from "../redux/thunks";
import { selectInstanceActiveTab, selectNoteEditorMode } from "../redux/selectors";
import PageHeader from "@/features/shell/components/header/PageHeader";
import { NoteContentEditor } from "./NoteContentEditor";
import { NoteMetadataBar } from "./NoteMetadataBar";
import { NoteTabBar } from "./NoteTabBar";
import { NoteSidebar } from "./NoteSidebar";
import { cn } from "@/lib/utils";

export interface NotesViewConfig {
  /** Show the sidebar with folder tree (default: true) */
  showSidebar?: boolean;
  /** Show the tab bar (default: true) */
  showTabs?: boolean;
  /** Lock to a single note — no tabs, no sidebar (default: null) */
  singleNote?: string | null;
  /** Custom instance ID (default: auto-generated) */
  instanceId?: string;
}

export interface NotesViewProps {
  config?: NotesViewConfig;
  className?: string;
}

export function NotesView({ config, className }: NotesViewProps) {
  const dispatch = useAppDispatch();
  const { id: userId } = useAppSelector(selectUser);

  const showSidebar = config?.showSidebar ?? true;
  const showTabs = config?.showTabs ?? true;
  const singleNote = config?.singleNote ?? null;

  // ── Generate or use provided instance ID ──────────────────────────
  const instanceIdRef = useRef(
    config?.instanceId ??
      `notes-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
  );
  const instanceId = instanceIdRef.current;

  // ── Register instance on mount, unregister on unmount ─────────────
  useEffect(() => {
    dispatch(registerInstance(instanceId));
    return () => {
      dispatch(unregisterInstance(instanceId));
    };
  }, [dispatch, instanceId]);

  // ── Fetch notes list on mount ─────────────────────────────────────
  const fetchedRef = useRef(false);
  useEffect(() => {
    if (!fetchedRef.current && userId) {
      fetchedRef.current = true;
      dispatch(fetchNotesList());
    }
  }, [dispatch, userId]);

  // ── Single note mode: set active immediately ──────────────────────
  useEffect(() => {
    if (singleNote) {
      dispatch(addInstanceTab({ instanceId, noteId: singleNote }));
      dispatch(setInstanceActiveTab({ instanceId, noteId: singleNote }));
      dispatch(fetchNoteContent(singleNote));
    }
  }, [dispatch, instanceId, singleNote]);

  const activeTabId = useAppSelector(selectInstanceActiveTab(instanceId));
  const editorMode = useAppSelector(
    activeTabId ? selectNoteEditorMode(activeTabId) : () => "plain",
  ) ?? "plain";

  const setMode = useCallback(
    (mode: string) => {
      if (activeTabId) dispatch(setNoteEditorMode({ id: activeTabId, mode }));
    },
    [dispatch, activeTabId],
  );

  const modeBtnClass = (mode: string) =>
    cn(
      "flex items-center gap-1 px-2.5 py-0.5 text-[0.6875rem] font-medium rounded-full transition-colors cursor-pointer",
      "[&_svg]:w-3.5 [&_svg]:h-3.5",
      editorMode === mode
        ? "bg-[var(--shell-glass-bg-active)] text-[var(--shell-nav-text-hover)]"
        : "text-[var(--shell-nav-text)] hover:text-[var(--shell-nav-text-hover)]",
    );

  // ── Render ────────────────────────────────────────────────────────
  return (
    <div className={`flex h-full w-full min-h-0 ${className ?? ""}`}>
      {/* ── Header center: View mode buttons (portaled into shell header) */}
      {activeTabId && (
        <PageHeader>
          <div className="shell-glass flex items-center gap-0.5 rounded-full p-0.5">
            <button className={modeBtnClass("plain")} onClick={() => setMode("plain")}>
              <FileText /> Edit
            </button>
            <button className={cn(modeBtnClass("split"), "max-lg:hidden")} onClick={() => setMode("split")}>
              <SplitSquareHorizontal /> Split
            </button>
            <button className={cn(modeBtnClass("wysiwyg"), "max-lg:hidden")} onClick={() => setMode("wysiwyg")}>
              <PilcrowRight /> Rich
            </button>
            <button className={cn(modeBtnClass("markdown-split"), "max-lg:hidden")} onClick={() => setMode("markdown-split")}>
              <Columns /> MD Split
            </button>
            <button className={modeBtnClass("preview")} onClick={() => setMode("preview")}>
              <Eye /> Preview
            </button>
          </div>
        </PageHeader>
      )}

      {/* Layer 5: Sidebar */}
      {showSidebar && !singleNote && (
        <div className="w-[280px] shrink-0 border-r border-border flex flex-col min-h-0 max-lg:hidden">
          <NoteSidebar instanceId={instanceId} />
        </div>
      )}

      {/* Main content area */}
      <div className="flex-1 flex flex-col min-w-0 min-h-0">
        {/* Layer 4: Tab bar (top) */}
        {showTabs && !singleNote && <NoteTabBar instanceId={instanceId} />}

        {/* Layer 1: Content editor (fills available space) */}
        {activeTabId ? (
          <NoteContentEditor noteId={activeTabId} />
        ) : (
          <div className="flex-1 flex items-center justify-center text-muted-foreground">
            <div className="text-center">
              <p className="text-sm">No note selected</p>
              <p className="text-xs mt-1">Select a note or create a new one</p>
            </div>
          </div>
        )}

        {/* Layer 2: Metadata bar (bottom — folder, tags, status) */}
        {activeTabId && <NoteMetadataBar noteId={activeTabId} />}
      </div>
    </div>
  );
}
