"use client";

// Layer 4: NoteTabBar — VSCode-style compact tab row.
// Matches the SSR workspace tab bar design exactly.
// Props: instanceId only. Everything from Redux.

import React, { useRef, useEffect, useCallback, useState } from "react";
import { Plus } from "lucide-react";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import {
  addInstanceTab,
  setInstanceActiveTab,
  reorderInstanceTabs,
  createAutogeneratedNote,
  setSplitNote,
} from "../redux/slice";
import { fetchNoteContent } from "../redux/thunks";
import {
  selectInstanceTabs,
  selectInstanceActiveTab,
  selectInstanceSplitNoteId,
} from "../redux/selectors";
import { NoteTabItem } from "./NoteTabItem";
import { SplitNotePicker } from "./SplitNotePicker";
import { cn } from "@/lib/utils";

interface NoteTabBarProps {
  instanceId: string;
}

const actionBtnClass =
  "flex items-center justify-center w-6 h-6 rounded cursor-pointer transition-colors text-muted-foreground hover:bg-accent hover:text-foreground [&_svg]:w-3.5 [&_svg]:h-3.5";

export function NoteTabBar({ instanceId }: NoteTabBarProps) {
  const dispatch = useAppDispatch();

  const openTabs = useAppSelector(selectInstanceTabs(instanceId));
  const activeTabId = useAppSelector(selectInstanceActiveTab(instanceId));
  const splitNoteId = useAppSelector(selectInstanceSplitNoteId(instanceId));
  const userId = useAppSelector((s) => s.user?.id);

  const scrollRef = useRef<HTMLDivElement>(null);
  const hydratedRef = useRef(false);
  const lastPushedUrlRef = useRef("");

  // ── DnD state (local only) ────────────────────────────────────────
  const [draggedTab, setDraggedTab] = useState<string | null>(null);
  const [dragOverTab, setDragOverTab] = useState<string | null>(null);

  // ── URL → Redux: hydrate ONCE on mount ────────────────────────────
  useEffect(() => {
    if (hydratedRef.current) return;
    hydratedRef.current = true;

    const params = new URLSearchParams(window.location.search);
    const tabsParam = params.get("tabs");
    if (!tabsParam) return;

    const tabIds = tabsParam.split(",").filter(Boolean);
    if (tabIds.length === 0) return;

    tabIds.forEach((id) => {
      dispatch(addInstanceTab({ instanceId, noteId: id }));
      dispatch(fetchNoteContent(id));
    });

    const activeParam = params.get("active");
    if (activeParam && tabIds.includes(activeParam)) {
      dispatch(setInstanceActiveTab({ instanceId, noteId: activeParam }));
    } else {
      dispatch(setInstanceActiveTab({ instanceId, noteId: tabIds[0] }));
    }

    const splitParam = params.get("split");
    if (splitParam) {
      dispatch(setSplitNote({ instanceId, noteId: splitParam }));
      dispatch(fetchNoteContent(splitParam));
    }
  }, [dispatch, instanceId]);

  // ── Redux → URL: push state to URL (no hook, no deps on URL) ──────
  useEffect(() => {
    if (!hydratedRef.current) return;

    const params = new URLSearchParams(window.location.search);

    if (openTabs && openTabs.length > 0) {
      params.set("tabs", openTabs.join(","));
    } else {
      params.delete("tabs");
    }

    if (activeTabId) {
      params.set("active", activeTabId);
    } else {
      params.delete("active");
    }

    if (splitNoteId) {
      params.set("split", splitNoteId);
    } else {
      params.delete("split");
    }

    const newUrl = `${window.location.pathname}?${params.toString()}`;
    if (newUrl !== lastPushedUrlRef.current) {
      lastPushedUrlRef.current = newUrl;
      window.history.replaceState(null, "", newUrl);
    }
  }, [openTabs, activeTabId, splitNoteId]);

  // ── New tab ────────────────────────────────────────────────────────
  const handleNewTab = useCallback(() => {
    if (!userId) return;
    const id = crypto.randomUUID();
    dispatch(
      createAutogeneratedNote({ id, userId, folder: "Draft", instanceId }),
    );
  }, [dispatch, userId, instanceId]);

  // ── DnD reorder ────────────────────────────────────────────────────
  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      const fromId = e.dataTransfer.getData("text/plain");
      if (!fromId || !openTabs || !dragOverTab) return;
      if (fromId === dragOverTab) return;

      const filtered = openTabs.filter((t) => t !== fromId);
      const dropIdx = filtered.indexOf(dragOverTab);
      if (dropIdx === -1) return;
      filtered.splice(dropIdx, 0, fromId);
      dispatch(reorderInstanceTabs({ instanceId, tabs: filtered }));
      setDraggedTab(null);
      setDragOverTab(null);
    },
    [dispatch, instanceId, openTabs, dragOverTab],
  );

  // ── Auto-scroll active tab into view ──────────────────────────────
  useEffect(() => {
    if (!scrollRef.current || !activeTabId) return;
    const el = scrollRef.current.querySelector(`[data-active="true"]`);
    el?.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "center" });
  }, [activeTabId]);

  if (!openTabs || openTabs.length === 0) return null;

  return (
    <div
      className="notes-tab-bar-scroll flex items-stretch h-8 min-h-[2rem] overflow-x-auto overflow-y-hidden border-b border-border shrink-0 mt-1"
      role="tablist"
      aria-label="Open notes"
      onDragOver={(e) => {
        e.preventDefault();
        e.dataTransfer.dropEffect = "move";
      }}
      onDrop={handleDrop}
    >
      <div ref={scrollRef} className="flex items-stretch flex-1 min-w-0 overflow-x-auto h-full">
        {openTabs.map((tabId) => (
          <div
            key={tabId}
            onDragOver={(e) => {
              if (!draggedTab || draggedTab === tabId) return;
              e.preventDefault();
              setDragOverTab(tabId);
            }}
            onDragStart={() => setDraggedTab(tabId)}
            onDragEnd={() => {
              setDraggedTab(null);
              setDragOverTab(null);
            }}
            className={cn(
              draggedTab === tabId && "opacity-40",
              dragOverTab === tabId && "border-l-2 border-primary",
            )}
          >
            <NoteTabItem noteId={tabId} instanceId={instanceId} />
          </div>
        ))}

        {/* New note tab button */}
        <button
          className={cn(actionBtnClass, "shrink-0 self-center ml-1")}
          onClick={handleNewTab}
          title="New Note"
        >
          <Plus />
        </button>

        {/* Split view button */}
        {activeTabId && !splitNoteId && (
          <div className="shrink-0 self-center mx-0.5">
            <SplitNotePicker />
          </div>
        )}
      </div>
    </div>
  );
}
