// features/notes/components/NoteTabBar.tsx
// Layer 4: Tab bar manager for an instance. Zero prop drilling — Redux selectors only.
"use client";

import React, { useRef, useEffect, useCallback } from "react";
import { Plus } from "lucide-react";
import { usePathname, useSearchParams } from "next/navigation";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import {
  setInstanceActiveTab,
  addInstanceTab,
  removeInstanceTab,
  reorderInstanceTabs,
  createAutogeneratedNote,
} from "../redux/slice";
import {
  selectInstanceTabs,
  selectInstanceActiveTab,
} from "../redux/selectors";
import { NoteTabItem } from "./NoteTabItem";

interface NoteTabBarProps {
  instanceId: string;
}

export function NoteTabBar({ instanceId }: NoteTabBarProps) {
  const dispatch = useAppDispatch();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const openTabs = useAppSelector(selectInstanceTabs(instanceId));
  const activeTabId = useAppSelector(selectInstanceActiveTab(instanceId));
  const userId = useAppSelector((s) => s.user?.id);

  const scrollRef = useRef<HTMLDivElement>(null);
  const hydrated = useRef(false);

  // ── URL sync: hydrate from URL on mount ─────────────────────────────

  useEffect(() => {
    if (hydrated.current) return;
    hydrated.current = true;

    const tabsParam = searchParams.get("tabs");
    if (!tabsParam) return;

    const tabIds = tabsParam.split(",").filter(Boolean);
    if (tabIds.length === 0) return;

    tabIds.forEach((id) => {
      dispatch(addInstanceTab({ instanceId, noteId: id }));
    });

    // Activate the first tab if none is active
    const activeParam = searchParams.get("active");
    if (activeParam && tabIds.includes(activeParam)) {
      dispatch(setInstanceActiveTab({ instanceId, noteId: activeParam }));
    } else if (tabIds.length > 0) {
      dispatch(setInstanceActiveTab({ instanceId, noteId: tabIds[0] }));
    }
  }, [dispatch, instanceId, searchParams]);

  // ── URL sync: push Redux state to URL ───────────────────────────────

  useEffect(() => {
    if (!hydrated.current) return;

    const params = new URLSearchParams(searchParams.toString());

    if (openTabs && openTabs.length > 0) {
      params.set("tabs", openTabs.join(","));
    } else {
      params.delete("tabs");
    }

    if (activeTabId) {
      params.set("active", activeTabId);
    } else {
      params.delete("active");
    }

    const newUrl = `${pathname}?${params.toString()}`;
    window.history.replaceState(null, "", newUrl);
  }, [openTabs, activeTabId, pathname, searchParams]);

  const handleNewTab = useCallback(() => {
    if (!userId) return;
    const id = crypto.randomUUID();
    dispatch(
      createAutogeneratedNote({
        id,
        userId,
        folder: "Notes",
        instanceId,
      }),
    );
  }, [dispatch, userId, instanceId]);

  // ── DnD reorder ─────────────────────────────────────────────────────

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = "move";
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      const draggedId = e.dataTransfer.getData("text/plain");
      if (!draggedId) return;

      // Determine drop position from mouse x relative to tab elements
      const container = scrollRef.current;
      if (!container) return;

      const tabElements = Array.from(
        container.querySelectorAll<HTMLElement>("[role='tab']"),
      );

      let insertIndex = openTabs?.length ?? 0;
      for (let i = 0; i < tabElements.length; i++) {
        const rect = tabElements[i].getBoundingClientRect();
        const midX = rect.left + rect.width / 2;
        if (e.clientX < midX) {
          insertIndex = i;
          break;
        }
      }

      const currentIndex = openTabs?.indexOf(draggedId) ?? -1;
      if (currentIndex === -1) return;

      const newOrder = (openTabs ?? []).filter((id) => id !== draggedId);
      // Adjust insert index if dragged item was before the drop target
      const adjustedIndex =
        currentIndex < insertIndex ? insertIndex - 1 : insertIndex;
      newOrder.splice(adjustedIndex, 0, draggedId);

      dispatch(reorderInstanceTabs({ instanceId, tabs: newOrder }));
    },
    [dispatch, instanceId, openTabs],
  );

  // ── Auto-scroll active tab into view ────────────────────────────────

  useEffect(() => {
    if (!scrollRef.current || !activeTabId) return;
    const activeEl = scrollRef.current.querySelector(`[aria-selected="true"]`);
    if (activeEl) {
      activeEl.scrollIntoView({
        behavior: "smooth",
        block: "nearest",
        inline: "center",
      });
    }
  }, [activeTabId]);

  return (
    <div className="border-b border-border bg-muted/30 flex items-center">
      {/* Scrollable tabs container */}
      <div
        ref={scrollRef}
        className="flex-1 flex items-end overflow-x-auto scrollbar-none gap-0.5 px-1 pt-1"
        onDragOver={handleDragOver}
        onDrop={handleDrop}
      >
        {openTabs?.map((tabId) => (
          <NoteTabItem key={tabId} noteId={tabId} instanceId={instanceId} />
        ))}
      </div>

      {/* New tab button */}
      <button
        onClick={handleNewTab}
        className="flex items-center justify-center h-7 w-7 mx-1 rounded hover:bg-accent transition-colors flex-shrink-0"
        title="New note"
      >
        <Plus className="h-3.5 w-3.5 text-muted-foreground" />
      </button>
    </div>
  );
}
