"use client";

// Layer 5: NoteSidebar
// Takes ONLY instanceId. Shows folder tree, search, note list.
// Highlights active tab and open tabs from the instance.
// All state from Redux selectors. All mutations via dispatch.
// ZERO PROP DRILLING.
//
// Features:
// - Search bar with instant filtering
// - Sort controls (field cycle + order toggle)
// - Expand/collapse all folders
// - Folder context menu (right-click: New Note, Rename, Delete All)
// - Note context menu (right-click: Open, Duplicate, Export, Move, Delete)
// - Auto-scroll to active note
// - Auto-expand folder of active note
// - Folder icons with colors from defaultFolders/folderCategories
// - Create Folder dialog with category picker
// - Rename Folder dialog
// - Empty state when no notes exist

import React, { useState, useCallback, useMemo, useRef, useEffect } from "react";
import {
  FileText,
  FolderOpen,
  Folder,
  ChevronDown,
  ChevronRight,
  Search,
  Plus,
  ArrowUpDown,
  ChevronsUpDown,
  FolderPlus,
  Copy,
  Download,
  FolderInput,
  Trash2,
  X,
  StickyNote,
} from "lucide-react";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import { selectUser } from "@/lib/redux/slices/userSlice";
import {
  setInstanceActiveTab,
  addInstanceTab,
  removeInstanceTab,
  createAutogeneratedNote,
} from "../redux/slice";
import {
  fetchNoteContent,
  copyNote,
  deleteNote,
  moveNoteToFolder,
} from "../redux/thunks";
import {
  selectAllNotesList,
  selectInstanceActiveTab,
  selectInstanceTabs,
  selectNotesListStatus,
  selectAllFolders,
} from "../redux/selectors";
import { renameFolder, deleteFolderNotes } from "../service/notesService";
import { getFolderIconAndColor } from "../utils/folderUtils";
import { isDefaultFolder } from "../utils/folderUtils";
import { CreateFolderDialog } from "./CreateFolderDialog";
import { RenameFolderDialog } from "./RenameFolderDialog";
import { cn } from "@/lib/utils";
import type { NoteRecord } from "../redux/notes.types";
import type { NoteSortField, NoteSortOrder } from "../types";

// ── Sort field labels ───────────────────────────────────────────────────────
const SORT_FIELDS: { field: NoteSortField; label: string }[] = [
  { field: "updated_at", label: "Modified" },
  { field: "label", label: "Name" },
  { field: "created_at", label: "Created" },
];

interface NoteSidebarProps {
  instanceId: string;
}

export function NoteSidebar({ instanceId }: NoteSidebarProps) {
  const dispatch = useAppDispatch();
  const { id: userId } = useAppSelector(selectUser);

  // ── Redux state (memoized selectors — no new references) ──────────
  const allNotes = useAppSelector(selectAllNotesList);
  const activeTabId = useAppSelector(selectInstanceActiveTab(instanceId));
  const openTabIds = useAppSelector(selectInstanceTabs(instanceId));
  const listStatus = useAppSelector(selectNotesListStatus);
  const allFolders = useAppSelector(selectAllFolders);

  // ── Local UI state ─────────────────────────────────────────────────
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(
    () => new Set(allFolders),
  );
  const [sortField, setSortField] = useState<NoteSortField>("updated_at");
  const [sortOrder, setSortOrder] = useState<NoteSortOrder>("desc");

  // Context menu state
  const [folderCtx, setFolderCtx] = useState<{ folder: string; x: number; y: number } | null>(null);
  const [noteCtx, setNoteCtx] = useState<{ noteId: string; noteLabel: string; folder: string; x: number; y: number } | null>(null);
  const [moveSubmenu, setMoveSubmenu] = useState(false);

  // Dialog state
  const [createFolderOpen, setCreateFolderOpen] = useState(false);
  const [renameFolderTarget, setRenameFolderTarget] = useState<string | null>(null);

  // Refs
  const folderTreeRef = useRef<HTMLDivElement>(null);
  const ctxMenuRef = useRef<HTMLDivElement>(null);

  // ── Auto-expand folder of active note ──────────────────────────────
  useEffect(() => {
    if (!activeTabId) return;
    const note = allNotes.find((n) => n.id === activeTabId);
    if (note?.folder_name) {
      setExpandedFolders((prev) => {
        if (prev.has(note.folder_name!)) return prev;
        const next = new Set(prev);
        next.add(note.folder_name!);
        return next;
      });
    }
  }, [activeTabId, allNotes]);

  // ── Auto-scroll active note into view ──────────────────────────────
  useEffect(() => {
    if (!activeTabId || !folderTreeRef.current) return;
    const el = folderTreeRef.current.querySelector(`[data-note-id="${activeTabId}"]`);
    el?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [activeTabId]);

  // ── Close context menus on outside click ──────────────────────────
  useEffect(() => {
    if (!folderCtx && !noteCtx) return;
    const handler = (e: MouseEvent) => {
      if (ctxMenuRef.current && !ctxMenuRef.current.contains(e.target as Node)) {
        setFolderCtx(null);
        setNoteCtx(null);
        setMoveSubmenu(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [folderCtx, noteCtx]);

  // ── Derived data ───────────────────────────────────────────────────
  const folders = useMemo(() => {
    // Start with known folders, add any from notes
    const set = new Set<string>(allFolders);
    for (const n of allNotes) {
      if (n.folder_name) set.add(n.folder_name);
    }
    return allFolders.concat(
      Array.from(set).filter((f) => !allFolders.includes(f)).sort(),
    );
  }, [allNotes, allFolders]);

  const notesByFolder = useMemo(() => {
    const map = new Map<string, NoteRecord[]>();
    const q = searchQuery.toLowerCase();
    for (const n of allNotes) {
      if (
        q &&
        !n.label.toLowerCase().includes(q) &&
        !n.content?.toLowerCase().includes(q) &&
        !n.tags?.some((t) => t.toLowerCase().includes(q))
      ) {
        continue;
      }
      const folder = n.folder_name || "Draft";
      if (!map.has(folder)) map.set(folder, []);
      map.get(folder)!.push(n);
    }
    // Sort each folder
    for (const notes of map.values()) {
      notes.sort((a, b) => {
        let cmp = 0;
        if (sortField === "label") {
          cmp = a.label.localeCompare(b.label);
        } else if (sortField === "created_at") {
          cmp = (a.created_at ?? "").localeCompare(b.created_at ?? "");
        } else {
          cmp = (a.updated_at ?? "").localeCompare(b.updated_at ?? "");
        }
        return sortOrder === "desc" ? -cmp : cmp;
      });
    }
    return map;
  }, [allNotes, searchQuery, sortField, sortOrder]);

  // ── Handlers ───────────────────────────────────────────────────────
  const toggleFolder = useCallback((folder: string) => {
    setExpandedFolders((prev) => {
      const next = new Set(prev);
      if (next.has(folder)) next.delete(folder);
      else next.add(folder);
      return next;
    });
  }, []);

  const toggleAllFolders = useCallback(() => {
    setExpandedFolders((prev) => {
      const allExpanded = folders.every((f) => prev.has(f));
      return allExpanded ? new Set<string>() : new Set(folders);
    });
  }, [folders]);

  const cycleSortField = useCallback(() => {
    setSortField((prev) => {
      const idx = SORT_FIELDS.findIndex((s) => s.field === prev);
      return SORT_FIELDS[(idx + 1) % SORT_FIELDS.length].field;
    });
  }, []);

  const toggleSortOrder = useCallback(() => {
    setSortOrder((prev) => (prev === "desc" ? "asc" : "desc"));
  }, []);

  const selectNote = useCallback(
    (noteId: string) => {
      dispatch(addInstanceTab({ instanceId, noteId }));
      dispatch(setInstanceActiveTab({ instanceId, noteId }));
      dispatch(fetchNoteContent(noteId));
    },
    [dispatch, instanceId],
  );

  const handleNewNote = useCallback(
    (folder: string) => {
      if (!userId) return;
      const existing = allNotes.find(
        (n) =>
          n._isAutogenerated && !n.content?.trim() && n.folder_name === folder,
      );
      if (existing) {
        selectNote(existing.id);
        return;
      }
      const id = crypto.randomUUID();
      dispatch(createAutogeneratedNote({ id, userId, folder, instanceId }));
    },
    [dispatch, instanceId, userId, allNotes, selectNote],
  );

  // ── Folder context menu actions ────────────────────────────────────
  const handleFolderRename = useCallback((folder: string) => {
    setRenameFolderTarget(folder);
    setFolderCtx(null);
  }, []);

  const handleFolderDeleteAll = useCallback(async (folder: string) => {
    setFolderCtx(null);
    const count = (notesByFolder.get(folder) ?? []).length;
    if (count === 0) return;
    try {
      await deleteFolderNotes(folder);
      // Reload will happen via realtime subscription
      window.location.reload();
    } catch {
      // Error handled in service
    }
  }, [notesByFolder]);

  const handleRenameConfirm = useCallback(async (newName: string) => {
    if (!renameFolderTarget) return;
    try {
      await renameFolder(renameFolderTarget, newName);
      window.location.reload();
    } catch {
      // Error handled in service
    }
  }, [renameFolderTarget]);

  // ── Note context menu actions ──────────────────────────────────────
  const handleNoteExport = useCallback((noteId: string, label: string) => {
    const note = allNotes.find((n) => n.id === noteId);
    if (!note) return;
    const blob = new Blob([note.content ?? ""], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${label}.md`;
    a.click();
    URL.revokeObjectURL(url);
    setNoteCtx(null);
  }, [allNotes]);

  // ── Create folder handler ──────────────────────────────────────────
  const handleCreateFolder = useCallback((folderName: string) => {
    handleNewNote(folderName);
  }, [handleNewNote]);

  // ── Format time ────────────────────────────────────────────────────
  const formatTime = (dateStr: string | null | undefined) => {
    if (!dateStr) return "";
    const d = new Date(dateStr);
    const mins = Math.floor((Date.now() - d.getTime()) / 60000);
    if (mins < 1) return "now";
    if (mins < 60) return `${mins}m`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `${hrs}h`;
    const days = Math.floor(hrs / 24);
    if (days < 7) return `${days}d`;
    return d.toLocaleDateString(undefined, { month: "short", day: "numeric" });
  };

  const sortLabel = SORT_FIELDS.find((s) => s.field === sortField)?.label ?? "Modified";

  // ── Render ─────────────────────────────────────────────────────────
  return (
    <div className="flex flex-col h-full min-h-0">
      {/* Search */}
      <div className="shrink-0 px-2 py-1.5 border-b border-border/30">
        <div className="flex items-center gap-1.5 px-2 py-1 bg-muted/50 rounded-md">
          <Search className="w-3 h-3 text-muted-foreground shrink-0" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search notes..."
            className="flex-1 min-w-0 bg-transparent text-xs outline-none placeholder:text-muted-foreground/50"
            style={{ fontSize: "16px" }}
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery("")}
              className="text-muted-foreground hover:text-foreground cursor-pointer [&_svg]:w-3 [&_svg]:h-3"
            >
              <X />
            </button>
          )}
        </div>
      </div>

      {/* Toolbar: sort + expand/collapse */}
      <div className="shrink-0 flex items-center gap-1 px-2 py-1 border-b border-border/20">
        <button
          onClick={cycleSortField}
          className="flex items-center gap-1 px-1.5 py-0.5 text-[0.625rem] text-muted-foreground hover:text-foreground cursor-pointer transition-colors rounded [&_svg]:w-3 [&_svg]:h-3"
          title={`Sort by: ${sortLabel}`}
        >
          <ArrowUpDown />
          <span>{sortLabel}</span>
        </button>
        <button
          onClick={toggleSortOrder}
          className="px-1 py-0.5 text-[0.625rem] text-muted-foreground hover:text-foreground cursor-pointer transition-colors rounded"
          title={sortOrder === "desc" ? "Newest first" : "Oldest first"}
        >
          {sortOrder === "desc" ? "\u2193" : "\u2191"}
        </button>
        <div className="flex-1" />
        <button
          onClick={toggleAllFolders}
          className="flex items-center justify-center w-5 h-5 text-muted-foreground hover:text-foreground cursor-pointer transition-colors rounded [&_svg]:w-3 [&_svg]:h-3"
          title="Expand/collapse all"
        >
          <ChevronsUpDown />
        </button>
      </div>

      {/* Folder tree */}
      <div className="flex-1 overflow-y-auto" ref={folderTreeRef}>
        {listStatus === "loaded" && allNotes.length === 0 ? (
          // Empty state
          <div className="flex flex-col items-center justify-center h-full text-muted-foreground/60 px-6 py-8">
            <StickyNote className="w-10 h-10 mb-3 opacity-40" />
            <p className="text-xs font-medium">No notes yet</p>
            <p className="text-[0.625rem] mt-1 text-center">
              Click "New Note" below to get started
            </p>
          </div>
        ) : (
          folders.map((folder) => {
            const folderNotes = notesByFolder.get(folder) ?? [];
            const isExpanded = expandedFolders.has(folder);
            const { icon: FolderIcon, color: iconColor } = getFolderIconAndColor(folder);
            const count = folderNotes.length;

            if (searchQuery && count === 0) return null;

            return (
              <div key={folder}>
                <button
                  className="group flex items-center gap-1 w-full px-2 py-1 text-[0.6875rem] font-semibold uppercase tracking-wider text-muted-foreground cursor-pointer transition-colors hover:text-foreground hover:bg-accent/50 [&_svg]:w-3 [&_svg]:h-3"
                  onClick={() => toggleFolder(folder)}
                  onContextMenu={(e) => {
                    e.preventDefault();
                    setNoteCtx(null);
                    setFolderCtx({ folder, x: e.clientX, y: e.clientY });
                  }}
                >
                  {isExpanded ? (
                    <ChevronDown className="opacity-60" />
                  ) : (
                    <ChevronRight className="opacity-60" />
                  )}
                  {isExpanded ? (
                    <FolderOpen className={cn("opacity-70", iconColor)} />
                  ) : (
                    <FolderIcon className={cn("opacity-70", iconColor)} />
                  )}
                  <span className="flex-1 text-left truncate">{folder}</span>
                  <span className="text-[0.625rem] font-normal opacity-50 tabular-nums">
                    {count}
                  </span>
                  <Plus
                    className="w-3 h-3 opacity-0 group-hover:opacity-60 hover:!opacity-100 transition-opacity"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleNewNote(folder);
                    }}
                  />
                </button>

                {isExpanded && (
                  <div className="ml-2">
                    {folderNotes.length === 0 ? (
                      <div className="px-5 py-2 text-[0.625rem] text-muted-foreground/50 italic">
                        Empty
                      </div>
                    ) : (
                      folderNotes.map((note) => {
                        const isActive = activeTabId === note.id;
                        const isOpenTab = openTabIds?.includes(note.id) ?? false;
                        return (
                          <button
                            key={note.id}
                            data-note-id={note.id}
                            className={cn(
                              "flex items-center gap-1.5 w-full text-left px-2 py-[3px] rounded-sm cursor-pointer transition-colors group/item",
                              isActive
                                ? "bg-accent text-foreground"
                                : isOpenTab
                                  ? "bg-accent/30 text-foreground/80"
                                  : "text-muted-foreground hover:bg-accent/50 hover:text-foreground",
                            )}
                            onClick={() => selectNote(note.id)}
                            onContextMenu={(e) => {
                              e.preventDefault();
                              setFolderCtx(null);
                              setNoteCtx({
                                noteId: note.id,
                                noteLabel: note.label,
                                folder: note.folder_name || "Draft",
                                x: e.clientX,
                                y: e.clientY,
                              });
                            }}
                          >
                            <FileText className="w-3.5 h-3.5 shrink-0 opacity-50" />
                            <span className="flex-1 text-xs truncate leading-tight">
                              {note.label}
                            </span>
                            <span className="text-[0.625rem] opacity-40 tabular-nums shrink-0">
                              {formatTime(note.updated_at)}
                            </span>
                          </button>
                        );
                      })
                    )}
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

      {/* Bottom: New Note + New Folder */}
      <div className="shrink-0 px-2 py-1.5 border-t border-border/30 flex items-center gap-1">
        <button
          className="flex items-center gap-1.5 flex-1 px-2 py-1 text-[0.6875rem] text-muted-foreground cursor-pointer transition-colors hover:text-foreground hover:bg-accent/50 rounded-md [&_svg]:w-3 [&_svg]:h-3"
          onClick={() => handleNewNote("Draft")}
        >
          <Plus /> New Note
        </button>
        <button
          className="flex items-center justify-center w-7 h-7 text-muted-foreground cursor-pointer transition-colors hover:text-foreground hover:bg-accent/50 rounded-md [&_svg]:w-3.5 [&_svg]:h-3.5"
          onClick={() => setCreateFolderOpen(true)}
          title="New Folder"
        >
          <FolderPlus />
        </button>
      </div>

      {/* ── Folder context menu ────────────────────────────────────────── */}
      {folderCtx && (
        <>
          <div className="fixed inset-0 z-[110]" onClick={() => setFolderCtx(null)} />
          <div
            ref={ctxMenuRef}
            className="fixed z-[120] min-w-[160px] py-1 bg-card/95 backdrop-blur-2xl border border-border rounded-lg shadow-lg"
            style={{ left: folderCtx.x, top: folderCtx.y }}
          >
            <button
              className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
              onClick={() => { handleNewNote(folderCtx.folder); setFolderCtx(null); }}
            >
              <Plus className="w-3 h-3" /> New Note in {folderCtx.folder}
            </button>
            {!isDefaultFolder(folderCtx.folder) && (
              <>
                <div className="h-px bg-border/50 my-1" />
                <button
                  className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                  onClick={() => handleFolderRename(folderCtx.folder)}
                >
                  <FileText className="w-3 h-3" /> Rename Folder
                </button>
                <button
                  className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-destructive hover:bg-destructive/10 cursor-pointer transition-colors"
                  onClick={() => handleFolderDeleteAll(folderCtx.folder)}
                >
                  <Trash2 className="w-3 h-3" /> Delete All Notes
                </button>
              </>
            )}
          </div>
        </>
      )}

      {/* ── Note context menu ──────────────────────────────────────────── */}
      {noteCtx && (
        <>
          <div className="fixed inset-0 z-[110]" onClick={() => { setNoteCtx(null); setMoveSubmenu(false); }} />
          <div
            ref={ctxMenuRef}
            className="fixed z-[120] min-w-[160px] py-1 bg-card/95 backdrop-blur-2xl border border-border rounded-lg shadow-lg"
            style={{ left: noteCtx.x, top: noteCtx.y }}
          >
            <button
              className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
              onClick={() => { selectNote(noteCtx.noteId); setNoteCtx(null); }}
            >
              <FileText className="w-3 h-3" /> Open
            </button>
            <button
              className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
              onClick={() => { dispatch(copyNote(noteCtx.noteId)); setNoteCtx(null); }}
            >
              <Copy className="w-3 h-3" /> Duplicate
            </button>
            <button
              className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
              onClick={() => handleNoteExport(noteCtx.noteId, noteCtx.noteLabel)}
            >
              <Download className="w-3 h-3" /> Export as Markdown
            </button>
            <div className="h-px bg-border/50 my-1" />
            {/* Move to folder submenu */}
            <div className="relative">
              <button
                className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                onClick={() => setMoveSubmenu((v) => !v)}
              >
                <FolderInput className="w-3 h-3" /> Move to Folder
                <ChevronRight className="w-3 h-3 ml-auto" />
              </button>
              {moveSubmenu && (
                <div className="absolute left-full top-0 ml-1 min-w-[120px] max-h-[200px] overflow-auto py-1 bg-card/95 backdrop-blur-2xl border border-border rounded-lg shadow-lg">
                  {allFolders
                    .filter((f) => f !== noteCtx.folder)
                    .map((f) => (
                      <button
                        key={f}
                        className="w-full text-left px-3 py-1.5 text-[0.625rem] text-foreground hover:bg-accent cursor-pointer transition-colors"
                        onClick={() => {
                          dispatch(moveNoteToFolder({ noteId: noteCtx.noteId, folder: f }));
                          setNoteCtx(null);
                          setMoveSubmenu(false);
                        }}
                      >
                        {f}
                      </button>
                    ))}
                </div>
              )}
            </div>
            <div className="h-px bg-border/50 my-1" />
            <button
              className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-destructive hover:bg-destructive/10 cursor-pointer transition-colors"
              onClick={() => {
                dispatch(removeInstanceTab({ instanceId, noteId: noteCtx.noteId }));
                dispatch(deleteNote(noteCtx.noteId));
                setNoteCtx(null);
              }}
            >
              <Trash2 className="w-3 h-3" /> Delete Note
            </button>
          </div>
        </>
      )}

      {/* ── Dialogs ────────────────────────────────────────────────────── */}
      <CreateFolderDialog
        open={createFolderOpen}
        onOpenChange={setCreateFolderOpen}
        onConfirm={handleCreateFolder}
        existingFolders={allFolders}
      />

      {renameFolderTarget && (
        <RenameFolderDialog
          open={!!renameFolderTarget}
          onOpenChange={(open) => { if (!open) setRenameFolderTarget(null); }}
          onConfirm={handleRenameConfirm}
          currentName={renameFolderTarget}
          existingFolders={allFolders}
        />
      )}
    </div>
  );
}
