"use client";

// Layer 5: NoteSidebar
// Takes ONLY instanceId. Shows folder tree, search, note list.
// Highlights active tab and open tabs from the instance.
// All state from Redux selectors. All mutations via dispatch.
// ZERO PROP DRILLING.
//
// Features:
// - Search bar with instant filtering
// - Sort controls (field cycle + order toggle)
// - Expand/collapse all folders
// - Folder context menu (right-click: New Note, Rename, Delete All)
// - Note context menu (right-click: Open, Duplicate, Export, Move, Delete)
// - Auto-scroll to active note
// - Auto-expand folder of active note
// - Folder icons with colors from defaultFolders/folderCategories
// - Create Folder dialog with category picker
// - Rename Folder dialog
// - Empty state when no notes exist

import React, {
  useState,
  useCallback,
  useMemo,
  useRef,
  useEffect,
} from "react";
import { createPortal } from "react-dom";
import dynamic from "next/dynamic";
import {
  FileText,
  FolderOpen,
  Folder,
  ChevronDown,
  ChevronRight,
  Search,
  Plus,
  ArrowUpDown,
  ChevronsUpDown,
  FolderPlus,
  Copy,
  Download,
  FolderInput,
  Trash2,
  X,
  StickyNote,
  Layers,
  Clock,
  Building2,
  Kanban,
  ListTodo,
  Tag,
  RotateCcw,
} from "lucide-react";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import { selectUser } from "@/lib/redux/slices/userSlice";
import {
  selectOrganizationId,
  selectOrganizationName,
  selectScopeSelectionsContext,
  selectProjectId,
  selectProjectName,
  selectTaskId,
  selectTaskName,
} from "@/features/agent-context/redux/appContextSlice";
import { fetchEntitiesByScopes } from "@/features/agent-context/redux/scope/scopeAssignmentsSlice";
import {
  setInstanceActiveTab,
  addInstanceTab,
  removeInstanceTab,
  createAutogeneratedNote,
} from "../redux/slice";
import {
  fetchNotesList,
  fetchNoteContent,
  copyNote,
  deleteNote,
  restoreNote,
  moveNoteToFolder,
  fetchAllNoteScopes,
  fetchDeletedNotes,
} from "../redux/thunks";
import {
  selectAllNotesList,
  selectDeletedNotesList,
  selectInstanceActiveTab,
  selectInstanceTabs,
  selectNotesListStatus,
  selectAllFolders,
  selectNotesGroupedByScope,
  selectNoteScopesLoaded,
} from "../redux/selectors";
import {
  createFolder,
  renameFolder,
  deleteFolderNotes,
} from "../service/notesService";
import {
  selectAllAssignments,
  selectScopeNameMap,
  selectScopeTypeLabelMap,
} from "@/features/agent-context/redux/scope";
import { getFolderIconAndColor, isDefaultFolder } from "../utils/folderUtils";
import { CreateFolderDialog } from "./CreateFolderDialog";
import { RenameFolderDialog } from "./RenameFolderDialog";
import { cn } from "@/lib/utils";
import type { NoteRecord } from "../redux/notes.types";
import type { NoteSortField, NoteSortOrder, NoteGroupBy } from "../types";

const DirectContextSelection = dynamic(
  () => import("@/features/shell/components/sidebar/DirectContextSelection"),
  { ssr: false },
);

// ── Sort field labels ───────────────────────────────────────────────────────
const SORT_FIELDS: { field: NoteSortField; label: string }[] = [
  { field: "updated_at", label: "Modified" },
  { field: "label", label: "Name" },
  { field: "created_at", label: "Created" },
];

// ── Group-by modes ──────────────────────────────────────────────────────────
const GROUP_MODES: {
  mode: NoteGroupBy | "recent";
  label: string;
  icon: typeof Folder;
}[] = [
  { mode: "folder", label: "Folder", icon: Folder },
  { mode: "recent", label: "Recent", icon: Clock },
];

interface NoteSidebarProps {
  instanceId: string;
  /**
   * When provided, context menus are rendered via createPortal into this element
   * instead of as fixed-positioned children inside the sidebar DOM tree.
   * Pass `document.body` when the sidebar is inside a floating window to ensure
   * context menus appear above the window's stacking context.
   */
  contextMenuPortalTarget?: Element | null;
}

export function NoteSidebar({
  instanceId,
  contextMenuPortalTarget,
}: NoteSidebarProps) {
  const dispatch = useAppDispatch();
  const { id: userId } = useAppSelector(selectUser);

  // ── Redux state (memoized selectors — no new references) ──────────
  const allNotes = useAppSelector(selectAllNotesList);
  const activeTabId = useAppSelector(selectInstanceActiveTab(instanceId));
  const openTabIds = useAppSelector(selectInstanceTabs(instanceId));
  const listStatus = useAppSelector(selectNotesListStatus);
  const allFolders = useAppSelector(selectAllFolders);
  const scopeGrouped = useAppSelector(selectNotesGroupedByScope);
  const scopesLoaded = useAppSelector(selectNoteScopesLoaded);

  // ── Active context for filtering + grouping labels ──────────────────
  const activeOrgId = useAppSelector(selectOrganizationId);
  const activeProjectId = useAppSelector(selectProjectId);
  const activeTaskId = useAppSelector(selectTaskId);
  const scopeSelections = useAppSelector(selectScopeSelectionsContext);
  const orgName = useAppSelector(selectOrganizationName);
  const projName = useAppSelector(selectProjectName);
  const taskName = useAppSelector(selectTaskName);

  // ── Scope-filtered note IDs (fetched when scopes change) ──────────
  const activeScopeIds = useMemo(
    () => Object.values(scopeSelections).filter(Boolean) as string[],
    [scopeSelections],
  );
  const [scopeFilteredNoteIds, setScopeFilteredNoteIds] = useState<Set<string> | null>(null);
  const lastScopeKey = useRef("");

  useEffect(() => {
    const key = [...activeScopeIds].sort().join(",");
    if (key === lastScopeKey.current) return;
    lastScopeKey.current = key;
    if (activeScopeIds.length === 0) {
      setScopeFilteredNoteIds(null);
      return;
    }
    dispatch(
      fetchEntitiesByScopes({
        scope_ids: activeScopeIds,
        entity_type: "note",
        match_all: false,
      }),
    )
      .unwrap()
      .then((entities) =>
        setScopeFilteredNoteIds(new Set(entities.map((e) => e.entity_id))),
      )
      .catch(() => setScopeFilteredNoteIds(null));
  }, [dispatch, activeScopeIds]);

  // ── Filter notes by active context (org + scopes + project + task) ─
  const contextFiltered = useMemo(() => {
    let result = allNotes;
    if (activeOrgId) result = result.filter((n) => n.organization_id === activeOrgId);
    if (scopeFilteredNoteIds) result = result.filter((n) => scopeFilteredNoteIds.has(n.id));
    if (activeProjectId) result = result.filter((n) => n.project_id === activeProjectId);
    if (activeTaskId) result = result.filter((n) => n.task_id === activeTaskId);
    return result;
  }, [allNotes, activeOrgId, scopeFilteredNoteIds, activeProjectId, activeTaskId]);

  // ── Local UI state ─────────────────────────────────────────────────
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(() => {
    if (!activeTabId) return new Set<string>();
    const activeNote = allNotes.find((n) => n.id === activeTabId);
    if (activeNote?.folder_name) return new Set([activeNote.folder_name]);
    return new Set<string>();
  });
  const [sortField, setSortField] = useState<NoteSortField>("updated_at");
  const [sortOrder, setSortOrder] = useState<NoteSortOrder>("desc");
  const [groupBy, setGroupBy] = useState<NoteGroupBy | "recent">("folder");
  const [trashOpen, setTrashOpen] = useState(false);
  const trashFetchedRef = useRef(false);
  const deletedNotes = useAppSelector(selectDeletedNotesList);
  const [groupByDropdown, setGroupByDropdown] = useState(false);

  // ── Fetch scope assignments when switching to scope mode ────────────
  useEffect(() => {
    if (groupBy === "scope" && !scopesLoaded) {
      dispatch(fetchAllNoteScopes());
    }
  }, [dispatch, groupBy, scopesLoaded]);

  // Context menu state
  const [folderCtx, setFolderCtx] = useState<{
    folder: string;
    x: number;
    y: number;
  } | null>(null);
  const [noteCtx, setNoteCtx] = useState<{
    noteId: string;
    noteLabel: string;
    folder: string;
    x: number;
    y: number;
  } | null>(null);
  const [moveSubmenu, setMoveSubmenu] = useState(false);

  // DnD state
  const [draggedNoteId, setDraggedNoteId] = useState<string | null>(null);
  const [dropTargetFolder, setDropTargetFolder] = useState<string | null>(null);

  // Dialog state
  const [createFolderOpen, setCreateFolderOpen] = useState(false);
  const [renameFolderTarget, setRenameFolderTarget] = useState<string | null>(
    null,
  );

  // Refs
  const folderTreeRef = useRef<HTMLDivElement>(null);
  const ctxMenuRef = useRef<HTMLDivElement>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const searchFocusedRef = useRef(false);

  // ── Auto-expand folder of active note ──────────────────────────────
  useEffect(() => {
    if (!activeTabId) return;
    const note = allNotes.find((n) => n.id === activeTabId);
    if (note?.folder_name) {
      setExpandedFolders((prev) => {
        if (prev.has(note.folder_name!)) return prev;
        const next = new Set(prev);
        next.add(note.folder_name!);
        return next;
      });
    }
  }, [activeTabId, allNotes]);

  // ── Auto-scroll active note into view ──────────────────────────────
  useEffect(() => {
    if (!activeTabId || !folderTreeRef.current) return;
    const el = folderTreeRef.current.querySelector(
      `[data-note-id="${activeTabId}"]`,
    );
    el?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [activeTabId]);

  // ── Auto-scroll first search result into view ─────────────────────
  useEffect(() => {
    if (!searchQuery || !folderTreeRef.current) return;
    // Small delay to let the filtered list render
    const timer = setTimeout(() => {
      const firstNote = folderTreeRef.current?.querySelector("[data-note-id]");
      if (firstNote) {
        firstNote.scrollIntoView({ behavior: "smooth", block: "nearest" });
      }
    }, 50);
    return () => clearTimeout(timer);
  }, [searchQuery]);

  // ── Close context menus on outside click ──────────────────────────
  useEffect(() => {
    if (!folderCtx && !noteCtx) return;
    const handler = (e: MouseEvent) => {
      if (
        ctxMenuRef.current &&
        !ctxMenuRef.current.contains(e.target as Node)
      ) {
        setFolderCtx(null);
        setNoteCtx(null);
        setMoveSubmenu(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [folderCtx, noteCtx]);

  // ── Derived data ───────────────────────────────────────────────────
  const folders = useMemo(() => {
    const set = new Set<string>(allFolders);
    for (const n of allNotes) {
      if (n.folder_name) set.add(n.folder_name);
    }
    // Add "Uncategorized" if any notes lack a folder_name
    const hasOrphans = allNotes.some((n) => !n.folder_name);
    const result = allFolders.concat(
      Array.from(set)
        .filter((f) => !allFolders.includes(f))
        .sort(),
    );
    if (hasOrphans && !result.includes("Uncategorized")) {
      result.push("Uncategorized");
    }
    return result;
  }, [allNotes, allFolders]);

  // Filter notes by search (operates on context-filtered set)
  const filteredNotes = useMemo(() => {
    if (!searchQuery) return contextFiltered;
    const q = searchQuery.toLowerCase();
    return contextFiltered.filter(
      (n) =>
        n.label.toLowerCase().includes(q) ||
        n.content?.toLowerCase().includes(q) ||
        n.tags?.some((t) => t.toLowerCase().includes(q)),
    );
  }, [contextFiltered, searchQuery]);

  // Sort function
  const sortNotes = useCallback(
    (notes: NoteRecord[]) => {
      return [...notes].sort((a, b) => {
        let cmp = 0;
        if (sortField === "label") {
          cmp = a.label.localeCompare(b.label);
        } else if (sortField === "created_at") {
          cmp = (a.created_at ?? "").localeCompare(b.created_at ?? "");
        } else {
          cmp = (a.updated_at ?? "").localeCompare(b.updated_at ?? "");
        }
        return sortOrder === "desc" ? -cmp : cmp;
      });
    },
    [sortField, sortOrder],
  );

  // Group notes by selected mode
  const groupedNotes = useMemo(() => {
    const map = new Map<string, NoteRecord[]>();

    if (groupBy === "recent") {
      map.set("__all__", sortNotes(filteredNotes));
      return map;
    }

    // Scope grouping uses the pre-computed selector (many-to-many)
    if (groupBy === "scope") {
      // Apply search filter to the scope-grouped results
      const searchIds = searchQuery
        ? new Set(filteredNotes.map((n) => n.id))
        : null;
      for (const [key, notes] of scopeGrouped) {
        const filtered = searchIds
          ? notes.filter((n) => searchIds.has(n.id))
          : notes;
        if (filtered.length > 0) {
          map.set(key, sortNotes(filtered));
        }
      }
      return map;
    }

    for (const n of filteredNotes) {
      let key: string;
      switch (groupBy) {
        case "organization":
          key = n.organization_id || "__none__";
          break;
        case "project":
          key = n.project_id || "__none__";
          break;
        case "task":
          key = n.task_id || "__none__";
          break;
        default: // "folder"
          key = n.folder_name || "Uncategorized";
          break;
      }
      if (!map.has(key)) map.set(key, []);
      map.get(key)!.push(n);
    }

    // Sort each group
    for (const [key, notes] of map) {
      map.set(key, sortNotes(notes));
    }

    return map;
  }, [filteredNotes, groupBy, sortNotes]);

  // Get group labels for display
  const getGroupLabel = useCallback(
    (key: string): string => {
      if (key === "__all__") return "All Notes";
      if (key === "__none__" || key === "Unassigned") return "Unassigned";
      if (groupBy === "folder") return key;
      // Scope keys are already human-readable: "Department: SEO"
      if (groupBy === "scope") return key;
      // For org/project/task, the key is a UUID — show context name if matching
      if (groupBy === "organization" && orgName) return orgName;
      if (groupBy === "project" && projName) return projName;
      if (groupBy === "task" && taskName) return taskName;
      return key.slice(0, 8) + "...";
    },
    [groupBy, orgName, projName, taskName],
  );

  // Ordered group keys
  const groupKeys = useMemo(() => {
    if (groupBy === "folder") return folders;
    if (groupBy === "recent") return ["__all__"];
    if (groupBy === "scope") {
      // Sort scope groups alphabetically, "Unassigned" last
      const keys = Array.from(groupedNotes.keys());
      return keys.sort((a, b) => {
        if (a === "Unassigned") return 1;
        if (b === "Unassigned") return -1;
        return a.localeCompare(b);
      });
    }
    // For hierarchy modes, show assigned first, then unassigned
    const keys = Array.from(groupedNotes.keys());
    return keys.sort((a, b) => {
      if (a === "__none__") return 1;
      if (b === "__none__") return -1;
      return 0;
    });
  }, [groupBy, folders, groupedNotes]);

  // ── Handlers ───────────────────────────────────────────────────────
  const toggleFolder = useCallback((folder: string) => {
    setExpandedFolders((prev) => {
      const next = new Set(prev);
      if (next.has(folder)) next.delete(folder);
      else next.add(folder);
      return next;
    });
  }, []);

  // ── DnD handlers ──────────────────────────────────────────────────
  const handleNoteDragStart = useCallback(
    (e: React.DragEvent, noteId: string) => {
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData("text/plain", noteId);
      setDraggedNoteId(noteId);
    },
    [],
  );

  const handleNoteDragEnd = useCallback(() => {
    setDraggedNoteId(null);
    setDropTargetFolder(null);
  }, []);

  const handleFolderDragOver = useCallback(
    (e: React.DragEvent, folder: string) => {
      if (!draggedNoteId) return;
      e.preventDefault();
      e.dataTransfer.dropEffect = "move";
      setDropTargetFolder(folder);
    },
    [draggedNoteId],
  );

  const handleFolderDragLeave = useCallback(() => {
    setDropTargetFolder(null);
  }, []);

  const handleFolderDrop = useCallback(
    (e: React.DragEvent, targetFolder: string) => {
      e.preventDefault();
      const noteId = e.dataTransfer.getData("text/plain");
      if (!noteId) return;
      // Find the note's current folder to avoid no-op moves
      const note = allNotes.find((n) => n.id === noteId);
      if (note && note.folder_name !== targetFolder) {
        dispatch(moveNoteToFolder({ noteId, folder: targetFolder }));
      }
      setDraggedNoteId(null);
      setDropTargetFolder(null);
    },
    [dispatch, allNotes],
  );

  const toggleAllFolders = useCallback(() => {
    setExpandedFolders((prev) => {
      const allExpanded = folders.every((f) => prev.has(f));
      return allExpanded ? new Set<string>() : new Set(folders);
    });
  }, [folders]);

  const cycleSortField = useCallback(() => {
    setSortField((prev) => {
      const idx = SORT_FIELDS.findIndex((s) => s.field === prev);
      return SORT_FIELDS[(idx + 1) % SORT_FIELDS.length].field;
    });
  }, []);

  const toggleSortOrder = useCallback(() => {
    setSortOrder((prev) => (prev === "desc" ? "asc" : "desc"));
  }, []);

  const selectNote = useCallback(
    (noteId: string) => {
      dispatch(addInstanceTab({ instanceId, noteId }));
      dispatch(setInstanceActiveTab({ instanceId, noteId }));
      dispatch(fetchNoteContent(noteId));
    },
    [dispatch, instanceId],
  );

  const handleNewNote = useCallback(
    (folder: string) => {
      if (!userId) return;
      const existing = allNotes.find(
        (n) =>
          n._isAutogenerated && !n.content?.trim() && n.folder_name === folder,
      );
      if (existing) {
        selectNote(existing.id);
        return;
      }
      const id = crypto.randomUUID();
      dispatch(createAutogeneratedNote({ id, userId, folder, instanceId }));
    },
    [dispatch, instanceId, userId, allNotes, selectNote],
  );

  // ── Folder context menu actions ────────────────────────────────────
  const handleFolderRename = useCallback((folder: string) => {
    setRenameFolderTarget(folder);
    setFolderCtx(null);
  }, []);

  const handleFolderDeleteAll = useCallback(
    async (folder: string) => {
      setFolderCtx(null);
      const count = (groupedNotes.get(folder) ?? []).length;
      if (count === 0) return;
      try {
        await deleteFolderNotes(folder);
        // Re-fetch notes list to reflect deletions
        dispatch(fetchNotesList());
      } catch {
        // Error handled in service
      }
    },
    [dispatch, groupedNotes],
  );

  const handleRenameConfirm = useCallback(
    async (newName: string) => {
      if (!renameFolderTarget) return;
      try {
        await renameFolder(renameFolderTarget, newName);
        // Re-fetch notes list to reflect renamed folder_name
        dispatch(fetchNotesList());
      } catch {
        // Error handled in service
      }
    },
    [dispatch, renameFolderTarget],
  );

  // ── Note context menu actions ──────────────────────────────────────
  const handleNoteExport = useCallback(
    (noteId: string, label: string) => {
      const note = allNotes.find((n) => n.id === noteId);
      if (!note) return;
      const blob = new Blob([note.content ?? ""], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${label}.md`;
      a.click();
      URL.revokeObjectURL(url);
      setNoteCtx(null);
    },
    [allNotes],
  );

  // ── Create folder handler ──────────────────────────────────────────
  const handleCreateFolder = useCallback(
    async (folderName: string) => {
      try {
        // Create the note_folders record first
        await createFolder(folderName);
        // Then create a new note in that folder (which will resolve folder_id)
        handleNewNote(folderName);
      } catch {
        // Fall back to just creating the note
        handleNewNote(folderName);
      }
    },
    [handleNewNote],
  );

  // ── Format time ────────────────────────────────────────────────────
  const formatTime = (dateStr: string | null | undefined) => {
    if (!dateStr) return "";
    const d = new Date(dateStr);
    const mins = Math.floor((Date.now() - d.getTime()) / 60000);
    if (mins < 1) return "now";
    if (mins < 60) return `${mins}m`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `${hrs}h`;
    const days = Math.floor(hrs / 24);
    if (days < 7) return `${days}d`;
    return d.toLocaleDateString(undefined, { month: "short", day: "numeric" });
  };

  const sortLabel =
    SORT_FIELDS.find((s) => s.field === sortField)?.label ?? "Modified";

  // ── Render ─────────────────────────────────────────────────────────
  return (
    <div className="flex flex-col h-full min-h-0">
      {/* Search */}
      <div className="shrink-0 px-2 py-1.5 border-b border-border/30">
        <div className="flex items-center gap-1.5 px-2 py-1 bg-muted/50 rounded-md">
          <Search className="w-3 h-3 text-muted-foreground shrink-0" />
          <input
            ref={searchInputRef}
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            onFocus={() => { searchFocusedRef.current = true; }}
            onBlur={() => {
              // Defer the blur check — if focus was stolen by a re-render,
              // restore it on the next frame
              const wasFocused = searchFocusedRef.current;
              searchFocusedRef.current = false;
              if (wasFocused && searchQuery) {
                requestAnimationFrame(() => {
                  if (document.activeElement?.tagName === "TEXTAREA" || document.activeElement?.tagName === "BODY") {
                    searchInputRef.current?.focus();
                  }
                });
              }
            }}
            placeholder="Search notes..."
            className="flex-1 min-w-0 bg-transparent text-xs outline-none placeholder:text-muted-foreground/50"
            style={{ fontSize: "16px" }}
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery("")}
              className="text-muted-foreground hover:text-foreground cursor-pointer [&_svg]:w-3 [&_svg]:h-3"
            >
              <X />
            </button>
          )}
        </div>
      </div>

      {/* Context filter (org/scopes/project/task — filters sidebar notes) */}
      <div className="shrink-0 border-b border-border/20">
        <DirectContextSelection />
      </div>

      {/* Toolbar: group-by + sort + expand/collapse */}
      <div className="shrink-0 flex items-center gap-1 px-2 py-1 border-b border-border/20">
        {/* Group-by dropdown */}
        <div className="relative">
          <button
            onClick={() => setGroupByDropdown((v) => !v)}
            className="flex items-center gap-1 px-1.5 py-0.5 text-[0.625rem] text-muted-foreground hover:text-foreground cursor-pointer transition-colors rounded [&_svg]:w-3 [&_svg]:h-3"
            title="Group by"
          >
            <Layers />
            <span>
              {GROUP_MODES.find((m) => m.mode === groupBy)?.label ?? "Folder"}
            </span>
            <ChevronDown className="w-2! h-2! opacity-50" />
          </button>
          {groupByDropdown && (
            <>
              <div
                className="fixed inset-0 z-[100]"
                onClick={() => setGroupByDropdown(false)}
              />
              <div className="absolute left-0 top-full mt-1 z-[110] min-w-[130px] py-1 bg-card/95 backdrop-blur-2xl border border-border rounded-lg shadow-lg">
                {GROUP_MODES.map((m) => {
                  const Icon = m.icon;
                  return (
                    <button
                      key={m.mode}
                      className={cn(
                        "flex items-center gap-2 w-full px-3 py-1.5 text-[0.625rem] cursor-pointer transition-colors",
                        groupBy === m.mode
                          ? "bg-primary/10 text-primary font-medium"
                          : "text-foreground hover:bg-accent",
                      )}
                      onClick={() => {
                        setGroupBy(m.mode);
                        setGroupByDropdown(false);
                      }}
                    >
                      <Icon className="w-3 h-3" /> {m.label}
                    </button>
                  );
                })}
              </div>
            </>
          )}
        </div>

        <button
          onClick={cycleSortField}
          className="flex items-center gap-1 px-1.5 py-0.5 text-[0.625rem] text-muted-foreground hover:text-foreground cursor-pointer transition-colors rounded [&_svg]:w-3 [&_svg]:h-3"
          title={`Sort by: ${sortLabel}`}
        >
          <ArrowUpDown />
          <span>{sortLabel}</span>
        </button>
        <button
          onClick={toggleSortOrder}
          className="px-1 py-0.5 text-[0.625rem] text-muted-foreground hover:text-foreground cursor-pointer transition-colors rounded"
          title={sortOrder === "desc" ? "Newest first" : "Oldest first"}
        >
          {sortOrder === "desc" ? "\u2193" : "\u2191"}
        </button>
        <div className="flex-1" />
        {groupBy !== "recent" && (
          <button
            onClick={toggleAllFolders}
            className="flex items-center justify-center w-5 h-5 text-muted-foreground hover:text-foreground cursor-pointer transition-colors rounded [&_svg]:w-3 [&_svg]:h-3"
            title="Expand/collapse all"
          >
            <ChevronsUpDown />
          </button>
        )}
      </div>

      {/* Note list — grouped or flat */}
      <div className="flex-1 overflow-y-auto" ref={folderTreeRef}>
        {listStatus === "loaded" && allNotes.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full text-muted-foreground/60 px-6 py-8">
            <StickyNote className="w-10 h-10 mb-3 opacity-40" />
            <p className="text-xs font-medium">No notes yet</p>
            <p className="text-[0.625rem] mt-1 text-center">
              Click "New Note" below to get started
            </p>
          </div>
        ) : groupBy === "recent" ? (
          /* ── Recent mode: flat sorted list ──────────────────────── */
          <div className="ml-1">
            {(groupedNotes.get("__all__") ?? []).map((note) => {
              const isActive = activeTabId === note.id;
              const isOpenTab = openTabIds?.includes(note.id) ?? false;
              return (
                <button
                  key={note.id}
                  data-note-id={note.id}
                  className={cn(
                    "flex items-center gap-1.5 w-full text-left px-2 py-[3px] rounded-sm cursor-pointer transition-colors group/item",
                    isActive
                      ? "bg-accent text-foreground"
                      : isOpenTab
                        ? "bg-accent/30 text-foreground/80"
                        : "text-muted-foreground hover:bg-accent/50 hover:text-foreground",
                  )}
                  onClick={() => selectNote(note.id)}
                  onContextMenu={(e) => {
                    e.preventDefault();
                    setFolderCtx(null);
                    setNoteCtx({
                      noteId: note.id,
                      noteLabel: note.label,
                      folder: note.folder_name || "Uncategorized",
                      x: e.clientX,
                      y: e.clientY,
                    });
                  }}
                >
                  <FileText className="w-3.5 h-3.5 shrink-0 opacity-50" />
                  <span className="flex-1 text-xs truncate leading-tight">
                    {note.label}
                  </span>
                  <span className="text-[0.5625rem] opacity-30 shrink-0 truncate max-w-[50px]">
                    {note.folder_name || "Draft"}
                  </span>
                  <span className="text-[0.625rem] opacity-40 tabular-nums shrink-0">
                    {formatTime(note.updated_at)}
                  </span>
                </button>
              );
            })}
          </div>
        ) : (
          /* ── Grouped mode: collapsible sections ──────────────────── */
          groupKeys.map((groupKey) => {
            const groupNotes = groupedNotes.get(groupKey) ?? [];
            const isExpanded = expandedFolders.has(groupKey);
            const label = getGroupLabel(groupKey);
            const count = groupNotes.length;

            // For folder mode, use folder icons with colors
            const isFolderMode = groupBy === "folder";
            const { icon: FolderIcon, color: iconColor } = isFolderMode
              ? getFolderIconAndColor(groupKey)
              : {
                  icon:
                    GROUP_MODES.find((m) => m.mode === groupBy)?.icon ?? Folder,
                  color: undefined,
                };

            if (searchQuery && count === 0) return null;

            return (
              <div
                key={groupKey}
                onDragOver={
                  isFolderMode
                    ? (e) => handleFolderDragOver(e, groupKey)
                    : undefined
                }
                onDragLeave={isFolderMode ? handleFolderDragLeave : undefined}
                onDrop={
                  isFolderMode
                    ? (e) => handleFolderDrop(e, groupKey)
                    : undefined
                }
              >
                <button
                  className={cn(
                    "group flex items-center gap-1 w-full px-2 py-1 text-[0.6875rem] font-semibold uppercase tracking-wider text-muted-foreground cursor-pointer transition-colors hover:text-foreground hover:bg-accent/50 [&_svg]:w-3 [&_svg]:h-3",
                    isFolderMode &&
                      dropTargetFolder === groupKey &&
                      "bg-primary/10 border-l-2 border-primary",
                  )}
                  onClick={() => toggleFolder(groupKey)}
                  onContextMenu={
                    isFolderMode
                      ? (e) => {
                          e.preventDefault();
                          setNoteCtx(null);
                          setFolderCtx({
                            folder: groupKey,
                            x: e.clientX,
                            y: e.clientY,
                          });
                        }
                      : undefined
                  }
                >
                  {isExpanded ? (
                    <ChevronDown className="opacity-60" />
                  ) : (
                    <ChevronRight className="opacity-60" />
                  )}
                  {isExpanded ? (
                    <FolderOpen className={cn("opacity-70", iconColor)} />
                  ) : (
                    <FolderIcon className={cn("opacity-70", iconColor)} />
                  )}
                  <span className="flex-1 text-left truncate">{label}</span>
                  <span className="text-[0.625rem] font-normal opacity-50 tabular-nums">
                    {count}
                  </span>
                  {isFolderMode && (
                    <Plus
                      className="w-3 h-3 opacity-0 group-hover:opacity-60 hover:!opacity-100 transition-opacity"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleNewNote(groupKey);
                      }}
                    />
                  )}
                </button>

                {isExpanded && (
                  <div className="ml-2">
                    {groupNotes.length === 0 ? (
                      <div className="px-5 py-2 text-[0.625rem] text-muted-foreground/50 italic">
                        Empty
                      </div>
                    ) : (
                      groupNotes.map((note) => {
                        const isActive = activeTabId === note.id;
                        const isOpenTab =
                          openTabIds?.includes(note.id) ?? false;
                        const isDragging = draggedNoteId === note.id;
                        return (
                          <button
                            key={note.id}
                            data-note-id={note.id}
                            draggable={isFolderMode}
                            onDragStart={
                              isFolderMode
                                ? (e) => handleNoteDragStart(e, note.id)
                                : undefined
                            }
                            onDragEnd={
                              isFolderMode ? handleNoteDragEnd : undefined
                            }
                            className={cn(
                              "flex items-center gap-1.5 w-full text-left px-2 py-[3px] rounded-sm cursor-pointer transition-colors group/item",
                              isActive
                                ? "bg-accent text-foreground"
                                : isOpenTab
                                  ? "bg-accent/30 text-foreground/80"
                                  : "text-muted-foreground hover:bg-accent/50 hover:text-foreground",
                              isDragging && "opacity-40",
                            )}
                            onClick={() => selectNote(note.id)}
                            onContextMenu={(e) => {
                              e.preventDefault();
                              setFolderCtx(null);
                              setNoteCtx({
                                noteId: note.id,
                                noteLabel: note.label,
                                folder: note.folder_name || "Uncategorized",
                                x: e.clientX,
                                y: e.clientY,
                              });
                            }}
                          >
                            <FileText className="w-3.5 h-3.5 shrink-0 opacity-50" />
                            <span className="flex-1 text-xs truncate leading-tight">
                              {note.label}
                            </span>
                            <span className="text-[0.625rem] opacity-40 tabular-nums shrink-0">
                              {formatTime(note.updated_at)}
                            </span>
                          </button>
                        );
                      })
                    )}
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

      {/* Bottom: New Note + New Folder */}
      <div className="shrink-0 px-2 py-1.5 border-t border-border/30 flex items-center gap-1">
        <button
          className="flex items-center gap-1.5 flex-1 px-2 py-1 text-[0.6875rem] text-muted-foreground cursor-pointer transition-colors hover:text-foreground hover:bg-accent/50 rounded-md [&_svg]:w-3 [&_svg]:h-3"
          onClick={() => handleNewNote("Draft")}
        >
          <Plus /> New Note
        </button>
        <button
          className="flex items-center justify-center w-7 h-7 text-muted-foreground cursor-pointer transition-colors hover:text-foreground hover:bg-accent/50 rounded-md [&_svg]:w-3.5 [&_svg]:h-3.5"
          onClick={() => setCreateFolderOpen(true)}
          title="New Folder"
        >
          <FolderPlus />
        </button>
      </div>

      {/* ── Folder context menu ────────────────────────────────────────── */}
      {folderCtx &&
        (() => {
          const zBackdrop = contextMenuPortalTarget ? "z-[9980]" : "z-[110]";
          const zMenu = contextMenuPortalTarget ? "z-[9990]" : "z-[120]";
          const content = (
            <>
              <div
                className={`fixed inset-0 ${zBackdrop}`}
                onClick={() => setFolderCtx(null)}
              />
              <div
                ref={ctxMenuRef}
                className={`fixed ${zMenu} min-w-[160px] py-1 bg-card/95 backdrop-blur-2xl border border-border rounded-lg shadow-lg`}
                style={{ left: folderCtx.x, top: folderCtx.y }}
              >
                <button
                  className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                  onClick={() => {
                    handleNewNote(folderCtx.folder);
                    setFolderCtx(null);
                  }}
                >
                  <Plus className="w-3 h-3" /> New Note in {folderCtx.folder}
                </button>
                {!isDefaultFolder(folderCtx.folder) && (
                  <>
                    <div className="h-px bg-border/50 my-1" />
                    <button
                      className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                      onClick={() => handleFolderRename(folderCtx.folder)}
                    >
                      <FileText className="w-3 h-3" /> Rename Folder
                    </button>
                    <button
                      className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-destructive hover:bg-destructive/10 cursor-pointer transition-colors"
                      onClick={() => handleFolderDeleteAll(folderCtx.folder)}
                    >
                      <Trash2 className="w-3 h-3" /> Delete All Notes
                    </button>
                  </>
                )}
              </div>
            </>
          );
          return contextMenuPortalTarget
            ? createPortal(content, contextMenuPortalTarget)
            : content;
        })()}

      {/* ── Note context menu ──────────────────────────────────────────── */}
      {noteCtx &&
        (() => {
          const zBackdrop = contextMenuPortalTarget ? "z-[9980]" : "z-[110]";
          const zMenu = contextMenuPortalTarget ? "z-[9990]" : "z-[120]";
          const content = (
            <>
              <div
                className={`fixed inset-0 ${zBackdrop}`}
                onClick={() => {
                  setNoteCtx(null);
                  setMoveSubmenu(false);
                }}
              />
              <div
                ref={ctxMenuRef}
                className={`fixed ${zMenu} min-w-[160px] py-1 bg-card/95 backdrop-blur-2xl border border-border rounded-lg shadow-lg`}
                style={{ left: noteCtx.x, top: noteCtx.y }}
              >
                <button
                  className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                  onClick={() => {
                    selectNote(noteCtx.noteId);
                    setNoteCtx(null);
                  }}
                >
                  <FileText className="w-3 h-3" /> Open
                </button>
                <button
                  className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                  onClick={() => {
                    dispatch(copyNote(noteCtx.noteId));
                    setNoteCtx(null);
                  }}
                >
                  <Copy className="w-3 h-3" /> Duplicate
                </button>
                <button
                  className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                  onClick={() =>
                    handleNoteExport(noteCtx.noteId, noteCtx.noteLabel)
                  }
                >
                  <Download className="w-3 h-3" /> Export as Markdown
                </button>
                <div className="h-px bg-border/50 my-1" />
                {/* Move to folder submenu */}
                <div className="relative">
                  <button
                    className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                    onClick={() => setMoveSubmenu((v) => !v)}
                  >
                    <FolderInput className="w-3 h-3" /> Move to Folder
                    <ChevronRight className="w-3 h-3 ml-auto" />
                  </button>
                  {moveSubmenu && (
                    <div className="absolute left-full top-0 ml-1 min-w-[120px] max-h-[200px] overflow-auto py-1 bg-card/95 backdrop-blur-2xl border border-border rounded-lg shadow-lg">
                      {allFolders
                        .filter((f) => f !== noteCtx.folder)
                        .map((f) => (
                          <button
                            key={f}
                            className="w-full text-left px-3 py-1.5 text-[0.625rem] text-foreground hover:bg-accent cursor-pointer transition-colors"
                            onClick={() => {
                              dispatch(
                                moveNoteToFolder({
                                  noteId: noteCtx.noteId,
                                  folder: f,
                                }),
                              );
                              setNoteCtx(null);
                              setMoveSubmenu(false);
                            }}
                          >
                            {f}
                          </button>
                        ))}
                    </div>
                  )}
                </div>
                <div className="h-px bg-border/50 my-1" />
                <button
                  className="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-destructive hover:bg-destructive/10 cursor-pointer transition-colors"
                  onClick={() => {
                    dispatch(
                      removeInstanceTab({ instanceId, noteId: noteCtx.noteId }),
                    );
                    dispatch(deleteNote(noteCtx.noteId));
                    setNoteCtx(null);
                  }}
                >
                  <Trash2 className="w-3 h-3" /> Delete Note
                </button>
              </div>
            </>
          );
          return contextMenuPortalTarget
            ? createPortal(content, contextMenuPortalTarget)
            : content;
        })()}

      {/* ── Trash section ──────────────────────────────────────────────── */}
      <div className="shrink-0 border-t border-border/20">
        <button
          onClick={() => {
            setTrashOpen((v) => !v);
            if (!trashFetchedRef.current) {
              trashFetchedRef.current = true;
              dispatch(fetchDeletedNotes());
            }
          }}
          className="flex items-center gap-1.5 w-full px-3 py-1.5 text-[0.625rem] text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
        >
          <Trash2 className="w-3 h-3" />
          <span>Trash</span>
          {deletedNotes.length > 0 && (
            <span className="text-[0.5rem] bg-muted px-1 rounded">{deletedNotes.length}</span>
          )}
          <ChevronDown className={cn("w-2.5 h-2.5 ml-auto transition-transform", trashOpen && "rotate-180")} />
        </button>
        {trashOpen && (
          <div className="max-h-40 overflow-y-auto px-1 pb-1">
            {deletedNotes.length === 0 ? (
              <p className="text-[0.5625rem] text-muted-foreground/50 px-3 py-2">Trash is empty</p>
            ) : (
              deletedNotes.map((note) => (
                <div
                  key={note.id}
                  className="flex items-center gap-1.5 px-2 py-1 rounded-sm group/trash"
                >
                  <FileText className="w-3 h-3 text-muted-foreground/40 shrink-0" />
                  <span className="text-[0.625rem] text-muted-foreground truncate flex-1">
                    {note.label || "Untitled"}
                  </span>
                  <button
                    onClick={() => dispatch(restoreNote(note.id))}
                    className="opacity-0 group-hover/trash:opacity-100 text-muted-foreground hover:text-foreground transition-opacity cursor-pointer [&_svg]:w-3 [&_svg]:h-3"
                    title="Restore"
                  >
                    <RotateCcw />
                  </button>
                </div>
              ))
            )}
          </div>
        )}
      </div>

      {/* ── Dialogs ────────────────────────────────────────────────────── */}
      <CreateFolderDialog
        open={createFolderOpen}
        onOpenChange={setCreateFolderOpen}
        onConfirm={handleCreateFolder}
        existingFolders={allFolders}
      />

      {renameFolderTarget && (
        <RenameFolderDialog
          open={!!renameFolderTarget}
          onOpenChange={(open) => {
            if (!open) setRenameFolderTarget(null);
          }}
          onConfirm={handleRenameConfirm}
          currentName={renameFolderTarget}
          existingFolders={allFolders}
        />
      )}
    </div>
  );
}
