"use client";

// Layer 6: NotesView — Instance wrapper.
// Registers a unique notes instance on mount, cleans up on unmount.
// Renders sidebar + tab bar + active note editor.
// Can be used as full page, floating window, or single-note embed.
// ZERO PROP DRILLING — each child receives only an instanceId or noteId.

import React, { useEffect, useRef, useCallback, useState } from "react";
import dynamic from "next/dynamic";
import {
  FileText,
  SplitSquareHorizontal,
  PilcrowRight,
  Columns,
  Eye,
  History,
} from "lucide-react";
import { useIsMobile } from "@/hooks/use-mobile";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import { selectUser } from "@/lib/redux/slices/userSlice";

const MobileNotesView = dynamic(() => import("./mobile/MobileNotesView"), {
  ssr: false,
});

const NoteVersionHistory = dynamic(
  () =>
    import("@/app/(ssr)/ssr/notes/_components/NoteVersionHistory").then(
      (mod) => ({ default: mod.NoteVersionHistory }),
    ),
  { ssr: false },
);
import {
  registerInstance,
  unregisterInstance,
  setInstanceActiveTab,
  addInstanceTab,
  removeInstanceTab,
  createAutogeneratedNote,
  setNoteEditorMode,
} from "../redux/slice";
import { fetchNotesList, fetchNoteContent, saveNote } from "../redux/thunks";
import {
  fetchScopeTypes,
  fetchScopes,
} from "@/features/agent-context/redux/scope";
import { selectOrganizationId } from "@/features/agent-context/redux/appContextSlice";
import {
  selectOtherUsersActive,
  selectActiveNoteEditedByOthers,
  selectInstanceActiveTab,
  selectInstanceTabs,
  selectNoteEditorMode,
} from "../redux/selectors";
import PageHeader from "@/features/shell/components/header/PageHeader";
import { NotesInstanceProvider } from "../context/NotesInstanceContext";
import { NoteContentEditor } from "./NoteContentEditor";
import { NoteMetadataBar } from "./NoteMetadataBar";
import { NoteTabBar } from "./NoteTabBar";
import { NoteSidebar } from "./NoteSidebar";
import { cn } from "@/lib/utils";

export interface NotesViewConfig {
  /** Show the sidebar with folder tree (default: true) */
  showSidebar?: boolean;
  /** Show the tab bar (default: true) */
  showTabs?: boolean;
  /** Lock to a single note — no tabs, no sidebar (default: null) */
  singleNote?: string | null;
  /** Custom instance ID (default: auto-generated) */
  instanceId?: string;
  /** Tabs to restore from DB session (skips URL hydration for these) */
  initialTabs?: string[];
  /** Active tab to restore from DB session */
  initialActiveTab?: string | null;
}

export interface NotesViewProps {
  config?: NotesViewConfig;
  className?: string;
}

export function NotesView({ config, className }: NotesViewProps) {
  const dispatch = useAppDispatch();
  const { id: userId } = useAppSelector(selectUser);
  const isMobile = useIsMobile();

  const showSidebar = config?.showSidebar ?? true;
  const showTabs = config?.showTabs ?? true;
  const [showHistory, setShowHistory] = useState(false);
  const singleNote = config?.singleNote ?? null;
  const initialTabs = config?.initialTabs;
  const initialActiveTab = config?.initialActiveTab;

  // ── Generate or use provided instance ID ──────────────────────────
  const instanceIdRef = useRef(
    config?.instanceId ??
      `notes-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
  );
  const instanceId = instanceIdRef.current;

  // ── Register instance on mount, unregister on unmount ─────────────
  useEffect(() => {
    dispatch(registerInstance(instanceId));
    return () => {
      dispatch(unregisterInstance(instanceId));
    };
  }, [dispatch, instanceId]);

  // ── Restore tabs from DB session (initialTabs wins over URL params) ─
  const restoredFromDbRef = useRef(false);
  useEffect(() => {
    if (restoredFromDbRef.current) return;
    if (!initialTabs || initialTabs.length === 0) return;
    restoredFromDbRef.current = true;

    initialTabs.forEach((noteId) => {
      dispatch(addInstanceTab({ instanceId, noteId }));
      dispatch(fetchNoteContent(noteId));
    });

    const activeId =
      initialActiveTab && initialTabs.includes(initialActiveTab)
        ? initialActiveTab
        : initialTabs[0];
    dispatch(setInstanceActiveTab({ instanceId, noteId: activeId }));
    // Only run once on mount — initialTabs/initialActiveTab are stable
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dispatch, instanceId]);

  // ── Fetch notes list + scope data on mount ──────────────────────────
  const orgId = useAppSelector(selectOrganizationId);
  const fetchedRef = useRef(false);
  useEffect(() => {
    if (!fetchedRef.current && userId) {
      fetchedRef.current = true;
      dispatch(fetchNotesList());
      // Pre-fetch scope types + scopes so ScopePicker and ScopeTagsDisplay work
      dispatch(fetchScopeTypes());
      dispatch(fetchScopes());
    }
  }, [dispatch, userId]);

  // ── Single note mode: set active immediately ──────────────────────
  useEffect(() => {
    if (singleNote) {
      dispatch(addInstanceTab({ instanceId, noteId: singleNote }));
      dispatch(setInstanceActiveTab({ instanceId, noteId: singleNote }));
      dispatch(fetchNoteContent(singleNote));
    }
  }, [dispatch, instanceId, singleNote]);

  const activeTabId = useAppSelector(selectInstanceActiveTab(instanceId));
  const openTabs = useAppSelector(selectInstanceTabs(instanceId));
  const othersActive = useAppSelector(selectOtherUsersActive);
  const activeNoteEditedByOthers = useAppSelector(
    selectActiveNoteEditedByOthers,
  );
  const editorMode =
    useAppSelector(
      activeTabId ? selectNoteEditorMode(activeTabId) : () => "plain",
    ) ?? "plain";

  const setMode = useCallback(
    (mode: string) => {
      if (activeTabId) dispatch(setNoteEditorMode({ id: activeTabId, mode }));
    },
    [dispatch, activeTabId],
  );

  // ── Keyboard shortcuts ───────────────────────────────────────────
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      const mod = e.ctrlKey || e.metaKey;

      // Ctrl+S — save active note
      if (mod && e.key === "s") {
        e.preventDefault();
        if (activeTabId) dispatch(saveNote(activeTabId));
        return;
      }

      // Ctrl+W — close active tab
      if (mod && e.key === "w") {
        e.preventDefault();
        if (activeTabId) {
          dispatch(removeInstanceTab({ instanceId, noteId: activeTabId }));
        }
        return;
      }

      // Ctrl+Tab — cycle to next tab
      if (mod && e.key === "Tab") {
        e.preventDefault();
        if (openTabs && openTabs.length > 1 && activeTabId) {
          const idx = openTabs.indexOf(activeTabId);
          const next = openTabs[(idx + 1) % openTabs.length];
          dispatch(setInstanceActiveTab({ instanceId, noteId: next }));
          dispatch(fetchNoteContent(next));
        }
        return;
      }
    };

    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [dispatch, instanceId, activeTabId, openTabs]);

  const modeBtnClass = (mode: string) =>
    cn(
      "flex items-center gap-1 px-2.5 py-0.5 text-[0.6875rem] font-medium rounded-full transition-colors cursor-pointer",
      "[&_svg]:w-3.5 [&_svg]:h-3.5",
      editorMode === mode
        ? "bg-[var(--shell-glass-bg-active)] text-[var(--shell-nav-text-hover)]"
        : "text-[var(--shell-nav-text)] hover:text-[var(--shell-nav-text-hover)]",
    );

  // ── Mobile: render MobileNotesView instead of desktop layout ──────
  if (isMobile) {
    return <MobileNotesView />;
  }

  // ── Desktop Render ────────────────────────────────────────────────
  return (
    <NotesInstanceProvider value={instanceId}>
      <div className={`flex h-full w-full min-h-0 ${className ?? ""}`}>
        {/* ── Header center: View mode buttons (portaled into shell header) */}
        {activeTabId && (
          <PageHeader>
            <div className="shell-glass flex items-center gap-0.5 rounded-full p-0.5">
              <button
                className={modeBtnClass("plain")}
                onClick={() => setMode("plain")}
              >
                <FileText /> Edit
              </button>
              <button
                className={cn(modeBtnClass("split"), "max-lg:hidden")}
                onClick={() => setMode("split")}
              >
                <SplitSquareHorizontal /> Split
              </button>
              <button
                className={cn(modeBtnClass("wysiwyg"), "max-lg:hidden")}
                onClick={() => setMode("wysiwyg")}
              >
                <PilcrowRight /> Rich
              </button>
              <button
                className={cn(modeBtnClass("markdown-split"), "max-lg:hidden")}
                onClick={() => setMode("markdown-split")}
              >
                <Columns /> MD Split
              </button>
              <button
                className={modeBtnClass("preview")}
                onClick={() => setMode("preview")}
              >
                <Eye /> Preview
              </button>
              <div className="w-px h-4 bg-border/30 mx-0.5" />
              <button
                className={cn(
                  "flex items-center gap-1 px-2.5 py-0.5 text-[0.6875rem] font-medium rounded-full transition-colors cursor-pointer [&_svg]:w-3.5 [&_svg]:h-3.5",
                  showHistory
                    ? "bg-[var(--shell-glass-bg-active)] text-[var(--shell-nav-text-hover)]"
                    : "text-[var(--shell-nav-text)] hover:text-[var(--shell-nav-text-hover)]",
                )}
                onClick={() => setShowHistory((v) => !v)}
              >
                <History /> History
              </button>
            </div>
          </PageHeader>
        )}

        {/* Layer 5: Sidebar */}
        {showSidebar && !singleNote && (
          <div className="w-[280px] shrink-0 border-r border-border flex flex-col min-h-0 max-lg:hidden">
            <NoteSidebar instanceId={instanceId} />
          </div>
        )}

        {/* Main content area */}
        <div className="flex-1 flex min-w-0 min-h-0">
          {/* Editor column */}
          <div className="flex-1 flex flex-col min-w-0 min-h-0">
            {/* Layer 4: Tab bar (top) */}
            {showTabs && !singleNote && <NoteTabBar instanceId={instanceId} />}

            {/* Presence indicator */}
            {activeTabId && activeNoteEditedByOthers && (
              <div className="flex items-center gap-2 px-4 py-1 bg-amber-500/10 border-b border-amber-500/20 shrink-0">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-amber-400 opacity-75" />
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-amber-500" />
                </span>
                <span className="text-[0.6875rem] text-amber-700 dark:text-amber-300">
                  Another user is editing this note
                </span>
              </div>
            )}
            {othersActive && !activeNoteEditedByOthers && (
              <div className="flex items-center gap-2 px-4 py-0.5 bg-blue-500/5 border-b border-blue-500/10 shrink-0">
                <span className="relative flex h-1.5 w-1.5">
                  <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-blue-500" />
                </span>
                <span className="text-[0.625rem] text-blue-600/70 dark:text-blue-400/70">
                  Other users are active in notes
                </span>
              </div>
            )}

            {/* Layer 1: Content editor (fills available space) */}
            {activeTabId ? (
              <NoteContentEditor noteId={activeTabId} />
            ) : (
              <div className="flex-1 flex items-center justify-center text-muted-foreground">
                <div className="text-center">
                  <p className="text-sm">No note selected</p>
                  <p className="text-xs mt-1">
                    Select a note or create a new one
                  </p>
                </div>
              </div>
            )}

            {/* Layer 2: Metadata bar (bottom — folder, tags, status) */}
            {activeTabId && <NoteMetadataBar noteId={activeTabId} />}
          </div>

          {/* Version history side panel */}
          {showHistory && activeTabId && (
            <div className="w-[300px] shrink-0 max-lg:hidden">
              <NoteVersionHistory
                noteId={activeTabId}
                onClose={() => setShowHistory(false)}
                onVersionRestored={() => {
                  dispatch(fetchNoteContent(activeTabId));
                }}
              />
            </div>
          )}
        </div>
      </div>
    </NotesInstanceProvider>
  );
}
