import { Headphones } from "@mynaui/icons-react";
import {
    Braces,
    Code,
    Calculator,
    Globe,
    Search,
    Thermometer,
    FileText,
    Cloud,
    Settings,
    Plane,
    BarChart,
    ShoppingCart,
    Map,
    Notebook,
    Mail,
    MessageSquare,
    Phone,
    CheckSquare,
    Calendar,
    Mic,
    Star,
    Brain,
    Home,
    Mic2,
    Lock,
    Edit,
    Film,
    Image,
    Video,
    FlaskConical,
    Zap,
    BarChart3,
    Table,
    Grid,
    Palette,
    Cpu,
    Flame,
    Activity,
    Monitor,
    Circle,
    Box,
    Triangle,
    Server,
    Hexagon,
    Send,
    Feather,
    Shuffle,
    Layers,
    Atom,
    Droplet,
    ArrowUpRight,
    Brush,
    Check,
    CheckCircle,
    Coffee,
    Database,
    Eye,
    Layout,
    Leaf,
    LineChart,
    Link,
    MousePointer,
    Network,
    Package,
    Plug,
    RefreshCw,
    Rocket,
    Smile,
    Soup,
    Square,
    Wind,
    Wrench,
    Waves,
    Briefcase,
    Building,
    Users,
    User,
    MapPin,
    CloudRain,
    TrendingUp,
    Award,
    Bell,
    Sunrise,
    BookOpen,
    CreditCard,
    Folder,
    Heart,
    DollarSign,
    Target,
    List,
    Clipboard,
    Megaphone,
    Book,
    Shield,
    Truck,
    BarChart2,
    HelpCircle,
    Car,
    Bookmark,
    Smartphone,
    FileCode,
    Compass,
    MapPin as Location,
    Wifi,
    Anchor,
    GitBranch,
    GraduationCap,
    Clock,
    AlertTriangle,
    PencilRuler,
    Library,
    Printer,
    Pizza,
    Bus,
    PenTool,
    Lightbulb,
    Tag,
    Key,
    Flag,
    PieChart,
    Play,
} from "lucide-react";

import { CubeIcon } from "@radix-ui/react-icons";
import { GiPrism } from "react-icons/gi";

export const programmingLibraries = [
    {
        id: "python",
        label: "Python",
        icon: <Brain />,
        items: [
            {
                id: "webDevelopment",
                label: "Web Development",
                icon: <Globe />,
                items: [
                    { id: "django", label: "Django", icon: <Layers /> },
                    { id: "flask", label: "Flask", icon: <FlaskConical /> },
                    { id: "fastApi", label: "FastAPI", icon: <Zap /> },
                    { id: "tornado", label: "Tornado", icon: <Wind /> },
                    { id: "bottle", label: "Bottle", icon: <Droplet /> },
                ],
            },
            {
                id: "dataAnalysis",
                label: "Data Analysis & Visualization",
                icon: <BarChart3 />,
                items: [
                    { id: "pandas", label: "Pandas", icon: <Table /> },
                    { id: "numpy", label: "NumPy", icon: <Grid /> },
                    { id: "matplotlib", label: "Matplotlib", icon: <Image /> },
                    { id: "seaborn", label: "Seaborn", icon: <Palette /> },
                    { id: "plotly", label: "Plotly", icon: <LineChart /> },
                    { id: "bokeh", label: "Bokeh", icon: <Eye /> },
                ],
            },
            {
                id: "machineLearning",
                label: "Machine Learning & AI",
                icon: <Cpu />,
                items: [
                    { id: "tensorflow", label: "TensorFlow", icon: <Brain /> },
                    { id: "pytorch", label: "PyTorch", icon: <Flame /> },
                    { id: "scikitLearn", label: "Scikit-Learn", icon: <Code /> },
                    { id: "keras", label: "Keras", icon: <Activity /> },
                    { id: "xgboost", label: "XGBoost", icon: <Rocket /> },
                    { id: "lightgbm", label: "LightGBM", icon: <Leaf /> },
                ],
            },
            {
                id: "databaseTools",
                label: "Database & ORM Tools",
                icon: <Database />,
                items: [
                    { id: "sqlalchemy", label: "SQLAlchemy", icon: <Link /> },
                    { id: "djangoOrm", label: "Django ORM", icon: <Layers /> },
                    { id: "psycopg2", label: "Psycopg2", icon: <Plug /> },
                    { id: "pymongo", label: "PyMongo", icon: <Database /> },
                ],
            },
            {
                id: "automation",
                label: "Automation & Scripting",
                icon: <Wrench />,
                items: [
                    { id: "selenium", label: "Selenium", icon: <MousePointer /> },
                    { id: "beautifulsoup", label: "Beautiful Soup", icon: <Soup /> },
                    { id: "requests", label: "Requests", icon: <Send /> },
                    { id: "pytest", label: "Pytest", icon: <CheckCircle /> },
                ],
            },
        ],
    },
    {
        id: "javascript",
        label: "JavaScript",
        icon: <Code />,
        items: [
            {
                id: "frontEndFrameworks",
                label: "Front-End Frameworks",
                icon: <Monitor />,
                items: [
                    { id: "react", label: "React.js", icon: <Circle /> },
                    { id: "angular", label: "Angular", icon: <Box /> },
                    { id: "vue", label: "Vue.js", icon: <Triangle /> },
                    { id: "svelte", label: "Svelte", icon: <Flame /> },
                    { id: "nextjs", label: "Next.js", icon: <ArrowUpRight /> },
                    { id: "nuxtjs", label: "Nuxt.js", icon: <Square /> },
                ],
            },
            {
                id: "backEndFrameworks",
                label: "Back-End Frameworks",
                icon: <Server />,
                items: [
                    { id: "node", label: "Node.js", icon: <Hexagon /> },
                    { id: "express", label: "Express.js", icon: <Send /> },
                    { id: "nestjs", label: "NestJS", icon: <Feather /> },
                    { id: "koa", label: "Koa", icon: <Waves /> },
                    { id: "fastify", label: "Fastify", icon: <Zap /> },
                ],
            },
            {
                id: "stateManagement",
                label: "State Management",
                icon: <Shuffle />,
                items: [
                    { id: "redux", label: "Redux", icon: <Layers /> },
                    { id: "mobx", label: "MobX", icon: <Atom /> },
                    { id: "zustand", label: "Zustand", icon: <CubeIcon /> },
                    { id: "recoil", label: "Recoil", icon: <RefreshCw /> },
                    { id: "contextApi", label: "Context API", icon: <Network /> },
                ],
            },
            {
                id: "uiLibraries",
                label: "UI Libraries & Tools",
                icon: <Palette />,
                items: [
                    { id: "materialUi", label: "Material-UI", icon: <Brush /> },
                    { id: "tailwind", label: "Tailwind CSS", icon: <Wind /> },
                    { id: "bootstrap", label: "Bootstrap", icon: <Grid /> },
                    { id: "chakraUi", label: "Chakra UI", icon: <Box /> },
                    { id: "antDesign", label: "Ant Design", icon: <Layout /> },
                ],
            },
            {
                id: "databaseTools",
                label: "Database & Backend Services",
                icon: <Database />,
                items: [
                    { id: "mongoose", label: "Mongoose", icon: <Link /> },
                    { id: "prisma", label: "Prisma", icon: <GiPrism /> },
                    { id: "supabase", label: "Supabase", icon: <Cloud /> },
                    { id: "firebase", label: "Firebase", icon: <Flame /> },
                ],
            },
            {
                id: "testing",
                label: "Testing Frameworks",
                icon: <CheckCircle />,
                items: [
                    { id: "jest", label: "Jest", icon: <Smile /> },
                    { id: "mocha", label: "Mocha", icon: <Coffee /> },
                    { id: "cypress", label: "Cypress", icon: <Eye /> },
                    { id: "vitest", label: "Vitest", icon: <Zap /> },
                ],
            },
        ],
    },
    {
        id: "crossPlatform",
        label: "Cross-Platform & Utilities",
        icon: <Globe />,
        items: [
            {
                id: "apiTools",
                label: "API & Backend Services",
                icon: <Plug />,
                items: [
                    { id: "supabase", label: "Supabase", icon: <Cloud /> },
                    { id: "firebase", label: "Firebase", icon: <Flame /> },
                    { id: "graphql", label: "GraphQL", icon: <Hexagon /> },
                    { id: "axios", label: "Axios", icon: <Send /> },
                ],
            },
            {
                id: "devTools",
                label: "Development Tools",
                icon: <Wrench />,
                items: [
                    { id: "typescript", label: "TypeScript", icon: <Code /> },
                    { id: "eslint", label: "ESLint", icon: <Check /> },
                    { id: "prettier", label: "Prettier", icon: <Brush /> },
                    { id: "webpack", label: "Webpack", icon: <Package /> },
                    { id: "vite", label: "Vite", icon: <Rocket /> },
                ],
            },
        ],
    },
];

// Tool type definition
export interface Tool {
    id: string;
    name: string;
    description: string;
    category: string;
    icon: React.ReactNode;
}

export const allTools: Tool[] = [
    // Code Tools
    {
        id: "python",
        name: "Run Python Code",
        description: "Execute Python code to process data or perform complex operations",
        category: "Code",
        icon: <Code size={20} />,
    },
    {
        id: "javascript",
        name: "Run JavaScript",
        description: "Execute JavaScript code for web interactions and data manipulation",
        category: "Code",
        icon: <Braces size={20} />,
    },

    // Data Tools
    {
        id: "calculations",
        name: "Calculations",
        description: "Perform mathematical calculations, conversions, and financial estimates",
        category: "Data",
        icon: <Calculator size={20} />,
    },
    {
        id: "dataAnalysis",
        name: "Data Insights",
        description: "Analyze user data to provide summaries, trends, and predictions",
        category: "Data",
        icon: <BarChart size={20} />,
    },
    {
        id: "data_sql_list_tables",
        name: "List Database Tables",
        description: "List all tables in the Supabase database to discover available data",
        category: "Data",
        icon: <Database size={20} />,
    },
    {
        id: "data_sql_get_table_schema",
        name: "Get Table Schema",
        description: "View detailed structure of a specific database table including columns and data types",
        category: "Data",
        icon: <Table size={20} />,
    },
    {
        id: "data_user_lists_create_list",
        name: "Create User Data List",
        description: "Create a list of any data and save it to your official lists, which can be used to create components and other data.",
        category: "Data",
        icon: <List size={20} />,
    },
    {
        id: "data_sql_execute_query",
        name: "Execute SQL Query",
        description: "Run SQL queries to insert, update, select, or delete data in the Supabase database",
        category: "Data",
        icon: <Play size={20} />,
    },
    {
        id: "create_user_generated_table_data",
        name: "Create User Generated Table Data",
        description: "Converts any data from AI-Generated Tables into a table that will be accessible to you and saved to your personal database. This data can also be used as a Data Broker in the system.",
        category: "Data",
        icon: <Table size={20} />,
    },
    // Web Tools
    {
        id: "news",
        name: "Today's News",
        description: "Access latest news and current events tailored to your interests",
        category: "Web",
        icon: <Globe size={20} />,
    },
    {
        id: "search",
        name: "Web Search",
        description: "Search the internet for information, references, and real-time updates",
        category: "Web",
        icon: <Search size={20} />,
    },
    {
        id: "shopping",
        name: "Online Shopping Assistant",
        description: "Find products, compare prices, and complete purchases online",
        category: "Web",
        icon: <ShoppingCart size={20} />,
    },

    // Location Tools
    {
        id: "weather",
        name: "Local Weather",
        description: "Get current weather conditions, forecasts, and travel alerts",
        category: "Location",
        icon: <Thermometer size={20} />,
    },
    {
        id: "maps",
        name: "Navigation",
        description: "Get directions, traffic updates, and location-based recommendations",
        category: "Location",
        icon: <Map size={20} />,
    },

    // Files Tools
    {
        id: "documents",
        name: "Access User Documents",
        description: "Read, summarize, and analyze files uploaded by the user",
        category: "Files",
        icon: <FileText size={20} />,
    },
    {
        id: "cloud",
        name: "Cloud Storage",
        description: "Access, upload, and manage files in cloud services like Google Drive or Dropbox",
        category: "Files",
        icon: <Cloud size={20} />,
    },
    {
        id: "noteTaking",
        name: "Note-Taking",
        description: "Create, organize, and retrieve notes with smart categorization",
        category: "Files",
        icon: <Notebook size={20} />,
    },

    // Communication Tools
    {
        id: "email",
        name: "Send Email",
        description: "Draft, send, and manage emails with personalized templates",
        category: "Communication",
        icon: <Mail size={20} />,
    },
    {
        id: "text",
        name: "Send Text Message",
        description: "Compose and send SMS messages to contacts",
        category: "Communication",
        icon: <MessageSquare size={20} />,
    },
    {
        id: "call",
        name: "Make Phone Call",
        description: "Initiate calls and manage call schedules",
        category: "Communication",
        icon: <Phone size={20} />,
    },

    // Task Management Tools
    {
        id: "tasks",
        name: "Task Manager",
        description: "Create, track, and prioritize tasks with reminders and deadlines",
        category: "Tasks",
        icon: <CheckSquare size={20} />,
    },
    {
        id: "calendar",
        name: "Calendar Updates",
        description: "Schedule events, update appointments, and sync with calendars",
        category: "Tasks",
        icon: <Calendar size={20} />,
    },
    {
        id: "meetingSummary",
        name: "Meeting Summarizer",
        description: "Record and summarize meetings with action items",
        category: "Tasks",
        icon: <Mic size={20} />,
    },

    // Personalization Tools
    {
        id: "recommendations",
        name: "Personalized Recommendations",
        description: "Get tailored suggestions for news, entertainment, or shopping",
        category: "Personalization",
        icon: <Star size={20} />,
    },
    {
        id: "learning",
        name: "Adaptive Learning",
        description: "Adjust AI behavior based on your preferences and usage patterns",
        category: "Personalization",
        icon: <Brain size={20} />,
    },

    // Smart Home Tools
    {
        id: "smartHome",
        name: "Smart Home Control",
        description: "Manage lights, thermostats, and other connected devices",
        category: "Smart Home",
        icon: <Home size={20} />,
    },
    {
        id: "voice",
        name: "Voice Commands",
        description: "Interact with the AI using natural voice instructions",
        category: "Smart Home",
        icon: <Mic2 size={20} />,
    },

    // Multimedia Tools (New Category)
    {
        id: "imageGen",
        name: "Generate Images",
        description: "Create images from text descriptions using AI generation tools",
        category: "Multimedia",
        icon: <Image size={20} />,
    },
    {
        id: "videoGen",
        name: "Generate Videos",
        description: "Produce short videos based on text prompts or templates",
        category: "Multimedia",
        icon: <Video size={20} />,
    },
    {
        id: "imageToImage",
        name: "Image Modification",
        description: "Transform one image into another with style or content changes",
        category: "Multimedia",
        icon: <Edit size={20} />,
    },
    {
        id: "imageToVideo",
        name: "Image to Video",
        description: "Convert static images into animated videos with AI",
        category: "Multimedia",
        icon: <Film size={20} />,
    },
    {
        id: "transcribeAudio",
        name: "Transcribe Audio",
        description: "Convert audio recordings or speech into written text",
        category: "Multimedia",
        icon: <Headphones size={20} />,
    },

    // Advanced Tools
    {
        id: "settings",
        name: "Custom Settings",
        description: "Customize AI behavior, privacy options, and tool preferences",
        category: "Advanced",
        icon: <Settings size={20} />,
    },
    {
        id: "privacy",
        name: "Privacy Manager",
        description: "Control data access, review usage, and ensure security",
        category: "Advanced",
        icon: <Lock size={20} />,
    },
    {
        id: "travel",
        name: "Travel Planner",
        description: "Book flights, hotels, and plan itineraries with real-time updates",
        category: "Advanced",
        icon: <Plane size={20} />,
    },
];

export interface InformationBroker {
    id: string;
    name: string;
    description: string;
    category: string;
    icon: React.ReactNode;
}

export const allInformationBrokers: InformationBroker[] = [
    // General Information (API-accessible)
    {
        id: "todaysNews",
        name: "Today's Top News",
        description: "Current news headlines and summaries from trusted sources",
        category: "General",
        icon: <Globe size={20} />,
    },
    {
        id: "dateTime",
        name: "Date & Time Information",
        description: "Current date, time, and timezone data for scheduling and planning",
        category: "General",
        icon: <Calendar size={20} />,
    },
    {
        id: "wikipediaArticles",
        name: "Wikipedia Knowledge",
        description: "Access to encyclopedia articles for factual information",
        category: "General",
        icon: <BookOpen size={20} />,
    },
    {
        id: "websiteScraper",
        name: "Website Content",
        description: "Scrape and process information from specific URLs",
        category: "General",
        icon: <Globe size={20} />,
    },
    {
        id: "weatherData",
        name: "Weather Information",
        description: "Real-time weather data and forecasts for the user's location",
        category: "General",
        icon: <CloudRain size={20} />,
    },
    {
        id: "stockMarket",
        name: "Stock Market Data",
        description: "Current stock prices and market trends for tracked companies",
        category: "General",
        icon: <TrendingUp size={20} />,
    },
    {
        id: "sportsScores",
        name: "Sports Updates",
        description: "Latest scores and schedules for favorite teams and leagues",
        category: "General",
        icon: <Award size={20} />,
    },
    {
        id: "holidays",
        name: "Holidays & Observances",
        description: "Upcoming holidays relevant to user's location and preferences",
        category: "General",
        icon: <Bell size={20} />,
    },
    {
        id: "flightStatus",
        name: "Flight Tracking",
        description: "Real-time flight status and updates for booked travel",
        category: "General",
        icon: <Plane size={20} />,
    },
    {
        id: "publicTransit",
        name: "Transit Information",
        description: "Public transportation schedules and service disruptions",
        category: "General",
        icon: <Anchor size={20} />,
    },
    {
        id: "localEvents",
        name: "Local Events",
        description: "Calendar of upcoming events based on location and interests",
        category: "General",
        icon: <Calendar size={20} />,
    },
    {
        id: "currencyExchange",
        name: "Currency Exchange",
        description: "Current exchange rates for international users and businesses",
        category: "General",
        icon: <DollarSign size={20} />,
    },
    {
        id: "airQuality",
        name: "Air Quality Index",
        description: "Air quality and pollen levels for health-conscious planning",
        category: "General",
        icon: <Sunrise size={20} />,
    },
    {
        id: "entertainmentReleases",
        name: "Entertainment Releases",
        description: "Movie, TV, and music release dates based on preferences",
        category: "General",
        icon: <Film size={20} />,
    },
    {
        id: "restaurantAvailability",
        name: "Restaurant Bookings",
        description: "Local restaurant availability and reservation options",
        category: "General",
        icon: <Coffee size={20} />,
    },
    {
        id: "socialMediaTrends",
        name: "Trending Topics on Social Media",
        description: "Current trending topics and hashtags from platforms like X",
        category: "General",
        icon: <TrendingUp size={20} />,
    },
    {
        id: "globalEvents",
        name: "Global Events",
        description: "Upcoming conferences, sports events, and festivals worldwide",
        category: "General",
        icon: <Calendar size={20} />,
    },
    // Personal Information
    {
        id: "userProfile",
        name: "Personal Information",
        description: "User's name, age, and other basic profile details",
        category: "Personal",
        icon: <User size={20} />,
    },
    {
        id: "chatPreferences",
        name: "Chat Preferences",
        description: "User's preferences for AI interaction style and content",
        category: "Personal",
        icon: <MessageSquare size={20} />,
    },
    {
        id: "location",
        name: "Location Data",
        description: "User's current and frequently visited locations",
        category: "Personal",
        icon: <MapPin size={20} />,
    },
    {
        id: "shoppingPreferences",
        name: "Shopping Preferences",
        description: "User's product preferences and shopping habits",
        category: "Personal",
        icon: <ShoppingCart size={20} />,
    },
    {
        id: "travelPreferences",
        name: "Travel Preferences",
        description: "User's travel style, destinations, and booking habits",
        category: "Personal",
        icon: <Plane size={20} />,
    },
    {
        id: "resume",
        name: "Resume & Skills",
        description: "User's professional background, skills, and experience",
        category: "Personal",
        icon: <FileText size={20} />,
    },
    {
        id: "jobDetails",
        name: "Job Information",
        description: "Details about the user's current employment",
        category: "Personal",
        icon: <Briefcase size={20} />,
    },
    {
        id: "calendar",
        name: "Calendar Events",
        description: "User's schedule, appointments, and upcoming events",
        category: "Personal",
        icon: <Calendar size={20} />,
    },
    {
        id: "emails",
        name: "Email Access",
        description: "Content from the user's email accounts for reference",
        category: "Personal",
        icon: <Mail size={20} />,
    },
    {
        id: "textMessages",
        name: "Text Messages",
        description: "Content from the user's text message history",
        category: "Personal",
        icon: <MessageSquare size={20} />,
    },
    {
        id: "todoList",
        name: "To-Do List",
        description: "User's tasks, reminders, and priorities",
        category: "Personal",
        icon: <CheckSquare size={20} />,
    },
    {
        id: "healthData",
        name: "Health Information",
        description: "Fitness tracking and health data from connected devices",
        category: "Personal",
        icon: <Heart size={20} />,
    },
    {
        id: "musicHistory",
        name: "Music Preferences",
        description: "Listening history and favorites from music streaming services",
        category: "Personal",
        icon: <Headphones size={20} />,
    },
    {
        id: "readingList",
        name: "Reading History",
        description: "Books and articles read or saved for later",
        category: "Personal",
        icon: <BookOpen size={20} />,
    },
    {
        id: "podcastSubscriptions",
        name: "Podcast Subscriptions",
        description: "Subscribed podcasts and listening history",
        category: "Personal",
        icon: <Mic size={20} />,
    },
    {
        id: "purchaseHistory",
        name: "Purchase History",
        description: "Transaction history from connected retailers and services",
        category: "Personal",
        icon: <CreditCard size={20} />,
    },
    {
        id: "dietaryPreferences",
        name: "Dietary Information",
        description: "Food preferences, restrictions, and allergies",
        category: "Personal",
        icon: <Coffee size={20} />,
    },
    {
        id: "entertainmentPreferences",
        name: "Entertainment Preferences",
        description: "Preferred movies, shows, and entertainment genres",
        category: "Personal",
        icon: <Film size={20} />,
    },
    {
        id: "socialMedia",
        name: "Social Media Profiles",
        description: "Connected social network accounts and activity",
        category: "Personal",
        icon: <Users size={20} />,
    },
    {
        id: "personalDocuments",
        name: "Personal Documents",
        description: "Important documents stored in cloud services",
        category: "Personal",
        icon: <Folder size={20} />,
    },
    {
        id: "familyDetails",
        name: "Family Information",
        description: "Details about family members for relevant recommendations",
        category: "Personal",
        icon: <Users size={20} />,
    },
    {
        id: "homeAutomation",
        name: "Home Settings",
        description: "Smart home preferences and device settings",
        category: "Personal",
        icon: <Home size={20} />,
    },
    {
        id: "languageLearning",
        name: "Language Progress",
        description: "Language learning goals and achievements",
        category: "Personal",
        icon: <Globe size={20} />,
    },
    {
        id: "personalGoals",
        name: "Personal Goals",
        description: "Objectives and aspirations set in planning apps",
        category: "Personal",
        icon: <Target size={20} />,
    },
    {
        id: "financialPlanning",
        name: "Financial Information",
        description: "Budgeting and financial planning data",
        category: "Personal",
        icon: <DollarSign size={20} />,
    },
    {
        id: "photosMemories",
        name: "Photos & Memories",
        description: "References to past events or trips from user photo libraries",
        category: "Personal",
        icon: <Image size={20} />,
    },
    {
        id: "voicePreferences",
        name: "Voice Preferences",
        description: "User's preferred voice settings for AI audio output",
        category: "Personal",
        icon: <Mic size={20} />,
    },
    // Business Information
    {
        id: "companyProfile",
        name: "Company Profile",
        description: "Basic information about the company and its operations",
        category: "Business",
        icon: <Building size={20} />,
    },
    {
        id: "companyMission",
        name: "Company Mission",
        description: "Mission statement, goals, and corporate values",
        category: "Business",
        icon: <Target size={20} />,
    },
    {
        id: "companyChatPreferences",
        name: "Company Chat Settings",
        description: "Organization-wide preferences for AI interactions",
        category: "Business",
        icon: <MessageSquare size={20} />,
    },
    {
        id: "orgStructure",
        name: "Organizational Structure",
        description: "Company hierarchy and employee information",
        category: "Business",
        icon: <Users size={20} />,
    },
    {
        id: "serviceDetails",
        name: "Service Catalog",
        description: "Detailed information about company services and offerings",
        category: "Business",
        icon: <List size={20} />,
    },
    {
        id: "clientList",
        name: "Client Directory",
        description: "List of company clients and basic information",
        category: "Business",
        icon: <Users size={20} />,
    },
    {
        id: "clientDetails",
        name: "Client Profiles",
        description: "Detailed information about specific clients",
        category: "Business",
        icon: <User size={20} />,
    },
    {
        id: "clientPreferences",
        name: "Client Preferences",
        description: "Service preferences and history for specific clients",
        category: "Business",
        icon: <CheckSquare size={20} />,
    },
    {
        id: "projectManagement",
        name: "Project Tools",
        description: "Integration with project management platforms",
        category: "Business",
        icon: <Layers size={20} />,
    },
    {
        id: "crmData",
        name: "CRM Integration",
        description: "Customer relationship management data access",
        category: "Business",
        icon: <Users size={20} />,
    },
    {
        id: "salesPipeline",
        name: "Sales Pipeline",
        description: "Current sales opportunities and forecasts",
        category: "Business",
        icon: <BarChart size={20} />,
    },
    {
        id: "productInventory",
        name: "Inventory Status",
        description: "Product inventory and availability information",
        category: "Business",
        icon: <Database size={20} />,
    },
    {
        id: "knowledgeBase",
        name: "Knowledge Base",
        description: "Company wiki content and internal documentation",
        category: "Business",
        icon: <Book size={20} />,
    },
    {
        id: "internalPolicies",
        name: "Company Policies",
        description: "Internal procedures and policy documentation",
        category: "Business",
        icon: <Clipboard size={20} />,
    },
    {
        id: "teamAvailability",
        name: "Team Schedules",
        description: "Availability and schedules for team members",
        category: "Business",
        icon: <Calendar size={20} />,
    },
    {
        id: "meetingNotes",
        name: "Meeting Information",
        description: "Notes and action items from company meetings",
        category: "Business",
        icon: <FileText size={20} />,
    },
    {
        id: "departmentKPIs",
        name: "Department Metrics",
        description: "Key performance indicators for various departments",
        category: "Business",
        icon: <BarChart2 size={20} />,
    },
    {
        id: "processDocumentation",
        name: "Process Documentation",
        description: "Documented business processes and workflows",
        category: "Business",
        icon: <FileText size={20} />,
    },
    {
        id: "companyAnnouncements",
        name: "Company Announcements",
        description: "Internal news and communications",
        category: "Business",
        icon: <Megaphone size={20} />,
    },
    {
        id: "trainingMaterials",
        name: "Training Resources",
        description: "Educational content and training documentation",
        category: "Business",
        icon: <BookOpen size={20} />,
    },
    {
        id: "industryRegulations",
        name: "Compliance Information",
        description: "Regulatory requirements relevant to the business",
        category: "Business",
        icon: <Shield size={20} />,
    },
    {
        id: "vendorRelationships",
        name: "Vendor Directory",
        description: "Information about suppliers and service providers",
        category: "Business",
        icon: <Truck size={20} />,
    },
    {
        id: "marketingCampaigns",
        name: "Marketing Analytics",
        description: "Performance data for marketing initiatives",
        category: "Business",
        icon: <BarChart size={20} />,
    },
    {
        id: "supportTickets",
        name: "Support History",
        description: "Customer support tickets and common issues",
        category: "Business",
        icon: <HelpCircle size={20} />,
    },
    {
        id: "companyFinancials",
        name: "Company Financials",
        description: "Revenue, budgets, and expense data for financial insights",
        category: "Business",
        icon: <DollarSign size={20} />,
    },
    {
        id: "competitorAnalysis",
        name: "Competitor Analysis",
        description: "Insights on competitors’ activities and market position",
        category: "Business",
        icon: <BarChart2 size={20} />,
    },
    // Integration Possibilities
    {
        id: "smartHome",
        name: "Smart Home Data",
        description: "Connected home device status and preferences",
        category: "Integrations",
        icon: <Thermometer size={20} />,
    },
    {
        id: "vehicleInfo",
        name: "Vehicle Information",
        description: "Car maintenance schedule and driving patterns",
        category: "Integrations",
        icon: <Car size={20} />,
    },
    {
        id: "learningManagement",
        name: "Learning Systems",
        description: "Educational platform integration for students",
        category: "Integrations",
        icon: <BookOpen size={20} />,
    },
    {
        id: "recipeDatabase",
        name: "Recipe Collection",
        description: "Cooking ideas linked to dietary preferences",
        category: "Integrations",
        icon: <Coffee size={20} />,
    },
    {
        id: "travelBookings",
        name: "Travel History",
        description: "Past trips and bookings for recommendations",
        category: "Integrations",
        icon: <Plane size={20} />,
    },
    {
        id: "publicDataSources",
        name: "Public Data",
        description: "Government and research open data access",
        category: "Integrations",
        icon: <Database size={20} />,
    },
    {
        id: "browserHistory",
        name: "Browsing Activity",
        description: "Web history and bookmarks for context",
        category: "Integrations",
        icon: <Bookmark size={20} />,
    },
    {
        id: "streamingServices",
        name: "Media Recommendations",
        description: "Streaming service viewing history and suggestions",
        category: "Integrations",
        icon: <Video size={20} />,
    },
    {
        id: "digitalWallet",
        name: "Payment Methods",
        description: "Digital wallet and payment preferences",
        category: "Integrations",
        icon: <CreditCard size={20} />,
    },
    {
        id: "gamingProfiles",
        name: "Gaming Data",
        description: "Gaming history, achievements, and preferences",
        category: "Integrations",
        icon: <Zap size={20} />,
    },
    {
        id: "collaborativeDocuments",
        name: "Shared Documents",
        description: "History from collaborative document platforms",
        category: "Integrations",
        icon: <FileText size={20} />,
    },
    {
        id: "cloudStorage",
        name: "Cloud Storage",
        description: "Access to files stored in cloud services",
        category: "Integrations",
        icon: <Server size={20} />,
    },
    {
        id: "professionalNetwork",
        name: "Professional Network",
        description: "Career connections and professional data",
        category: "Integrations",
        icon: <Users size={20} />,
    },
    {
        id: "loyaltyPrograms",
        name: "Loyalty Programs",
        description: "Retail rewards status from connected merchants",
        category: "Integrations",
        icon: <Award size={20} />,
    },
    {
        id: "gamingPreferences",
        name: "Gaming Preferences",
        description: "User’s preferred games and play styles (distinct from gamingData)",
        category: "Integrations",
        icon: <Zap size={20} />,
    },
    // Specialized Context
    {
        id: "academicResearch",
        name: "Academic Databases",
        description: "Research paper access for students and academics",
        category: "Specialized",
        icon: <BookOpen size={20} />,
    },
    {
        id: "medicalInformation",
        name: "Medical Context",
        description: "Health records for healthcare applications",
        category: "Specialized",
        icon: <Heart size={20} />,
    },
    {
        id: "legalDocuments",
        name: "Legal Resources",
        description: "Legal document repositories for professionals",
        category: "Specialized",
        icon: <FileText size={20} />,
    },
    {
        id: "codeRepositories",
        name: "Code Libraries",
        description: "Access to coding repositories and documentation",
        category: "Specialized",
        icon: <GitBranch size={20} />,
    },
    {
        id: "designAssets",
        name: "Design Resources",
        description: "Creative asset libraries for designers",
        category: "Specialized",
        icon: <Edit size={20} />,
    },
    {
        id: "citizenScience",
        name: "Citizen Science",
        description: "Collaborative research project data",
        category: "Specialized",
        icon: <Globe size={20} />,
    },
    {
        id: "languageTranslation",
        name: "Translation Context",
        description: "Language preferences for multilingual users",
        category: "Specialized",
        icon: <Globe size={20} />,
    },
    {
        id: "industryNews",
        name: "Industry Intelligence",
        description: "Sector-specific news sources for professionals",
        category: "Specialized",
        icon: <FileText size={20} />,
    },
    {
        id: "buildingInformation",
        name: "Building Models",
        description: "Architecture and construction project data",
        category: "Specialized",
        icon: <Home size={20} />,
    },
    {
        id: "agriculturalData",
        name: "Agricultural Information",
        description: "Weather and crop data for farming applications",
        category: "Specialized",
        icon: <Droplet size={20} />,
    },
    {
        id: "iotDevices",
        name: "IoT Device Data",
        description: "Connected device sensors and status information",
        category: "Specialized",
        icon: <Wifi size={20} />,
    },
    {
        id: "technicalDocumentation",
        name: "Technical Manuals",
        description: "Product documentation and technical specifications",
        category: "Specialized",
        icon: <FileCode size={20} />,
    },

    // 🧠 AI Behavioral Context
    {
        id: "chatHistorySummary",
        name: "Chat History Summary",
        description: "Summarized past AI interactions for deeper memory and personalization",
        category: "AI",
        icon: <MessageSquare size={20} />,
    },
    {
        id: "interactionStyle",
        name: "Interaction Style",
        description: "Preferred response tone, structure, and verbosity based on prior usage",
        category: "AI",
        icon: <MessageSquare size={20} />,
    },
    {
        id: "modelPreferences",
        name: "Model Configuration",
        description: "User-specific model settings such as creativity level and response limits",
        category: "AI",
        icon: <Settings size={20} />,
    },
    // 🧭 Life Context & Intention
    {
        id: "dailyFocus",
        name: "Daily Intentions",
        description: "User-defined goals or themes for the current day",
        category: "Personal",
        icon: <Target size={20} />,
    },
    {
        id: "weeklyThemes",
        name: "Weekly Themes",
        description: "Patterns or focus areas declared for the week (e.g. Deep Work Week)",
        category: "Personal",
        icon: <Calendar size={20} />,
    },
    {
        id: "coachingNotes",
        name: "Coaching or Therapy Notes",
        description: "Input from coaching, mentoring, or therapy sessions to align guidance",
        category: "Personal",
        icon: <FileText size={20} />,
    },

    // 📚 Learning & Development
    {
        id: "learningGoals",
        name: "Learning Objectives",
        description: "Topics or skills the user is actively trying to learn or explore",
        category: "Personal",
        icon: <BookOpen size={20} />,
    },
    {
        id: "currentCourses",
        name: "Active Courses",
        description: "User's current educational programs and coursework",
        category: "Personal",
        icon: <GraduationCap size={20} />,
    },

    // 🌍 External Awareness
    {
        id: "searchTrends",
        name: "Search Engine Trends",
        description: "Current trending topics and questions from Google, Bing, etc.",
        category: "General",
        icon: <Search size={20} />,
    },
    {
        id: "publicSentiment",
        name: "Social Sentiment",
        description: "Recent public sentiment from Twitter, Reddit, or forums on key topics",
        category: "General",
        icon: <Users size={20} />,
    },

    // 🏢 Business Process Automation
    {
        id: "employeePerformance",
        name: "Employee Performance",
        description: "Access to performance reviews and OKRs for individuals or teams",
        category: "Business",
        icon: <BarChart2 size={20} />,
    },
    {
        id: "contractManagement",
        name: "Contract Data",
        description: "Current contracts, renewal dates, and SLA details",
        category: "Business",
        icon: <FileText size={20} />,
    },
    {
        id: "competitiveAnalysis",
        name: "Competitor Intelligence",
        description: "Market insights, competitor updates, and SWOT analysis",
        category: "Business",
        icon: <Globe size={20} />,
    },

    // 📊 Performance Metrics
    {
        id: "keyPerformanceIndicators",
        name: "KPIs",
        description: "Quantifiable metrics for business operations and goals",
        category: "Business",
        icon: <BarChart2 size={20} />,
    },
    {
        id: "salesMetrics",
        name: "Sales Metrics",
        description: "Sales performance data and trends",
        category: "Business",
        icon: <BarChart2 size={20} />,
    },
    {
        id: "customerFeedback",
        name: "Customer Feedback",
        description: "Recent customer feedback and sentiment",
        category: "Business",
        icon: <Users size={20} />,
    },

    // 📈 Market Analysis
    {
        id: "marketResearch",
        name: "Market Research",
        description: "Market research data and trends",
        category: "Business",
        icon: <Globe size={20} />,
    },

    // 🧬 Miscellaneous Innovation
    {
        id: "personalityProfile",
        name: "Personality Data",
        description: "User's cognitive or psychological profile (e.g. MBTI, Big 5)",
        category: "Personal",
        icon: <User size={20} />,
    },
    {
        id: "writingPatterns",
        name: "Writing Style Profile",
        description: "Analysis of user's tone, sentence structure, and grammar patterns",
        category: "AI",
        icon: <Edit size={20} />,
    },

    // Core Academic Information
    {
        id: "currentCourses",
        name: "Current Courses",
        description: "List of courses the student is enrolled in this term",
        category: "Student",
        icon: <Book size={20} />,
    },
    {
        id: "courseSyllabus",
        name: "Course Syllabus",
        description: "Detailed syllabus for each enrolled course including assignments and readings",
        category: "Student",
        icon: <FileText size={20} />,
    },
    {
        id: "examSchedule",
        name: "Exam Schedule",
        description: "Dates, times, and locations of upcoming exams and quizzes",
        category: "Student",
        icon: <Calendar size={20} />,
    },
    {
        id: "flashcardSets",
        name: "Flashcard Sets",
        description: "Custom AI-generated or user-created flashcards for each course",
        category: "Student",
        icon: <Layers size={20} />,
    },
    {
        id: "courseNotes",
        name: "Course Notes",
        description: "Student's personal notes from lectures, synced across devices",
        category: "Student",
        icon: <Edit size={20} />,
    },
    {
        id: "textbookSummaries",
        name: "Textbook Summaries",
        description: "AI-generated summaries of assigned textbooks or chapters",
        category: "Student",
        icon: <BookOpen size={20} />,
    },
    {
        id: "currentChapter",
        name: "Current Chapter or Topic",
        description: "Current chapter or topic being covered in each class",
        category: "Student",
        icon: <Bookmark size={20} />,
    },
    {
        id: "assignmentDeadlines",
        name: "Assignment Deadlines",
        description: "Due dates and details for homework, projects, and papers",
        category: "Student",
        icon: <Clock size={20} />,
    },
    {
        id: "lectureRecordings",
        name: "Lecture Recordings",
        description: "Access to recorded lectures or audio notes from class",
        category: "Student",
        icon: <Video size={20} />,
    },
    {
        id: "studySchedule",
        name: "Study Schedule",
        description: "Personalized study plan based on exams and assignments",
        category: "Student",
        icon: <Calendar size={20} />,
    },
    {
        id: "gradeTracker",
        name: "Grade Tracker",
        description: "Current grades and GPA calculations for all courses",
        category: "Student",
        icon: <BarChart size={20} />,
    },
    {
        id: "professorDetails",
        name: "Professor Information",
        description: "Contact info, office hours, and teaching style of instructors",
        category: "Student",
        icon: <User size={20} />,
    },
    {
        id: "groupStudy",
        name: "Group Study Contacts",
        description: "List of classmates or study group members for collaboration",
        category: "Student",
        icon: <Users size={20} />,
    },
    {
        id: "libraryResources",
        name: "Library Resources",
        description: "Access to digital library books, articles, or research databases",
        category: "Student",
        icon: <Database size={20} />,
    },
    {
        id: "tutoringSessions",
        name: "Tutoring Sessions",
        description: "Schedule and details of booked tutoring or AI tutoring sessions",
        category: "Student",
        icon: <HelpCircle size={20} />,
    },
    {
        id: "academicCalendar",
        name: "Academic Calendar",
        description: "Key dates like semester start/end, breaks, and registration deadlines",
        category: "Student",
        icon: <Calendar size={20} />,
    },
    {
        id: "learningGoals",
        name: "Learning Goals",
        description: "Student-defined goals for mastering topics or skills",
        category: "Student",
        icon: <Target size={20} />,
    },
    {
        id: "quizPractice",
        name: "Practice Quizzes",
        description: "AI-generated practice quizzes based on course material",
        category: "Student",
        icon: <CheckSquare size={20} />,
    },
    {
        id: "researchPapers",
        name: "Research Papers",
        description: "Student's saved or drafted research papers and citations",
        category: "Student",
        icon: <FileText size={20} />,
    },
    {
        id: "campusEvents",
        name: "Campus Events",
        description: "Upcoming academic, social, or club events on campus",
        category: "Student",
        icon: <Bell size={20} />,
    },
    {
        id: "textbookAvailability",
        name: "Textbook Availability",
        description: "Options to rent, buy, or access digital textbooks",
        category: "Student",
        icon: <ShoppingCart size={20} />,
    },
    {
        id: "studyMusic",
        name: "Study Music Preferences",
        description: "Curated playlists for focus based on music preferences",
        category: "Student",
        icon: <Headphones size={20} />,
    },
    {
        id: "classForum",
        name: "Class Discussion Forum",
        description: "Integration with course forums or discussion boards",
        category: "Student",
        icon: <MessageSquare size={20} />,
    },
    {
        id: "labSchedules",
        name: "Lab & Practical Schedules",
        description: "Timetables for lab sessions, workshops, or practicals",
        category: "Student",
        icon: <PencilRuler size={20} />,
    },
    {
        id: "extracurriculars",
        name: "Extracurricular Activities",
        description: "Clubs, sports, or volunteer schedules and commitments",
        category: "Student",
        icon: <Award size={20} />,
    },
    {
        id: "scholarshipInfo",
        name: "Scholarship Opportunities",
        description: "Eligible scholarships and application deadlines",
        category: "Student",
        icon: <DollarSign size={20} />,
    },
    {
        id: "careerResources",
        name: "Career Resources",
        description: "Internship listings, resume tips, and career fair dates",
        category: "Student",
        icon: <Briefcase size={20} />,
    },

    // New Practical Additions
    {
        id: "courseRegistration",
        name: "Course Registration",
        description: "Registration windows, course availability, and prerequisite information",
        category: "Student",
        icon: <Clipboard size={20} />,
    },
    {
        id: "degreeProgress",
        name: "Degree Progress Tracker",
        description: "Progress toward degree requirements and graduation",
        category: "Student",
        icon: <GraduationCap size={20} />,
    },
    {
        id: "campusMap",
        name: "Campus Navigation",
        description: "Interactive maps with classroom locations and navigation directions",
        category: "Student",
        icon: <Map size={20} />,
    },
    {
        id: "studySpaces",
        name: "Study Space Finder",
        description: "Available study rooms, quiet areas, and group work spaces on campus",
        category: "Student",
        icon: <Home size={20} />,
    },
    {
        id: "campusWifi",
        name: "Campus WiFi Status",
        description: "WiFi coverage, login credentials, and current status across campus",
        category: "Student",
        icon: <Wifi size={20} />,
    },
    {
        id: "campusTransportation",
        name: "Campus Transportation",
        description: "Shuttle schedules, bus routes, and parking information",
        category: "Student",
        icon: <Bus size={20} />,
    },
    {
        id: "mealPlan",
        name: "Meal Plan Balance",
        description: "Dining hall hours, meal plan balance, and campus food options",
        category: "Student",
        icon: <Pizza size={20} />,
    },
    {
        id: "campusCafes",
        name: "Coffee Shop Hours",
        description: "Hours and locations of coffee shops and study cafes on campus",
        category: "Student",
        icon: <Coffee size={20} />,
    },
    {
        id: "computerLabs",
        name: "Computer Lab Availability",
        description: "Available computers in labs across campus with software information",
        category: "Student",
        icon: <Monitor size={20} />,
    },
    {
        id: "printingServices",
        name: "Printing Credits",
        description: "Printing balance, locations, and costs for campus printing services",
        category: "Student",
        icon: <Printer size={20} />,
    },
    {
        id: "financialAid",
        name: "Financial Aid Status",
        description: "Financial aid application status, deadlines, and requirements",
        category: "Student",
        icon: <CreditCard size={20} />,
    },
    {
        id: "tuitionPayments",
        name: "Tuition Payment Schedule",
        description: "Payment deadlines, installment options, and account balance",
        category: "Student",
        icon: <DollarSign size={20} />,
    },
    {
        id: "healthServices",
        name: "Campus Health Services",
        description: "Health center hours, appointment booking, and health resources",
        category: "Student",
        icon: <Heart size={20} />,
    },
    {
        id: "mentalHealthResources",
        name: "Mental Health Resources",
        description: "Counseling services, support groups, and wellness resources",
        category: "Student",
        icon: <Brain size={20} />,
    },
    {
        id: "libraryReservations",
        name: "Library Room Bookings",
        description: "Reserved study rooms and available library spaces",
        category: "Student",
        icon: <Library size={20} />,
    },
    {
        id: "academicAdvising",
        name: "Academic Advisor Meetings",
        description: "Advisor contact information and scheduled appointments",
        category: "Student",
        icon: <User size={20} />,
    },
    {
        id: "courseReviews",
        name: "Course Reviews",
        description: "Student reviews and ratings of courses and professors",
        category: "Student",
        icon: <Star size={20} />,
    },
    {
        id: "officeHoursTracker",
        name: "Office Hours Tracker",
        description: "Schedule of professor and TA office hours with reminders",
        category: "Student",
        icon: <Clock size={20} />,
    },
    {
        id: "studyBreakReminders",
        name: "Study Break Timer",
        description: "Pomodoro timer and break reminders for productive studying",
        category: "Student",
        icon: <Clock size={20} />,
    },
    {
        id: "attendanceTracker",
        name: "Attendance Tracker",
        description: "Course attendance records and absence allowances",
        category: "Student",
        icon: <CheckSquare size={20} />,
    },
    {
        id: "labEquipment",
        name: "Lab Equipment Reservations",
        description: "Availability and booking for specialized lab equipment",
        category: "Student",
        icon: <PencilRuler size={20} />,
    },
    {
        id: "homeworkHelp",
        name: "Homework Solution Checker",
        description: "AI-powered assistance for checking homework solutions",
        category: "Student",
        icon: <Zap size={20} />,
    },
    {
        id: "mathFormulas",
        name: "Math Formula Database",
        description: "Searchable database of mathematical formulas and examples",
        category: "Student",
        icon: <Calculator size={20} />,
    },
    {
        id: "citationGenerator",
        name: "Citation Generator",
        description: "Automatic citation formatting in multiple styles (APA, MLA, Chicago)",
        category: "Student",
        icon: <Link size={20} />,
    },
    {
        id: "thesisTracker",
        name: "Thesis Progress Tracker",
        description: "Milestones, deadlines, and advisor feedback for thesis projects",
        category: "Student",
        icon: <Target size={20} />,
    },
    {
        id: "studyGroupScheduler",
        name: "Study Group Scheduler",
        description: "Tool to coordinate and schedule study group sessions",
        category: "Student",
        icon: <Users size={20} />,
    },
    {
        id: "digitalNotecards",
        name: "Digital Notecard System",
        description: "Spaced repetition system for effective memorization",
        category: "Student",
        icon: <Layers size={20} />,
    },
    {
        id: "academicIntegrityGuide",
        name: "Academic Integrity Guide",
        description: "Guidelines for proper citations and avoiding plagiarism",
        category: "Student",
        icon: <AlertTriangle size={20} />,
    },
    {
        id: "internationalStudentResources",
        name: "International Student Resources",
        description: "Visa information, cultural resources, and international services",
        category: "Student",
        icon: <Globe size={20} />,
    },
    {
        id: "accessibilityServices",
        name: "Accessibility Services",
        description: "Accommodation information and accessibility resources",
        category: "Student",
        icon: <Heart size={20} />,
    },
    {
        id: "syllabusAnalyzer",
        name: "Syllabus Analyzer",
        description: "AI tool that extracts key dates and requirements from syllabi",
        category: "Student",
        icon: <Lightbulb size={20} />,
    },
    {
        id: "paperOutliner",
        name: "Paper Outliner",
        description: "AI-assisted outlining tool for research papers and essays",
        category: "Student",
        icon: <PenTool size={20} />,
    },
    {
        id: "lectureQuestions",
        name: "Lecture Question Generator",
        description: "AI-generated questions based on lecture content for active learning",
        category: "Student",
        icon: <MessageSquare size={20} />,
    },
    {
        id: "textbookCompanion",
        name: "Textbook AI Companion",
        description: "AI tutor that can answer questions about specific textbooks",
        category: "Student",
        icon: <BookOpen size={20} />,
    },
    {
        id: "conceptMapper",
        name: "Concept Mapping Tool",
        description: "Visual mapping tool to connect course concepts and ideas",
        category: "Student",
        icon: <PieChart size={20} />,
    },
    {
        id: "semesterPlanner",
        name: "Semester Timeline",
        description: "Visual timeline of all deadlines and events for the semester",
        category: "Student",
        icon: <Flag size={20} />,
    },
    {
        id: "examPrep",
        name: "Exam Prep Materials",
        description: "Past exams, study guides, and practice problems",
        category: "Student",
        icon: <FileText size={20} />,
    },
    {
        id: "programRequirements",
        name: "Program Requirements",
        description: "Detailed major/minor requirements and elective options",
        category: "Student",
        icon: <CheckSquare size={20} />,
    },
    {
        id: "studyAbroadInfo",
        name: "Study Abroad Information",
        description: "Study abroad programs, deadlines, and credit transfer details",
        category: "Student",
        icon: <Globe size={20} />,
    },
    {
        id: "researchOpportunities",
        name: "Research Opportunities",
        description: "Research assistant positions and undergraduate research programs",
        category: "Student",
        icon: <Lightbulb size={20} />,
    },
    {
        id: "courseEquivalencies",
        name: "Course Equivalencies",
        description: "Transfer credit information and course equivalencies",
        category: "Student",
        icon: <Link size={20} />,
    },
    {
        id: "campusResourceDirectory",
        name: "Campus Resource Directory",
        description: "Comprehensive directory of academic and support services",
        category: "Student",
        icon: <Database size={20} />,
    },
    {
        id: "emergencyAlerts",
        name: "Campus Emergency Alerts",
        description: "Weather closures, safety alerts, and emergency information",
        category: "Student",
        icon: <AlertTriangle size={20} />,
    },
    {
        id: "studentDiscounts",
        name: "Student Discounts",
        description: "Available student discounts for software, services, and local businesses",
        category: "Student",
        icon: <Tag size={20} />,
    },
    {
        id: "classroomTech",
        name: "Classroom Technology",
        description: "Available technology in classrooms and how to access it",
        category: "Student",
        icon: <Monitor size={20} />,
    },
    {
        id: "studentID",
        name: "Student ID Services",
        description: "ID card information, replacement procedures, and associated benefits",
        category: "Student",
        icon: <Key size={20} />,
    },
    {
        id: "gradSchoolApplications",
        name: "Grad School Application Tracker",
        description: "Deadlines, requirements, and status for graduate school applications",
        category: "Student",
        icon: <GraduationCap size={20} />,
    },
    {
        id: "courseDropDates",
        name: "Course Add/Drop Deadlines",
        description: "Important dates for adding or dropping courses without penalty",
        category: "Student",
        icon: <AlertTriangle size={20} />,
    },
    {
        id: "languageLearningResources",
        name: "Language Learning Resources",
        description: "Language labs, conversation partners, and practice resources",
        category: "Student",
        icon: <Globe size={20} />,
    },
    {
        id: "eduApps",
        name: "Educational Apps",
        description: "Recommended apps for specific courses and learning needs",
        category: "Student",
        icon: <Smartphone size={20} />,
    },
    {
        id: "virtualLabs",
        name: "Virtual Lab Access",
        description: "Remote access to specialized software and virtual lab environments",
        category: "Student",
        icon: <Cpu size={20} />,
    },
];
