import { Flashcard } from "./page";

export const initialFlashCardData: Flashcard[] = [
    { id: 1, front: "Matter", back: "Anything that has mass and takes up space.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 2, front: "Mass", back: "The amount of matter in an object, measured in kilograms or grams.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 3, front: "Weight", back: "The force exerted by gravity on an object’s mass, measured in newtons.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 4, front: "Volume", back: "The amount of space an object occupies, measured in liters or cubic meters.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { 
        id: 5, 
        front: "Density", 
        back: `Mass per unit volume of a substance, calculated as mass divided by volume (D = m/v). Density is how tightly packed matter is in a substance. It tells us how much stuff (mass) is in a certain amount of space (volume).\n\nThe formula is:\nDensity (D) = Mass (m) ÷ Volume (v)\n\nMass is how much something weighs.\nVolume is how much space it takes up.\nFor example, if you have two objects of the same size, the one that weighs more has a higher density. Your teacher wants you to know that density is measured in units like grams per cubic centimeter (g/cm³) or kilograms per liter (kg/L).`, 
        reviewCount: 0, 
        correctCount: 0, 
        incorrectCount: 0 
      },
    { id: 6, front: "States of Matter", back: "The physical forms in which matter can exist: solid, liquid, and gas.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 7, front: "Physical Properties", back: "Characteristics that can be observed or measured without changing the substance’s chemical identity (e.g., color, melting point, density).", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 8, front: "Chemical Properties", back: "Characteristics that describe a substance’s ability to change into different substances (e.g., flammability, reactivity).", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 9, front: "Elements", back: "Pure substances that consist of only one type of atom.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 10, front: "Atoms", back: "The smallest unit of an element that retains the properties of that element.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 11, front: "Periodic Table", back: "A table of the chemical elements arranged by atomic number, symbol, and atomic mass, showing the periodic patterns in their properties.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 12, front: "Atomic Number", back: "The number of protons in the nucleus of an atom, which determines the element’s identity.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 13, front: "Symbol", back: "One or two letters that represent an element (e.g., H for hydrogen, O for oxygen).", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 14, front: "Atomic Mass", back: "The weighted average mass of the atoms in a naturally occurring sample of the element.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 15, front: "Groups", back: "Vertical columns in the periodic table where elements have similar chemical properties.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 16, front: "Metal vs. Nonmetal", back: "Metals are typically shiny, malleable, and good conductors of heat and electricity, while nonmetals are not.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 17, front: "Pure Substances", back: "Materials made of only one type of particle; includes elements and compounds.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 18, front: "Molecules", back: "Two or more atoms bonded together.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 19, front: "Chemical Bonds", back: "The forces that hold atoms together in a molecule.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 20, front: "Compounds", back: "Substances formed from two or more elements chemically bonded in fixed proportions.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 21, front: "Atomic Ratios", back: "The ratio of different types of atoms in a compound.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 22, front: "Models of Molecules", back: "Representations of molecules showing the arrangement of atoms and the bonds between them.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 23, front: "Complex Molecules", back: "Large molecules such as polymers, crystals, and metals, whose properties are influenced by their atomic composition and structure.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 24, front: "Polymers", back: "Large molecules made up of repeating units called monomers.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 25, front: "Crystals", back: "Solids whose atoms are arranged in a highly ordered, repeating pattern.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 26, front: "Metals", back: "Elements that are typically hard, shiny, and good conductors of heat and electricity.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 27, front: "How a material’s properties are influenced by both its atomic composition and structure", back: "The specific arrangement and types of atoms in a material determine its physical and chemical properties.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 28, front: "How could you measure mass, weight, volume, or density?", back: "Mass: balance scale; Weight: spring scale; Volume: graduated cylinder or displacement method; Density: calculate using mass and volume (D = m/v).", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 29, front: "What are examples of physical / chemical properties, how are they different?", back: "Physical: color, melting point; Chemical: flammability, reactivity. Physical properties can be observed without changing the substance, chemical properties involve a change in composition.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 30, front: "Given a periodic table, identify an element’s properties.", back: "Use the atomic number, symbol, and atomic mass to determine the element’s identity and properties.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 31, front: "What are the similarities and differences of atoms, molecules, and compounds?", back: "Atoms are single units of elements; molecules are two or more atoms bonded together; compounds are molecules made of different elements.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 32, front: "Be able to draw a molecular model for a given molecule, or vice versa.", back: "Practice drawing models showing atoms and bonds, or identify molecules from given models.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 33, front: "Describe an experimental procedure to identify an unknown substance by comparing to known substances and their properties.", back: "Measure physical and chemical properties (e.g., melting point, density, reactivity) and compare to known substances.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 34, front: "Compare and contrast the properties that different extended structures molecules could have.", back: "Polymers: flexible, durable; Crystals: hard, brittle; Metals: conductive, malleable.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 35, front: "If different objects have the same mass, the most dense one has which volume?", back: "The smallest volume.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 36, front: "Which of the following is not a chemical property?", back: "Melting point.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 37, front: "What is the symbol for gold?", back: "Au.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 38, front: "The symbol Sb is for what element?", back: "Antimony.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 39, front: "Which element has an atomic number of 5?", back: "Boron.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 40, front: "Which group is known as the noble gases?", back: "Group 18.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 41, front: "The element of potassium is a metal.", back: "True.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 42, front: "English breakfast tea is an example of a pure substance.", back: "False.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 43, front: "Chlorine gas, Cl2, is a molecule.", back: "True.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 44, front: "Which of the following is an example of a compound?", back: "Water (H2O).", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 45, front: "Carbon dioxide is a molecule with which atom in the center?", back: "Carbon.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 46, front: "What is the atomic number defined by?", back: "The number of protons in an atom’s nucleus.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 47, front: "Alchemy was the study of attempting to turn lead into...", back: "Gold.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 48, front: "Molecules contain atoms held together by...", back: "Chemical bonds.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 49, front: "Sodium chloride, or table salt, is an example of a...", back: "Compound.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 50, front: "Elements in the same row in the periodic table are likely to have similar properties.", back: "False.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 51, front: "Elements in the same column (or group) in the periodic table are likely to have similar properties.", back: "True.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 52, front: "Volume is a measure of...", back: "The amount of space an object occupies.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 53, front: "Mass changes depending on the amount of gravity something experiences.", back: "False. Weight changes, not mass.", reviewCount: 0, correctCount: 0, incorrectCount: 0 },
    { id: 54, front: "The most common molecule in the air is...", back: "Nitrogen (N2).", reviewCount: 0, correctCount: 0, incorrectCount: 0 }
  ];
  
