// features/artifacts/types.ts
//
// Shared types for the artifact tracking system.
//
// An "artifact" is any piece of structured content generated by AI from a
// chat message — HTML pages, flashcard decks, org charts, diagrams, etc.
// Every artifact is linked back to the cx_message that produced it so users
// can see what was generated from any message and avoid duplicates.
//
// The cx_artifact table lives in the main Supabase project.
// External content stores (html_pages, etc.) are separate systems linked via
// external_system + external_id.

// ── Enums / literal unions ─────────────────────────────────────────────────

/**
 * All known artifact types. Maps 1:1 to the artifact_type PostgreSQL enum.
 * Add new types here AND in the DB migration (001_cx_artifact.sql) together.
 */
export type ArtifactType =
  | "html_page"
  | "flashcard_deck"
  | "org_chart"
  | "diagram"
  | "data_table"
  | "timeline"
  | "comparison_table"
  | "quiz"
  | "summary"
  | "outline"
  | "report"
  | "code_snippet"
  | "spreadsheet"
  | "presentation"
  | "other";

export type ArtifactStatus = "draft" | "published" | "archived" | "failed";

export const ARTIFACT_TYPE_LABELS: Record<ArtifactType, string> = {
  html_page: "HTML Page",
  flashcard_deck: "Flashcard Deck",
  org_chart: "Org Chart",
  diagram: "Diagram",
  data_table: "Data Table",
  timeline: "Timeline",
  comparison_table: "Comparison Table",
  quiz: "Quiz",
  summary: "Summary",
  outline: "Outline",
  report: "Report",
  code_snippet: "Code Snippet",
  spreadsheet: "Spreadsheet",
  presentation: "Presentation",
  other: "Other",
};

export const ARTIFACT_STATUS_LABELS: Record<ArtifactStatus, string> = {
  draft: "Draft",
  published: "Published",
  archived: "Archived",
  failed: "Failed",
};

// ── DB row shape (snake_case — matches Supabase response) ─────────────────

/** Shape of a row returned from the cx_artifact table. */
export interface CxArtifactRow {
  id: string;
  message_id: string;
  conversation_id: string;
  user_id: string;
  organization_id: string | null;
  workspace_id: string | null;
  project_id: string | null;
  task_id: string | null;
  artifact_type: ArtifactType;
  status: ArtifactStatus;
  external_system: string | null;
  external_id: string | null;
  external_url: string | null;
  title: string | null;
  description: string | null;
  thumbnail_url: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

// ── Redux record shape (camelCase — in-memory representation) ─────────────

/** In-memory artifact record stored in Redux. camelCase version of CxArtifactRow. */
export interface CxArtifactRecord {
  id: string;
  messageId: string;
  conversationId: string;
  userId: string;
  organizationId: string | null;
  workspaceId: string | null;
  projectId: string | null;
  taskId: string | null;
  artifactType: ArtifactType;
  status: ArtifactStatus;
  externalSystem: string | null;
  externalId: string | null;
  externalUrl: string | null;
  title: string | null;
  description: string | null;
  thumbnailUrl: string | null;
  metadata: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

/** Convert a DB row to a Redux record. */
export function rowToArtifactRecord(row: CxArtifactRow): CxArtifactRecord {
  return {
    id: row.id,
    messageId: row.message_id,
    conversationId: row.conversation_id,
    userId: row.user_id,
    organizationId: row.organization_id,
    workspaceId: row.workspace_id,
    projectId: row.project_id,
    taskId: row.task_id,
    artifactType: row.artifact_type,
    status: row.status,
    externalSystem: row.external_system,
    externalId: row.external_id,
    externalUrl: row.external_url,
    title: row.title,
    description: row.description,
    thumbnailUrl: row.thumbnail_url,
    metadata: row.metadata ?? {},
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// ── API payload types ─────────────────────────────────────────────────────

/** Payload to create a new artifact. */
export interface CreateArtifactPayload {
  messageId: string;
  conversationId: string;
  artifactType: ArtifactType;
  title?: string;
  description?: string;
  externalSystem?: string;
  externalId?: string;
  externalUrl?: string;
  thumbnailUrl?: string;
  metadata?: Record<string, unknown>;
  // Org context — captured from appContextSlice at dispatch time
  organizationId?: string | null;
  workspaceId?: string | null;
  projectId?: string | null;
  taskId?: string | null;
}

/** Payload to update an existing artifact. */
export interface UpdateArtifactPayload {
  id: string;
  status?: ArtifactStatus;
  title?: string;
  description?: string;
  externalSystem?: string;
  externalId?: string;
  externalUrl?: string;
  thumbnailUrl?: string;
  metadata?: Record<string, unknown>;
}

/** Filters for querying artifacts. */
export interface ArtifactFilters {
  artifactType?: ArtifactType;
  status?: ArtifactStatus;
  projectId?: string;
  taskId?: string;
  conversationId?: string;
  messageId?: string;
}

// ── HTML page record (from /api/html-pages list response) ─────────────────

/** A page record as returned by the html-pages API list/get actions. */
export interface HtmlPageRecord {
  id: string;
  metaTitle: string;
  metaDescription: string | null;
  metaKeywords: string | null;
  ogImage: string | null;
  canonicalUrl: string | null;
  isIndexable: boolean;
  createdAt: string;
  updatedAt?: string;
  url: string;
  artifactId: string | null;
  sourceMessageId: string | null;
}
