import {
    Brain,
    Code,
    User,
    Database,
    Mail,
    Calendar,
    FileText,
    Webhook,
    ArrowRightLeft,
    Plus,
    Cpu,
    MessageSquare,
    Image,
    Zap,
    Settings,
    Command,
    Bot,
    Cog,
    Filter,
    File,
    Globe,
    Play,
    Plug,
    Terminal,
    Radio,
    MoreHorizontal,
} from "lucide-react";

export const CATEGORY_DEFINITIONS = [
    { id: "prompts", icon: MessageSquare, label: "Prompts" },
    { id: "agents", icon: Bot, label: "Agents" },
    { id: "recipes", icon: Brain, label: "Recipes" },
    { id: "processors", icon: Cog, label: "Processors" },
    { id: "extractors", icon: Filter, label: "Extractors" },
    { id: "files", icon: File, label: "Files" },
    { id: "database", icon: Database, label: "Database", title: "Database Functions" },
    { id: "web", icon: Globe, label: "Web", title: "Web Services" },
    { id: "media", icon: Image, label: "Media", title: "Media Processing" },
    { id: "documents", icon: FileText, label: "Documents" },
    { id: "integrations", icon: Plug, label: "Integrations" },
    { id: "commands", icon: Terminal, label: "Commands" },
    { id: "executors", icon: Play, label: "Executors" },
    { id: "api", icon: Radio, label: "API", title: "API Integrations" },
    { id: "other", icon: MoreHorizontal, label: "Other", title: "Other Functions" },
];

export const INTEGRATION_NODES = [
    {
        id: "userInput",
        type: "userInput",
        icon: User,
        label: "User Input",
        description: "Capture input data from users through forms, prompts, or interactive interfaces.",
    },
    {
        id: "brokerRelay",
        type: "brokerRelay",
        icon: ArrowRightLeft,
        label: "Broker Relay",
        description: "Route and transform data between different systems and services in your workflow.",
    },
    {
        id: "agent",
        type: "agent",
        icon: Brain,
        label: "Agent",
        description: "Deploy AI agents to perform autonomous tasks and decision-making processes.",
    },
    {
        id: "api",
        type: "api",
        icon: Webhook,
        label: "API",
        description: "Connect to external APIs and web services to fetch or send data.",
    },
    {
        id: "database",
        type: "database",
        icon: Database,
        label: "Database",
        description: "Store, retrieve, and manipulate data using various database operations.",
    },
    {
        id: "email",
        type: "email",
        icon: Mail,
        label: "Email",
        description: "Send automated emails, notifications, and communication to users or systems.",
    },
    {
        id: "calendar",
        type: "calendar",
        icon: Calendar,
        label: "Calendar",
        description: "Schedule events, manage appointments, and integrate with calendar systems.",
    },
    {
        id: "fileOperation",
        type: "fileOperation",
        icon: FileText,
        label: "File Ops",
        description: "Read, write, upload, download, and manipulate files and documents.",
    },
];
