export const classColorOptions = {
    rose: {
      card: "bg-white dark:bg-slate-900 overflow-hidden p-0 rounded-3xl border border-rose-200 dark:border-rose-600",  
      cardHeader: "bg-gray-100 dark:bg-gray-700 border border-rose-200 dark:border-rose-600 p-3 rounded-t-3xl",
      cardTitle: "text-rose-500 dark:text-rose-600",
      cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
      cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
      cardContent: "text-gray-600 dark:text-gray-300 text-sm",
      cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    primary: {
        card: "bg-gray-100 dark:bg-gray-700 border border-rose-200 dark:border-rose-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-rose-200 dark:border-rose-600 p-3 rounded-t-3xl",
        cardTitle: "text-rose-500 dark:text-rose-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    blue: {
        card: "bg-gray-100 dark:bg-gray-700 border border-blue-200 dark:border-blue-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-blue-200 dark:border-blue-600 p-3 rounded-t-3xl",
        cardTitle: "text-blue-500 dark:text-blue-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    green: {
        card: "bg-gray-100 dark:bg-gray-700 border border-green-200 dark:border-green-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-green-200 dark:border-green-600 p-3 rounded-t-3xl",
        cardTitle: "text-green-500 dark:text-green-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    yellow: {
        card: "bg-gray-100 dark:bg-gray-700 border border-yellow-200 dark:border-yellow-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-yellow-200 dark:border-yellow-600 p-3 rounded-t-3xl",
        cardTitle: "text-yellow-500 dark:text-yellow-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    red: {
        card: "bg-gray-100 dark:bg-gray-700 border border-red-200 dark:border-red-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-red-200 dark:border-red-600 p-3 rounded-t-3xl",
        cardTitle: "text-red-500 dark:text-red-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    purple: {
        card: "bg-gray-100 dark:bg-gray-700 border border-purple-200 dark:border-purple-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-purple-200 dark:border-purple-600 p-3 rounded-t-3xl",
        cardTitle: "text-purple-500 dark:text-purple-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    orange: {
        card: "bg-gray-100 dark:bg-gray-700 border border-orange-200 dark:border-orange-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-orange-200 dark:border-orange-600 p-3 rounded-t-3xl",
        cardTitle: "text-orange-500 dark:text-orange-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    pink: {
        card: "bg-gray-100 dark:bg-gray-700 border border-pink-200 dark:border-pink-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-pink-200 dark:border-pink-600 p-3 rounded-t-3xl",
        cardTitle: "text-pink-500 dark:text-pink-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    gray: {
        card: "bg-gray-100 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 p-3 rounded-t-3xl",
        cardTitle: "text-gray-500 dark:text-gray-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    indigo: {
        card: "bg-gray-100 dark:bg-gray-700 border border-indigo-200 dark:border-indigo-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-indigo-200 dark:border-indigo-600 p-3 rounded-t-3xl",
        cardTitle: "text-indigo-500 dark:text-indigo-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    teal: {
        card: "bg-gray-100 dark:bg-gray-700 border border-teal-200 dark:border-teal-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-teal-200 dark:border-teal-600 p-3 rounded-t-3xl",
        cardTitle: "text-teal-500 dark:text-teal-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    cyan: {
        card: "bg-gray-100 dark:bg-gray-700 border border-cyan-200 dark:border-cyan-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-cyan-200 dark:border-cyan-600 p-3 rounded-t-3xl",
        cardTitle: "text-cyan-500 dark:text-cyan-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    amber: {
        card: "bg-gray-100 dark:bg-gray-700 border border-amber-200 dark:border-amber-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-amber-200 dark:border-amber-600 p-3 rounded-t-3xl",
        cardTitle: "text-amber-500 dark:text-amber-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    lime: {
        card: "bg-gray-100 dark:bg-gray-700 border border-lime-200 dark:border-lime-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-lime-200 dark:border-lime-600 p-3 rounded-t-3xl",
        cardTitle: "text-lime-500 dark:text-lime-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    emerald: {
        card: "bg-gray-100 dark:bg-gray-700 border border-emerald-200 dark:border-emerald-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-emerald-200 dark:border-emerald-600 p-3 rounded-t-3xl",
        cardTitle: "text-emerald-500 dark:text-emerald-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    violet: {
        card: "bg-gray-100 dark:bg-gray-700 border border-violet-200 dark:border-violet-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-violet-200 dark:border-violet-600 p-3 rounded-t-3xl",
        cardTitle: "text-violet-500 dark:text-violet-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
    fuchsia: {
        card: "bg-gray-100 dark:bg-gray-700 border border-fuchsia-200 dark:border-fuchsia-600 p-3 rounded-t-3xl",
        cardHeader: "bg-gray-100 dark:bg-gray-700 border border-fuchsia-200 dark:border-fuchsia-600 p-3 rounded-t-3xl",
        cardTitle: "text-fuchsia-500 dark:text-fuchsia-600",
        cardDescription: "text-gray-600 dark:text-gray-300 text-sm",
        cardDescriptionNode: "text-gray-600 dark:text-gray-300 text-sm pt-2",
        cardContent: "text-gray-600 dark:text-gray-300 text-sm",
        cardFooter: "flex justify-end gap-3 pt-0 border-t border-gray-200 dark:border-gray-800",
    },
};
