import type { WAConversation } from "../types";

const NOW = new Date("2026-05-04T21:30:00");

function iso(offsetMs: number): string {
  return new Date(NOW.getTime() + offsetMs).toISOString();
}

const MIN = 60_000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;

export const MOCK_CONVERSATIONS: WAConversation[] = [
  {
    id: "self",
    name: "Armani (You)",
    avatarUrl: null,
    isGroup: false,
    participants: [{ id: "me", name: "Armani" }],
    lastMessagePreview: "https://github.com/anthropics/claude-code",
    lastMessageAt: iso(-DAY),
    lastMessageStatus: "read",
    lastMessageIsOwn: true,
    unreadCount: 0,
    isPinned: true,
  },
  {
    id: "kelvin",
    name: "Kelvin React Dev Mantine",
    avatarUrl: null,
    isGroup: false,
    participants: [{ id: "kelvin", name: "Kelvin Mantine", online: true }],
    lastMessagePreview: "I need to see what you're talking about with the changes…",
    lastMessageAt: iso(-3 * MIN),
    lastMessageStatus: "read",
    lastMessageIsOwn: true,
    unreadCount: 0,
    online: true,
  },
  {
    id: "steve",
    name: "Steve Wright",
    avatarUrl: null,
    isGroup: false,
    participants: [{ id: "steve", name: "Steve Wright" }],
    lastMessagePreview: "okay, I am starting on the new dashboard layout this morning",
    lastMessageAt: iso(-12 * HOUR - 16 * MIN),
    lastMessageStatus: "delivered",
    lastMessageIsOwn: false,
    unreadCount: 1,
  },
  {
    id: "aamir",
    name: "Aamir Hussain",
    avatarUrl: null,
    isGroup: false,
    participants: [{ id: "aamir", name: "Aamir Hussain" }],
    lastMessagePreview: "Send me a copy of the SEO audit when you get a chance",
    lastMessageAt: iso(-13 * HOUR - 15 * MIN),
    lastMessageStatus: "sent",
    lastMessageIsOwn: false,
    unreadCount: 0,
    draft: "Send me a copy of the SEO audit when you get a chance",
  },
  {
    id: "melisa",
    name: "+90 543 312 8810 (Melisa)",
    avatarUrl: null,
    isGroup: false,
    participants: [{ id: "melisa", name: "Melisa" }],
    lastMessagePreview: "Patients' daily schedule is attached for review",
    lastMessageAt: iso(-13 * HOUR - 24 * MIN),
    lastMessageStatus: "delivered",
    lastMessageIsOwn: false,
    unreadCount: 0,
  },
  {
    id: "kamal",
    name: "Kamal Accounting",
    avatarUrl: null,
    isGroup: true,
    participants: [
      { id: "k1", name: "Kamal" },
      { id: "k2", name: "Sarah" },
      { id: "k3", name: "Mike" },
    ],
    lastMessagePreview: "Ok",
    lastMessageAt: iso(-3 * DAY),
    lastMessageStatus: "read",
    lastMessageIsOwn: false,
    unreadCount: 0,
  },
  {
    id: "amir-invoices",
    name: "Amir Invoices",
    avatarUrl: null,
    isGroup: true,
    participants: [
      { id: "a1", name: "Amir" },
      { id: "a2", name: "Finance" },
    ],
    lastMessagePreview: "This is approved — proceed with the wire transfer",
    lastMessageAt: iso(-4 * DAY),
    lastMessageStatus: "read",
    lastMessageIsOwn: true,
    unreadCount: 0,
  },
  {
    id: "cic-seo",
    name: "CIC SEO",
    avatarUrl: null,
    isGroup: true,
    participants: [
      { id: "c1", name: "Aamir" },
      { id: "c2", name: "Linda" },
      { id: "c3", name: "Ben" },
    ],
    lastMessagePreview: "Aamir Hussain SEO Admin: rolling out the new keyword set tomorrow",
    lastMessageAt: iso(-7 * DAY),
    lastMessageStatus: "read",
    lastMessageIsOwn: false,
    unreadCount: 0,
    isMuted: true,
  },
  {
    id: "albie",
    name: "Albie Rafael",
    avatarUrl: null,
    isGroup: false,
    participants: [{ id: "albie", name: "Albie Rafael" }],
    lastMessagePreview: "Just 31 Days Until Launch — counting down with you",
    lastMessageAt: iso(-7 * DAY),
    lastMessageStatus: "read",
    lastMessageIsOwn: false,
    unreadCount: 0,
  },
  {
    id: "tools-purchasing",
    name: "TOOLS PURCHASING",
    avatarUrl: null,
    isGroup: true,
    participants: [
      { id: "t1", name: "Kamal" },
      { id: "t2", name: "Procurement" },
    ],
    lastMessagePreview: "Kamal Accounting: PO #4421 has been logged for approval",
    lastMessageAt: iso(-7 * DAY),
    lastMessageStatus: "read",
    lastMessageIsOwn: false,
    unreadCount: 0,
  },
  {
    id: "aamir-2",
    name: "Aamir Hussain SEO Admin",
    avatarUrl: null,
    isGroup: false,
    participants: [{ id: "aamir2", name: "Aamir Hussain" }],
    lastMessagePreview: "Steve Wright: I added the meta descriptions for the regional pages",
    lastMessageAt: iso(-8 * DAY),
    lastMessageStatus: "read",
    lastMessageIsOwn: false,
    unreadCount: 0,
  },
  {
    id: "accounting-team",
    name: "Accounting Team",
    avatarUrl: null,
    isGroup: true,
    participants: [
      { id: "ac1", name: "Kamal" },
      { id: "ac2", name: "Layla" },
    ],
    lastMessagePreview: "Kamal Accounting: month-end close is scheduled for Friday",
    lastMessageAt: iso(-11 * DAY),
    lastMessageStatus: "read",
    lastMessageIsOwn: false,
    unreadCount: 0,
  },
  {
    id: "praveen",
    name: "Praveen Pemathilaka",
    avatarUrl: null,
    isGroup: false,
    participants: [{ id: "praveen", name: "Praveen P" }],
    lastMessagePreview: "I will contact with the supplier and confirm by tomorrow",
    lastMessageAt: iso(-12 * DAY),
    lastMessageStatus: "read",
    lastMessageIsOwn: false,
    unreadCount: 0,
  },
  {
    id: "ts-team",
    name: "TS Team",
    avatarUrl: null,
    isGroup: true,
    participants: [
      { id: "ts1", name: "Engineering" },
      { id: "ts2", name: "QA" },
    ],
    lastMessagePreview: "Draft: The CIC website redesign is going live next week",
    lastMessageAt: iso(-12 * DAY),
    lastMessageStatus: "sent",
    lastMessageIsOwn: false,
    unreadCount: 0,
    draft: "The CIC website redesign is going live next week",
  },
];

export function getMockConversations(): WAConversation[] {
  return MOCK_CONVERSATIONS;
}
