import {
    IconSquareX, IconSquareXFilled, IconSquares, IconSquaresDiagonal, IconSquaresFilled, IconSquaresSelected, IconStack,
    IconStack2, IconStack2Filled, IconStack3, IconStack3Filled, IconStackBack, IconStackBackward, IconStackFilled,
    IconStackForward, IconStackFront, IconStackMiddle, IconStackPop, IconStackPush, IconStairs, IconStairsDown,
    IconStairsUp, IconStar, IconStarFilled, IconStarHalf, IconStarHalfFilled, IconStarOff, IconStars, IconStarsFilled,
    IconStarsOff, IconStatusChange, IconSteam, IconSteeringWheel, IconSteeringWheelFilled, IconSteeringWheelOff,
    IconStepInto, IconStepOut, IconStereoGlasses, IconStethoscope, IconStethoscopeOff, IconSticker, IconSticker2,
    IconStopwatch, IconStorm, IconStormOff, IconStretching, IconStretching2, IconStrikethrough, IconSubmarine,
    IconSubscript, IconSubtask, IconSum, IconSumOff, IconSun, IconSunElectricity, IconSunFilled, IconSunHigh,
    IconSunLow, IconSunMoon, IconSunOff, IconSunWind, IconSunglasses, IconSunglassesFilled, IconSunrise, IconSunset,
    IconSunset2, IconSuperscript, IconSvg, IconSwimming, IconSwipe, IconSwipeDown, IconSwipeDownFilled, IconSwipeLeft,
    IconSwipeLeftFilled, IconSwipeRight, IconSwipeRightFilled, IconSwipeUp, IconSwipeUpFilled, IconSwitch, IconSwitch2,
    IconSwitch3, IconSwitchHorizontal, IconSwitchVertical, IconSword, IconSwordOff, IconSwords, IconTable,
    IconTableAlias, IconTableColumn, IconTableDashed, IconTableDown, IconTableExport, IconTableFilled, IconTableHeart,
    IconTableImport, IconTableMinus, IconTableOff, IconTableOptions, IconTablePlus, IconTableRow, IconTableShare,
    IconTableShortcut, IconTableSpark, IconTag, IconTagFilled, IconTagMinus, IconTagOff, IconTagPlus, IconTagStarred,
    IconTags, IconTagsFilled, IconTagsOff, IconTallymark1, IconTallymark2, IconTallymark3, IconTallymark4,
    IconTallymarks, IconTank, IconTarget, IconTargetArrow, IconTargetOff, IconTax, IconTaxEuro, IconTaxPound,
    IconTeapot, IconTelescope, IconTelescopeOff, IconTemperature, IconTemperatureCelsius, IconTemperatureFahrenheit,
    IconTemperatureMinus, IconTemperatureOff, IconTemperaturePlus, IconTemperatureSnow, IconTemperatureSun,
    IconTemplate, IconTemplateOff, IconTent, IconTentOff, IconTerminal, IconTerminal2, IconTestPipe, IconTestPipe2,
    IconTestPipe2Filled, IconTestPipeOff, IconTex, IconTextCaption, IconTextColor, IconTextDecrease, IconTextDirectionLtr,
    IconTextDirectionRtl, IconTextGrammar, IconTextIncrease, IconTextOrientation, IconTextPlus, IconTextRecognition,
    IconTextResize, IconTextScan2, IconTextSize, IconTextSpellcheck, IconTextWrap, IconTextWrapColumn, IconTextWrapDisabled,
    IconTexture, IconTheater, IconThermometer, IconThumbDown, IconThumbDownFilled, IconThumbDownOff, IconThumbUp,
    IconThumbUpFilled, IconThumbUpOff, IconTicTac, IconTicket, IconTicketOff, IconTie, IconTilde, IconTiltShift,
    IconTiltShiftFilled, IconTiltShiftOff, IconTimeDuration0, IconTimeDuration10, IconTimeDuration15, IconTimeDuration30,
    IconTimeDuration45, IconTimeDuration5, IconTimeDuration60, IconTimeDuration90, IconTimeDurationOff, IconTimeline,
    IconTimelineEvent, IconTimelineEventExclamation, IconTimelineEventFilled, IconTimelineEventMinus, IconTimelineEventPlus,
    IconTimelineEventText, IconTimelineEventX, IconTimezone, IconTipJar, IconTipJarEuro, IconTipJarPound, IconTir,
    IconToggleLeft, IconToggleLeftFilled, IconToggleRight, IconToggleRightFilled, IconToiletPaper, IconToiletPaperOff,
    IconToml, IconTool, IconTools, IconToolsKitchen, IconToolsKitchen2, IconToolsKitchen2Off, IconToolsKitchen3,
    IconToolsKitchenOff, IconToolsOff, IconTooltip, IconTopologyBus, IconTopologyComplex, IconTopologyFull,
    IconTopologyFullHierarchy, IconTopologyRing, IconTopologyRing2, IconTopologyRing3, IconTopologyStar,
    IconTopologyStar2, IconTopologyStar3, IconTopologyStarRing, IconTopologyStarRing2, IconTopologyStarRing3,
    IconTorii, IconTornado, IconTournament, IconTower, IconTowerOff, IconTrack, IconTractor, IconTrademark,
    IconTrafficCone, IconTrafficConeOff, IconTrafficLights, IconTrafficLightsOff, IconTrain, IconTransactionBitcoin,
    IconTransactionDollar, IconTransactionEuro, IconTransactionPound, IconTransactionRupee, IconTransactionYen,
    IconTransactionYuan, IconTransfer, IconTransferIn, IconTransferOut, IconTransferVertical, IconTransform,
    IconTransformFilled, IconTransformPoint, IconTransformPointBottomLeft, IconTransformPointBottomRight,
    IconTransformPointTopLeft, IconTransformPointTopRight, IconTransitionBottom, IconTransitionBottomFilled,
    IconTransitionLeft, IconTransitionLeftFilled, IconTransitionRight, IconTransitionRightFilled,
    IconTransitionTop, IconTransitionTopFilled, IconTrash, IconTrashFilled, IconTrashOff, IconTrashX, IconTrashXFilled,
    IconTreadmill, IconTree, IconTrees, IconTrekking, IconTrendingDown, IconTrendingDown2, IconTrendingDown3,
    IconTrendingUp, IconTrendingUp2, IconTrendingUp3, IconTriangle, IconTriangleFilled, IconTriangleInverted,
    IconTriangleInvertedFilled, IconTriangleMinus, IconTriangleMinus2, IconTriangleOff, IconTrianglePlus,
    IconTrianglePlus2, IconTriangleSquareCircle, IconTriangleSquareCircleFilled, IconTriangles, IconTrident,
    IconTrolley, IconTrophy, IconTrophyFilled, IconTrophyOff, IconTrowel, IconTruck, IconTruckDelivery,
    IconTruckLoading, IconTruckOff, IconTruckReturn, IconTxt, IconTypeface, IconTypography, IconTypographyOff,
    IconUTurnLeft, IconUTurnRight, IconUfo, IconUfoOff, IconUhd, IconUmbrella, IconUmbrella2, IconUmbrellaClosed,
    IconUmbrellaClosed2, IconUmbrellaFilled, IconUmbrellaOff, IconUnderline, IconUniverse, IconUnlink, IconUpload,
    IconUrgent, IconUsb, IconUser, IconUserBitcoin, IconUserBolt, IconUserCancel, IconUserCheck, IconUserCircle,
    IconUserCode, IconUserCog, IconUserDollar, IconUserDown, IconUserEdit, IconUserExclamation, IconUserFilled,
    IconUserHeart, IconUserHexagon, IconUserMinus, IconUserOff, IconUserPause, IconUserPentagon, IconUserPin,
    IconUserPlus, IconUserQuestion, IconUserScan, IconUserScreen, IconUserSearch, IconUserShare, IconUserShield,
    IconUserSquare, IconUserSquareRounded, IconUserStar, IconUserUp, IconUserX, IconUsers, IconUsersGroup,
    IconUsersMinus, IconUsersPlus, IconUvIndex, IconUxCircle, IconVaccine, IconVaccineBottle, IconVaccineBottleOff,
    IconVaccineOff, IconVacuumCleaner, IconVariable, IconVariableMinus, IconVariableOff, IconVariablePlus, IconVector,
    IconVectorBezier, IconVectorBezier2, IconVectorBezierArc, IconVectorBezierCircle, IconVectorOff, IconVectorSpline,
    IconVectorTriangle, IconVectorTriangleOff, IconVenus, IconVersions, IconVersionsFilled, IconVersionsOff, IconVideo,
    IconVideoFilled, IconVideoMinus, IconVideoOff, IconVideoPlus, IconView360, IconView360Arrow, IconView360Number,
    IconView360Off, IconViewfinder, IconViewfinderOff, IconViewportNarrow, IconViewportShort, IconViewportTall,
    IconViewportWide, IconVinyl, IconVip, IconVipOff, IconVirus, IconVirusOff, IconVirusSearch, IconVocabulary,
    IconVocabularyOff, IconVolcano, IconVolume, IconVolume2, IconVolume3, IconVolumeOff, IconVs, IconWalk, IconWall,
    IconWallOff, IconWallet, IconWalletOff, IconWallpaper, IconWallpaperOff, IconWand, IconWandOff, IconWash,
    IconWashDry, IconWashDry1, IconWashDry2, IconWashDry3, IconWashDryA, IconWashDryDip, IconWashDryF, IconWashDryFlat,
    IconWashDryHang, IconWashDryOff, IconWashDryP, IconWashDryShade, IconWashDryW, IconWashDryclean, IconWashDrycleanOff,
    IconWashEco, IconWashGentle, IconWashHand, IconWashMachine, IconWashOff, IconWashPress,
    IconWashTemperature1, IconWashTemperature2, IconWashTemperature3, IconWashTemperature4,
    IconWashTemperature5, IconWashTemperature6, IconWashTumbleDry, IconWashTumbleOff,
    IconWaterpolo, IconWaveSawTool, IconWaveSine, IconWaveSquare, IconWavesElectricity,
    IconWebhook, IconWebhookOff, IconWeight, IconWheat, IconWheatOff, IconWheel, IconWheelchair,
    IconWheelchairOff, IconWhirl, IconWifi, IconWifi0, IconWifi1, IconWifi2, IconWifiOff, IconWind,
    IconWindElectricity, IconWindOff, IconWindmill, IconWindmillFilled, IconWindmillOff, IconWindow,
    IconWindowMaximize, IconWindowMinimize, IconWindowOff, IconWindsock, IconWindsockFilled,
    IconWiper, IconWiperWash, IconWoman, IconWomanFilled, IconWood, IconWorld, IconWorldBolt,
    IconWorldCancel, IconWorldCheck, IconWorldCode, IconWorldCog, IconWorldDollar, IconWorldDown,
    IconWorldDownload, IconWorldExclamation, IconWorldHeart, IconWorldLatitude, IconWorldLongitude,
    IconWorldMinus, IconWorldOff, IconWorldPause, IconWorldPin, IconWorldPlus, IconWorldQuestion,
    IconWorldSearch, IconWorldShare, IconWorldStar, IconWorldUp, IconWorldUpload, IconWorldWww,
    IconWorldX, IconWreckingBall, IconWriting, IconWritingOff, IconWritingSign, IconWritingSignOff,
    IconX, IconXPowerY, IconXboxA, IconXboxAFilled, IconXboxB, IconXboxBFilled, IconXboxX,
    IconXboxXFilled, IconXboxY, IconXboxYFilled, IconXd, IconXxx, IconYinYang, IconYinYangFilled,
    IconYoga, IconZeppelin, IconZeppelinFilled, IconZeppelinOff, IconZip, IconZodiacAquarius,
    IconZodiacAries, IconZodiacCancer, IconZodiacCapricorn, IconZodiacGemini, IconZodiacLeo,
    IconZodiacLibra, IconZodiacPisces, IconZodiacSagittarius, IconZodiacScorpio, IconZodiacTaurus,
    IconZodiacVirgo, IconZoom, IconZoomCancel, IconZoomCancelFilled, IconZoomCheck, IconZoomCheckFilled,
    IconZoomCode, IconZoomCodeFilled, IconZoomExclamation, IconZoomExclamationFilled, IconZoomFilled,
    IconZoomIn, IconZoomInArea, IconZoomInAreaFilled, IconZoomInFilled, IconZoomMoney, IconZoomMoneyFilled,
    IconZoomOut, IconZoomOutArea, IconZoomOutAreaFilled, IconZoomOutFilled, IconZoomPan, IconZoomPanFilled,
    IconZoomQuestion, IconZoomQuestionFilled, IconZoomReplace, IconZoomReset, IconZoomScan,
    IconZoomScanFilled, IconZzz, IconZzzOff,


} from "@tabler/icons-react";


export const availableIcons2 = {
    IconSquareX, IconSquareXFilled, IconSquares, IconSquaresDiagonal, IconSquaresFilled, IconSquaresSelected, IconStack,
    IconStack2, IconStack2Filled, IconStack3, IconStack3Filled, IconStackBack, IconStackBackward, IconStackFilled,
    IconStackForward, IconStackFront, IconStackMiddle, IconStackPop, IconStackPush, IconStairs, IconStairsDown,
    IconStairsUp, IconStar, IconStarFilled, IconStarHalf, IconStarHalfFilled, IconStarOff, IconStars, IconStarsFilled,
    IconStarsOff, IconStatusChange, IconSteam, IconSteeringWheel, IconSteeringWheelFilled, IconSteeringWheelOff,
    IconStepInto, IconStepOut, IconStereoGlasses, IconStethoscope, IconStethoscopeOff, IconSticker, IconSticker2,
    IconStopwatch, IconStorm, IconStormOff, IconStretching, IconStretching2, IconStrikethrough, IconSubmarine,
    IconSubscript, IconSubtask, IconSum, IconSumOff, IconSun, IconSunElectricity, IconSunFilled, IconSunHigh,
    IconSunLow, IconSunMoon, IconSunOff, IconSunWind, IconSunglasses, IconSunglassesFilled, IconSunrise, IconSunset,
    IconSunset2, IconSuperscript, IconSvg, IconSwimming, IconSwipe, IconSwipeDown, IconSwipeDownFilled, IconSwipeLeft,
    IconSwipeLeftFilled, IconSwipeRight, IconSwipeRightFilled, IconSwipeUp, IconSwipeUpFilled, IconSwitch, IconSwitch2,
    IconSwitch3, IconSwitchHorizontal, IconSwitchVertical, IconSword, IconSwordOff, IconSwords, IconTable,
    IconTableAlias, IconTableColumn, IconTableDashed, IconTableDown, IconTableExport, IconTableFilled, IconTableHeart,
    IconTableImport, IconTableMinus, IconTableOff, IconTableOptions, IconTablePlus, IconTableRow, IconTableShare,
    IconTableShortcut, IconTableSpark, IconTag, IconTagFilled, IconTagMinus, IconTagOff, IconTagPlus, IconTagStarred,
    IconTags, IconTagsFilled, IconTagsOff, IconTallymark1, IconTallymark2, IconTallymark3, IconTallymark4,
    IconTallymarks, IconTank, IconTarget, IconTargetArrow, IconTargetOff, IconTax, IconTaxEuro, IconTaxPound,
    IconTeapot, IconTelescope, IconTelescopeOff, IconTemperature, IconTemperatureCelsius, IconTemperatureFahrenheit,
    IconTemperatureMinus, IconTemperatureOff, IconTemperaturePlus, IconTemperatureSnow, IconTemperatureSun,
    IconTemplate, IconTemplateOff, IconTent, IconTentOff, IconTerminal, IconTerminal2, IconTestPipe, IconTestPipe2,
    IconTestPipe2Filled, IconTestPipeOff, IconTex, IconTextCaption, IconTextColor, IconTextDecrease, IconTextDirectionLtr,
    IconTextDirectionRtl, IconTextGrammar, IconTextIncrease, IconTextOrientation, IconTextPlus, IconTextRecognition,
    IconTextResize, IconTextScan2, IconTextSize, IconTextSpellcheck, IconTextWrap, IconTextWrapColumn, IconTextWrapDisabled,
    IconTexture, IconTheater, IconThermometer, IconThumbDown, IconThumbDownFilled, IconThumbDownOff, IconThumbUp,
    IconThumbUpFilled, IconThumbUpOff, IconTicTac, IconTicket, IconTicketOff, IconTie, IconTilde, IconTiltShift,
    IconTiltShiftFilled, IconTiltShiftOff, IconTimeDuration0, IconTimeDuration10, IconTimeDuration15, IconTimeDuration30,
    IconTimeDuration45, IconTimeDuration5, IconTimeDuration60, IconTimeDuration90, IconTimeDurationOff, IconTimeline,
    IconTimelineEvent, IconTimelineEventExclamation, IconTimelineEventFilled, IconTimelineEventMinus, IconTimelineEventPlus,
    IconTimelineEventText, IconTimelineEventX, IconTimezone, IconTipJar, IconTipJarEuro, IconTipJarPound, IconTir,
    IconToggleLeft, IconToggleLeftFilled, IconToggleRight, IconToggleRightFilled, IconToiletPaper, IconToiletPaperOff,
    IconToml, IconTool, IconTools, IconToolsKitchen, IconToolsKitchen2, IconToolsKitchen2Off, IconToolsKitchen3,
    IconToolsKitchenOff, IconToolsOff, IconTooltip, IconTopologyBus, IconTopologyComplex, IconTopologyFull,
    IconTopologyFullHierarchy, IconTopologyRing, IconTopologyRing2, IconTopologyRing3, IconTopologyStar,
    IconTopologyStar2, IconTopologyStar3, IconTopologyStarRing, IconTopologyStarRing2, IconTopologyStarRing3,
    IconTorii, IconTornado, IconTournament, IconTower, IconTowerOff, IconTrack, IconTractor, IconTrademark,
    IconTrafficCone, IconTrafficConeOff, IconTrafficLights, IconTrafficLightsOff, IconTrain, IconTransactionBitcoin,
    IconTransactionDollar, IconTransactionEuro, IconTransactionPound, IconTransactionRupee, IconTransactionYen,
    IconTransactionYuan, IconTransfer, IconTransferIn, IconTransferOut, IconTransferVertical, IconTransform,
    IconTransformFilled, IconTransformPoint, IconTransformPointBottomLeft, IconTransformPointBottomRight,
    IconTransformPointTopLeft, IconTransformPointTopRight, IconTransitionBottom, IconTransitionBottomFilled,
    IconTransitionLeft, IconTransitionLeftFilled, IconTransitionRight, IconTransitionRightFilled,
    IconTransitionTop, IconTransitionTopFilled, IconTrash, IconTrashFilled, IconTrashOff, IconTrashX, IconTrashXFilled,
    IconTreadmill, IconTree, IconTrees, IconTrekking, IconTrendingDown, IconTrendingDown2, IconTrendingDown3,
    IconTrendingUp, IconTrendingUp2, IconTrendingUp3, IconTriangle, IconTriangleFilled, IconTriangleInverted,
    IconTriangleInvertedFilled, IconTriangleMinus, IconTriangleMinus2, IconTriangleOff, IconTrianglePlus,
    IconTrianglePlus2, IconTriangleSquareCircle, IconTriangleSquareCircleFilled, IconTriangles, IconTrident,
    IconTrolley, IconTrophy, IconTrophyFilled, IconTrophyOff, IconTrowel, IconTruck, IconTruckDelivery,
    IconTruckLoading, IconTruckOff, IconTruckReturn, IconTxt, IconTypeface, IconTypography, IconTypographyOff,
    IconUTurnLeft, IconUTurnRight, IconUfo, IconUfoOff, IconUhd, IconUmbrella, IconUmbrella2, IconUmbrellaClosed,
    IconUmbrellaClosed2, IconUmbrellaFilled, IconUmbrellaOff, IconUnderline, IconUniverse, IconUnlink, IconUpload,
    IconUrgent, IconUsb, IconUser, IconUserBitcoin, IconUserBolt, IconUserCancel, IconUserCheck, IconUserCircle,
    IconUserCode, IconUserCog, IconUserDollar, IconUserDown, IconUserEdit, IconUserExclamation, IconUserFilled,
    IconUserHeart, IconUserHexagon, IconUserMinus, IconUserOff, IconUserPause, IconUserPentagon, IconUserPin,
    IconUserPlus, IconUserQuestion, IconUserScan, IconUserScreen, IconUserSearch, IconUserShare, IconUserShield,
    IconUserSquare, IconUserSquareRounded, IconUserStar, IconUserUp, IconUserX, IconUsers, IconUsersGroup,
    IconUsersMinus, IconUsersPlus, IconUvIndex, IconUxCircle, IconVaccine, IconVaccineBottle, IconVaccineBottleOff,
    IconVaccineOff, IconVacuumCleaner, IconVariable, IconVariableMinus, IconVariableOff, IconVariablePlus, IconVector,
    IconVectorBezier, IconVectorBezier2, IconVectorBezierArc, IconVectorBezierCircle, IconVectorOff, IconVectorSpline,
    IconVectorTriangle, IconVectorTriangleOff, IconVenus, IconVersions, IconVersionsFilled, IconVersionsOff, IconVideo,
    IconVideoFilled, IconVideoMinus, IconVideoOff, IconVideoPlus, IconView360, IconView360Arrow, IconView360Number,
    IconView360Off, IconViewfinder, IconViewfinderOff, IconViewportNarrow, IconViewportShort, IconViewportTall,
    IconViewportWide, IconVinyl, IconVip, IconVipOff, IconVirus, IconVirusOff, IconVirusSearch, IconVocabulary,
    IconVocabularyOff, IconVolcano, IconVolume, IconVolume2, IconVolume3, IconVolumeOff, IconVs, IconWalk, IconWall,
    IconWallOff, IconWallet, IconWalletOff, IconWallpaper, IconWallpaperOff, IconWand, IconWandOff, IconWash,
    IconWashDry, IconWashDry1, IconWashDry2, IconWashDry3, IconWashDryA, IconWashDryDip, IconWashDryF, IconWashDryFlat,
    IconWashDryHang, IconWashDryOff, IconWashDryP, IconWashDryShade, IconWashDryW, IconWashDryclean, IconWashDrycleanOff,
    IconWashEco, IconWashGentle, IconWashHand, IconWashMachine, IconWashOff, IconWashPress,
    IconWashTemperature1, IconWashTemperature2, IconWashTemperature3, IconWashTemperature4,
    IconWashTemperature5, IconWashTemperature6, IconWashTumbleDry, IconWashTumbleOff,
    IconWaterpolo, IconWaveSawTool, IconWaveSine, IconWaveSquare, IconWavesElectricity,
    IconWebhook, IconWebhookOff, IconWeight, IconWheat, IconWheatOff, IconWheel, IconWheelchair,
    IconWheelchairOff, IconWhirl, IconWifi, IconWifi0, IconWifi1, IconWifi2, IconWifiOff, IconWind,
    IconWindElectricity, IconWindOff, IconWindmill, IconWindmillFilled, IconWindmillOff, IconWindow,
    IconWindowMaximize, IconWindowMinimize, IconWindowOff, IconWindsock, IconWindsockFilled,
    IconWiper, IconWiperWash, IconWoman, IconWomanFilled, IconWood, IconWorld, IconWorldBolt,
    IconWorldCancel, IconWorldCheck, IconWorldCode, IconWorldCog, IconWorldDollar, IconWorldDown,
    IconWorldDownload, IconWorldExclamation, IconWorldHeart, IconWorldLatitude, IconWorldLongitude,
    IconWorldMinus, IconWorldOff, IconWorldPause, IconWorldPin, IconWorldPlus, IconWorldQuestion,
    IconWorldSearch, IconWorldShare, IconWorldStar, IconWorldUp, IconWorldUpload, IconWorldWww,
    IconWorldX, IconWreckingBall, IconWriting, IconWritingOff, IconWritingSign, IconWritingSignOff,
    IconX, IconXPowerY, IconXboxA, IconXboxAFilled, IconXboxB, IconXboxBFilled, IconXboxX,
    IconXboxXFilled, IconXboxY, IconXboxYFilled, IconXd, IconXxx, IconYinYang, IconYinYangFilled,
    IconYoga, IconZeppelin, IconZeppelinFilled, IconZeppelinOff, IconZip, IconZodiacAquarius,
    IconZodiacAries, IconZodiacCancer, IconZodiacCapricorn, IconZodiacGemini, IconZodiacLeo,
    IconZodiacLibra, IconZodiacPisces, IconZodiacSagittarius, IconZodiacScorpio, IconZodiacTaurus,
    IconZodiacVirgo, IconZoom, IconZoomCancel, IconZoomCancelFilled, IconZoomCheck, IconZoomCheckFilled,
    IconZoomCode, IconZoomCodeFilled, IconZoomExclamation, IconZoomExclamationFilled, IconZoomFilled,
    IconZoomIn, IconZoomInArea, IconZoomInAreaFilled, IconZoomInFilled, IconZoomMoney, IconZoomMoneyFilled,
    IconZoomOut, IconZoomOutArea, IconZoomOutAreaFilled, IconZoomOutFilled, IconZoomPan, IconZoomPanFilled,
    IconZoomQuestion, IconZoomQuestionFilled, IconZoomReplace, IconZoomReset, IconZoomScan,
    IconZoomScanFilled, IconZzz, IconZzzOff,
};
