import {
    FileJson, FileText, FileCode, FileImage,
    FileInput, FileVideo, FileSpreadsheet,
    FileAudio, Table2, FileArchive, Book,
    Circle, Square, Triangle, Heart, Star,
    // Arrows and navigation
    ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
    ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
    // User interface
    Search, Settings, Home, Menu, X, Check, Plus, Minus,
    // Media and files
    Image, Video, Music, File, Folder, Camera,
    // Communication
    Mail, Phone, MessageCircle, Bell,
    // Users and accounts
    User, Users, UserPlus, UserMinus,
    // Devices and tech
    Smartphone, Tablet, Laptop, Monitor,
    // Weather and nature
    Sun, Moon, Cloud, CloudRain,
    // Business and commerce
    DollarSign, ShoppingCart, CreditCard,
    // Social and sharing
    Share, Link, Upload, Download,
    // Editor tools
    Bold, Italic, Underline, List,
    // Others
    Calendar, Clock, Map, Bookmark,
    Save, Trash, Edit, Eye, EyeOff,
    Lock, Unlock, Key, Flag,
    ClipboardCopy, Clipboard,
    Database, Server, Code,
    StopCircleIcon, PlayCircleIcon, PauseCircleIcon,

} from 'lucide-react';
import {
    IconFile3d, IconFileAi, IconFileAlert, IconFileAnalytics, IconFileArrowLeft, IconFileArrowRight,
    IconFileBarcode, IconFileBitcoin, IconFileBroken, IconFileCertificate, IconFileChart, IconFileCheck,
    IconFileCode, IconFileCode2, IconFileCv, IconFileDatabase, IconFileDelta, IconFileDescription,
    IconFileDiff, IconFileDigit, IconFileDislike, IconFileDollar, IconFileDots, IconFileDownload,
    IconFileEuro, IconFileExcel, IconFileExport, IconFileFilled, IconFileFunction, IconFileHorizontal,
    IconFileImport, IconFileInfinity, IconFileInfo, IconFileInvoice, IconFileIsr, IconFileLambda,
    IconFileLike, IconFileMinus, IconFileMusic, IconFileNeutral, IconFileOff, IconFileOrientation,
    IconFilePencil, IconFilePercent, IconFilePhone, IconFilePlus, IconFilePower, IconFileReport,
    IconFileRss, IconFileSad, IconFileScissors, IconFileSearch, IconFileSettings, IconFileShredder,
    IconFileSignal, IconFileSmile, IconFileSpark, IconFileSpreadsheet, IconFileStack, IconFileStar,
    IconFileSymlink, IconFileText, IconFileTextAi, IconFileTextSpark, IconFileTime, IconFileTypeBmp,
    IconFileTypeCss, IconFileTypeCsv, IconFileTypeDoc, IconFileTypeDocx, IconFileTypeHtml, IconFileTypeJpg,
    IconFileTypeJs, IconFileTypeJsx, IconFileTypePdf, IconFileTypePhp, IconFileTypePng, IconFileTypePpt,
    IconFileTypeRs, IconFileTypeSql, IconFileTypeSvg, IconFileTypeTs, IconFileTypeTsx, IconFileTypeTxt,
    IconFileTypeVue, IconFileTypeXls, IconFileTypeXml, IconFileTypeZip, IconFileTypography, IconFileUnknown,
    IconFileUpload, IconFileVector, IconFileWord, IconFileX, IconFileXFilled, IconFileZip, IconFiles,
    IconFilesOff, IconGif, IconGlobe, IconGraph,
    IconFilter, IconFilterBolt, IconFilterCancel, IconFilterCheck, IconFilterCode, IconFilterCog,
    IconFilterDiscount, IconFilterDollar, IconFilterDown, IconFilterEdit, IconFilterExclamation,
    IconFilterFilled, IconFilterHeart, IconFilterMinus, IconFilterOff, IconFilterPause, IconFilterPin,
    IconFilterPlus, IconFilterQuestion, IconFilterSearch, IconFilterShare, IconFilterStar, IconFilterUp,
    IconFilterX, IconFilters, IconFiltersFilled, IconFingerprint, IconFingerprintOff, IconFingerprintScan,
    IconHandTwoFingers, IconHanger, IconHanger2, IconHanger2Filled, IconHangerOff, IconHash, IconHaze,
    IconHazeMoon, IconHdr, IconHeading, IconHeadingOff, IconHeadphones, IconHeadphonesFilled,



    IconHeadphonesOff, IconHeadset, IconHeadsetOff, IconHealthRecognition, IconHeart, IconHeartBitcoin,
    IconHeartBolt, IconHeartBroken, IconHeartCancel, IconHeartCheck, IconHeartCode, IconHeartCog,
    IconHeartDiscount, IconHeartDollar, IconHeartDown, IconHeartExclamation, IconHeartFilled, IconHeartHandshake,
    IconHeartMinus, IconHeartOff, IconHeartPause, IconHeartPin, IconHeartPlus, IconHeartQuestion, IconHeartRateMonitor,
    IconHeartSearch, IconHeartShare, IconHeartSpark, IconHeartStar, IconHeartUp, IconHeartX, IconHeartbeat, IconHearts,
    IconHeartsOff, IconHelicopter, IconHelicopterLanding, IconHelicopterLandingFilled, IconHelmet, IconHelmetOff,
    IconHelp, IconHelpCircle, IconHelpCircleFilled, IconHelpHexagon, IconHelpHexagonFilled, IconHelpOctagon,
    IconHelpOctagonFilled, IconHelpOff, IconHelpSmall, IconHelpSquare, IconHelpSquareFilled, IconHelpSquareRounded,
    IconHelpSquareRoundedFilled, IconHelpTriangle, IconHelpTriangleFilled,
    IconInputAi, IconInputCheck, IconInputSearch, IconInputSpark, IconInputX, IconInvoice, IconIroning,
    IconIroning1, IconIroning1Filled, IconIroning2, IconIroning2Filled, IconIroning3, IconIroning3Filled,
    IconIroningFilled, IconIroningOff, IconIroningSteam, IconIroningSteamFilled, IconIroningSteamOff,
    IconIrregularPolyhedron, IconIrregularPolyhedronOff, IconIrregularPolyhedronPlus, IconItalic, IconJacket,
    IconJetpack, IconJetpackFilled, IconJewishStar, IconJewishStarFilled, IconJoinBevel, IconJoinRound,
    IconJoinStraight, IconJoker, IconJpg, IconJson, IconJumpRope, IconKarate, IconKayak, IconKering,
    IconKerning, IconKey, IconKeyFilled, IconKeyOff, IconKeyboard, IconKeyboardFilled, IconKeyboardHide,
    IconKeyboardOff, IconKeyboardShow, IconKeyframe, IconKeyframeAlignCenter, IconKeyframeAlignCenterFilled,


    IconKeyframeAlignHorizontal, IconKeyframeAlignHorizontalFilled, IconKeyframeAlignVertical,
    IconKeyframeAlignVerticalFilled, IconKeyframeFilled, IconKeyframes, IconKeyframesFilled, IconLabel,
    IconLabelFilled, IconLabelImportant, IconLabelImportantFilled, IconLabelOff, IconLadder, IconLadderOff,
    IconLadle, IconLambda, IconLamp, IconLamp2, IconLampOff, IconLane, IconLanguage, IconLanguageHiragana,
    IconLanguageKatakana, IconLanguageOff, IconLasso, IconLassoOff, IconLassoPolygon, IconLassoPolygonFilled,
    IconLaurelWreath, IconLaurelWreath1, IconLaurelWreath2, IconLaurelWreath3, IconLaurelWreathFilled,
    IconLayersDifference, IconLayersIntersect, IconLayersIntersect2, IconLayersLinked, IconLayersOff,
    IconLayersSelected, IconLayersSelectedBottom, IconLayersSubtract, IconLayersUnion, IconLayout, IconLayout2,
    IconLayout2Filled, IconLayoutAlignBottom, IconLayoutAlignBottomFilled, IconLayoutAlignCenter,
    IconLayoutAlignCenterFilled, IconLayoutAlignLeft, IconLayoutAlignLeftFilled, IconLayoutAlignMiddle,
    IconLayoutAlignMiddleFilled, IconLayoutAlignRight, IconLayoutAlignRightFilled, IconLayoutAlignTop,

    IconLayoutAlignTopFilled, IconLayoutBoard, IconLayoutBoardSplit, IconLayoutBottombar, IconLayoutBottombarCollapse,
    IconLayoutBottombarCollapseFilled, IconLayoutBottombarExpand, IconLayoutBottombarExpandFilled,
    IconLayoutBottombarFilled, IconLayoutBottombarInactive, IconLayoutCards, IconLayoutCardsFilled,
    IconLayoutCollage, IconLayoutColumns, IconLayoutDashboard, IconLayoutDashboardFilled, IconLayoutDistributeHorizontal,
    IconLayoutDistributeHorizontalFilled, IconLayoutDistributeVertical, IconLayoutDistributeVerticalFilled,
    IconLayoutFilled, IconLayoutGrid, IconLayoutGridAdd, IconLayoutGridFilled, IconLayoutGridRemove, IconLayoutKanban,
    IconLayoutKanbanFilled, IconLayoutList, IconLayoutListFilled, IconLayoutNavbar, IconLayoutNavbarCollapse,
    IconLayoutNavbarCollapseFilled, IconLayoutNavbarExpand, IconLayoutNavbarExpandFilled, IconLayoutNavbarFilled,
    IconLayoutNavbarInactive, IconLayoutOff, IconLayoutRows, IconLayoutSidebar, IconLayoutSidebarFilled,

    IconLayoutSidebarInactive, IconLayoutSidebarLeftCollapse, IconLayoutSidebarLeftCollapseFilled,
    IconLayoutSidebarLeftExpand, IconLayoutSidebarLeftExpandFilled, IconLayoutSidebarRight, IconLayoutSidebarRightCollapse,
    IconLayoutSidebarRightCollapseFilled, IconLayoutSidebarRightExpand, IconLayoutSidebarRightExpandFilled,
    IconLayoutSidebarRightFilled, IconLayoutSidebarRightInactive, IconLeaf, IconLeaf2, IconLeafOff, IconLego,
    IconLegoFilled, IconLegoOff, IconLemon, IconLemon2, IconLemon2Filled, IconLetterA, IconLetterASmall,
    IconLetterB, IconLetterBSmall, IconLetterC, IconLetterCSmall, IconLetterCase, IconLetterCaseLower,
    IconLetterCaseToggle, IconLetterCaseUpper, IconLetterD, IconLetterDSmall, IconLetterE, IconLetterESmall,
    IconLetterF, IconLetterFSmall, IconLetterG, IconLetterGSmall, IconLetterH, IconLetterHSmall, IconLetterI,
    IconLetterISmall, IconLetterJ, IconLetterJSmall, IconLetterK, IconLetterKSmall, IconLetterL, IconLetterLSmall,

    IconLetterM, IconLetterMSmall, IconLetterN, IconLetterNSmall, IconLetterO, IconLetterOSmall, IconLetterP,
    IconLetterPSmall, IconLetterQ, IconLetterQSmall, IconLetterR, IconLetterRSmall, IconLetterS, IconLetterSSmall,
    IconLetterSpacing, IconLetterT, IconLetterTSmall, IconLetterU, IconLetterUSmall, IconLetterV, IconLetterVSmall,
    IconLetterW, IconLetterWSmall, IconLetterX, IconLetterXSmall, IconLetterY, IconLetterYSmall, IconLetterZ,
    IconLetterZSmall, IconLibrary, IconLibraryMinus, IconLibraryPhoto, IconLibraryPlus, IconLicense, IconLicenseOff,
    IconLifebuoy, IconLifebuoyFilled, IconLifebuoyOff, IconLighter, IconLine, IconLineDashed, IconLineDotted,
    IconLineHeight, IconLineScan, IconLink, IconLinkMinus, IconLinkOff, IconLinkPlus, IconList, IconListCheck,
    IconListDetails, IconListLetters, IconListNumbers, IconListSearch, IconListTree, IconLivePhoto,

    IconLivePhotoFilled, IconLivePhotoOff, IconLiveView, IconLiveViewFilled, IconLoadBalancer, IconLoader,
    IconLoader2, IconLoader3, IconLoaderQuarter, IconLocation, IconLocationBolt, IconLocationBroken, IconLocationCancel,
    IconLocationCheck, IconLocationCode, IconLocationCog, IconLocationDiscount, IconLocationDollar, IconLocationDown,
    IconLocationExclamation, IconLocationFilled, IconLocationHeart, IconLocationMinus, IconLocationOff,
    IconLocationPause, IconLocationPin, IconLocationPlus, IconLocationQuestion, IconLocationSearch, IconLocationShare,
    IconLocationStar, IconLocationUp, IconLocationX, IconLock, IconLockAccess, IconLockAccessOff, IconLockBitcoin,
    IconLockBolt, IconLockCancel, IconLockCheck, IconLockCode, IconLockCog, IconLockDollar, IconLockDown,
    IconLockExclamation, IconLockFilled, IconLockHeart, IconLockMinus, IconLockOff, IconLockOpen, IconLockOpen2,
    IconLockOpenOff, IconLockPassword, IconLockPause, IconLockPin, IconLockPlus, IconLockQuestion, IconLockSearch,
    IconLockShare, IconLockSquare, IconLockSquareRounded, IconLockSquareRoundedFilled, IconLockStar, IconLockUp,
    IconLockX, IconLogicAnd, IconLogicBuffer, IconLogicNand, IconLogicNor, IconLogicNot, IconLogicOr, IconLogicXnor,
    IconLogicXor, IconLogin, IconLogin2, IconLogout, IconLogout2, IconLogs, IconLollipop, IconLollipopOff,

    IconLuggage, IconLuggageOff, IconLungs, IconLungsFilled, IconLungsOff, IconMacro, IconMacroFilled,
    IconMacroOff, IconMagnet, IconMagnetFilled, IconMagnetOff, IconMagnetic, IconMail, IconMailAi,
    IconMailBitcoin, IconMailBolt, IconMailCancel, IconMailCheck, IconMailCode, IconMailCog, IconMailDollar,
    IconMailDown, IconMailExclamation, IconMailFast, IconMailFilled, IconMailForward, IconMailHeart,
    IconMailMinus, IconMailOff, IconMailOpened, IconMailOpenedFilled, IconMailPause, IconMailPin, IconMailPlus,
    IconMailQuestion, IconMailSearch, IconMailShare, IconMailSpark, IconMailStar, IconMailUp, IconMailX,
    IconMailbox, IconMailboxOff, IconMan, IconManFilled, IconManualGearbox, IconManualGearboxFilled,
    IconMap, IconMap2, IconMapBolt, IconMapCancel, IconMapCheck, IconMapCode, IconMapCog, IconMapDiscount,
    IconMapDollar, IconMapDown, IconMapEast, IconMapExclamation, IconMapHeart, IconMapMinus, IconMapNorth,
    IconMapOff, IconMapPause, IconMapPin, IconMapPin2, IconMapPinBolt, IconMapPinCancel, IconMapPinCheck,
    IconMapPinCode, IconMapPinCog, IconMapPinDollar, IconMapPinDown, IconMapPinExclamation, IconMapPinFilled,
    IconMapPinHeart, IconMapPinMinus, IconMapPinOff, IconMapPinPause, IconMapPinPin, IconMapPinPlus,

    IconMapPinQuestion, IconMapPinSearch, IconMapPinShare, IconMapPinStar, IconMapPinUp, IconMapPinX,
    IconMapPins, IconMapPlus, IconMapQuestion, IconMapRoute, IconMapSearch, IconMapShare, IconMapSouth,
    IconMapStar, IconMapUp, IconMapWest, IconMapX, IconMarkdown, IconMarkdownOff, IconMarquee, IconMarquee2,
    IconMarqueeOff, IconMars, IconMask, IconMaskOff, IconMasksTheater, IconMasksTheaterOff, IconMassage,
    IconMatchstick, IconMath, IconMath1Divide2, IconMath1Divide3, IconMathAvg, IconMathCos, IconMathCtg,
    IconMathEqualGreater, IconMathEqualLower, IconMathFunction, IconMathFunctionOff, IconMathFunctionY,
    IconMathGreater, IconMathIntegral, IconMathIntegralX, IconMathIntegrals, IconMathLower, IconMathMax,
    IconMathMaxMin, IconMathMin, IconMathNot, IconMathOff, IconMathPi, IconMathPiDivide2, IconMathSec,

    IconMathSin, IconMathSymbols, IconMathTg, IconMathXDivide2, IconMathXDivideY, IconMathXDivideY2,
    IconMathXFloorDivideY, IconMathXMinusX, IconMathXMinusY, IconMathXPlusX, IconMathXPlusY, IconMathXy,
    IconMathYMinusY, IconMathYPlusY, IconMatrix, IconMaximize, IconMaximizeOff, IconMeat, IconMeatOff,
    IconMedal, IconMedal2, IconMedicalCross, IconMedicalCrossCircle, IconMedicalCrossFilled, IconMedicalCrossOff,
    IconMedicineSyrup, IconMeeple, IconMeepleFilled, IconMelon, IconMelonFilled, IconMenorah, IconMenu,
    IconMenu2, IconMenu3, IconMenu4, IconMenuDeep, IconMenuOrder, IconMessage, IconMessage2, IconMessage2Bolt,
    IconMessage2Cancel, IconMessage2Check, IconMessage2Code, IconMessage2Cog, IconMessage2Dollar, IconMessage2Down,
    IconMessage2Exclamation, IconMessage2Filled, IconMessage2Heart, IconMessage2Minus, IconMessage2Off,

    IconMessage2Pause, IconMessage2Pin, IconMessage2Plus, IconMessage2Question, IconMessage2Search,
    IconMessage2Share, IconMessage2Star, IconMessage2Up, IconMessage2X, IconMessageBolt, IconMessageCancel,
    IconMessageChatbot, IconMessageChatbotFilled, IconMessageCheck, IconMessageCircle, IconMessageCircle2,
    IconMessageCircle2Filled, IconMessageCircleBolt, IconMessageCircleCancel, IconMessageCircleCheck,
    IconMessageCircleCode, IconMessageCircleCog, IconMessageCircleDollar, IconMessageCircleDown,
    IconMessageCircleExclamation, IconMessageCircleFilled, IconMessageCircleHeart, IconMessageCircleMinus,
    IconMessageCircleOff, IconMessageCirclePause, IconMessageCirclePin, IconMessageCirclePlus,
    IconMessageCircleQuestion, IconMessageCircleSearch, IconMessageCircleShare, IconMessageCircleStar,
    IconMessageCircleUp, IconMessageCircleUser, IconMessageCircleX, IconMessageCode, IconMessageCog,

    IconMessageDollar, IconMessageDots, IconMessageDown, IconMessageExclamation, IconMessageFilled,
    IconMessageForward, IconMessageHeart, IconMessageLanguage, IconMessageMinus, IconMessageOff, IconMessagePause,
    IconMessagePin, IconMessagePlus, IconMessageQuestion, IconMessageReply, IconMessageReport, IconMessageReportFilled,
    IconMessageSearch, IconMessageShare, IconMessageStar, IconMessageUp, IconMessageUser, IconMessageX,
    IconMessages, IconMessagesOff, IconMeteor, IconMeteorFilled, IconMeteorOff, IconMeterCube, IconMeterSquare,
    IconMetronome, IconMichelinBibGourmand, IconMichelinStar, IconMichelinStarFilled, IconMichelinStarGreen,
    IconMickey, IconMickeyFilled, IconMicrophone, IconMicrophone2, IconMicrophone2Off, IconMicrophoneFilled,
    IconMicrophoneOff, IconMicroscope, IconMicroscopeOff, IconMicrowave, IconMicrowaveFilled, IconMicrowaveOff,
    IconMilitaryAward, IconMilitaryRank, IconMilitaryRankFilled, IconMilk, IconMilkFilled, IconMilkOff,
    IconMilkshake, IconMinimize, IconMinus, IconMinusVertical, IconMist, IconMistOff, IconMobiledata,

    IconMobiledataOff, IconMoneybag, IconMonkeybar, IconMoodAngry, IconMoodAngryFilled, IconMoodAnnoyed,
    IconMoodAnnoyed2, IconMoodBitcoin, IconMoodBoy, IconMoodCheck, IconMoodCog, IconMoodConfuzed,
    IconMoodConfuzedFilled, IconMoodCrazyHappy, IconMoodCrazyHappyFilled, IconMoodCry, IconMoodDollar,
    IconMoodEdit, IconMoodEmpty, IconMoodEmptyFilled,
    IconMoodHappy, IconMoodHappyFilled, IconMoodHeart, IconMoodKid, IconMoodKidFilled, IconMoodLookDown,
    IconMoodLookLeft, IconMoodLookRight, IconMoodLookUp, IconMoodMinus, IconMoodNerd, IconMoodNervous,
    IconMoodNeutral, IconMoodNeutralFilled, IconMoodOff, IconMoodPin, IconMoodPlus, IconMoodPuzzled, IconMoodSad,

    IconMoodSad2, IconMoodSadDizzy, IconMoodSadFilled, IconMoodSadSquint, IconMoodSearch, IconMoodShare,
    IconMoodSick, IconMoodSilence, IconMoodSing, IconMoodSmile, IconMoodSmileBeam, IconMoodSmileDizzy,
    IconMoodSmileFilled, IconMoodSpark, IconMoodSuprised, IconMoodSurprised, IconMoodTongue, IconMoodTongueWink,
    IconMoodTongueWink2, IconMoodUnamused, IconMoodUp, IconMoodWink, IconMoodWink2, IconMoodWrrr,
    IconMoodWrrrFilled, IconMoodX, IconMoodXd, IconMoon, IconMoon2, IconMoonFilled, IconMoonOff, IconMoonStars,
    IconMoped, IconMotorbike, IconMountain, IconMountainFilled, IconMountainOff, IconMouse, IconMouse2,
    IconMouseFilled, IconMouseOff, IconMoustache, IconMovie, IconMovieOff, IconMug, IconMugFilled, IconMugOff,
    IconMultiplier05x, IconMultiplier15x, IconMultiplier1x, IconMultiplier2x, IconMushroom, IconMushroomFilled,

    IconMushroomOff, IconMusic, IconMusicBolt, IconMusicCancel, IconMusicCheck, IconMusicCode, IconMusicCog,
    IconMusicDiscount, IconMusicDollar, IconMusicDown, IconMusicExclamation, IconMusicHeart, IconMusicMinus,
    IconMusicOff, IconMusicPause, IconMusicPin, IconMusicPlus, IconMusicQuestion, IconMusicSearch, IconMusicShare,
    IconMusicStar, IconMusicUp, IconMusicX, IconNavigation, IconNavigationBolt, IconNavigationCancel,
    IconNavigationCheck, IconNavigationCode, IconNavigationCog, IconNavigationDiscount, IconNavigationDollar,
    IconNavigationDown, IconNavigationEast, IconNavigationExclamation, IconNavigationFilled, IconNavigationHeart,
    IconNavigationMinus, IconNavigationNorth, IconNavigationOff, IconNavigationPause, IconNavigationPin,

    IconNavigationPlus, IconNavigationQuestion, IconNavigationSearch, IconNavigationShare, IconNavigationSouth,
    IconNavigationStar, IconNavigationTop, IconNavigationUp, IconNavigationWest, IconNavigationX, IconNeedle,
    IconNeedleThread, IconNetwork, IconNetworkOff, IconNewSection, IconNews, IconNewsOff, IconNfc, IconNfcOff,
    IconNoCopyright, IconNoCreativeCommons, IconNoDerivatives, IconNorthStar, IconNote, IconNoteOff,
    IconNotebook, IconNotebookOff, IconNotes, IconNotesOff, IconNotification, IconNotificationOff,

    IconNumber,    IconNumber0, IconNumber0Small, IconNumber1, IconNumber10, IconNumber100Small, IconNumber10Small, IconNumber11,
    IconNumber11Small, IconNumber123, IconNumber12Small, IconNumber13Small, IconNumber14Small, IconNumber15Small,
    IconNumber16Small, IconNumber17Small, IconNumber18Small, IconNumber19Small, IconNumber1Small, IconNumber2,
    IconNumber20Small, IconNumber21Small, IconNumber22Small, IconNumber23Small, IconNumber24Small, IconNumber25Small,
    IconNumber26Small, IconNumber27Small, IconNumber28Small, IconNumber29Small, IconNumber2Small, IconNumber3,
    IconNumber30Small, IconNumber31Small, IconNumber32Small, IconNumber33Small, IconNumber34Small, IconNumber35Small,
    IconNumber36Small, IconNumber37Small, IconNumber38Small, IconNumber39Small, IconNumber3Small, IconNumber4,
    IconNumber40Small, IconNumber41Small, IconNumber42Small, IconNumber43Small, IconNumber44Small, IconNumber45Small,
    IconNumber46Small, IconNumber47Small, IconNumber48Small, IconNumber49Small, IconNumber4Small, IconNumber5,
    IconNumber50Small, IconNumber51Small, IconNumber52Small, IconNumber53Small, IconNumber54Small, IconNumber55Small,
    IconNumber56Small, IconNumber57Small, IconNumber58Small, IconNumber59Small, IconNumber5Small, IconNumber6,
    IconNumber60Small, IconNumber61Small, IconNumber62Small, IconNumber63Small, IconNumber64Small, IconNumber65Small,
    IconNumber66Small, IconNumber67Small, IconNumber68Small, IconNumber69Small, IconNumber6Small, IconNumber7,
    IconNumber70Small, IconNumber71Small, IconNumber72Small, IconNumber73Small, IconNumber74Small, IconNumber75Small,
    IconNumber76Small, IconNumber77Small, IconNumber78Small, IconNumber79Small, IconNumber7Small, IconNumber8,
    IconNumber80Small, IconNumber81Small, IconNumber82Small, IconNumber83Small, IconNumber84Small, IconNumber85Small,
    IconNumber86Small, IconNumber87Small, IconNumber88Small, IconNumber89Small, IconNumber8Small, IconNumber9,
    IconNumber90Small, IconNumber91Small, IconNumber92Small, IconNumber93Small, IconNumber94Small, IconNumber95Small,
    IconNumber96Small, IconNumber97Small, IconNumber98Small, IconNumber99Small, IconNumbers,

    IconNurse, IconNurseFilled,
    IconNut, IconObjectScan, IconOctagon, IconOctagonFilled, IconOctagonMinus, IconOctagonMinus2, IconOctagonOff,
    IconOctagonPlus, IconOctagonPlus2, IconOctahedron, IconOctahedronOff, IconOctahedronPlus, IconOld, IconOlympics,
    IconOlympicsOff, IconOm, IconOmega, IconOutbound, IconOutlet, IconOval, IconOvalFilled, IconOvalVertical,
    IconOvalVerticalFilled, IconOverline, IconPackage, IconPackageExport, IconPackageImport, IconPackageOff, IconPackages,
    IconPacman, IconPageBreak, IconPaint, IconPaintFilled, IconPaintOff, IconPalette, IconPaletteFilled, IconPaletteOff,
    IconPanoramaHorizontal, IconPanoramaHorizontalFilled, IconPanoramaHorizontalOff, IconPanoramaVertical,
    IconPanoramaVerticalFilled, IconPanoramaVerticalOff, IconPaperBag, IconPaperBagOff, IconPaperclip, IconParachute,
    IconParachuteOff, IconParentheses, IconParenthesesOff, IconParking, IconParkingCircle, IconParkingCircleFilled,
    IconParkingOff, IconPassword, IconPasswordFingerprint, IconPasswordMobilePhone, IconPasswordUser, IconPaw,
    IconPawFilled, IconPawOff, IconPaywall, IconPdf, IconPeace, IconPencil, IconPencilBolt, IconPencilCancel, IconPencilCheck,
    IconPencilCode, IconPencilCog, IconPencilDiscount, IconPencilDollar, IconPencilDown, IconPencilExclamation,
    IconPencilHeart, IconPencilMinus, IconPencilOff, IconPencilPause, IconPencilPin, IconPencilPlus, IconPencilQuestion,
    IconPencilSearch, IconPencilShare, IconPencilStar, IconPencilUp, IconPencilX, IconPennant, IconPennant2,
    IconPennant2Filled, IconPennantFilled, IconPennantOff, IconPentagon, IconPentagonFilled, IconPentagonMinus,
    IconPentagonNumber0, IconPentagonNumber1, IconPentagonNumber2, IconPentagonNumber3, IconPentagonNumber4,
    IconPentagonNumber5, IconPentagonNumber6, IconPentagonNumber7, IconPentagonNumber8, IconPentagonNumber9,
    IconPentagonOff, IconPentagonPlus, IconPentagonX, IconPentagram, IconPepper, IconPepperOff, IconPercentage,
    IconPercentage0, IconPercentage10, IconPercentage100, IconPercentage20, IconPercentage25, IconPercentage30,
    IconPercentage33, IconPercentage40, IconPercentage50, IconPercentage60, IconPercentage66, IconPercentage70,
    IconPercentage75,     IconPercentage80, IconPercentage90, IconPerfume, IconPerspective, IconPerspectiveOff, IconPhone,

    IconPhoneCall, IconPhoneCalling, IconPhoneCheck, IconPhoneDone, IconPhoneEnd, IconPhoneFilled,
    IconPhoneIncoming, IconPhoneOff, IconPhoneOutgoing, IconPhonePause, IconPhonePlus, IconPhoneRinging,
    IconPhoneSpark, IconPhoneX, IconPhoto, IconPhotoAi, IconPhotoBitcoin, IconPhotoBolt, IconPhotoCancel,
    IconPhotoCheck, IconPhotoCircle, IconPhotoCircleMinus, IconPhotoCirclePlus, IconPhotoCode, IconPhotoCog,
    IconPhotoDollar, IconPhotoDown, IconPhotoEdit, IconPhotoExclamation, IconPhotoFilled, IconPhotoHeart,
    IconPhotoHexagon, IconPhotoMinus, IconPhotoOff, IconPhotoPause, IconPhotoPentagon, IconPhotoPin,
    IconPhotoPlus, IconPhotoQuestion, IconPhotoScan, IconPhotoSearch, IconPhotoSensor, IconPhotoSensor2,
    IconPhotoSensor3, IconPhotoShare, IconPhotoShield, IconPhotoSpark, IconPhotoSquareRounded, IconPhotoStar,
    IconPhotoUp, IconPhotoVideo, IconPhotoX, IconPhysotherapist, IconPiano, IconPick, IconPicnicTable,
    IconPictureInPicture, IconPictureInPictureFilled, IconPictureInPictureOff, IconPictureInPictureOn,
    IconPictureInPictureTop, IconPictureInPictureTopFilled, IconPig, IconPigMoney, IconPigOff, IconPilcrow,
    IconPilcrowLeft, IconPilcrowRight, IconPill, IconPillFilled, IconPillOff, IconPills, IconPin, IconPinEnd,
    IconPinFilled, IconPinInvoke, IconPingPong, IconPinned, IconPinnedFilled, IconPinnedOff, IconPizza,
    IconPizzaFilled, IconPizzaOff, IconPlaceholder, IconPlane, IconPlaneArrival, IconPlaneDeparture,
    IconPlaneInflight, IconPlaneOff, IconPlaneTilt, IconPlanet, IconPlanetOff, IconPlant, IconPlant2,
    IconPlant2Off, IconPlantOff, IconPlayBasketball, IconPlayCard, IconPlayCard1, IconPlayCard10,
    IconPlayCard10Filled, IconPlayCard1Filled, IconPlayCard2, IconPlayCard2Filled, IconPlayCard3,

    IconPlayCard3Filled, IconPlayCard4, IconPlayCard4Filled, IconPlayCard5, IconPlayCard5Filled,
    IconPlayCard6, IconPlayCard6Filled, IconPlayCard7, IconPlayCard7Filled, IconPlayCard8, IconPlayCard8Filled,
    IconPlayCard9, IconPlayCard9Filled, IconPlayCardA, IconPlayCardAFilled, IconPlayCardJ, IconPlayCardJFilled,
    IconPlayCardK, IconPlayCardKFilled, IconPlayCardOff, IconPlayCardQ, IconPlayCardQFilled, IconPlayCardStar,
    IconPlayCardStarFilled, IconPlayFootball, IconPlayHandball, IconPlayVolleyball, IconPlayerEject,
    IconPlayerEjectFilled, IconPlayerPause, IconPlayerPauseFilled, IconPlayerPlay, IconPlayerPlayFilled,
    IconPlayerRecord, IconPlayerRecordFilled, IconPlayerSkipBack, IconPlayerSkipBackFilled, IconPlayerSkipForward,
    IconPlayerSkipForwardFilled, IconPlayerStop, IconPlayerStopFilled, IconPlayerTrackNext, IconPlayerTrackNextFilled,
    IconPlayerTrackPrev, IconPlayerTrackPrevFilled, IconPlaylist, IconPlaylistAdd, IconPlaylistOff, IconPlaylistX,
    IconPlaystationCircle, IconPlaystationSquare, IconPlaystationTriangle, IconPlaystationX, IconPlug,
    IconPlugConnected, IconPlugConnectedX, IconPlugOff, IconPlugX, IconPlus, IconPlusEqual, IconPlusMinus,
    IconPng, IconPodium, IconPodiumOff, IconPoint, IconPointFilled, IconPointOff, IconPointer, IconPointerBolt,
    IconPointerCancel, IconPointerCheck, IconPointerCode, IconPointerCog, IconPointerDollar, IconPointerDown,
    IconPointerExclamation, IconPointerFilled, IconPointerHeart, IconPointerMinus, IconPointerOff, IconPointerPause,

    IconPointerPin, IconPointerPlus, IconPointerQuestion, IconPointerSearch, IconPointerShare, IconPointerStar,
    IconPointerUp, IconPointerX, IconPokeball, IconPokeballOff, IconPokerChip, IconPolaroid, IconPolaroidFilled,
    IconPolygon, IconPolygonOff, IconPoo, IconPooFilled, IconPool, IconPoolOff, IconPower, IconPray, IconPremiumRights,
    IconPrescription, IconPresentation, IconPresentationAnalytics, IconPresentationAnalyticsFilled,
    IconPresentationFilled, IconPresentationOff, IconPrinter, IconPrinterOff, IconPrism, IconPrismLight,
    IconPrismOff, IconPrismPlus, IconPrison, IconProgress, IconProgressAlert, IconProgressBolt, IconProgressCheck,
    IconProgressDown, IconProgressHelp, IconProgressX, IconPrompt, IconProng, IconPropeller, IconPropellerOff,
    IconProtocol, IconPumpkinScary, IconPuzzle, IconPuzzle2, IconPuzzleFilled, IconPuzzleOff, IconPyramid,
    IconPyramidOff, IconPyramidPlus, IconQrcode, IconQrcodeOff, IconQuestionMark, IconQuote, IconQuoteFilled,
    IconQuoteOff, IconQuotes, IconRadar, IconRadar2, IconRadarFilled, IconRadarOff, IconRadio, IconRadioOff,
    IconRadioactive, IconRadioactiveFilled, IconRadioactiveOff, IconRadiusBottomLeft, IconRadiusBottomRight,
    IconRadiusTopLeft, IconRadiusTopRight, IconRainbow, IconRainbowOff, IconRating12Plus, IconRating14Plus,
    IconRating16Plus, IconRating18Plus, IconRating21Plus, IconRazor, IconRazorElectric, IconReceipt, IconReceipt2,
    IconReceiptBitcoin, IconReceiptDollar, IconReceiptEuro, IconReceiptFilled, IconReceiptOff, IconReceiptPound,

    IconReceiptRefund, IconReceiptRupee, IconReceiptTax, IconReceiptYen, IconReceiptYuan, IconRecharging,
    IconRecordMail, IconRecordMailOff, IconRectangle, IconRectangleFilled, IconRectangleRoundedBottom,
    IconRectangleRoundedTop, IconRectangleVertical, IconRectangleVerticalFilled, IconRectangularPrism,
    IconRectangularPrismOff, IconRectangularPrismPlus, IconRecycle, IconRecycleOff, IconRefresh, IconRefreshAlert,
    IconRefreshDot, IconRefreshOff, IconRegex, IconRegexOff, IconRegistered, IconRelationManyToMany,
    IconRelationManyToManyFilled, IconRelationOneToMany, IconRelationOneToManyFilled, IconRelationOneToOne,
    IconRelationOneToOneFilled, IconReload, IconReorder, IconRepeat, IconRepeatOff, IconRepeatOnce, IconReplace,
    IconReplaceFilled, IconReplaceOff, IconReport, IconReportAnalytics, IconReportMedical, IconReportMoney,
    IconReportOff, IconReportSearch, IconReservedLine, IconResize, IconRestore, IconRewindBackward10,
    IconRewindBackward15, IconRewindBackward20, IconRewindBackward30, IconRewindBackward40, IconRewindBackward5,
    IconRewindBackward50, IconRewindBackward60, IconRewindForward10, IconRewindForward15, IconRewindForward20,
    IconRewindForward30, IconRewindForward40, IconRewindForward5, IconRewindForward50, IconRewindForward60,
    IconRibbonHealth, IconRings, IconRipple, IconRippleOff, IconRoad, IconRoadOff, IconRoadSign, IconRobot,
    IconRobotFace, IconRobotOff, IconRocket, IconRocketOff, IconRollerSkating, IconRollercoaster, IconRollercoasterOff,

    IconRosette, IconRosetteDiscount, IconRosetteDiscountCheck, IconRosetteDiscountCheckFilled, IconRosetteDiscountFilled,
    IconRosetteDiscountOff, IconRosetteFilled, IconRosetteNumber0, IconRosetteNumber1, IconRosetteNumber2,
    IconRosetteNumber3, IconRosetteNumber4, IconRosetteNumber5, IconRosetteNumber6, IconRosetteNumber7,
    IconRosetteNumber8, IconRosetteNumber9, IconRotate, IconRotate2, IconRotate360, IconRotate3d, IconRotateClockwise,
    IconRotateClockwise2, IconRotateDot, IconRotateRectangle, IconRoute, IconRoute2, IconRouteAltLeft, IconRouteAltRight,
    IconRouteOff, IconRouteScan, IconRouteSquare, IconRouteSquare2, IconRouteX, IconRouteX2, IconRouter, IconRouterOff,
    IconRowInsertBottom, IconRowInsertTop, IconRowRemove, IconRss, IconRubberStamp, IconRubberStampOff, IconRuler,
    IconRuler2, IconRuler2Off, IconRuler3, IconRulerMeasure, IconRulerMeasure2, IconRulerOff, IconRun, IconRvTruck,
    IconSTurnDown, IconSTurnLeft, IconSTurnRight, IconSTurnUp, IconSailboat, IconSailboat2, IconSailboatOff, IconSalad,
    IconSaladFilled, IconSalt, IconSandbox, IconSatellite, IconSatelliteOff, IconSausage, IconScale, IconScaleOff,
    IconScaleOutline, IconScaleOutlineOff, IconScan, IconScanEye, IconScanPosition, IconSchema, IconSchemaOff,
    IconSchool, IconSchoolBell, IconSchoolOff, IconScissors, IconScissorsOff, IconScooter, IconScooterElectric,
    IconScoreboard, IconScreenShare, IconScreenShareOff, IconScreenshot, IconScribble, IconScribbleOff, IconScript,

    IconScriptMinus, IconScriptPlus, IconScriptX, IconScubaDiving, IconScubaDivingTank, IconScubaDivingTankFilled,
    IconScubaMask, IconScubaMaskOff, IconSdk, IconSearch, IconSearchOff, IconSection, IconSectionFilled,
    IconSectionSign, IconSeeding, IconSeedingFilled, IconSeedingOff, IconSelect, IconSelectAll, IconSelector,
    IconSend, IconSend2, IconSendOff, IconSeo, IconSeparator, IconSeparatorHorizontal, IconSeparatorVertical,
    IconServer, IconServer2, IconServerBolt, IconServerCog, IconServerOff, IconServerSpark, IconServicemark,
    IconSettings, IconSettings2, IconSettingsAutomation, IconSettingsBolt, IconSettingsCancel, IconSettingsCheck,
    IconSettingsCode, IconSettingsCog, IconSettingsDollar, IconSettingsDown, IconSettingsExclamation,
    IconSettingsFilled, IconSettingsHeart, IconSettingsMinus, IconSettingsOff, IconSettingsPause,
    IconSettingsPin, IconSettingsPlus, IconSettingsQuestion, IconSettingsSearch, IconSettingsShare,
    IconSettingsSpark, IconSettingsStar, IconSettingsUp, IconSettingsX, IconShadow, IconShadowOff,
    IconShape, IconShape2, IconShape3, IconShapeOff, IconShare, IconShare2, IconShare3, IconShareOff,
    IconShareplay, IconShiJumping, IconShield, IconShieldBolt, IconShieldCancel, IconShieldCheck,

    IconShieldCheckFilled, IconShieldCheckered, IconShieldCheckeredFilled, IconShieldChevron, IconShieldCode,
    IconShieldCog, IconShieldDollar, IconShieldDown, IconShieldExclamation, IconShieldFilled, IconShieldHalf,
    IconShieldHalfFilled, IconShieldHeart, IconShieldLock, IconShieldLockFilled, IconShieldMinus, IconShieldOff,
    IconShieldPause, IconShieldPin, IconShieldPlus, IconShieldQuestion, IconShieldSearch, IconShieldShare,
    IconShieldStar, IconShieldUp, IconShieldX, IconShip, IconShipOff, IconShirt, IconShirtFilled, IconShirtOff,
    IconShirtSport, IconShoe, IconShoeOff, IconShoppingBag, IconShoppingBagCheck, IconShoppingBagDiscount,
    IconShoppingBagEdit, IconShoppingBagExclamation, IconShoppingBagHeart, IconShoppingBagMinus,
    IconShoppingBagPlus, IconShoppingBagSearch, IconShoppingBagX, IconShoppingCart, IconShoppingCartBolt,
    IconShoppingCartCancel, IconShoppingCartCheck, IconShoppingCartCode, IconShoppingCartCog, IconShoppingCartCopy,
    IconShoppingCartDiscount, IconShoppingCartDollar, IconShoppingCartDown, IconShoppingCartExclamation,

    IconShoppingCartFilled, IconShoppingCartHeart, IconShoppingCartMinus, IconShoppingCartOff, IconShoppingCartPause,
    IconShoppingCartPin, IconShoppingCartPlus, IconShoppingCartQuestion, IconShoppingCartSearch,
    IconShoppingCartShare, IconShoppingCartStar, IconShoppingCartUp, IconShoppingCartX, IconShovel,
    IconShovelPitchforks, IconShredder, IconSignLeft, IconSignLeftFilled, IconSignRight, IconSignRightFilled,
    IconSignal2g, IconSignal3g, IconSignal4g, IconSignal4gPlus, IconSignal5g, IconSignal6g, IconSignalE,
    IconSignalG, IconSignalH, IconSignalHPlus, IconSignalLte, IconSignature, IconSignatureOff, IconSitemap,
    IconSitemapFilled, IconSitemapOff, IconSkateboard, IconSkateboardOff, IconSkateboarding, IconSkewX,
    IconSkewY, IconSkiJumping, IconSkull, IconSlash, IconSlashes, IconSleigh, IconSlice, IconSlideshow,
    IconSmartHome, IconSmartHomeOff, IconSmoking, IconSmokingNo, IconSnowboarding, IconSnowflake,
    IconSnowflakeOff, IconSnowman, IconSoccerField, IconSocial, IconSocialOff, IconSock, IconSofa, IconSofaOff,
    IconSolarElectricity, IconSolarPanel, IconSolarPanel2,
} from "@tabler/icons-react";


export const availableIcons = {
    Heart, Star, Sun, Moon, Camera, Music,
    Mail, Settings, User, Phone, Bell, Book,
    FileJson, FileText, FileCode, FileImage,
    FileInput, FileVideo, FileSpreadsheet, File,
    FileAudio, Table2, FileArchive,
    IconFile3d, IconFileAi, IconFileAlert, IconFileAnalytics, IconFileArrowLeft, IconFileArrowRight,
    IconFileBarcode, IconFileBitcoin, IconFileBroken, IconFileCertificate, IconFileChart, IconFileCheck,
    IconFileCode, IconFileCode2, IconFileCv, IconFileDatabase, IconFileDelta, IconFileDescription,
    IconFileDiff, IconFileDigit, IconFileDislike, IconFileDollar, IconFileDots, IconFileDownload,
    IconFileEuro, IconFileExcel, IconFileExport, IconFileFilled, IconFileFunction, IconFileHorizontal,
    IconFileImport, IconFileInfinity, IconFileInfo, IconFileInvoice, IconFileIsr, IconFileLambda,
    IconFileLike, IconFileMinus, IconFileMusic, IconFileNeutral, IconFileOff, IconFileOrientation,
    IconFilePencil, IconFilePercent, IconFilePhone, IconFilePlus, IconFilePower, IconFileReport,
    IconFileRss, IconFileSad, IconFileScissors, IconFileSearch, IconFileSettings, IconFileShredder,
    IconFileSignal, IconFileSmile, IconFileSpark, IconFileSpreadsheet, IconFileStack, IconFileStar,
    IconFileSymlink, IconFileText, IconFileTextAi, IconFileTextSpark, IconFileTime, IconFileTypeBmp,
    IconFileTypeCss, IconFileTypeCsv, IconFileTypeDoc, IconFileTypeDocx, IconFileTypeHtml, IconFileTypeJpg,
    IconFileTypeJs, IconFileTypeJsx, IconFileTypePdf, IconFileTypePhp, IconFileTypePng, IconFileTypePpt,
    IconFileTypeRs, IconFileTypeSql, IconFileTypeSvg, IconFileTypeTs, IconFileTypeTsx, IconFileTypeTxt,
    IconFileTypeVue, IconFileTypeXls, IconFileTypeXml, IconFileTypeZip, IconFileTypography, IconFileUnknown,
    IconFileUpload, IconFileVector, IconFileWord, IconFileX, IconFileXFilled, IconFileZip, IconFiles,
    IconFilesOff, IconGif, IconGlobe, IconGraph,
    Circle, Square, Triangle,
    ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
    ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
    Search, Home, Menu, X, Check, Plus, Minus,
    Image, Video, Folder, MessageCircle, Users, UserPlus, UserMinus,
    Smartphone, Tablet, Laptop, Monitor,
    Cloud, CloudRain, DollarSign, ShoppingCart, CreditCard,
    Share, Link, Upload, Download,
    Bold, Italic, Underline, List,
    Calendar, Clock, Map, Bookmark,
    Save, Trash, Edit, Eye, EyeOff,
    Lock, Unlock, Key, Flag,
    ClipboardCopy, Clipboard,
    Database, Server, Code,
    StopCircleIcon, PlayCircleIcon, PauseCircleIcon,
    IconFilter, IconFilterBolt, IconFilterCancel, IconFilterCheck, IconFilterCode, IconFilterCog,
    IconFilterDiscount, IconFilterDollar, IconFilterDown, IconFilterEdit, IconFilterExclamation,
    IconFilterFilled, IconFilterHeart, IconFilterMinus, IconFilterOff, IconFilterPause, IconFilterPin,
    IconFilterPlus, IconFilterQuestion, IconFilterSearch, IconFilterShare, IconFilterStar, IconFilterUp,
    IconFilterX, IconFilters, IconFiltersFilled, IconFingerprint, IconFingerprintOff, IconFingerprintScan,
    IconHanger2, IconHanger2Filled, IconHangerOff, IconHash, IconHaze,
    IconHazeMoon, IconHdr, IconHeading, IconHeadingOff, IconHeadphones, IconHeadphonesFilled,
    IconHeadphonesOff, IconHeadset, IconHeadsetOff, IconHealthRecognition, IconHeart, IconHeartBitcoin,
    IconHeartBolt, IconHeartBroken, IconHeartCancel, IconHeartCheck, IconHeartCode, IconHeartCog,
    IconHeartDiscount, IconHeartDollar, IconHeartDown, IconHeartExclamation, IconHeartFilled, IconHeartHandshake,
    IconHeartMinus, IconHeartOff, IconHeartPause, IconHeartPin, IconHeartPlus, IconHeartQuestion, IconHeartRateMonitor,
    IconHeartSearch, IconHeartShare, IconHeartSpark, IconHeartStar, IconHeartUp, IconHeartX, IconHeartbeat, IconHearts,
    IconHeartsOff, IconHelicopter, IconHelicopterLanding, IconHelicopterLandingFilled, IconHelmet, IconHelmetOff,
    IconHelp, IconHelpCircle, IconHelpCircleFilled, IconHelpHexagon, IconHelpHexagonFilled, IconHelpOctagon,
    IconHelpOctagonFilled, IconHelpOff, IconHelpSmall, IconHelpSquare, IconHelpSquareFilled, IconHelpSquareRounded,
    IconHelpSquareRoundedFilled, IconHelpTriangle, IconHelpTriangleFilled,
    IconInputAi, IconInputCheck, IconInputSearch, IconInputSpark, IconInputX, IconInvoice, IconIroning,
    IconIroning1, IconIroning1Filled, IconIroning2, IconIroning2Filled, IconIroning3, IconIroning3Filled,
    IconIroningFilled, IconIroningOff, IconIroningSteam, IconIroningSteamFilled, IconIroningSteamOff,
    IconIrregularPolyhedron, IconIrregularPolyhedronOff, IconIrregularPolyhedronPlus, IconItalic, IconJacket,
    IconJetpack, IconJetpackFilled, IconJewishStar, IconJewishStarFilled, IconJoinBevel, IconJoinRound,
    IconJoinStraight, IconJoker, IconJpg, IconJson, IconJumpRope, IconKarate, IconKayak, IconKering,
    IconKerning, IconKey, IconKeyFilled, IconKeyOff, IconKeyboard, IconKeyboardFilled, IconKeyboardHide,
    IconKeyboardOff, IconKeyboardShow, IconKeyframe, IconKeyframeAlignCenter, IconKeyframeAlignCenterFilled,
    IconKeyframeAlignHorizontal, IconKeyframeAlignHorizontalFilled, IconKeyframeAlignVertical,
    IconKeyframeAlignVerticalFilled, IconKeyframeFilled, IconKeyframes, IconKeyframesFilled, IconLabel,
    IconLabelFilled, IconLabelImportant, IconLabelImportantFilled, IconLabelOff, IconLadder, IconLadderOff,
    IconLadle, IconLambda, IconLamp, IconLamp2, IconLampOff, IconLane, IconLanguage, IconLanguageHiragana,
    IconLanguageKatakana, IconLanguageOff, IconLasso, IconLassoOff, IconLassoPolygon, IconLassoPolygonFilled,
    IconLaurelWreath, IconLaurelWreath1, IconLaurelWreath2, IconLaurelWreath3, IconLaurelWreathFilled,
    IconLayersDifference, IconLayersIntersect, IconLayersIntersect2, IconLayersLinked, IconLayersOff,
    IconLayersSelected, IconLayersSelectedBottom, IconLayersSubtract, IconLayersUnion, IconLayout, IconLayout2,
    IconLayout2Filled, IconLayoutAlignBottom, IconLayoutAlignBottomFilled, IconLayoutAlignCenter,
    IconLayoutAlignCenterFilled, IconLayoutAlignLeft, IconLayoutAlignLeftFilled, IconLayoutAlignMiddle,
    IconLayoutAlignMiddleFilled, IconLayoutAlignRight, IconLayoutAlignRightFilled, IconLayoutAlignTop,
    IconLayoutAlignTopFilled, IconLayoutBoard, IconLayoutBoardSplit, IconLayoutBottombar, IconLayoutBottombarCollapse,
    IconLayoutBottombarCollapseFilled, IconLayoutBottombarExpand, IconLayoutBottombarExpandFilled,
    IconLayoutBottombarFilled, IconLayoutBottombarInactive, IconLayoutCards, IconLayoutCardsFilled,
    IconLayoutCollage, IconLayoutColumns, IconLayoutDashboard, IconLayoutDashboardFilled, IconLayoutDistributeHorizontal,
    IconLayoutDistributeHorizontalFilled, IconLayoutDistributeVertical, IconLayoutDistributeVerticalFilled,
    IconLayoutFilled, IconLayoutGrid, IconLayoutGridAdd, IconLayoutGridFilled, IconLayoutGridRemove, IconLayoutKanban,
    IconLayoutKanbanFilled, IconLayoutList, IconLayoutListFilled, IconLayoutNavbar, IconLayoutNavbarCollapse,
    IconLayoutNavbarCollapseFilled, IconLayoutNavbarExpand, IconLayoutNavbarExpandFilled, IconLayoutNavbarFilled,
    IconLayoutNavbarInactive, IconLayoutOff, IconLayoutRows, IconLayoutSidebar, IconLayoutSidebarFilled,
    IconLayoutSidebarInactive, IconLayoutSidebarLeftCollapse, IconLayoutSidebarLeftCollapseFilled,IconHandTwoFingers, IconHanger,
    IconLayoutSidebarLeftExpand, IconLayoutSidebarLeftExpandFilled, IconLayoutSidebarRight, IconLayoutSidebarRightCollapse,
    IconLayoutSidebarRightCollapseFilled, IconLayoutSidebarRightExpand, IconLayoutSidebarRightExpandFilled,
    IconLayoutSidebarRightFilled, IconLayoutSidebarRightInactive, IconLeaf, IconLeaf2, IconLeafOff, IconLego,
    IconLegoFilled, IconLegoOff, IconLemon, IconLemon2, IconLemon2Filled, IconLetterA, IconLetterASmall,
    IconLetterB, IconLetterBSmall, IconLetterC, IconLetterCSmall, IconLetterCase, IconLetterCaseLower,
    IconLetterCaseToggle, IconLetterCaseUpper, IconLetterD, IconLetterDSmall, IconLetterE, IconLetterESmall,
    IconLetterF, IconLetterFSmall, IconLetterG, IconLetterGSmall, IconLetterH, IconLetterHSmall, IconLetterI,
    IconLetterISmall, IconLetterJ, IconLetterJSmall, IconLetterK, IconLetterKSmall, IconLetterL, IconLetterLSmall,
    IconLetterM, IconLetterMSmall, IconLetterN, IconLetterNSmall, IconLetterO, IconLetterOSmall, IconLetterP,
    IconLetterPSmall, IconLetterQ, IconLetterQSmall, IconLetterR, IconLetterRSmall, IconLetterS, IconLetterSSmall,
    IconLetterSpacing, IconLetterT, IconLetterTSmall, IconLetterU, IconLetterUSmall, IconLetterV, IconLetterVSmall,
    IconLetterW, IconLetterWSmall, IconLetterX, IconLetterXSmall, IconLetterY, IconLetterYSmall, IconLetterZ,
    IconLetterZSmall, IconLibrary, IconLibraryMinus, IconLibraryPhoto, IconLibraryPlus, IconLicense, IconLicenseOff,
    IconLifebuoy, IconLifebuoyFilled, IconLifebuoyOff, IconLighter, IconLine, IconLineDashed, IconLineDotted,
    IconLineHeight, IconLineScan, IconLink, IconLinkMinus, IconLinkOff, IconLinkPlus, IconList, IconListCheck,
    IconListDetails, IconListLetters, IconListNumbers, IconListSearch, IconListTree, IconLivePhoto,
    IconLivePhotoFilled, IconLivePhotoOff, IconLiveView, IconLiveViewFilled, IconLoadBalancer, IconLoader,
    IconLoader2, IconLoader3, IconLoaderQuarter, IconLocation, IconLocationBolt, IconLocationBroken, IconLocationCancel,
    IconLocationCheck, IconLocationCode, IconLocationCog, IconLocationDiscount, IconLocationDollar, IconLocationDown,
    IconLocationExclamation, IconLocationFilled, IconLocationHeart, IconLocationMinus, IconLocationOff,
    IconLocationPause, IconLocationPin, IconLocationPlus, IconLocationQuestion, IconLocationSearch, IconLocationShare,
    IconLocationStar, IconLocationUp, IconLocationX, IconLock, IconLockAccess, IconLockAccessOff, IconLockBitcoin,
    IconLockBolt, IconLockCancel, IconLockCheck, IconLockCode, IconLockCog, IconLockDollar, IconLockDown,
    IconLockExclamation, IconLockFilled, IconLockHeart, IconLockMinus, IconLockOff, IconLockOpen, IconLockOpen2,
    IconLockOpenOff, IconLockPassword, IconLockPause, IconLockPin, IconLockPlus, IconLockQuestion, IconLockSearch,
    IconLockShare, IconLockSquare, IconLockSquareRounded, IconLockSquareRoundedFilled, IconLockStar, IconLockUp,
    IconLockX, IconLogicAnd, IconLogicBuffer, IconLogicNand, IconLogicNor, IconLogicNot, IconLogicOr, IconLogicXnor,
    IconLogicXor, IconLogin, IconLogin2, IconLogout, IconLogout2, IconLogs, IconLollipop, IconLollipopOff,
    IconLuggage, IconLuggageOff, IconLungs, IconLungsFilled, IconLungsOff, IconMacro, IconMacroFilled,
    IconMacroOff, IconMagnet, IconMagnetFilled, IconMagnetOff, IconMagnetic, IconMail, IconMailAi,
    IconMailBitcoin, IconMailBolt, IconMailCancel, IconMailCheck, IconMailCode, IconMailCog, IconMailDollar,
    IconMailDown, IconMailExclamation, IconMailFast, IconMailFilled, IconMailForward, IconMailHeart,
    IconMailMinus, IconMailOff, IconMailOpened, IconMailOpenedFilled, IconMailPause, IconMailPin, IconMailPlus,
    IconMailQuestion, IconMailSearch, IconMailShare, IconMailSpark, IconMailStar, IconMailUp, IconMailX,
    IconMailbox, IconMailboxOff, IconMan, IconManFilled, IconManualGearbox, IconManualGearboxFilled,
    IconMap, IconMap2, IconMapBolt, IconMapCancel, IconMapCheck, IconMapCode, IconMapCog, IconMapDiscount,
    IconMapDollar, IconMapDown, IconMapEast, IconMapExclamation, IconMapHeart, IconMapMinus, IconMapNorth,
    IconMapOff, IconMapPause, IconMapPin, IconMapPin2, IconMapPinBolt, IconMapPinCancel, IconMapPinCheck,
    IconMapPinCode, IconMapPinCog, IconMapPinDollar, IconMapPinDown, IconMapPinExclamation, IconMapPinFilled,
    IconMapPinHeart, IconMapPinMinus, IconMapPinOff, IconMapPinPause, IconMapPinPin, IconMapPinPlus,
    IconMapPinQuestion, IconMapPinSearch, IconMapPinShare, IconMapPinStar, IconMapPinUp, IconMapPinX,
    IconMapPins, IconMapPlus, IconMapQuestion, IconMapRoute, IconMapSearch, IconMapShare, IconMapSouth,
    IconMapStar, IconMapUp, IconMapWest, IconMapX, IconMarkdown, IconMarkdownOff, IconMarquee, IconMarquee2,
    IconMarqueeOff, IconMars, IconMask, IconMaskOff, IconMasksTheater, IconMasksTheaterOff, IconMassage,
    IconMatchstick, IconMath, IconMath1Divide2, IconMath1Divide3, IconMathAvg, IconMathCos, IconMathCtg,
    IconMathEqualGreater, IconMathEqualLower, IconMathFunction, IconMathFunctionOff, IconMathFunctionY,
    IconMathGreater, IconMathIntegral, IconMathIntegralX, IconMathIntegrals, IconMathLower, IconMathMax,
    IconMathMaxMin, IconMathMin, IconMathNot, IconMathOff, IconMathPi, IconMathPiDivide2, IconMathSec,
    IconMathSin, IconMathSymbols, IconMathTg, IconMathXDivide2, IconMathXDivideY, IconMathXDivideY2,
    IconMathXFloorDivideY, IconMathXMinusX, IconMathXMinusY, IconMathXPlusX, IconMathXPlusY, IconMathXy,
    IconMathYMinusY, IconMathYPlusY, IconMatrix, IconMaximize, IconMaximizeOff, IconMeat, IconMeatOff,
    IconMedal, IconMedal2, IconMedicalCross, IconMedicalCrossCircle, IconMedicalCrossFilled, IconMedicalCrossOff,
    IconMedicineSyrup, IconMeeple, IconMeepleFilled, IconMelon, IconMelonFilled, IconMenorah, IconMenu,
    IconMenu2, IconMenu3, IconMenu4, IconMenuDeep, IconMenuOrder, IconMessage, IconMessage2, IconMessage2Bolt,
    IconMessage2Cancel, IconMessage2Check, IconMessage2Code, IconMessage2Cog, IconMessage2Dollar, IconMessage2Down,
    IconMessage2Exclamation, IconMessage2Filled, IconMessage2Heart, IconMessage2Minus, IconMessage2Off,
    IconMessage2Pause, IconMessage2Pin, IconMessage2Plus, IconMessage2Question, IconMessage2Search,
    IconMessage2Share, IconMessage2Star, IconMessage2Up, IconMessage2X, IconMessageBolt, IconMessageCancel,
    IconMessageChatbot, IconMessageChatbotFilled, IconMessageCheck, IconMessageCircle, IconMessageCircle2,
    IconMessageCircle2Filled, IconMessageCircleBolt, IconMessageCircleCancel, IconMessageCircleCheck,
    IconMessageCircleCode, IconMessageCircleCog, IconMessageCircleDollar, IconMessageCircleDown,
    IconMessageCircleExclamation, IconMessageCircleFilled, IconMessageCircleHeart, IconMessageCircleMinus,
    IconMessageCircleOff, IconMessageCirclePause, IconMessageCirclePin, IconMessageCirclePlus,
    IconMessageCircleQuestion, IconMessageCircleSearch, IconMessageCircleShare, IconMessageCircleStar,
    IconMessageCircleUp, IconMessageCircleUser, IconMessageCircleX, IconMessageCode, IconMessageCog,
    IconMessageDollar, IconMessageDots, IconMessageDown, IconMessageExclamation, IconMessageFilled,
    IconMessageForward, IconMessageHeart, IconMessageLanguage, IconMessageMinus, IconMessageOff, IconMessagePause,
    IconMessagePin, IconMessagePlus, IconMessageQuestion, IconMessageReply, IconMessageReport, IconMessageReportFilled,
    IconMessageSearch, IconMessageShare, IconMessageStar, IconMessageUp, IconMessageUser, IconMessageX,
    IconMessages, IconMessagesOff, IconMeteor, IconMeteorFilled, IconMeteorOff, IconMeterCube, IconMeterSquare,
    IconMetronome, IconMichelinBibGourmand, IconMichelinStar, IconMichelinStarFilled, IconMichelinStarGreen,
    IconMickey, IconMickeyFilled, IconMicrophone, IconMicrophone2, IconMicrophone2Off, IconMicrophoneFilled,
    IconMicrophoneOff, IconMicroscope, IconMicroscopeOff, IconMicrowave, IconMicrowaveFilled, IconMicrowaveOff,
    IconMilitaryAward, IconMilitaryRank, IconMilitaryRankFilled, IconMilk, IconMilkFilled, IconMilkOff,
    IconMilkshake, IconMinimize, IconMinus, IconMinusVertical, IconMist, IconMistOff, IconMobiledata,
    IconMobiledataOff, IconMoneybag, IconMonkeybar, IconMoodAngry, IconMoodAngryFilled, IconMoodAnnoyed,
    IconMoodAnnoyed2, IconMoodBitcoin, IconMoodBoy, IconMoodCheck, IconMoodCog, IconMoodConfuzed,
    IconMoodConfuzedFilled, IconMoodCrazyHappy, IconMoodCrazyHappyFilled, IconMoodCry, IconMoodDollar,
    IconMoodEdit, IconMoodEmpty, IconMoodEmptyFilled,
    IconMoodHappy, IconMoodHappyFilled, IconMoodHeart, IconMoodKid, IconMoodKidFilled, IconMoodLookDown,
    IconMoodLookLeft, IconMoodLookRight, IconMoodLookUp, IconMoodMinus, IconMoodNerd, IconMoodNervous,
    IconMoodNeutral, IconMoodNeutralFilled, IconMoodOff, IconMoodPin, IconMoodPlus, IconMoodPuzzled, IconMoodSad,
    IconMoodSad2, IconMoodSadDizzy, IconMoodSadFilled, IconMoodSadSquint, IconMoodSearch, IconMoodShare,
    IconMoodSick, IconMoodSilence, IconMoodSing, IconMoodSmile, IconMoodSmileBeam, IconMoodSmileDizzy,
    IconMoodSmileFilled, IconMoodSpark, IconMoodSuprised, IconMoodSurprised, IconMoodTongue, IconMoodTongueWink,
    IconMoodTongueWink2, IconMoodUnamused, IconMoodUp, IconMoodWink, IconMoodWink2, IconMoodWrrr,
    IconMoodWrrrFilled, IconMoodX, IconMoodXd, IconMoon, IconMoon2, IconMoonFilled, IconMoonOff, IconMoonStars,
    IconMoped, IconMotorbike, IconMountain, IconMountainFilled, IconMountainOff, IconMouse, IconMouse2,
    IconMouseFilled, IconMouseOff, IconMoustache, IconMovie, IconMovieOff, IconMug, IconMugFilled, IconMugOff,
    IconMultiplier05x, IconMultiplier15x, IconMultiplier1x, IconMultiplier2x, IconMushroom, IconMushroomFilled,
    IconMushroomOff, IconMusic, IconMusicBolt, IconMusicCancel, IconMusicCheck, IconMusicCode, IconMusicCog,
    IconMusicDiscount, IconMusicDollar, IconMusicDown, IconMusicExclamation, IconMusicHeart, IconMusicMinus,
    IconMusicOff, IconMusicPause, IconMusicPin, IconMusicPlus, IconMusicQuestion, IconMusicSearch, IconMusicShare,
    IconMusicStar, IconMusicUp, IconMusicX, IconNavigation, IconNavigationBolt, IconNavigationCancel,
    IconNavigationCheck, IconNavigationCode, IconNavigationCog, IconNavigationDiscount, IconNavigationDollar,
    IconNavigationDown, IconNavigationEast, IconNavigationExclamation, IconNavigationFilled, IconNavigationHeart,
    IconNavigationMinus, IconNavigationNorth, IconNavigationOff, IconNavigationPause, IconNavigationPin,
    IconNavigationPlus, IconNavigationQuestion, IconNavigationSearch, IconNavigationShare, IconNavigationSouth,
    IconNavigationStar, IconNavigationTop, IconNavigationUp, IconNavigationWest, IconNavigationX, IconNeedle,
    IconNeedleThread, IconNetwork, IconNetworkOff, IconNewSection, IconNews, IconNewsOff, IconNfc, IconNfcOff,
    IconNoCopyright, IconNoCreativeCommons, IconNoDerivatives, IconNorthStar, IconNote, IconNoteOff,
    IconNotebook, IconNotebookOff, IconNotes, IconNotesOff, IconNotification, IconNotificationOff, IconNumber,
    IconNumber0, IconNumber0Small, IconNumber1, IconNumber10, IconNumber100Small, IconNumber10Small, IconNumber11,
    IconNumber11Small, IconNumber123, IconNumber12Small, IconNumber13Small, IconNumber14Small, IconNumber15Small,
    IconNumber16Small, IconNumber17Small, IconNumber18Small, IconNumber19Small, IconNumber1Small, IconNumber2,
    IconNumber20Small, IconNumber21Small, IconNumber22Small, IconNumber23Small, IconNumber24Small, IconNumber25Small,
    IconNumber26Small, IconNumber27Small, IconNumber28Small, IconNumber29Small, IconNumber2Small, IconNumber3,
    IconNumber30Small, IconNumber31Small, IconNumber32Small, IconNumber33Small, IconNumber34Small, IconNumber35Small,
    IconNumber36Small, IconNumber37Small, IconNumber38Small, IconNumber39Small, IconNumber3Small, IconNumber4,
    IconNumber40Small, IconNumber41Small, IconNumber42Small, IconNumber43Small, IconNumber44Small, IconNumber45Small,
    IconNumber46Small, IconNumber47Small, IconNumber48Small, IconNumber49Small, IconNumber4Small, IconNumber5,
    IconNumber50Small, IconNumber51Small, IconNumber52Small, IconNumber53Small, IconNumber54Small, IconNumber55Small,
    IconNumber56Small, IconNumber57Small, IconNumber58Small, IconNumber59Small, IconNumber5Small, IconNumber6,
    IconNumber60Small, IconNumber61Small, IconNumber62Small, IconNumber63Small, IconNumber64Small, IconNumber65Small,
    IconNumber66Small, IconNumber67Small, IconNumber68Small, IconNumber69Small, IconNumber6Small, IconNumber7,
    IconNumber70Small, IconNumber71Small, IconNumber72Small, IconNumber73Small, IconNumber74Small, IconNumber75Small,
    IconNumber76Small, IconNumber77Small, IconNumber78Small, IconNumber79Small, IconNumber7Small, IconNumber8,
    IconNumber80Small, IconNumber81Small, IconNumber82Small, IconNumber83Small, IconNumber84Small, IconNumber85Small,
    IconNumber86Small, IconNumber87Small, IconNumber88Small, IconNumber89Small, IconNumber8Small, IconNumber9,
    IconNumber90Small, IconNumber91Small, IconNumber92Small, IconNumber93Small, IconNumber94Small, IconNumber95Small,
    IconNumber96Small, IconNumber97Small, IconNumber98Small, IconNumber99Small, IconNumbers, IconNurse, IconNurseFilled,
    IconNut, IconObjectScan, IconOctagon, IconOctagonFilled, IconOctagonMinus, IconOctagonMinus2, IconOctagonOff,
    IconOctagonPlus, IconOctagonPlus2, IconOctahedron, IconOctahedronOff, IconOctahedronPlus, IconOld, IconOlympics,
    IconOlympicsOff, IconOm, IconOmega, IconOutbound, IconOutlet, IconOval, IconOvalFilled, IconOvalVertical,
    IconOvalVerticalFilled, IconOverline, IconPackage, IconPackageExport, IconPackageImport, IconPackageOff, IconPackages,
    IconPacman, IconPageBreak, IconPaint, IconPaintFilled, IconPaintOff, IconPalette, IconPaletteFilled, IconPaletteOff,
    IconPanoramaHorizontal, IconPanoramaHorizontalFilled, IconPanoramaHorizontalOff, IconPanoramaVertical,
    IconPanoramaVerticalFilled, IconPanoramaVerticalOff, IconPaperBag, IconPaperBagOff, IconPaperclip, IconParachute,
    IconParachuteOff, IconParentheses, IconParenthesesOff, IconParking, IconParkingCircle, IconParkingCircleFilled,
    IconParkingOff, IconPassword, IconPasswordFingerprint, IconPasswordMobilePhone, IconPasswordUser, IconPaw,
    IconPawFilled, IconPawOff, IconPaywall, IconPdf, IconPeace, IconPencil, IconPencilBolt, IconPencilCancel, IconPencilCheck,
    IconPencilCode, IconPencilCog, IconPencilDiscount, IconPencilDollar, IconPencilDown, IconPencilExclamation,
    IconPencilHeart, IconPencilMinus, IconPencilOff, IconPencilPause, IconPencilPin, IconPencilPlus, IconPencilQuestion,
    IconPencilSearch, IconPencilShare, IconPencilStar, IconPencilUp, IconPencilX, IconPennant, IconPennant2,
    IconPennant2Filled, IconPennantFilled, IconPennantOff, IconPentagon, IconPentagonFilled, IconPentagonMinus,
    IconPentagonNumber0, IconPentagonNumber1, IconPentagonNumber2, IconPentagonNumber3, IconPentagonNumber4,
    IconPentagonNumber5, IconPentagonNumber6, IconPentagonNumber7, IconPentagonNumber8, IconPentagonNumber9,
    IconPentagonOff, IconPentagonPlus, IconPentagonX, IconPentagram, IconPepper, IconPepperOff, IconPercentage,
    IconPercentage0, IconPercentage10, IconPercentage100, IconPercentage20, IconPercentage25, IconPercentage30,
    IconPercentage33, IconPercentage40, IconPercentage50, IconPercentage60, IconPercentage66, IconPercentage70,
    IconPercentage75,    IconPercentage80, IconPercentage90, IconPerfume, IconPerspective, IconPerspectiveOff, IconPhone,
    IconPhoneCall, IconPhoneCalling, IconPhoneCheck, IconPhoneDone, IconPhoneEnd, IconPhoneFilled,
    IconPhoneIncoming, IconPhoneOff, IconPhoneOutgoing, IconPhonePause, IconPhonePlus, IconPhoneRinging,
    IconPhoneSpark, IconPhoneX, IconPhoto, IconPhotoAi, IconPhotoBitcoin, IconPhotoBolt, IconPhotoCancel,
    IconPhotoCheck, IconPhotoCircle, IconPhotoCircleMinus, IconPhotoCirclePlus, IconPhotoCode, IconPhotoCog,
    IconPhotoDollar, IconPhotoDown, IconPhotoEdit, IconPhotoExclamation, IconPhotoFilled, IconPhotoHeart,
    IconPhotoHexagon, IconPhotoMinus, IconPhotoOff, IconPhotoPause, IconPhotoPentagon, IconPhotoPin,
    IconPhotoPlus, IconPhotoQuestion, IconPhotoScan, IconPhotoSearch, IconPhotoSensor, IconPhotoSensor2,
    IconPhotoSensor3, IconPhotoShare, IconPhotoShield, IconPhotoSpark, IconPhotoSquareRounded, IconPhotoStar,
    IconPhotoUp, IconPhotoVideo, IconPhotoX, IconPhysotherapist, IconPiano, IconPick, IconPicnicTable,
    IconPictureInPicture, IconPictureInPictureFilled, IconPictureInPictureOff, IconPictureInPictureOn,
    IconPictureInPictureTop, IconPictureInPictureTopFilled, IconPig, IconPigMoney, IconPigOff, IconPilcrow,
    IconPilcrowLeft, IconPilcrowRight, IconPill, IconPillFilled, IconPillOff, IconPills, IconPin, IconPinEnd,
    IconPinFilled, IconPinInvoke, IconPingPong, IconPinned, IconPinnedFilled, IconPinnedOff, IconPizza,
    IconPizzaFilled, IconPizzaOff, IconPlaceholder, IconPlane, IconPlaneArrival, IconPlaneDeparture,
    IconPlaneInflight, IconPlaneOff, IconPlaneTilt, IconPlanet, IconPlanetOff, IconPlant, IconPlant2,
    IconPlant2Off, IconPlantOff, IconPlayBasketball, IconPlayCard, IconPlayCard1, IconPlayCard10,
    IconPlayCard10Filled, IconPlayCard1Filled, IconPlayCard2, IconPlayCard2Filled, IconPlayCard3,
    IconPlayCard3Filled, IconPlayCard4, IconPlayCard4Filled, IconPlayCard5, IconPlayCard5Filled,
    IconPlayCard6, IconPlayCard6Filled, IconPlayCard7, IconPlayCard7Filled, IconPlayCard8, IconPlayCard8Filled,
    IconPlayCard9, IconPlayCard9Filled, IconPlayCardA, IconPlayCardAFilled, IconPlayCardJ, IconPlayCardJFilled,
    IconPlayCardK, IconPlayCardKFilled, IconPlayCardOff, IconPlayCardQ, IconPlayCardQFilled, IconPlayCardStar,
    IconPlayCardStarFilled, IconPlayFootball, IconPlayHandball, IconPlayVolleyball, IconPlayerEject,
    IconPlayerEjectFilled, IconPlayerPause, IconPlayerPauseFilled, IconPlayerPlay, IconPlayerPlayFilled,
    IconPlayerRecord, IconPlayerRecordFilled, IconPlayerSkipBack, IconPlayerSkipBackFilled, IconPlayerSkipForward,
    IconPlayerSkipForwardFilled, IconPlayerStop, IconPlayerStopFilled, IconPlayerTrackNext, IconPlayerTrackNextFilled,
    IconPlayerTrackPrev, IconPlayerTrackPrevFilled, IconPlaylist, IconPlaylistAdd, IconPlaylistOff, IconPlaylistX,
    IconPlaystationCircle, IconPlaystationSquare, IconPlaystationTriangle, IconPlaystationX, IconPlug,
    IconPlugConnected, IconPlugConnectedX, IconPlugOff, IconPlugX, IconPlus, IconPlusEqual, IconPlusMinus,
    IconPng, IconPodium, IconPodiumOff, IconPoint, IconPointFilled, IconPointOff, IconPointer, IconPointerBolt,
    IconPointerCancel, IconPointerCheck, IconPointerCode, IconPointerCog, IconPointerDollar, IconPointerDown,
    IconPointerExclamation, IconPointerFilled, IconPointerHeart, IconPointerMinus, IconPointerOff, IconPointerPause,
    IconPointerPin, IconPointerPlus, IconPointerQuestion, IconPointerSearch, IconPointerShare, IconPointerStar,
    IconPointerUp, IconPointerX, IconPokeball, IconPokeballOff, IconPokerChip, IconPolaroid, IconPolaroidFilled,
    IconPolygon, IconPolygonOff, IconPoo, IconPooFilled, IconPool, IconPoolOff, IconPower, IconPray, IconPremiumRights,
    IconPrescription, IconPresentation, IconPresentationAnalytics, IconPresentationAnalyticsFilled,
    IconPresentationFilled, IconPresentationOff, IconPrinter, IconPrinterOff, IconPrism, IconPrismLight,
    IconPrismOff, IconPrismPlus, IconPrison, IconProgress, IconProgressAlert, IconProgressBolt, IconProgressCheck,
    IconProgressDown, IconProgressHelp, IconProgressX, IconPrompt, IconProng, IconPropeller, IconPropellerOff,
    IconProtocol, IconPumpkinScary, IconPuzzle, IconPuzzle2, IconPuzzleFilled, IconPuzzleOff, IconPyramid,
    IconPyramidOff, IconPyramidPlus, IconQrcode, IconQrcodeOff, IconQuestionMark, IconQuote, IconQuoteFilled,
    IconQuoteOff, IconQuotes, IconRadar, IconRadar2, IconRadarFilled, IconRadarOff, IconRadio, IconRadioOff,
    IconRadioactive, IconRadioactiveFilled, IconRadioactiveOff, IconRadiusBottomLeft, IconRadiusBottomRight,
    IconRadiusTopLeft, IconRadiusTopRight, IconRainbow, IconRainbowOff, IconRating12Plus, IconRating14Plus,
    IconRating16Plus, IconRating18Plus, IconRating21Plus, IconRazor, IconRazorElectric, IconReceipt, IconReceipt2,
    IconReceiptBitcoin, IconReceiptDollar, IconReceiptEuro, IconReceiptFilled, IconReceiptOff, IconReceiptPound,
    IconReceiptRefund, IconReceiptRupee, IconReceiptTax, IconReceiptYen, IconReceiptYuan, IconRecharging,
    IconRecordMail, IconRecordMailOff, IconRectangle, IconRectangleFilled, IconRectangleRoundedBottom,
    IconRectangleRoundedTop, IconRectangleVertical, IconRectangleVerticalFilled, IconRectangularPrism,
    IconRectangularPrismOff, IconRectangularPrismPlus, IconRecycle, IconRecycleOff, IconRefresh, IconRefreshAlert,
    IconRefreshDot, IconRefreshOff, IconRegex, IconRegexOff, IconRegistered, IconRelationManyToMany,
    IconRelationManyToManyFilled, IconRelationOneToMany, IconRelationOneToManyFilled, IconRelationOneToOne,
    IconRelationOneToOneFilled, IconReload, IconReorder, IconRepeat, IconRepeatOff, IconRepeatOnce, IconReplace,
    IconReplaceFilled, IconReplaceOff, IconReport, IconReportAnalytics, IconReportMedical, IconReportMoney,
    IconReportOff, IconReportSearch, IconReservedLine, IconResize, IconRestore, IconRewindBackward10,
    IconRewindBackward15, IconRewindBackward20, IconRewindBackward30, IconRewindBackward40, IconRewindBackward5,
    IconRewindBackward50, IconRewindBackward60, IconRewindForward10, IconRewindForward15, IconRewindForward20,
    IconRewindForward30, IconRewindForward40, IconRewindForward5, IconRewindForward50, IconRewindForward60,
    IconRibbonHealth, IconRings, IconRipple, IconRippleOff, IconRoad, IconRoadOff, IconRoadSign, IconRobot,
    IconRobotFace, IconRobotOff, IconRocket, IconRocketOff, IconRollerSkating, IconRollercoaster, IconRollercoasterOff,
    IconRosette, IconRosetteDiscount, IconRosetteDiscountCheck, IconRosetteDiscountCheckFilled, IconRosetteDiscountFilled,
    IconRosetteDiscountOff, IconRosetteFilled, IconRosetteNumber0, IconRosetteNumber1, IconRosetteNumber2,
    IconRosetteNumber3, IconRosetteNumber4, IconRosetteNumber5, IconRosetteNumber6, IconRosetteNumber7,
    IconRosetteNumber8, IconRosetteNumber9, IconRotate, IconRotate2, IconRotate360, IconRotate3d, IconRotateClockwise,
    IconRotateClockwise2, IconRotateDot, IconRotateRectangle, IconRoute, IconRoute2, IconRouteAltLeft, IconRouteAltRight,
    IconRouteOff, IconRouteScan, IconRouteSquare, IconRouteSquare2, IconRouteX, IconRouteX2, IconRouter, IconRouterOff,
    IconRowInsertBottom, IconRowInsertTop, IconRowRemove, IconRss, IconRubberStamp, IconRubberStampOff, IconRuler,
    IconRuler2, IconRuler2Off, IconRuler3, IconRulerMeasure, IconRulerMeasure2, IconRulerOff, IconRun, IconRvTruck,
    IconSTurnDown, IconSTurnLeft, IconSTurnRight, IconSTurnUp, IconSailboat, IconSailboat2, IconSailboatOff, IconSalad,
    IconSaladFilled, IconSalt, IconSandbox, IconSatellite, IconSatelliteOff, IconSausage, IconScale, IconScaleOff,
    IconScaleOutline, IconScaleOutlineOff, IconScan, IconScanEye, IconScanPosition, IconSchema, IconSchemaOff,
    IconSchool, IconSchoolBell, IconSchoolOff, IconScissors, IconScissorsOff, IconScooter, IconScooterElectric,
    IconScoreboard, IconScreenShare, IconScreenShareOff, IconScreenshot, IconScribble, IconScribbleOff, IconScript,
    IconScriptMinus, IconScriptPlus, IconScriptX, IconScubaDiving, IconScubaDivingTank, IconScubaDivingTankFilled,
    IconScubaMask, IconScubaMaskOff, IconSdk, IconSearch, IconSearchOff, IconSection, IconSectionFilled,
    IconSectionSign, IconSeeding, IconSeedingFilled, IconSeedingOff, IconSelect, IconSelectAll, IconSelector,
    IconSend, IconSend2, IconSendOff, IconSeo, IconSeparator, IconSeparatorHorizontal, IconSeparatorVertical,
    IconServer, IconServer2, IconServerBolt, IconServerCog, IconServerOff, IconServerSpark, IconServicemark,
    IconSettings, IconSettings2, IconSettingsAutomation, IconSettingsBolt, IconSettingsCancel, IconSettingsCheck,
    IconSettingsCode, IconSettingsCog, IconSettingsDollar, IconSettingsDown, IconSettingsExclamation,
    IconSettingsFilled, IconSettingsHeart, IconSettingsMinus, IconSettingsOff, IconSettingsPause,
    IconSettingsPin, IconSettingsPlus, IconSettingsQuestion, IconSettingsSearch, IconSettingsShare,
    IconSettingsSpark, IconSettingsStar, IconSettingsUp, IconSettingsX, IconShadow, IconShadowOff,
    IconShape, IconShape2, IconShape3, IconShapeOff, IconShare, IconShare2, IconShare3, IconShareOff,
    IconShareplay, IconShiJumping, IconShield, IconShieldBolt, IconShieldCancel, IconShieldCheck,
    IconShieldCheckFilled, IconShieldCheckered, IconShieldCheckeredFilled, IconShieldChevron, IconShieldCode,
    IconShieldCog, IconShieldDollar, IconShieldDown, IconShieldExclamation, IconShieldFilled, IconShieldHalf,
    IconShieldHalfFilled, IconShieldHeart, IconShieldLock, IconShieldLockFilled, IconShieldMinus, IconShieldOff,
    IconShieldPause, IconShieldPin, IconShieldPlus, IconShieldQuestion, IconShieldSearch, IconShieldShare,
    IconShieldStar, IconShieldUp, IconShieldX, IconShip, IconShipOff, IconShirt, IconShirtFilled, IconShirtOff,
    IconShirtSport, IconShoe, IconShoeOff, IconShoppingBag, IconShoppingBagCheck, IconShoppingBagDiscount,
    IconShoppingBagEdit, IconShoppingBagExclamation, IconShoppingBagHeart, IconShoppingBagMinus,
    IconShoppingBagPlus, IconShoppingBagSearch, IconShoppingBagX, IconShoppingCart, IconShoppingCartBolt,
    IconShoppingCartCancel, IconShoppingCartCheck, IconShoppingCartCode, IconShoppingCartCog, IconShoppingCartCopy,
    IconShoppingCartDiscount, IconShoppingCartDollar, IconShoppingCartDown, IconShoppingCartExclamation,
    IconShoppingCartFilled, IconShoppingCartHeart, IconShoppingCartMinus, IconShoppingCartOff, IconShoppingCartPause,
    IconShoppingCartPin, IconShoppingCartPlus, IconShoppingCartQuestion, IconShoppingCartSearch,
    IconShoppingCartShare, IconShoppingCartStar, IconShoppingCartUp, IconShoppingCartX, IconShovel,
    IconShovelPitchforks, IconShredder, IconSignLeft, IconSignLeftFilled, IconSignRight, IconSignRightFilled,
    IconSignal2g, IconSignal3g, IconSignal4g, IconSignal4gPlus, IconSignal5g, IconSignal6g, IconSignalE,
    IconSignalG, IconSignalH, IconSignalHPlus, IconSignalLte, IconSignature, IconSignatureOff, IconSitemap,
    IconSitemapFilled, IconSitemapOff, IconSkateboard, IconSkateboardOff, IconSkateboarding, IconSkewX,
    IconSkewY, IconSkiJumping, IconSkull, IconSlash, IconSlashes, IconSleigh, IconSlice, IconSlideshow,
    IconSmartHome, IconSmartHomeOff, IconSmoking, IconSmokingNo, IconSnowboarding, IconSnowflake,
    IconSnowflakeOff, IconSnowman, IconSoccerField, IconSocial, IconSocialOff, IconSock, IconSofa, IconSofaOff,
    IconSolarElectricity, IconSolarPanel, IconSolarPanel2,
};
